### ISSUE TITLE
Apple Tv Remote Doesn't Work For Games

### ISSUE THREAD

**Issue by zane568** [jasarien/Provenance#100]
I got an apple tv dev kit, and downloaded provenance, then put some emulators on. All ran smooth, but the apple tv remote doesn't work. Swiping does work, but clicking doesn't.

**Comment by jasarien** [comment]
Yup, this is going to be a common complaint it seems. The Siri Remote only has a touch pad and two buttons. Even the most basic controller in Provenance requires a dPad and 3 buttons (the Gamegear, it has a dPad, Button1, Button2 and a start/pause button). Everything else requires at least 4 or more buttons. The SNES is probably most complex with a dPad, 4 face buttons, two shoulders, start and select, 8 buttons! The Remote has 2! 😫

**Comment by zane568** [comment]
Are Any Controllers (buyable) supported?

**Comment by jasarien** [comment]
Yes, any MFi game controller is supported.

**Comment by jasarien** [comment]
I'm including the Siri Remote in the controller mappings, but it's not going to work for every game. I mean, you might be able to play Sonic, since you only need one button to jump, and another to start the game.

**Comment by zane568** [comment]
that sounds like it would be awesome! Any idea on release?

**Comment by jasarien** [comment]
Nothing confirmed yet, I'm working on refactoring the controller handling as we speak.

**Comment by zane568** [comment]
!!!!;)

**Comment by jpete24** [comment]
What about NES30 Pro controllers? Can anyone confirm icade will work with TvOS?

**Comment by jasarien** [comment]
iCade support is in there from the iOS code, but I don't have one to test with, and I don't even know if iCades can connect to the Apple TV yet.

**Comment by jpete24** [comment]
Please please please Apple.....be cool and allow icade.....
