### ISSUE TITLE
Error on Building "ld: library not found for -lPVSupport"

### ISSUE THREAD

**Issue by sabont** [jasarien/Provenance#101]
I tried following the guide, but I am having issues.  Fresh installation of Xcode-beta 7.1.

<img width="1512" alt="screen shot 2015-09-19 at 8 45 45 pm" src="https://cloud.githubusercontent.com/assets/5597207/9979143/71bc4dfc-5f0f-11e5-9b0b-aa38f236715e.png">

This is happening on my new Dev Kit TV, and iPhone 6+.

<img width="1512" alt="screen shot 2015-09-19 at 8 54 45 pm" src="https://cloud.githubusercontent.com/assets/5597207/9979156/b1c2e626-5f10-11e5-991e-affef0979829.png">

Any help would be GREATLY appreciated!
Thanks,
Scott

**Comment by jasarien** [comment]
Make sure you're opening the workspace file and not the standalone project file. The workspace contains the app and the dependencies.

**Comment by sabont** [comment]
That did it, I was opening the xcodeproj, not the workspace file.  Thanks!
