### ISSUE TITLE
Build errors: undeclared identifier (PVGameLibrarySectionHeaderView.h)

### ISSUE THREAD

**Issue by thibmaek** [jasarien/Provenance#106]
<img width="819" alt="screen shot 2015-09-22 at 10 34 06" src="https://cloud.githubusercontent.com/assets/6213695/10013873/972b3e10-6115-11e5-92a2-ad45b38c3152.png">

**Comment by jasarien** [comment]
You need to build Provenance with the iOS 9 SDK (Xcode 7 public release). (It still supports iOS 8+).
