### ISSUE TITLE
Sync Between Devices (What interface could we use?)

### ISSUE THREAD

**Issue by jpete24** [jasarien/Provenance#107]
This has been discussed, but I think will be more of an issue as people want to use this app on their devices and on the new AppleTV, but we need to accommodate a way to sync game ROM's and game save files so we can just play on any device. I know there has been some discussion about Dropbox, but I wonder if there is any way we can incorporate this? A web server connection is a good stop gap, but I think a full blown sync solution is going to be necessary.

**Comment by jasarien** [comment]
Closing as duplicate of #1 - feel free to copy your comment over and continue discussion there.
