### ISSUE TITLE
Tv out support for iOS

### ISSUE THREAD

**Issue by BetoRn** [jasarien/Provenance#108]
Is it possible to add tv out support for the iOS version?

**Comment by jasarien** [comment]
I'll have to pickup a tv-out adapter to test this one, but as soon as I get one I'll take a look at supporting this.

**Comment by Asmod4n** [comment]
afaik tv-out is just the same as airplay?

**Comment by jasarien** [comment]
Yeah I think you're right. I'll still pick up an adaptive to test it though.

**Comment by Asmod4n** [comment]
at least with lightning cables, iOS just sends h264 to the adapter which then does the HDMI conversion.

**Comment by jasarien** [comment]
Cool

**Comment by jasarien** [comment]
Implemented in a161464859570cea7991fec53541d1d3af685179
