### ISSUE TITLE
Crashed on TV

### ISSUE THREAD

**Issue by Memtimen** [jasarien/Provenance#109]
<img width="1873" alt="screen shot 2015-09-23 at 9 32 43 pm" src="https://cloud.githubusercontent.com/assets/4409143/10065425/b4407062-623a-11e5-82cd-f6004d5e4e31.png">

<img width="1873" alt="screen shot 2015-09-23 at 9 33 49 pm" src="https://cloud.githubusercontent.com/assets/4409143/10065437/cee6e6c6-623a-11e5-901a-82761314b9d6.png">

**Comment by jasarien** [comment]
Yep I'm aware of this. I don't have any solution for it yet though. I think it's a bug with Realm on tvOS, but I haven't heard back from them after raising it yet.

**Comment by jasarien** [comment]
You can follow the discussion on this bug at the link I posted in the comment above, but the shortened version is that Apple has limited the use of a required function that Realm uses since tvOS beta 2, which breaks Realm and, by extension, Provenance... I'm not sure when a fix will be available.

**Comment by Memtimen** [comment]
I'll follow the discussion, thanks @jasarien

**Comment by jasarien** [comment]
A quick summary from the linked issue at Realm's repo:

tvOS beta 2 restricts access to particular APIs that Realm uses. I have logged a bug with Apple explaining why these APIs probably should be restricted (rdar://22847480). The Realm dev team have created a workaround in the form of an experimental tvOS compatible branch of Realm. Don't consider this a permanent solution yet.

But for now, Provenance is currently working on tvOS beta 2 again.
