### ISSUE TITLE
Lag in iPod 5 iOS 9

### ISSUE THREAD

**Issue by mehdihz** [jasarien/Provenance#110]
I tested your framework some times ago with iOS 8 and there was no problem with it. But I recently updated my iPod to iOS 9 and tested with your framework and there was very bad lag in playing.
I tested your code's compilation with Xcode 6.4 and 7 and there was no difference.

**Comment by jasarien** [comment]
Please make sure you're following the instructions on the wiki when building from source, in particular the step about ensuring to build in release mode as this fixes most performance related issues. 

Also if you could state which generation iPod touch you're using, and which system/games you were trying to play that might help to identify performance issues too.

**Comment by mehdihz** [comment]
Dear jasarian.. I was compiling under release mode and followed your help and found out that this lag was related to my ROM. I downloaded Super mario bros (NES) from Emuparadise and it was working ok. But this time I tested from Loveroms and It caused the lag. I changed my ROM and now it's working ok.
Sorry to taking your time and thanks.
