### ISSUE TITLE
tvOS Web Uploader Broken

### ISSUE THREAD

**Issue by charlestruluck** [jasarien/Provenance#111]
When using tvOS Beta  2, the website has a lot of errors:
<img width="1186" alt="error" src="https://cloud.githubusercontent.com/assets/8528039/10119142/aaa20d86-645b-11e5-9211-3f49563a3285.png">

**Comment by jasarien** [comment]
Yeah I'm seeing these errors too. I'm working on it.

**Comment by charlestruluck** [comment]
One thing I noticed is The New TV is (partially) compatible with iMazing/DiskAid. I can see the file system for Provenance.

**Comment by charlestruluck** [comment]
I found that if you go to Provenance/Library/Caches/roms/ and drop a Zip file in there, you can get a rom to run.

**Comment by jasarien** [comment]
I've found the issue. I'll get it fixed very soon.

**Comment by jasarien** [comment]
Fixed in 4847388236742ffb97f8a0b581fedf6dad3e599c
