### ISSUE TITLE
Diagonal dpad mfi controller support

### ISSUE THREAD

**Issue by jpaulus23** [jasarien/Provenance#113]
Certain games rely heavily on being able to press down + left/right and up + left/right at the same time. Games such as secret of mana, gradius 3, super metroid etc. this issue and happening with a steel series stratus xl controller purchased from an apple retail store.

**Comment by jasarien** [comment]
This should be fixed in the latest build - see here:  https://github.com/jasarien/Provenance/pull/112

**Comment by jpaulus23** [comment]
Thanks bro!

Sent from Outlook




On Sat, Sep 26, 2015 at 4:56 PM -0700, "James Addyman" <notifications@github.com> wrote:












This should be fixed in the latest build - see here:  #112
