### ISSUE TITLE
Linker Command Fail

### ISSUE THREAD

**Issue by xXH4tchXx** [jasarien/Provenance#116]
The build for TvOs and iOS are failing due to a linker command fail with error code 1.

**Comment by jasarien** [comment]
Please ensure you're opening the workspace file and not the standalone project file.

**Comment by xXH4tchXx** [comment]
Thank you, it worked. I tried using the workspace but, the build target was scrolled down(I'm stupid) and therefore below with only the individual emulators visible.

**Comment by jasarien** [comment]
Cool, have fun!
