### ISSUE TITLE
MFi Controller - "Ignored" D-Pad / Analog Stick directional inputs

### ISSUE THREAD

**Issue by oliviercharavel** [jasarien/Provenance#117]
I'm not exactly sure how to explain the issue I'm having with an MFi Controller (tested with a Mad Catz C.T.R.L.i) but I think the recent commits about the deadzone / diagonal MFi support may have something to do with it.

There seems to be an issue with directional inputs "being ignored" when using the D-Pad or the Analog Stick when you play a game that allows you to move in any direction (Chrono Trigger, Boktai, Golden Sun, ...). For example, if I move a character to the right and then decide to go to another direction (I would press left or down or up on the D-Pad/Analog), the character will keep moving to the right instead of moving to the new direction. The only way to stop this is to let go of the d-pad / analog stick to be able to move to the desired direction.

**Comment by jasarien** [comment]
Hm... yeah, seems like this area still needs some work. It's had like 5 iterations D:

**Comment by oliviercharavel** [comment]
FWIW, aside from this issue, it feels much better than before. It's almost there. 😊

**Comment by jasarien** [comment]
Pushed some codez. Pull the latest and give it a try. I think it's fixed now.

**Comment by oliviercharavel** [comment]
This seems to work much better. 👍

**Comment by jasarien** [comment]
Cool, good to hear it.
