### ISSUE TITLE
"No conflicts..." label crashes the app

### ISSUE THREAD

**Issue by oliviercharavel** [jasarien/Provenance#118]
It's not a big deal at all but a tap on the "No conflicts..." label inside the "Manage Conflicts" screen will always crash the app.

**Comment by jasarien** [comment]
Thanks, should be fixed in the latest.

**Comment by kvz** [comment]
Just ran into the problem where it does not crash, but when it says

> No conflicts...

there is no way to exit that screen to return to settings. I can visit the library and search, but settings has been replaced by the "No conflicts" screen. When I press menu/back, i exit Provenance. I had to double tap the Home button and swipe up Provenance to reset its state and be able to access Settings again.

As with OP, no big problem, just thought I'd be a sport and report this.

**Comment by jasarien** [comment]
Sounds like a different issue to the original. Would you mind creating a new issue for this please?

**Comment by jasarien** [comment]
Also, make a mention that it's when using Apple TV too. It's good to be clear.

**Comment by kvz** [comment]
Done
