### ISSUE TITLE
Roms don't play on Apple TV Dev Kit

### ISSUE THREAD

**Issue by bytor99999** [jasarien/Provenance#119]
Got some loaded on the new Apple TV, just get black screen when choosing to play a rom. NES, Genesis and SNES Roms are all I have and tried

**Comment by jasarien** [comment]
It's working fine for me in the latest build.

**Comment by bytor99999** [comment]
So I see the games in the main screen, but when I select a game and try to play it the screen is completely black. Everything works fine on my iPhone 6s Plus. I have the Apple TV 4 attached to my second computer monitor an LG 1080P 27" monitor via the HDMI cable. Hmmm. 

Thanks and great job, by the way. 

Mark

**Comment by bytor99999** [comment]
Just noticed I have XCode 7.1 Beta 1 and not Beta 2 installed. Not sure if that would make any difference, but I will try to install it with Beta 2.

**Comment by jasarien** [comment]
Let me know how it goes... Was there anything printing out in the console when trying to run a rom?

**Comment by bytor99999** [comment]
Good question, will check that out too. Was too excited to start playing that I didn't think to look. ;)

**Comment by bytor99999** [comment]
Lots of these in the console.

2015-09-28 17:11:34.205 Provenance[855:757114] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x14cd3a620> to GL_RENDERBUFFER 1
2015-09-28 17:11:34.206 Provenance[855:757114] Failed to make complete framebuffer object 8cd6
2015-09-28 17:11:34.223 Provenance[855:757114] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x14cd3a620> to GL_RENDERBUFFER 1
2015-09-28 17:11:34.223 Provenance[855:757114] Failed to make complete framebuffer object 8cd6

Will re-run to make sure those are related to playing a rom.

**Comment by jasarien** [comment]
Ok, also definitely check it on B2 as well. It's possible something changed in OpenGLES, which might cause these errors.

**Comment by bytor99999** [comment]
Oh Yeah, definitely those are what scrolls like crazy when starting /running a rom. And stops when you exit out of the rom.

Thanks

**Comment by bytor99999** [comment]
Yes. It works with XCode Beta 2 for me. Now trying to figure out how things map to the Apple Remote ;) Contra wasn't much fun when you can't shoot. :D 

Mark

**Comment by jasarien** [comment]
Yeah Apple remote isn't good for games at all. For the most part the touchpad button mapped to A and the play/pause button is mapped to Start button. There's no much else I can do... the start button is required to even start most games...
