### ISSUE TITLE
VR Support

### ISSUE THREAD

**Issue by jhays** [jasarien/Provenance#121]
Enhancement request- Not sure if possible, but if it is...
Split-screen / side-by-side video output for VR headset support with iOS devices?

**Comment by jasarien** [comment]
I'm not going to say it's impossible, but I'd go as far as to say it's infeasible for Provenance. 

As far as I understand stereoscopic 3D requires the two images to be from slightly different angles to get the 3D illusion. If you feed the same image to the eyes then you're not going to get any 3D perspective.

**Comment by jhays** [comment]
Fair enough. Wondered if there would be a way to slightly transform each side's view to get the effect.. but I can understand it not being feasible.
