### ISSUE TITLE
'UIApplicationShortcutItem' is unavailable: not available on tvOS

### ISSUE THREAD

**Issue by Weble-xx** [jasarien/Provenance#122]
On Target ProvenanceTV-Release i get 3 issues:
.../Provenance-master/Provenance/PVAppDelegate.h:14:31: 'UIApplicationShortcutItem' is unavailable: not available on tvOS
.../Provenance-master/Provenance/PVAppDelegate.m:23:5: 'UIApplicationShortcutItem' is unavailable: not available on tvOS
.../Provenance-master/Provenance/PVAppDelegate.m:23:57: 'UIApplicationLaunchOptionsShortcutItemKey' is unavailable: not available on tvOS

Mac OS X: Version 10.11.1 Beta (15B22c)
Xcode: Version 7.1 beta (7B75)
AppleTV Beta2

**Comment by jasarien** [comment]
Oopsie poopsie. I'll get that sorted.

**Comment by jasarien** [comment]
Ok, pushed, try it out.

**Comment by Weble-xx** [comment]
Is working
Thanks for your work.
