### ISSUE TITLE
Apple TV Controls

### ISSUE THREAD

**Issue by kudit** [jasarien/Provenance#123]
I was trying to play an NES game and it really is impossible without at least A & B buttons but I noticed you mapped Play/Pause to Start.  Given that Start is rarely used for gameplay and probably never needs to be timed, would it be possible to add Start/Select to the menu that comes up when pressing the menu button and set Play/Pause to A and the click to B?  I found how to change the button maps, but wasn't sure how to invoke start/stop in the menu:

	#if TARGET_OS_TV
		[actionsheet addAction:[UIAlertAction actionWithTitle:@"(Start)" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
			// TODO: dismiss and press start button in game
		}]];
		[actionsheet addAction:[UIAlertAction actionWithTitle:@"(Select)" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
			// TODO: dismiss and press start button in game
		}]];
	#endif

**Comment by jasarien** [comment]
Sounds like it might be worth a try. I'll give it a go.

**Comment by jasarien** [comment]
Seems to work. Pull the latest code and give it a try.

**Comment by jasarien** [comment]
I will admit that the code to accomplish it feels a little bit like a hack, but then again, so does using the Siri Remote as a game controller. :/

**Comment by kudit** [comment]
Again, apologies for the delayed response!

Seems to work (and, yes, it is a bit of a hack, but there's not much to work with as far as inputs on the remote).  Another idea was to use the accelerometer as the direction control and then the entire touch pad could be used for ABXY buttons and the play/pause button could be used for start (and then just have select in the menu or perhaps touching opposite corners and pressing the trackpad).  Multiple touches on the trackpad is not currently supported by Apple, but I've filled a radar for it: radar:22989448.  Relevant forum post: https://forums.developer.apple.com/message/52539#52539
