### ISSUE TITLE
Sound on Apple TV

### ISSUE THREAD

**Issue by kudit** [jasarien/Provenance#124]
Is sound not playing on Apple TV a known issue?

**Comment by jasarien** [comment]
Sounds plays fine for me...

**Comment by oliviercharavel** [comment]
Make sure your device is not in Silent mode.

**Comment by jasarien** [comment]
I'm not sure if AppleTV eve has a silent mode?

**Comment by oliviercharavel** [comment]
Oops, I thought it had to do with AirPlay/TV-Out. 😜

**Comment by jasarien** [comment]
Any update on this issue? I'd like to close it if possible.

**Comment by jasarien** [comment]
Still waiting on an update.

**Comment by kudit** [comment]
Hey, sorry, was out of town.
Update: It does now seem to work on some ROMs (before it wasn't working on any ROMs).  So maybe it was just a fluke.  I know it wasn't a volume issue because I would hear the "clicks" in the menu when navigating to the ROMs.  I'll let you know if I can reproduce it again or I can send the ROMs that aren't working for testing.
