### ISSUE TITLE
Some gui tweaks possibly needed

### ISSUE THREAD

**Issue by Shawzborne** [jasarien/Provenance#125]
![](http://i.imgur.com/8CBburF.jpg)

**Comment by jasarien** [comment]
Lol, thanks for the suggestion. I don't really think there's much use case for playing in Provenance while in multitasking mode, but if I get some time I'll look into it.

**Comment by Shawzborne** [comment]
![](http://i.imgur.com/xcfXOoV.jpg)

**Comment by jasarien** [comment]
I'm going to close this issue. I don't think the use case for this scenario is popular enough to warrant spending any significant effort on it, but also it seems to work well enough anyway. You could just reposition the buttons with the "edit controls" to get around the controls overlapping.
