### ISSUE TITLE
MFI controller mapping mismatch

### ISSUE THREAD

**Issue by illando** [jasarien/Provenance#126]
I'm using a Moga Rebel MFI controller (Same layout as SteelSeries Stratus or Logitech PowerShell) And there's some mapping configuration that need to be modified to mach the different original joypad layouts.

Here's my report for Master System, Mega Drive, NES and SNES:

Master System
It should be:
Button A = Sega Button1
Button B = Sega Button2

Mega Drive
It should be:
Button X=Sega ButtonA
Button A=Sega ButtonB
Button B=Sega ButtonC

NES
Button A and B should be inverted
Button R2 and L2  (start and select) should be inverted

SNES
Button A and B should be inverted
Button X and Y should be inverted
Button R2 and L2 (start and select) should be inverted
Maybe also L1 and R1 should be inverted (I don't know any game that use it!)

Thanks.

**Comment by jasarien** [comment]
Sorted in the latest commit.

**Comment by zepfhyr** [comment]
This is not actually resolved. At least, for NES and SNES games, the buttons on the controller still match the button letters for NES and SNES games (meaning that A and B are still mapped to A and B, causing them to be in the wrong place on the controller itself, due to Nintendo's button placement being the reverse of MFi controllers).

**Comment by jasarien** [comment]
That's not what the code says: https://github.com/jasarien/Provenance/blob/master/Provenance/Controller/PVSNESControllerViewController.m#L127-L155

see the highlighted section. Notice how, for example, the controller's buttonX is mapped to SNES's buttonY. And controller B is mapped to SNES A, etc.

**Comment by jasarien** [comment]
Either you're not looking at the latest code, or something else is up.

**Comment by zepfhyr** [comment]
Strange. I thought I pulled down the code separately and built it again from scratch, but maybe I loaded the wrong project. I'll try it again.

**Comment by zepfhyr** [comment]
It appears to be working properly once I pulled the code down again. Not sure what the deal was.
