### ISSUE TITLE
Standstill after "Unable to start a web server" error

### ISSUE THREAD

**Issue by illando** [jasarien/Provenance#131]
If you accindetally press on the "+" button and you are not connected to a Wi-Fi network it appears the advice "Unable to start a web server!" but there's no button to confirm or to continue.
So then you are forced to close the app from the multitasking manager and reopen it.

**Comment by jasarien** [comment]
Hah, nice catch. I'll get it fixed sometime today.

**Comment by jasarien** [comment]
Should be fixed in the latest push
