### ISSUE TITLE
Naming of "Quit" menu

### ISSUE THREAD

**Issue by kudit** [jasarien/Provenance#134]
Perhaps this should be labelled "Exit Game" or "Quit Game" or "Game List" or "Suspend Game" as simply "Quit" makes me think this might go back to the Apple TV menu.  Even knowing what it is, seeing a big red "Quit" still makes me think it's going back to the Apple TV menu and could be a bit daunting for some.

**Comment by kudit** [comment]
(Obviously not a major issue)

**Comment by jasarien** [comment]
Renamed to "Return to Game Library"

**Comment by kudit** [comment]
Awesome! That will work. Thanks!
