### ISSUE TITLE
"linker command failed with exit code 1 (use -v to see invocation)"

### ISSUE THREAD

**Issue by darkjenso** [jasarien/Provenance#138]
![screenshot 2015-10-11 08 31 30](https://cloud.githubusercontent.com/assets/1343247/10415638/995ffd10-6ff2-11e5-8d9e-9a4c6f285f82.png)

**Comment by jasarien** [comment]
You need to open the workspace, not the project. (White icon, not blue icon)

**Comment by apelican** [comment]
I am getting this too, very definitely opening the workspace :(
Everything builds, looks like the library search is failing for some reason
