### ISSUE TITLE
Toggle for Hiding Title Labels in Game Library

### ISSUE THREAD

**Issue by ghost** [jasarien/Provenance#144]
For a cleaner look, a toggle to hide title labels in the Game Library screen would be nice. If there is no artwork, it can be displayed where the artwork would have been.

**Comment by marcelvoss** [comment]
Something like this?
![simulator screen shot 20 09 2016 22 55 28](https://cloud.githubusercontent.com/assets/5435925/18688597/5db6676a-7f85-11e6-835f-e491cd7a65fb.png)

**Comment by Armored-Dragon** [comment]
Could you make a pull request or something for that?

**Comment by marcelvoss** [comment]
I'm improving it at the moment and fixing small bugs that I caused due to this. Will submit a PR as soon as it's done.

**Comment by marcelvoss** [comment]
See pull request #415 for progress regarding this issue.

**Comment by marcelvoss** [comment]
Merged with #415. Can be closed.
