### ISSUE TITLE
Show recent games in Top Shelf on tvOS

### ISSUE THREAD

**Issue by hulehule20** [jasarien/Provenance#145]
It would be a great enhancement to display the latest played games in the top shelf found on the new tvOS.  You could also let the player set some fav games to display in that area.
I could implement this myself but I would need a better understanding of how the game library works and how can I get the games and sort them.

**Comment by appletv4** [comment]
This would be nice to have and keep provenance on top

**Comment by davidmuzi** [comment]
I have this working on a branch https://github.com/davidmuzi/Provenance/tree/tvos/topshelf

Ill clean it up, and issue a PR for this.

**Comment by appletv4** [comment]
@davidmuzi  on the top shelf it shows the most recent games or a wallpaper picture ?
And thanks

**Comment by davidmuzi** [comment]
Recent games.

![simulator screen shot dec 16 2015 8 53 23 pm](https://cloud.githubusercontent.com/assets/1058176/11859263/3cccc41a-a437-11e5-89f8-33b5a8d822c8.png)

I need to choose from a set of aspect ratios that closely match the aspect ratios of each console.  Not perfect :/
