### ISSUE TITLE
separatorColor unsupported on tvOS

### ISSUE THREAD

**Issue by hulehule20** [jasarien/Provenance#147]
When I tried to build Provenance this morning, Xcode threw an error telling me that separatorColor (from UITableViewController ) was not supported on tvOS.  It happens once in [this line, in the PVConflictViewController.m file](https://github.com/jasarien/Provenance/blob/master/Provenance/Game%20Library/PVConflictViewController.m#L46).  The code just sets the property to a clear color:
```objc
self.tableView.separatorColor = [UIColor clearColor];
```
What I don't get about this issue is that I built the same project yesterday and it didn't give me any issue.

**Comment by saagarjha** [comment]
That would be my fault. Just comment it out for now, I'll fix it when I get home.

**Comment by saagarjha** [comment]
The *real* fix is to move the line up so that it's inside the #if TARGET_OS_TV block.

**Comment by jasarien** [comment]
Fixed in latest.
