### ISSUE TITLE
iCade 8bitdo Nes30 mode not working properly

### ISSUE THREAD

**Issue by StyloBill** [jasarien/Provenance#153]
On version 1.2.2, it seems that Provenance is not working properly with the 8bitdo controller (in iCade mode 3, starting the controller with A+Start).
I think the emulator doesn't recognize the left direction release of the d-pad.

**Comment by jpete24** [comment]
You need to use the latest build. There was a point around that last version that broke icade. Make sure you have the latest build.

Josh

**Comment by jasarien** [comment]
I don't know much about the iCade support. Maybe @josejulio can help?

**Comment by josejulio** [comment]
What version of the 8bitdo controller are you using (firmware)? 
Could try opening the Notes app, and telling my what character shows up when you press the left direction of the d-pad? and when you release it?

**Comment by StyloBill** [comment]
I'm using the latest version : 2.63.
I just submitted a pull request to fix the problem.

**Comment by StyloBill** [comment]
After more tests, it appears that the issue is not related to Provenance.
Actually it is an iOS problem : the controller-key mapping is dependant of the keyboard layout selected on iOS.
To correctly map the controller with the keyboard keys, the iOS keyboard layout must be on QWERTY.

A possible Provenance improvement might be to check the OS keyboard layout and to remap the keys accordingly.

**Comment by jasarien** [comment]
Ah that's pretty interesting... Didn't expect that to be the case.

**Comment by alexjeune1** [comment]
My 8bitdo snes30 wont work on my iphone. I bought builds.io and the only thing it works with is the super smash bros app

**Comment by jasarien** [comment]
@alexjeune1 #320 

Please don't post in closed issues.

**Comment by vdruts** [comment]
No luck here, builds.io 1.2.7 build. Nes 30 controller (you can select it from the icade menu) but when you go to the assign controller to player 1/2, it's blank always. Just says "not playing" as an option... :/

**Comment by josejulio** [comment]
@vdruts Just enable iCade, enter the game and press a button (the virtual pad should disappear on button press), if its not working for you open a new issue please

**Comment by vdruts** [comment]
Tried that JoseJulio, not working. I'll open a new issue.
