### ISSUE TITLE
Scanline Support

### ISSUE THREAD

**Issue by maddox** [jasarien/Provenance#159]
Support for scanlines would be most welcomed. I'm not sure how the core of Provenance works, but implementing this with either a filter, or even a simple UIImageView overlay would work well.

Scanlines helps everything look much better at larger resolutions, especially ones used via tvOS.

**Comment by jasarien** [comment]
Duplicate of #54

**Comment by maddox** [comment]
@jasarien Thanks! Sorry about that. I even perused all the issues before I opened that. My bad.
