### ISSUE TITLE
Failed building tvOS target for device

### ISSUE THREAD

**Issue by siuying** [jasarien/Provenance#163]
When archive for device, i get following error:

```
ld: bitcode bundle could not be generated because 'Provenance/Realm-tvOS/Realm.framework/Realm' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jasarien** [comment]
No need to archive just Buick directly to device.

**Comment by siuying** [comment]
Oh, thanks.

**Comment by jrey1989** [comment]
Code Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.jamsoftonline.ProvenanceTV” were found. what do i do here???

**Comment by siuying** [comment]
You need to create an app on iTunes Connect, create corresponding provisioning profiles, change the com.jamsoftonline.ProvenanceTV to that bundle identifier, and build the app.
