### ISSUE TITLE
Cannot Connect to Apple TV

### ISSUE THREAD

**Issue by cortneytaylor** [jasarien/Provenance#165]
I know this isn't an issue as much as it is my ignorance, but I have scoured the internet and cannot find a solution. How can I connect my Apple TV (4th gen) to Xcode so that I can compile this? I've spend several hours looking around, and can't find it anywhere.

Sorry to create an issue for this, but I figured someone would know the answer. Thanks!

**Comment by jasarien** [comment]
You need a USB-C to USB-A cable which isn't included with the AppleTV. Something like: http://www.amazon.co.uk/gp/aw/d/B011TH8BB2/ref=mp_s_a_1_1?qid=1446319347&sr=8-1&pi=SY200_QL40&keywords=usb+a+c+cable&dpPl=1&dpID=414LOwaaOiL&ref=plSrch

**Comment by cortneytaylor** [comment]
I figured that would have been the case. I didn't want to go buy one if I didn't need to. Thanks for the quick response! And sorry again to bother you.

**Comment by jasarien** [comment]
No worries. Wireless would have been nice. Maybe next version.
