### ISSUE TITLE
provenance

### ISSUE THREAD

**Issue by jrey1989** [jasarien/Provenance#166]
Code Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.jamsoftonline.ProvenanceTV” were found. what do i do here

**Comment by liviur** [comment]
come on , this is really not an issue with the project. this is asking support for generally not knowing hot to sign apps.
This really is not what github issues is used for.

**Comment by jasarien** [comment]
https://github.com/jasarien/Provenance/wiki/Building-Provenance Follow the instructions. That's why they're there.

**Comment by cortneytaylor** [comment]
I'm not entirely sure that the instructions are as clear as they could be. Per the instructions, the only difference between iOS and tvOS deployments would be selecting the device and the target, but that fails (at least if you're on a personal team). A clarification that the team needs to be able to sign tvOS apps would go a long way for those that aren't developers, yet want to build this to their devices (as well as needing to update the bundle identifier for personal teams).

**Comment by jasarien** [comment]
@cortneytaylor 
I updated the build instructions, just for you :P

**Comment by cortneytaylor** [comment]
Much thanks. :) I'm sure it'll be helpful to others in the future. It's incredibly detailed now. Well done!

I actually found where the discrepancy is. If you have a developer account, it should work exactly how it was stated before. However, since a Devon account isn't required anymore to side load apps, those that are just using their Apple ID have to adjust the bundle identifier, exactly how you've stated in the instructions. I'm sure that's where most of the issues were coming from.

As always, excellent work! Thanks for devoting so much time and effort into a project so many love.

**Comment by theschwiz** [comment]
Hi,  Hopefully this thread is still sending notifications.

So I followed the posted instructions to the T and loaded Provenance onto my iPad air 2 yesterday without any issues.  Today I'm trying with my Apple TV Gen 4 with the modified instructions of adjusting to the TV-Release, and changing the bundle Identifier.  but I'm getting an error and it won't load onto my apple tv.  Hopefully someone can provide some guidance.

Im getting this error, even though on the main tab, I'm changing the Bundle Identifier:


Code Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.jamsoftonline.ProvenanceTV” were found.
No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.jamsoftonline.ProvenanceTV” were found.


Any help is appreciated.  BTW, I really appreciate the work on this, it runs flawlessly on my iPad.  Thanks for your hard work!

**Comment by migitalwarfare** [comment]
I found the solution to this last night. You need to go into ProvenanceTV target, go to the Build Settings tab, and change the Base SDK from "Latest iOS" to "Latest tvOS" in order to get around the provisioning error that jrey1989  was seeing. I had the same issue, and this is what fixed it for me.
