### ISSUE TITLE
apple tv steelseries nimbus dpad requires hard presses to register in game, works fine in Provenance menus

### ISSUE THREAD

**Issue by kaikai1234** [jasarien/Provenance#168]
apple tv steelseries nimbus dpad requires hard presses to register in game, but works fine in Provenance menus.which is strange must be something to do with apples stupid idea of pressure sensitive buttons lol, hope u can look into it  as at the moment its unplayable due to this. 

 also the analog stick is all over the place(same with most games on app store), most likely due to apple having so many controllers but as steelseries nimbus is the only made for apple tv controller so we might get devs getting a handle on these issues.

**Comment by jpete24** [comment]
I'll have mine loaded on my Apple TV tomorrow to confirm this. I also have the nimbus.

**Comment by jpete24** [comment]
This definitely an issue with the Steelseries Nimbus dpad. Not sure if its something on the hardware end or on the Provenance software side of things. Weird deal. Can you see if there is a decrease on mfi controller sensitivity?

**Comment by jpete24** [comment]
I do recall Nimbus having pressure sensitive buttons....

**Comment by jasarien** [comment]
All MFi controllers have pressure sensitive controls. It's part of the specification set out by Apple. It just differs between companies and designs as to how much pressure is required to register a press.

**Comment by jpete24** [comment]
Can you make an adjustment? Or is it a Steelseries issue?

**Comment by jasarien** [comment]
Sure, I could make the adjustment, but then all other MFi controllers would go back to behaving unpredictably, which is why the change was made in the first place.

**Comment by pdnellius** [comment]
Could you enable dome sort of settings slider or toggle to adjust the sensitivity?

**Comment by jasarien** [comment]
Yeah, probably.

**Comment by pdnellius** [comment]
@jasarien, 

I'm getting one of these controllers so I'll fork and see if I can implement. Any idea where to look to hook into the pressure sensitivity?

**Comment by kaikai1234** [comment]
jasarien would it not be easier to make a fork just for steelseries nimbus with the changes needed, untill you can make a slider for sensitivity in the main branch. anyway thanks for porting this great emu.

**Comment by jasarien** [comment]
No, it doesn't make sense to maintain multiple branches with diverged features.

**Comment by jasarien** [comment]
Just be patient. It'll get done when it gets done :P

**Comment by kaikai1234** [comment]
no worries take your time, and thanks

**Comment by cplr** [comment]
If the same is true for the other SteelSeries controllers, the vendorName property of GCController could be used... Still special casing a bunch of controllers is definitely not the way to go :).

**Comment by jasarien** [comment]
It's not the case. The stratus xl is fine, it's the one I have.

**Comment by Japspre** [comment]
Was wondering if there was no support for the stratus but then I found this ticket :+1:
