### ISSUE TITLE
Controls misplaced and missing when starting game in portrait mode. (iPhone 6)

### ISSUE THREAD

**Issue by voxl** [jasarien/Provenance#170]
Starting a game in portrait mode looks like this:

![photo nov 01 20 15 57](https://cloud.githubusercontent.com/assets/13472697/10874224/93a7e074-80d5-11e5-9043-240d26bf02cd.png)

Workaround is to rotate to landscape, then back to portrait.

**Comment by jasarien** [comment]
Removed the edit controls functionality.

Sorry if anyone was using it, but it was buggy and not really that well done. I'll do something better in the future. At least removing this fixes the controls being misplaced when starting a game.
