### ISSUE TITLE
Provenance crashes upon pressing "menu" button (iPad Air)

### ISSUE THREAD

**Issue by romerawr** [jasarien/Provenance#172]
I'm using Provenance v. 1.1.6, downloaded from the UnlimApps Cydia repository, on my iPad Air (jailbroken on iOS 8.1.2). Pressing the "menu" button on any ROM (that I have, at least) causes the application to crash back to the home screen.

**Comment by jasarien** [comment]
This was fixed a long while ago. The version uploaded to 'unlimapps' is old and hasn't been updated.

**Comment by romerawr** [comment]
So, is there no official Cydia repository for Provenance? Is it only available through iEmulators' Buildstore?

**Comment by jasarien** [comment]
No there is no Cydia repo. The only officially supported method of installation is compiling it yourself and side loading to your device. iEmulators may upload builds from time to time, but I don't control it or support it.

**Comment by romerawr** [comment]
Okay, thank you for your help. The information regarding Provenance is confusing and disparate depending on the source. Thanks for clearing that up.

**Comment by jasarien** [comment]
This GitHub repo is the only source of official information. There are build instructions in the Wiki section.
