### ISSUE TITLE
Rename games in AppleTV UI

### ISSUE THREAD

**Issue by cbjornn** [jasarien/Provenance#173]

**Comment by jasarien** [comment]
This already a feature. Press and hold a game. 
![image](https://cloud.githubusercontent.com/assets/104444/10917041/a18e0a74-8256-11e5-9eac-5abe8c5c13a1.png)

**Comment by cbjornn** [comment]
Is this feature available for the Apple TV version though?

**Comment by asos-jamesaddyman** [comment]
No, but you didn't specify Apple TV in your issue report.

It's not available on Apple TV for a few reasons:

- There is no Asset Library on tvOS, meaning no way to choose a picture for cover art
- The text input on tvOS is diabolical, and there's no Siri Dictation API or bluetooth keyboard support, so I left it out.

**Comment by jasarien** [comment]
No, but you didn't specify Apple TV in your issue report.

It's not available on Apple TV for a few reasons:

There is no Asset Library on tvOS, meaning no way to choose a picture for cover art
The text input on tvOS is diabolical, and there's no Siri Dictation API or bluetooth keyboard support, so I left it out.

**Comment by chriscthompson** [comment]
Diabolical is the perfect word to describe the destruction they did to text input on tvOS. Lol

**Comment by kudit** [comment]
I wonder why they didn't keep the grid layout of characters as it would be even easier to navigate with the new siri remote.

**Comment by chriscthompson** [comment]
Or let's us do text to speech like iPhone text input

Or update the remote app to allow for easy text entry

Or allow iCloud sync of keychain passwords

Or allow Bluetooth keyboards

There are a lot of options for   to make this easier for everyone...

**Comment by Hanterdro** [comment]
"The text input on tvOS is diabolical, and there's no Siri Dictation API or bluetooth keyboard support, so I left it out."

There is since iOS 9.2 an remote app with an very comfortable software keyboard.

**Comment by ajmi982** [comment]
now that tvos 9.2 supports BT keyboards, could this be reopened?  I have a number of titles that dont have artwork, would be great to rename the titles and add artwork.

Or perhaps we can do it from the Import Roms screen in our browser? I was trying to find where the images are stored but cant find them

**Comment by apexad** [comment]
This issue can now be closed since it is now possible to rename games on tvOS.

**Comment by ajmi982** [comment]
Hi looks like lots of progress. He can I get latest build

**Comment by jasarien** [comment]
[Building Provenance](https://github.com/jasarien/Provenance/wiki/Building-Provenance)
