### ISSUE TITLE
Rotation Arrow Keys for Apple TV 4

### ISSUE THREAD

**Issue by skyfliers** [jasarien/Provenance#177]
For the Apple TV 4, have an option to change the up, down, left and right buttons on the controller to use the gyroscope. For example, if you were playing Mario Kart, you could tilt the controller right to turn right, like a steering wheel. Up, tilt up.

As the controller wouldn't need physical actions for the arrow keys, you could replace them. If you slid up, it emulates select? Just an idea, but probably pretty cool if it could be stable enough.

**Comment by atezanos** [comment]
That would be nice, although I don't know how much work it would take for them to implement, but +1

**Comment by jasarien** [comment]
I'm not sure if it would work that well, I think it would be too sensitive, and even with an artificial deadzone, it wouldn't feel as natural as it does for a more modern game like MaroKart on the Wii. 

A gyro control is inherently analogue with increasing values as the device is tilted, whereas all controllers for the systems supported in provenance are digital with simple pressed/released states. With this in mind, if you were to tilt the controller to the left the slightest bit the controller would register it as a press for the left or right control, and you'd find yourself constantly tilting back and forth trying to keep the game straight, lol :P

**Comment by skyfliers** [comment]
What if you had provenance tap the arrow keys repeatedly at different rates? For example, if you open Mario Kart and hold left, your character turns left fully. If you just tap it, your character only verges left. Maybe the farther you tilt your remote, the faster provenance taps until tilted sharply, where it would just hold. Even if it worked poorly with games such as Mario Kart, it could still open up the opertunity for more available buttons for games such as Pokemon.

**Comment by jasarien** [comment]
Or you could just get a relatively inexpensive Game Controller ;) lol

**Comment by skyfliers** [comment]
Far enough! Anyway, great job on Provenance. Awesome app! On last thing, I haven't bought an Apple TV 4 yet, to get Provenance, can you do it without an developer account? If so, is it nessecary to have a usb-c cord?

**Comment by jasarien** [comment]
Sorry, didn't mean to come across so bluntly. It just seems like a lot of work for something that I don't think would end up being that useful in the long run. But those game controllers are fantastic, they feel a lot more like the real controllers of old.

**Comment by jasarien** [comment]
As for the AppleTV, you need a developer account and a USB-C to USB-A cable, there's no other way to get Apps onto it that aren't from the App Store.
