### ISSUE TITLE
SNES filter support

### ISSUE THREAD

**Issue by ajiuo** [jasarien/Provenance#179]
Would also be cool to have a global setting and per game override. For some reason Mario world is laggy in emulation.

**Comment by jasarien** [comment]
Can you elaborate on this issue? I'm not sure exactly what it is you're asking. And how does it relate to Mario World being laggy? Are they two separate issues?

**Comment by ajiuo** [comment]
Most versions of snes9x have various smoothing filter option that make the picture look better on newer/bigger TV's... In fact most emulators have filter options... Not just snes9x

Super Mario world has always been a bit laggy on emulation... Filters seem to make that particular game a lot worse.

Dillon Fontaine
df78@me.com
801-898-3334

**Comment by jasarien** [comment]
Provenance doesn't use any filters, not even ones included with particular emulators. So lagginess in Super Mario World 2 is not attributable to filters. There is also already an issue regarding filter support: #54, so I'll close this one as a duplicate.
