### ISSUE TITLE
Code Signing Error

### ISSUE THREAD

**Issue by acarrow92** [jasarien/Provenance#184]
Getting "Code Sign error: No provisioning profiles found: No non–expired provisioning profiles were found." when compiling the app. Says "An App ID with Identifier 'com.jamsoftonline.ProvenanceTV' is not available. Please enter a different string."

Any help someone can provide would be greatly appreciated

**Comment by jasarien** [comment]
Please follow the build instructions. They're linked clearly from the repo's front page. https://github.com/jasarien/Provenance/wiki/Building-Provenance
