### ISSUE TITLE
Cannot connect to ip address

### ISSUE THREAD

**Issue by landocarlsjr** [jasarien/Provenance#186]
I am no longer able to connect to my Apple TV's IP address to upload ROMs. Only environmental change made was recently changed TVs to play in family area and now back to original TV location. Network settings haven't changed and I am unsure if its a network issue or if app needs to be reinstalled.

**Comment by jasarien** [comment]
How is the AppleTV connected to the network, Wifi, ethernet, both?

**Comment by landocarlsjr** [comment]
wifi.

**Comment by jasarien** [comment]
Does the IP shown by Provenance match the IP shown in the network settings for the Apple TV?

**Comment by landocarlsjr** [comment]
yes

**Comment by jasarien** [comment]
Have you tried disconnecting the wifi and reconnecting, or rebooting the Apple TV?

**Comment by landocarlsjr** [comment]
Yeah, I've tried restarting the Apple TV unit twice, as well as the network and no dice.

**Comment by landocarlsjr** [comment]
Should I try reserving the IP address?

**Comment by jasarien** [comment]
Sure, you can try. No idea if it'll make much difference. Honestly, I'm just guessing, here, I don't know why this would happen.

**Comment by landocarlsjr** [comment]
i reserved the ip address with my airport and its up and running! thanks for the prompt response!

**Comment by jasarien** [comment]
Cool :+1:
