### ISSUE TITLE
Auto-update app on Apple TV?

### ISSUE THREAD

**Issue by cbjornn** [jasarien/Provenance#190]
I'm not sure if there is already a way to manually/automatically update the app on the Apple TV but I am not seeing that exists yet. Would be great to have this feature.

**Comment by jasarien** [comment]
The only methods of auto updating on AppleTV are reserved for those apps in the App Store. Since Provenance is not in the App Store, it isn't able to benefit from a lot of the things other apps do, such as iCloud, Auto Update etc.
