### ISSUE TITLE
Is game-saving supposed to work (SNES)?

### ISSUE THREAD

**Issue by bsabiston** [jasarien/Provenance#193]
Hi I don't know if this is the right place to ask this.  I started playing Super Metroid through Provenance on my iPhone 5.  It's really awesome to see these old games reproduced so well and be able to play the, with something like the Mad Catz I have,

I haven't been able to save my games though,at least using the game's own save mechanisms.  It seems like it saved once and ever since, it has not saved again.  It says it saves, but when I re-run the game, it only shows that very first save I did.

I mean, luckily there are Provenance save game states, so I can use that to save at any time I want, so maybe the question is moot.  I was just wondering if the in-game saving is supposed to work.

Thanks!
Bob

**Comment by jasarien** [comment]
Game saving is definitely supposed to work. It definitely works with Chrono Trigger, i just tested it. Can you try another SNES game and let me know if saves work for you on other games?

**Comment by jasarien** [comment]
I just tested saving on Super Metroid and it seems fine to me. You mentioned Save States, which might be having an effect here.

Using Save States can possibly interfere with game saves (also known as Battery Saves, since the original cartridges used to have battery powered memory chips). When you make a Save State, the state of the console's memory is dumped to a file, exactly as it was at that point in time.

If you can try starting a new game of Super Metroid without loading from a Save State first (make sure the auto load save states option is off in the settings, which it is by default), and let me know if Battery Saves work then?

**Comment by bsabiston** [comment]
Hm, It doesn’t seem to work for me.  As I said, it does make the very first battery save, but saves after that aren’t recording.  When you tried it, did you try two saves?  The initial one and then a second one a few minutes later? 

Seems like it is doing the same thing with Zelda Link to the past.  I’m pretty sure I did a save a little ways into Earthbound, too — only now when I continue my game it starts from the beginning. 

I do have some save states saved, maybe on all three of those games, though I didn’t use them and terminated the process before trying to replicate this issue.  Could just having the previous save states there, even if I don’t load them, cause the problem?

Thanks
bob

**Comment by jasarien** [comment]
I tested again with Chrono Trigger and saved multiple times, changing things in between, like spending some money, letting the game time advance, etc. Each time I saved, there was something to note a difference in, like how much money I had or what time the previous save was.

First save had 400g, spent some money down to 380g, saved again, reloaded save after quitting and restarting the emulator, save loaded with 380g.

In all cases the game saved correctly and when I quit the emulator and restarted the game from the beginning and loaded the save, the saved game was restored correctly.

I'm curious as to some other factors for your device. You said it was an iPhone 5, correct? Which OS are you running? How much storage space is available on your phone and have you tried this on another phone or an appletv (if you have one to test with)?

**Comment by bsabiston** [comment]
I just tried Chrono Trigger — on that one it doesn’t seem to save at all, for me.  I can save to the slots, but if I restart the game there are no saves.  It’s weird though, if I start the web server I can see the folder that says Battery Saves, and there’s a Chrono Trigger.sav in there.  When you start Chrono Trigger does it make you watch that overhead scene with the balloons, and enter a name and then  that scene where you get out of bed, before you can bring up the menu to load a save file?  Mine does that and then lists no saves in the slots.

Yeah iPhone 5 running iOS 9.1.  The Provenance version is 1.2.4.  I’ve got almost 2GB free space.

I just noticed in the Provenance settings that ‘Auto Save’ is on, though Automatically Load Autosaves on Launch is off.  Could that be an issue?  I never messed with those before though.

I do have an Apple TV with Provenance installed on it.  I’m pretty sure that works w/saves because I started playing Zelda on it and I think I’ve reloaded once.  But I will double check when I go home today.

Thanks
Bob

**Comment by bsabiston** [comment]
I also took a look at the console output in Xcode while trying to do these saves, and there’s nothing.

**Comment by jasarien** [comment]
"that scene where you get out of bed, before you can bring up the menu to load a save file?"

No, mine shows the Load Game menu as the first thing when starting the game, it even shows the save number (number 3 in this case) eg:
![Load Game](http://d.pr/i/1jDwi+)

Do you think you'd be able to record a video somehow of how you're starting the game, loading a save, etc, just so I can see exactly what's going on. It's so difficult to debug an issue when you can't reproduce it yourself, and seeing the steps end to end can help in some cases.

**Comment by bsabiston** [comment]
Yes, I can record something.  Have you tried it with the Simulator? Because I get the same issue when I try it in the iPhone 6 Simulator for example.

Thanks
Bob

**Comment by bsabiston** [comment]
Just wondering, might it be the roms themselves?  Maybe I got hold of some roms that had been modified and don’t save correctly?

**Comment by jasarien** [comment]
It could be the ROMs. Try with some others? Here's a video of it working in the simulator. http://d.pr/v/10eCM

**Comment by bsabiston** [comment]
Yeah, my Chrono Trigger does not show the load screen on start.    Do you know a website that has a reliable rom of CT?

**Comment by jasarien** [comment]
I can't help you find a particular ROM - legality and all that - but you could try looking for a version of Chrono Trigger from the No-Intro rom collection, they're usually reliable.

**Comment by bsabiston** [comment]
That must be what it was.  I tried a different version of Chrono Trigger and it worked the way yours does.  
Thanks,
Bob

**Comment by jasarien** [comment]
Awesome. Enjoy. Don't download bad ROMs, kids.

**Comment by bsabiston** [comment]
Hey sorry to bother you with this again.  Has anyone else reported being unable to save?  I've spent the past month playing Suoer Metroid, and I just used Save States so I stopped paying attention to the native saves.  But the other day I started The Legend of Zelda and I was trying to play it using the native saves.  But it just refuses to save.  I was pretty sure I had a good rom after the exchange we had from last month, but just to be sure, I downloaded the whole set of no-intro Roms today and tried again.  It just will not hold a save.  No one else has reported having this problem?
Thanks 
Bob

**Comment by G3NSVRV** [comment]
Same here, I cannot save game battery and game states in Kirby Super Deluxe, Hoshi no Kirby Super Star (both Roms of no-intro).

I'm using Provenance 1.3.2 (builds.io), and iOS 10.3 on iPhone 5

**Comment by G3NSVRV** [comment]
same error with **1.5 beta, release develop/a238067a** with Kirby Super Star (USA) (no intro)

**Comment by jasarien** [comment]
Saves fine for me on the latest builds. You probably have a bad Rom like the other people in this issue in the past. 
![d50a6ca2-0a04-4268-a993-73bafeda7bfb](https://user-images.githubusercontent.com/104444/41050742-2fe7f048-69ac-11e8-9ed9-fdc5c6362dbf.png)

**Comment by sevdestruct** [comment]
Also, @G3NSVRV, builds.io is not an official build of the app, and we can't guarantee anything in it works correctly. We advise you to delete it and install from this GitHub only, the official source. Instructions are in the wiki here.
