### ISSUE TITLE
Famicom Disk System Side B

### ISSUE THREAD

**Issue by apexad** [jasarien/Provenance#194]
A few games require that you flip to Side B, how do you do this in Provenance?

**Comment by jasarien** [comment]
I wasn't aware of this, I'll look into it.

**Comment by apexad** [comment]
A good example is called Yume Kōjō: Doki Doki Panic.

**Comment by jasarien** [comment]
Thanks, I'll check it out.

**Comment by silvercomet** [comment]
The two other games are Lutter (japan) and Samurai Sword. With Samurai sword, you click for a while then it asks for disc B. It would be great if you can configure the menu to have an auto button that only applies to FDS to auto eject disk and switch side B. In other emulator, you would have to click on menu to eject disk, then flip side, then insert the disc again then the Rom will continue again.

I look forward to the new update that will fix from you James!

**Comment by jasarien** [comment]
Fixed in 5925bc5a75f9f96154b49d46a1ad4ad3c3c26945

When the game asks you to swap sides, just press the Menu button, and choose "Swap Disk". You should see a message near the bottom of the screen telling you the disk was ejected, swapped and inserted. The game should then progress.
