### ISSUE TITLE
SNES sound/music issues in Super Star Wars, Super Star Wars: The Empire Strikes Back, and Super Star Wars: Return of The Jedi

### ISSUE THREAD

**Issue by dashby07** [jasarien/Provenance#195]
The audio in all three games is choppy. I'm not sure if anyone else has noticed.

**Comment by jasarien** [comment]
Did you make sure to build with the Release scheme?

**Comment by jasarien** [comment]
The audio on Star Wars doesnt' sound choppy to me in Release mode, but there does seem to be some annoying background drone on the audio that doesn't seem right.

What device/OS version are you running Provenance on?

**Comment by dashby07** [comment]
I think the background drone is what I'm hearing. Sorry I wasn't more specific. I'm using the latest update of Provenance on Apple TV 4, ipad Air 2, and iphone 6s+.
