### ISSUE TITLE
Sega CD BIOS WIKI

### ISSUE THREAD

**Issue by typkrft** [jasarien/Provenance#197]
Not sure if it is different on the TV, but you cannot get to the documents folder. The wiki should read "/BIOS/com.provenance.segacd/" It might also help to have a bios folder created by default or to let users  put the BIOS in the roms folder and have them auto sort to the appropriate folder. It was pretty confusing to create a BIOS folder then create another folder called "com.provenance.segacd", as there is one already then rename my BIOS and put them in there. I'd be happy to make those edits(as far as the wiki goes), but I don't want to impose if they are like that for some reason.

**Comment by jasarien** [comment]
I'll update the Wiki to remove the reference to `/Documents/`, but the rest of it is just the way things are.

Automatically importing BIOS ROMs would be nice, but I don't think there would be a reliable way to know which system a BIOS is intended for, or which region it's intended to be, etc.

I'm considering a refactoring of the directory structures within Provenance to simplify things, so these steps might get less confusing in the future.

Maybe I'll have a single system folder with the name `com.provenance.x` and within that have a `BIOS` folder, `ROMs`, `saves`, etc.
