### ISSUE TITLE
Web Server not working on tvOS

### ISSUE THREAD

**Issue by heinst** [jasarien/Provenance#202]
Just loaded the latest release target and nothing loads when trying to connect to the webserver, I can ping the Apple TV fine, but when trying to load the upload rom page, I just sit there waiting for it to load. Also the webserver page gives me a 192.168.1... IP. Is there a certain port I need to put? Or is this a bug?

**Comment by heinst** [comment]
I found out my Apple TV needed to be updated...fixed the issue

**Comment by hstriepe** [comment]
Do you have a wired ethernet connection? I found I had to go to WiFi, since it started giving itself self assigned addresses. Have not tried to see, whether the update fixed it.
