### ISSUE TITLE
controller assignments not saving on latest update, apple tv

### ISSUE THREAD

**Issue by kaikai1234** [jasarien/Provenance#203]
hi the controller assignments on apple tv  before the latest update used to save but now i have to go into settings to change the controller to player1 every time i open the app. it keeps putting the dam remote as player1. is there anyway to have have the controller as player1 by default and not have to change it every time.

**Comment by jasarien** [comment]
Provenance doesn't persist the controller selections, sorry. I don't think it can be done, since controller's don't have a unique identifier. All they have is a vendor and model name, which might be the same in some situations, e.g. if you have two controllers that are identical connected.

Maybe in the future if it becomes easier to distinguish between controllers.

**Comment by kaikai1234** [comment]
ok thanks for reply but how does other apps archive this e.g in rayman adventures it disables the remote when the game is played with the controller ,so it must be able  to distinguish between controllers and remotes.

**Comment by jasarien** [comment]
I've committed some code to prefer an extended or standard gamepad over. Checkout the latest, rebuild and let me know how it works for you.

**Comment by kaikai1234** [comment]
i thing you broke something on the latest.  pressing the menu button it now exits out of the app.

**Comment by jasarien** [comment]
Ah, my bad - that was from another piece of work I did earlier around disk swapping and the Famicom Disk System. Should be fixed in the latest commit. Let me know.

**Comment by kaikai1234** [comment]
app working now,controllers still behave the same, i guess i  can live with it, i just have make sure to only open the app with the controller only. thanks for this great app, classic retro games on apple tv with no jailbreak, i thought i would never see that day lol.

**Comment by jasarien** [comment]
Do you turn the controller on after starting provenance?

**Comment by kaikai1234** [comment]
nah both are connected but basically if i open app with remote that becomes player1 and i have to settings and change it back but if i open with the controller its fine controller stays as player1, i just have learn to only opening emu with controller and it should be fine.
