### ISSUE TITLE
Sound glitch issues in Final Fantasy 1 & 2 GBA

### ISSUE THREAD

**Issue by gh0sti** [jasarien/Provenance#206]
makes weird noises playing the game was playing FF2

**Comment by jasarien** [comment]
Did you build it yourself? Did you make sure to use the Release scheme? Which hardware are you running on?

**Comment by jasarien** [comment]
Just tried the FF 1 & 2 Advance ROM - is that the one you tried? It sounds fine to me when running in release mode.
