### ISSUE TITLE
Add BlueMSX for MSX support from OpenEMU

### ISSUE THREAD

**Issue by jamhayesshopping** [jasarien/Provenance#209]
Would be good to have MSX 1/2/2+ emulation included if possible. Only support for ROM cartridges and joystick mapping and using C-Bios etc if including disk support. Basically whatever OpenEMU uses.

That would allow a limited subset of MSX games but pretty much everything good was on ROM cartridge anyway (except a couple on disk) as the MSX is where a surprising amount of franchises started or had their best versions.

**Comment by jasarien** [comment]
I have no plans to include support for this system at this time.
