### ISSUE TITLE
Fast forward/Frameskip

### ISSUE THREAD

**Issue by jasarien** [jasarien/Provenance#21]

**Comment by callmekevo** [comment]
Want to write something productive in here? Something as simple as "this emulator does and will not have this feature"

**Comment by jasarien** [comment]
Or we can just leave it here to be tracked, as intended, until it is either implemented or closed.

**Comment by callmekevo** [comment]
Eh. Information is what's going to help you, not ambiguity.

**Comment by jasarien** [comment]
Ok, here's some information. Until this feature is decided upon one way or the other, the issue will be left here to track.

**Comment by josejulio** [comment]
@callmekevo this list of "issues" is used as "feature requests", so the point of "Fast forward/Frameskip" is to implement a way to "fast forward or skip frames feature" (or close for some reason, but that's up to the owner of this project).

**Comment by callmekevo** [comment]
Great! Now put that exact thing on the site so people who are interested in
your project can know!

**Comment by jasarien** [comment]
Looks like I was too hasty closing this one. Worked fine in the simulator, but not on device. Oh well, back to the drawing board.

**Comment by jasarien** [comment]
Ok, should be working in 54caeaeff9d58383638b97ba323fa7b5122a7038

SNES will show some flickering while fast-forwarding due to having to disable drawing synchronisation. Flickering goes away when disabling fast forward.
