### ISSUE TITLE
Unable to build newest release

### ISSUE THREAD

**Issue by big-three** [jasarien/Provenance#215]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AVAudioSession", referenced from:
      objc-class-ref in libPVSupportTV.a(OEGameAudio.o)
  "_AVAudioSessionCategoryAmbient", referenced from:
      -[OEGameAudio initWithCore:] in libPVSupportTV.a(OEGameAudio.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Am absolutely opening the workspace. Apple TV is plugged in, ProvenenceTV-Release selected. Using 1.2.6.

**Comment by jasarien** [comment]
Should be fixed in the latest commit. 2444e8162f57c394c3b1ac9d72f43098bfd0547e
