### ISSUE TITLE
[Request] Receive ROMs by iOS Sharing

### ISSUE THREAD

**Issue by wviana** [jasarien/Provenance#217]
My coworker sent to me some ROMs that he has on his Android thought SuperBeam.
When I selected the share to a ROM, it did show a lot of apps as Evernote, Telegram, Notes, but it didn't show Provenance.

Would be great to be able to transfer ROMs from other apps to Provenance by iOS sharing.

**Comment by jasarien** [comment]
If the ROM is not zipped, then Provenance won't show up in the share sheet. When sharing a ROM make sure it's zipped and you'll be able to select Provenance from the share sheet.

**Comment by jasarien** [comment]
I've just committed a change that should allow any arbitrary data file rather than just Zips.

This also means that any file that conforms to the public.data type will also be openable in Provenance, but obviously if it's not a ROM it won't import.

**Comment by wviana** [comment]
So great, 
Thank you very much @jasarien
