### ISSUE TITLE
A buildbot for latest nightlies needed

### ISSUE THREAD

**Issue by bronnel** [jasarien/Provenance#219]
Getting a cydia repo to dump all latest nightlies would be nice , there's only one version on cydia right now from unlimapps repo which is bugy everytime I press the menu button with ps3 controller it crashes, I think this bug was fixed in an earlear build But I cannot get the deb file to install it using ifile, It would be if someone could get us a deb file to install using ifile ,
And yes I know I can install from iemulators.com but that is for non jailbroken devices, Im on iOS 8.4 jailbroken with Taij.

**Comment by jasarien** [comment]
I don't support Cydia or the jailbreak community. If someone else wants to that's fine.

**Comment by bronnel** [comment]
Ok but how to get latest nighly build installed, I have an iPhone not jailbroken And I want to install the latest version,

**Comment by jasarien** [comment]
By following these instructions. https://github.com/jasarien/Provenance/wiki/Building-Provenance

**Comment by bronnel** [comment]
Ok thanks man

**Comment by bronnel** [comment]
Sorry to bother you, but I have one question, my iphone is on ios 8 , so should I install the sdk for ios 8 or I should update to ios 9, in another word do I have to be on the latest iOS? Thanks for your replies

**Comment by jasarien** [comment]
It should build to iOS 8 just fine.

**Comment by bronnel** [comment]
So its ok to ios 9 sdk and build for ios 8.

**Comment by jasarien** [comment]
Yes

**Comment by bronnel** [comment]
Thanks a lot https://github.com/jasarien for this amazing emulator, I appreciate your work, and I hope psx ( playstation ) will be supported in future.
