### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by mioz1990** [jasarien/Provenance#221]
Hi!

I have an issue on Xcode during the compilation of the program that says...

"An App ID with Identifier 'com.jamsoftonline.ProvenanceTV' is not available. Please enter a different string."

Someone can help me? What i have to do?

Thanx!

**Comment by jasarien** [comment]
Please follow the instructions: https://github.com/jasarien/Provenance/wiki/Building-Provenance

**Comment by appletv4** [comment]
change jamsoftonline to something else

**Comment by mioz1990** [comment]
Thanx for your help! finally i could install it on my apple tv
