### ISSUE TITLE
Transfer of large ROMs ( MegaCD ) timeout / fail

### ISSUE THREAD

**Issue by mkdj69** [jasarien/Provenance#222]
Hi jasarien,

Interesting one this one.

I'm having trouble uploading large ROMs, MegaCD's, to my iPhone 5S ( 9.0.2 ), iPad Air 1 (9.0.2) and Apple TV 4 (9.0.1 ) - but the simulators work fine.

As per the wiki, naming/ZIP requirements are met - hence the simulator being ok, but I may get about 75% on the Apple TV 4 and about 10-20% on the others before an error.

One thing I noticed is that the simulator wants me to connect via 8080 but the real devices with out them.  I'm static IP's on all devices but have tried dynamic.  The Apple TV 4 is hard wired.

I'm open for suggestions for further testing ... all other types are OK except for MegaCD's.

If you need screen dumps of the errors - let me know.

Markus.

**Comment by jasarien** [comment]
If there's any output from the console log, I'd be interest to see that.

**Comment by mkdj69** [comment]
Good point - I'll get back to you.

**Comment by mkdj69** [comment]
OK, just gave it a shot on the iPhone 5S ( 9.0.2 )

2015-11-22 15:45:57.428 Provenance[999:46116] Reachability Flag Status: -R ------- networkStatusForFlags
[INFO] GCDWebUploader started on port 80 and reachable at http://192.168.0.81/
2015-11-22 15:45:57.453 Provenance[999:46116] Interface name: lo0
2015-11-22 15:45:57.453 Provenance[999:46116] Interface name: pdp_ip0
2015-11-22 15:45:57.454 Provenance[999:46116] Interface name: en0
[INFO] GCDWebUploader now reachable at http://MkDjs-iPhone-5S.local/
[ERROR] No more data available on socket 10
[ERROR] Failed closing request body for socket 10: (null)

**Comment by mkdj69** [comment]
OK, just gave it a shot on the iPhone Simulator ( 9.0 ) - successful:

[INFO] GCDWebUploader started on port 8080 and reachable at http://192.168.0.100:8080/
2015-11-22 16:26:27.951 Provenance[77648:3641935] Interface name: lo0
2015-11-22 16:26:27.952 Provenance[77648:3641935] Interface name: en0
[INFO] GCDWebUploader now reachable at http://MkDjs-iMac.local:8080/
2015-11-22 16:27:51.940 Provenance[77648:3641935] [UPLOAD] /Users/mkdj/Library/Developer/CoreSimulator/Devices/8B67216D-17D9-41AD-AB05-0BC976D7AC56/data/Containers/Data/Application/30736ACE-7389-462E-A233-54272A5B051B/Documents/roms/Sonic_CD-PAL_EU.zip
[INFO] GCDWebUploader stopped

**Comment by jasarien** [comment]
I had a look in the code and this error is printed when there is no data in the request when it was expecting some, which would lead me to think there is a connection issue between the phone and your router. 

Testing between Simulator and device isn't really helpful, because the simulator runs locally on the same machine, so the transfer isn't going over the network.

I know it's frustrating to hear, but this isn't an issue with Provenance, as far as I can tell - you will need to try and find out why the transfer is failing on your network.
