### ISSUE TITLE
Setting menu problem

### ISSUE THREAD

**Issue by illando** [jasarien/Provenance#223]
In the  1.2.6 version on iphone and ipad (ios9.1) there is a bug in the setting menu.

If you click on the "Import/export Rom & Saves" it activates the "Refresh game library" command instead of starting the web server.
The web server is conneted to the icade controller command.

Thanks.

**Comment by jasarien** [comment]
Thanks. I'll take a look. Meanwhile you can start the web server from the the + button on the game library screen too.
