### ISSUE TITLE
SegaCD files with "_" in name get misnamed in the GUI

### ISSUE THREAD

**Issue by bluepixel00** [jasarien/Provenance#224]
Any SegaCD image with a "\_" in the name will get renamed to a different title with box art in the interface.  If I manually edit the cue file and rename the cue and bin to remove the "\_" the name in the interface reflects the file name but also does not have box art.

**Comment by jasarien** [comment]
In this situation do the cue sheet and the cd image file have the exact same name (excluding the extension)?

ie: Sonic_CD.cue & Sonic_CD.bin

Or do you have something like SonicCD.cue & SonicCD_US.bin?

**Comment by bluepixel00** [comment]
Yes all file names and the cue sheet details match.

**Comment by jasarien** [comment]
Ok, if you'd be able to let me know the file name of the ROM you experienced this issue with, then I can test it out.

**Comment by bluepixel00** [comment]
THE_TERMINATOR.bin / THE_TERMINATOR.cue

If I change the name to just TERMINATOR.bin / TERMINATOR.cue it is properly named in the UI without any album art.

By the way thanks for all your work on Provenance!

**Comment by bluepixel00** [comment]
Just to add that this was observed on the tvOS,  I did not test this on iOS.

**Comment by jasarien** [comment]
I had a look into this one. It's a side effect of a couple of fixes done in the past to try and look up game info by name (which is highly unreliable as it is). If the ROM hash lookup fails, it does a naive text search based on the ROM's filename. The underscore interferes with the text search and only "The" is actually searched, and the first game entry in the results for that search is "The Adventures of Batman and Robin".

My suggested fix would be to use a ROM from a reliable source (such as the No Intro collection) that hasn't modified the contents at all, which means the hash will be intact and will match what is in the database. Or do as you're currently doing and remove the underscores before uploading and make do without the cover artwork (or add your own if using iOS).

You can browse the OpenVGDB database to see which ROM hashes will successfully return game info.
