### ISSUE TITLE
Add optional on-screen quick load/save buttons

### ISSUE THREAD

**Issue by tgwaste** [jasarien/Provenance#227]

**Comment by marcelvoss** [comment]
I'm not sure if another on-screen control makes too much sense. For quick saves we could maybe consider adding a shake gesture that will automatically create a new save state every time the user shakes their device.

**Comment by tgwaste** [comment]
What do you mean 'not make much sense'?   Its makes perfect sense.  I think you mean 'not be desirable' which is relative.   The suggestion to shake misses the point of the request imho.  I can understand it not being desirable but it sure would add a world of convenience.

**Comment by marcelvoss** [comment]
Because the iPhone screen has already a very limited space and since we haven't implemented a way to customize the position be size of controls adding more controls to said limited screen space doesn't make sense.

**Comment by sevdestruct** [comment]
I'm looking into a small expandable HUD for Overlay Overhaul (#718) but not sure this will make it into the UI in this form..

**Comment by sevdestruct** [comment]
Maybe we can roll something similar into the quick change view Joe and I briefly discussed recently, gonna close this for now, absorbing this as a consideration for overlay overhaul or in-game quick change view ..
