### ISSUE TITLE
iCade/8bitdo snes30 crashes Provenance

### ISSUE THREAD

**Issue by CSPhobos** [jasarien/Provenance#228]
Hello, I just downloaded and pushed 1.2.6 to my iPhone 6s (iOS 9.1), and my 8bitdo SNES30 doesn't work with it. It either does nothing (while playing SNES games), or it crashes Provenance as soon as I press a button. I do not know how to do the diagnostics you might need, though. :L

**Comment by andematt** [comment]
I am also seeing this. I checked out "6ed2175" just to go back some amount of time and make sure my new snes30 was not DOA. I have not dug in much, there may be a crash log we could reproduce/generate although mainly I saw just no "reaction" to the controller (button presses did nothing, on screen controls stayed up, etc). I think it was when I chose "disconnect iCade" and then pressed a controller button that the app would crash.

**Comment by jasarien** [comment]
ICade support is likely broken since I refactored the input code to reduce latency. I don't have iCade hardware to test with, so I'll need @josejulio to look into it when he has some spare time (@josejulio is Provenance's resident iCade expert ;) )

**Comment by josejulio** [comment]
I had some time to check, there is an error on the hack-ish way the ICadeController is implemented.
Didn't implement the setPlayerIndex: method on it.

After adding, it no longer crash, but still doesn't work. I'll keep checking.

**Comment by bluevoice** [comment]
Hi guys, I also have the iCade/8bitdo snes30 console so I can also do some testing, but how on earth did you get the console paired with tha Apple TV? My Apple TV doesn't see the console when I go to Bluetooth devices.

**Comment by jasarien** [comment]
iCade controllers aren't compatible with AppleTV, they only work with iOS. This is because iCade controllers are Bluetooth keyboards and AppleTV doesn't support Bluetooth keyboards. If you want a controller for Apple TV you will need to buy one of the MFi controllers.

**Comment by bluevoice** [comment]
@jasarien Thank you for your explanation!

**Comment by xxredxpandaxx** [comment]
any update on the iCade controller crash?

**Comment by jasarien** [comment]
I think @josejulio is still working on it.

**Comment by pjpalomaki** [comment]
My buys would like to see their Snes30's working too.. ;-)

Slightly off-topic, is it possible to have two Snes30's (you can pair them as two keyboards in a specific way, they have different key-mappings to each other) working in Provenance? Either in iCade mode or in BT keyboard mode?

**Comment by jasarien** [comment]
Well just sit tight and it'll get done when it gets done.

**Comment by josejulio** [comment]
I'm sort of busy at this point (new job), so don't except it really soon, sorry, meanwhile you can try previous version of provenance where iCade is working well!

@pjpalomaki About having two snes30's, BT keyboard mode wouldn't work well, because it only reports button presses, not button releases (like iCade), plus I'm sure that BT mode and iCade mode have some common keys.
What would work, was if 8bitdo (snes30 manufacturers) enabled iCade player 1 and iCade player2 (player 1 uses lower cases while player2 uses upper cases).

**Comment by pjpalomaki** [comment]
Thanks @josejulio I've contacted the manufacturer and requested a firmware update, they seem fairly good with updates to their controllers. Shame I can't use any of them on AppleTV.. no MFi.

**Comment by pjpalomaki** [comment]
Sorry, could someone clarify the issue with BT keyboard mode (i.e. no separate key-up character) - I saw in the code that you're using OpenEmu code for the controller, is that right? In OpenEmu, I can use BT keyboard mode and you only map one key for each button (no up-key) - how is this possible in OpenEmu but not in Provenance? Just trying to get my head around it... 

I know that if you use iCade mode, you have to have both down and up keys, but how does OpenEmu get around this without iCade mode?

**Comment by jasarien** [comment]
Provenance doesn't use the same controller code as OpenEmu. The two are completely different.

As far as I understand, the BT keyboard limitation is with iOS. iOS only listens for keydown events, and key up events are ignored, so in order to simulate a button being pushed and subsequently released, the iCade controller, for example, sends a key press for H for a press and G for a release. So one button on an iCade controller occupies two keys on the BT keyboard, one for push, one for release. There are 26 (plus some others) usable keys on the keyboard, and 12 buttons on a SNES 30 controller. 12 * 2 = 24, almost maxing out the usable keys and not leaving any left for a player 2.

**Comment by pjpalomaki** [comment]
Thanks @jasarien, that explains it, I thought it would be an iOS API/Framework issue .. And I assume you're not interested in complicating the code with a private API like this? It would widen the controller compatibility (and having to 'support' them too... ) : [https://gist.github.com/steventroughtonsmith/7515380] (https://gist.github.com/steventroughtonsmith/7515380)

**Comment by jasarien** [comment]
The uppercase solution requires the manufacturer to update the firmware on the controllers. 

As for private API I prefer to stay away from hem in general. They're private for a reason and can't be relied upon.

**Comment by pjpalomaki** [comment]
Thanks @jasarien

**Comment by kennellroxco** [comment]
@josejulio, what version of Provenance would you suggest using where iCade was working well? Thanks!

**Comment by josejulio** [comment]
Not really sure what version, but below is a link to the last commit that is confirmed to work (https://github.com/jasarien/Provenance/pull/129):

https://github.com/jasarien/Provenance/commit/ab028dfa8ac14de6426d054c881fa51b4ab535a6

**Comment by kennellroxco** [comment]
Thanks @josejulio! I was able to get the controller to work with the commit you listed (once I rolled the firmware back on the controller to v1.6). The only issue now is the buttons seem to be reversed (A/B, X/Y, Start/Select). Is there an easy hack I can do on my local instance to reverse them? If not, I can live with it until you're able to get around updating it for the current version of Provenance. At least I can play games with it now :)

**Comment by appletv4** [comment]
With keyboard support coming to TVOS
http://forums.macrumors.com/threads/apple-seeds-first-beta-of-tvos-9-2-to-developers.1949864/

WILL.  Controllers like this 8bitdo work with provenance on Apple TV ?

**Comment by josejulio** [comment]
If i happen to get some time to actually make it work on iOS (or if someone else joins the iCade side of the controller), sure!
Sorry for the delay, new (good) things going on this year :).

**Comment by pjpalomaki** [comment]
@josejulio Do you have any idea at this stage what the issue could be and is it a big fix or a small tweak to get iCade working? I wish I could help, but my coding skill tree is seriously lacking point allocations...

**Comment by josejulio** [comment]
Well, the current iCade engine needs to have a zero size view (which implements a keyboard listener) that needs to be on every view, on top of that, the implementation that is currently on provenance extends the GCController class, but every method needs to be implemented.

As far as I have looked, (1) I didn't implement a method that is being currently used and (2) The keyboard listener is not receiving the input, probably because the keyboard listener is not well placed on the current key window.

I'll try to commit (1) to my fork, in case someone can give me a hand.

**Comment by appletv4** [comment]
@josejulio do you have the new Apple TV ? 
If you make it work on iOS  ,can you do it for the Apple TV without having one

**Comment by josejulio** [comment]
I don't have the new Apple TV. And I don't know if i could make it work on the Apple TV, hopefully yes.

**Comment by DanielFontes** [comment]
Good News: AppleTV and 8bitdo (iCade) is working fine with tvOS 9.2
Bad News: Only in debug mode so far (hasText isn't working and keyPressed seems to work only in debug mode)

**Comment by appletv4** [comment]
@DanielFontes thats great
I don't have a paid developer account, but when it becomes public ill try out  your version, which controller are you using from 8bitdo?

**Comment by DanielFontes** [comment]
@appletv4 SFC30

**Comment by appletv4** [comment]
@josejulio @DanielFontes  any updates ?

**Comment by oldschoolv** [comment]
Just want to say GREAT WORK on the Provenance project.  tvOS is the ideal platform for this app, **ideally with 2 8bitdo SNES30 though.**

I am confirming that with this HORIPAD (HIP-047U) remote, there is no noticeable lag at all with NES / SNES (on tvOS 9.0 & tvOS 9.2)(Provenance 1.2.6)  - http://www.apple.com/shop/product/HJ172ZM/A/horipad-ultimate-wireless-game-controller
_but its NOT a SNES style and too big for these old school games -_

Also confirmed on ATV4 - tvOS 9.2 beta (Provenance 1.2.6) NOW connects to the 8bitdo SNES30(2.65-latest) **DOES connect** in both keyboard(2)mode and iCade(3)mode, **but does NOT show up in Provenance as controller option (in either mode) ANY IDEAS???**    keyboard(2)mode and iCade(3)mode both "show up" on ATV4 as bluetooth keyboard 

Also FYI @jasarien @josejulio - the 8Bitdo SNES30 (2.65) has two player option in keyboard(2)mode = (KB) 
Button Mapping outlined below (default remote settings)
MODE(2-1P) KB: UP- DOWN- LEFT- RIGHT- L- R- SELECT- START- Y- X- B- A-
c d e f k m n o i h j g (no release)
MODE(2-2P) KB: UP- DOWN- LEFT- RIGHT- L- R- SELECT- START- Y- X- B- A-
p q r a v w x y t s u b (no release)
MODE(3) iCade: UP-  DOWN- LEFT- RIGHT- L- R- SELECT- START- Y- X- B- A-
we xz aq dc kp im lv og yt jn hr uf


@josejulio - just a thought...(maybe solve all controller problems...)
In reference to the adding 2+ iCade controllers, it might be very simple to incorporate the VGC as shown here: https://github.com/robreuss/VirtualGameController
https://github.com/robreuss/VirtualGameController/wiki/iCade-Controller-Support
I'm not sure about the latency however.  With this option, ideally using it for JUST the support for MULTIPLE (2-4) iCade controllers would be worth pursuing.

**Comment by josejulio** [comment]
Hey,

Haven't had the chance to give it a go.

@oldschoolv I wouldn't recommend the keyboard mode, many games won't work well, as it doesn't support *holding*(running, jumping, charging power, megabuster, etc) a button as the iCade mode does. There could be workarounds, but IMO they wouldn't work well.

As for the VGC, I haven't  checked it, but on a first look, it seems to be good.

**Comment by gabrielmph** [comment]
I know iCade is broke on current iOS build, but what was the last build that 8bitdo controller support worked well? Thanks

**Comment by jasarien** [comment]
It'll probably work in 1.2.5 (9b95492882633e80b2bdb043fe8b57ec0467e206)

**Comment by kyuzumaki** [comment]
Hey just tried the 1.2.5 version above, using an 8bitdo zero. The controller works but getting random pauses of the game every few seconds. Only happens with the controller connected, has anyone tried to fix this already? Don't know where to begin looking

**Comment by BLawicki** [comment]
Experience user here to iOS and understand how to install Provenance, but looking to fix the NES30 issue by installing the adjusted buffer 1.2.5 and not sure how to download/install this to my device.  Any suggestions?  Thanks so much in advance.  Old school user here and excited for Zelda and my new controller on my 6S:) :) :)

**Comment by kyuzumaki** [comment]
easiest way is to do clone my branch
git clone https://github.com/kyuzumaki/Provenance.git

or git clone https://github.com/jasarien/Provenance.git > git checkout 6ed217529389a336e43bf5dad43f6a89ec61781a

**Comment by BLawicki** [comment]
I followed this sub from another link, and really aren't familiar with GIT site mechanics or 'cloning.'  I really feel like a dummy here as I'm not normally the one to ask questions.  Do I just download the zip/tar.gz and push it to the phone?

**Comment by jasarien** [comment]
It 100% invokes compiling the software. The instructions are over on the wiki.

**Comment by BLawicki** [comment]
Ha!  I do appreciate the candid answer, but for the ability to use a controller with my phone, I can wait for now:)  Thank you, again.

**Comment by jasarien** [comment]
Could always invest in a MFi controller. Those are supported and nowhere near as buggy as iCade. They work better too.

**Comment by BLawicki** [comment]
Excellent tip!  I enjoy the aesthetics of the NES30, but realistically it's not the greatest for input.  Even on the WII U, it has the buffer-lag:(

**Comment by GrimReaper38** [comment]
Is there a link or a way to download provenance 1.0.5 or any version that works well with nes30 controller...I'm on a iPad Air 2 and have no way of using Xcode....if someone can help I would really appreciate it

**Comment by josejulio** [comment]
NES30 support for iOS is basically a hack, I wouldn't recommend buying one only for iOS. 
If you want an iOS-only controller, MFi is the way to go. The support of NES30 will be hardly as good as a MFi controller.

@GrimReaper38 Maybe you have a friend who has a Mac ? Its really easy to setup Xcode and build Provenance.

**Comment by GrimReaper38** [comment]
Ok thank you...ill do that instead

**Comment by josejulio** [comment]
@GrimReaper38 I'm sorry i can't be of more help, I don't know how to do a build that can be installed on any device (*date trick* or whatever iOS bug you are using to install it). 
Though I could try one of those if instructions to do so are provided (and don't take much time).

**Comment by GrimReaper38** [comment]
Does the MFi controller work on provenance 1.2.6??...because if it does I'll just buy one and use my nes30 for my android devices

**Comment by GrimReaper38** [comment]
Anyone know what gamepad/ controller works with Provenance 1.2.6?

**Comment by jasarien** [comment]
Any MFi controller works flawlessly. iCade controllers are hit and miss and I don't really recommend them.

**Comment by GrimReaper38** [comment]
Awsome I'll just buy one and enjoy mega man zero like God intended.....thakns

**Comment by dgenerationx116** [comment]
This is my 1st time here on this site. I bought a iCade controller and it makes my Provenance 1.2.6 crash every time i press a button. i wanted to downgrade to 1.2.5 but i have no idea how to do that. any help would be appreciated. i might've posted this in the wrong forum.
