### ISSUE TITLE
Lag in button input (steelseries nimbus)

### ISSUE THREAD

**Issue by z3r01** [jasarien/Provenance#229]
games would have a delay effect when the button is pressed using the nimbus controller on the new Apple TV. On the iPad pro it's perfect , but noticed that on the atv4

**Comment by jasarien** [comment]
Duplicate of #157

**Comment by jasarien** [comment]
Also, ensure you're building with Release mode, if you're using Debug mode, then you're not following the [Build Instructions](https://github.com/jasarien/Provenance/wiki/Building-Provenance)

**Comment by drcreek** [comment]
I had debug version installed. But just installed latest release. Still laggy with Nimbus.
