### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by z3r01** [jasarien/Provenance#230]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PViCadeSteelSeriesController", referenced from:
      objc-class-ref in kICadeControllerSetting.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

what am i doing wrong?

**Comment by jasarien** [comment]
Are you building for AppleTV?

**Comment by jasarien** [comment]
Should be fixed in the latest commit.
