### ISSUE TITLE
The connected MFi controller is always assigned to "Player 2"

### ISSUE THREAD

**Issue by joske500** [jasarien/Provenance#233]
Each time when I start Provenance and I connect my MFi controller (SteelSeries Nimbus) the "Generic controller" is always automatically assigned to Player 2 in the Settings menu. When I assign it to Player 1 this setting does not seem to be saved as the apple tv controller is always assigned to Player 1 by default.
It would be nice if this controller assignment is saved or the Generic Controller would be automatically assigned to Player 1 instead of 2.
I have the same behaviour when I connect the MFi controller prior to opening Provenance.

**Comment by jasarien** [comment]
You connect the controller after starting Provenance, that's why. If you connect the controller before starting Provenance it should automatically prioritise the controller over the spirit remote. Since the remote is always connected, when Provenance starts and can only see the remote, it chooses that as the first controller.

**Comment by fengb** [comment]
I'm having the same issue. After connecting the controller, Provenence launches with gamepad support and then switches to remote as controller 1 immediately afterwords.

**Comment by rtoohil** [comment]
I actually believe that this is maybe just a bit of confusion. I struggled with this same issue. Set the controller as player 1, go into a game, hit menu so I could use the start button, notice that I was P2.

What is actually happening, I believe, is that the menu button on the MFi controller is interpreted as being from the remote, which is assigned to player 2. So, it appears you're P2. In reality, it's just that the menu button maybe cannot be differentiated between devices?

Use one of the L triggers for the start button for the MFi remote, and it'll behave appropriately.
