### ISSUE TITLE
N64 support

### ISSUE THREAD

**Issue by xxredxpandaxx** [jasarien/Provenance#234]
It would be nice to have n64 support! Any plans for it?

**Comment by Mkaay83** [comment]
Don't close this plz !!! Would be awesome!!! Remember Mario Kart 64 or Goldeneye: "Odjob Is forbidden!!! Don't Look At my screen.." 😂😂😂 Or Mario Party... Maaaan good old times 😜

**Comment by jasarien** [comment]
It's closed because it's a duplicate of #17 

Please don't post comments, or create new issues without having something to contribute. If an issue is already raised, it is known about. "Me too" and "+1" comments are unhelpful.
