### ISSUE TITLE
Receiving iMessage Causes Screen Flash

### ISSUE THREAD

**Issue by semicolonsnet** [jasarien/Provenance#236]
Sometimes when receiving a notification from Messages in the middle of a game (usually SNES for me), the screen flashes all white for about 0.5 seconds before the notification appears. When this happens, the game appears to continue running in the background.

**Comment by jtf323** [comment]
I've noticed this happen while playing Genesis games as well

**Comment by jasarien** [comment]
I'm aware of it.

**Comment by sevdestruct** [comment]
Does this even happen anymore? I can't say I've ever seen it.

**Comment by sevdestruct** [comment]
Closing this unless a current confirmation against recent builds is reported..
