### ISSUE TITLE
Apple TV: resuming from sleep sometimes loses progress

### ISSUE THREAD

**Issue by fengb** [jasarien/Provenance#240]
When in game and the Apple TV goes to sleep, resuming sometimes kicks me to the games screen without saving the game state.

**Comment by jasarien** [comment]
Sounds like the Provenance is being removed from memory while suspended. You can try loading the auto save state to see if that was trigger before it was quit, otherwise I don't think there's anything that can be done. If the system is quitting the app forcefully while suspended, there is no way to save the state anyway.

**Comment by fengb** [comment]
The problem is that state isn't auto saved and having "autoload previous state" wipes the actual save.

I was hoping there might be a callback that's not implemented. If not, I guess there's nothing we can do...

**Comment by jasarien** [comment]
Well, for starters you shouldn't be relying on save states for long-term saving. They're volatile, and its even possible that they will change format between versions making an older save state incompatible with a new emulator version. Battery saves - that is, using the built in save function within the game - is the preferred method of saving your progress. The save states are a convenience.

It doesn't look like auto save states are created when resigning active or entering background though, like it should be, so I'll add that and hopefully it should solve your issue.

**Comment by jasarien** [comment]
Give it a try with the latest code.

**Comment by fengb** [comment]
Works like a charm. Thanks for the quick response!
