### ISSUE TITLE
No Sound in Iphone 6S with IOS 9.2

### ISSUE THREAD

**Issue by ipokampo** [jasarien/Provenance#244]
Hi, 

I just installed provenance and no sound is coming from it, not from the menus, neither from roms (snes). 

Any clues on this??

btw, provenance is installed through buildstore app (http://builds.io/)

**Comment by jasarien** [comment]
Check your silent switch and volume level. Sounds stupid, I know, but check it.

**Comment by ipokampo** [comment]
Ouch, totally owned!!! Now it's working...iphone noob here :D
Sorry man, thanks! ;)

**Comment by ipokampo** [comment]
btw, great job, keep going, looks awesome

**Comment by jasarien** [comment]
Enjoy.
