### ISSUE TITLE
cvbcvbvcb

### ISSUE THREAD

**Issue by wevecom** [jasarien/Provenance#247]
fbcvbcvb

**Comment by jasarien** [comment]
OK!

**Comment by wevecom** [comment]
available with Third party learned remocon on AppleTV ?
like 2048 game TVOS app?

**Comment by jasarien** [comment]
I don't know what you're trying to ask.

**Comment by wevecom** [comment]
sorry for poor grammars.
i just knew that
Apple TV support  third party remote.
https://www.google.com/search?client=safari&rls=en&q=Use+a+third-party+remote+with+your+Apple+TV

some of games can be controlled with third party remote.

**Comment by jasarien** [comment]
Provenance works with all MFi controllers and the Siri remote. I don't know if a 3rd part remote will work as intended. I have not tested it.
