### ISSUE TITLE
3rd party remote(neglected TV/DVD remote)support on AppleTV4

### ISSUE THREAD

**Issue by wevecom** [jasarien/Provenance#248]
pressing physical button is much better than tapping & swipes.
third party remote can be supported?

3rd party remote feature also support adding additional button for room for ABXY like pause fastfoward rewind.

https://www.google.com/search?client=safari&rls=en&q=Use+a+third-party+remote+with+your+Apple+TV&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=Aat2Vtn9DoummQXl-42wDw
![appletv-4gen-learn-remote](https://cloud.githubusercontent.com/assets/15904044/11918167/74fa906c-a769-11e5-843e-787bf18d3f5c.png)

**Comment by jasarien** [comment]
After setting up a 3rd party remote, if events from that remote aren't passed through to the app as controller events, then there's nothing that can be done from the app as far as I can tell. We'd have to wait for Apple to implement that kind of pass-through.
