### ISSUE TITLE
PC Engine and PC Engine Super CD-ROM support

### ISSUE THREAD

**Issue by sakuranbokun** [jasarien/Provenance#250]
First off, great work on Provenance so far, it's fantastic to be able to play emulators on my TV.  Nice clean UI too.

For a future version, could support be added for PC Engine and PC Engine Super CD-ROM games? It's an under appreciated system, but was amazingly powerful for its time, and it also has one of the best Castlevania games ever written.

**Comment by pmp174** [comment]
Mednafen which can emulate PC Engine is supported by open emu making it possible to run this on provenance. The addition of Mednafen could also allow provenance to emulate the virtual boy (mostly for novalty ) since the code is also in Mednafen .

http://mednafen.fobby.net

**Comment by appletv4** [comment]
who is working on ps1 support?

**Comment by pmp174** [comment]
Its a group effort I believe by multiple devs . Look at the cancelled pull request.

**Comment by apexad** [comment]
That was my Pull Request.

PS1 support was somewhat added a long time ago by XeresRazor, and I looked into brining it forward into the current version of Provenance.  It proved to be too difficult.  Additionally, the Mednafen core for PS1 is too weak, and PCSX Re-Armed would be way better.  The PCSX Re-Armed core does work in RetroArch on the iPhone.  As for Apple TV 4, I am not familiar enough with it to give an accurate answer to porting RetroArch cores to it.

If you actually look at the Provenance code base, it's actually somewhat of a merge between ideas of Open Emu (like the box art) and RetroArch. This idea that 'Open Emu does it so it should be easy to port it to Provenance' is false (the same goes for porting cores from RetroArch).

As far as I know, nobody is currently working on adding PSX or any other systems into Provenance.

**Comment by JoeMatt** [comment]
This is tied to #58, Mednafen is working with all PC Engine variants.

**Comment by JoeMatt** [comment]
This is now in main after Mednafen merge.
