### ISSUE TITLE
Official Top Shelf Icon tvOS

### ISSUE THREAD

**Issue by PolarHacker** [jasarien/Provenance#255]
While this is technically not an issue, I feel that this topic fits here. I noticed that when I put Provenance on the top shelf, that there was no top shelf art work. So I made on: It contains screenshots of popular games for every console Provenance supports. Here it is, along with a screenshot. Think it could be the official Top Shelf artwork?
![top shelf final](https://cloud.githubusercontent.com/assets/10091313/12004283/cdd01e1e-ab1a-11e5-8705-b3832d443ebb.png)
![simulator screen shot dec 25 2015 3 12 16 pm](https://cloud.githubusercontent.com/assets/10091313/12004286/f03f9632-ab1a-11e5-8223-7f90fcccfb42.png)

**Comment by pmp174** [comment]
There is a pull request for a recently played addition. This could be used for when the games haven't been played in a while. 

https://github.com/jasarien/Provenance/pull/242

**Comment by PolarHacker** [comment]
I was also thinking for a few other things. If there is an option to disable that feature, this could take it's place. Also it appears that when you first boot the Apple TV, apps have a top shelf picture while it waits for the interactive part of the top shelf to load (Try it with the App Store).

**Comment by pmp174** [comment]
I noticed thats why I said it could be used for when the app hasn't been used in a while.

**Comment by ajmi982** [comment]
how do i get this to work? I just did a full pull and loaded provenance again on my apple tv but dont see this.  Also tried the "Recent Played" top shelf stuff in xcode but that doesnt seem to work for me either.

**Comment by pmp174** [comment]
Anything on this?

**Comment by ajmi982** [comment]
No idea. I'm more interested in new cores. N64 :-)
