### ISSUE TITLE
Videos of gameplay with ReplayKit

### ISSUE THREAD

**Issue by drewbaumann** [jasarien/Provenance#257]
Hello,

I was curious if there are any plans to implement [ReplayKit](https://developer.apple.com/library/ios/navigation/#section=Frameworks&topic=ReplayKit) for iOS 9 builds.

It would fun to have the ability to record gameplay. Maybe this could be presented in the gameplay menu.

**Comment by grizzz78** [comment]
i have tried iOS 9.1 ReplayKit in my own project and it is very buggy. No one wants to use it in the current state.

**Comment by drewbaumann** [comment]
@grizzz78 Thats good to know.

**Comment by marcelvoss** [comment]
I'll take a look into his. [Here](https://www.youtube.com/watch?v=Qj0eiQujxb8&feature=youtu.be) is an example of a very basic recording. I'm quite sure if it's possible to change the recording frame though.

**Comment by marcelvoss** [comment]
So, I just submitted a pull request that adds screenshot functionality to Provenance. Even though it is not possible to record entire videos yet, this is at least a first step to full gameplay recordings. You can see the PR's progress here #419.

**Comment by JoeMatt** [comment]
I made a new dev ticket #686 to track and discuss how this feature will be implemented. I'll close this since it's a user question ticket and don't want to just take it over.
