### ISSUE TITLE
How do I delete games that I imported?

### ISSUE THREAD

**Issue by hdubb** [jasarien/Provenance#258]
I can't figure out how to delete them.

**Comment by RedLucas** [comment]
Don't you just hold on the item. Like hold the centre button, or it itself. iPhone or Tv

**Comment by hdubb** [comment]
but how do I delete multiple games easily?

**Comment by RedLucas** [comment]
I suppose that's the problem the. Eh? There's no interface for deleting multiple ones at once.

**Comment by hdubb** [comment]
what if I delete the app? Will they be deleted?

**Comment by RedLucas** [comment]
I personally think that this issue would be solved by solving this issue https://github.com/jasarien/Provenance/issues/1   

If it had some kind of Dropbox or iCloud integration, dealing with larger libraries might be easier. Especially considering how small these rims are at the point. Provenance could only load them when it wants to play them, then save the save files on Dropbox as well so you can use it on an iOS device for example. 

Will get more complicated as larger game emulators get added, but I'm just thinking about how to make the simplest possible experience.

**Comment by eito** [comment]
I suppose you could just start the web server for importing and then delete them with a single click through the web interface.

**Comment by jasarien** [comment]
Closing this issue as it's worded more like tech support (which issues is not intended for). There are other issues to address improving the tvOS UI (#266)
