### ISSUE TITLE
iOS 7 Game Controller Support

### ISSUE THREAD

**Issue by jasarien** [jasarien/Provenance#26]
Already implemented for Genesis - needs a generalised implementation and ability to customise button mappings.

**Comment by snhughes** [comment]
Hi James,
Are there any plans to support MFi?
From your blog it seems that you already started looking into MFi.

Many Thanks.

Ps: Awesome that you put Genesis and SNES together in one app! Hope you keep with the app development and I'm happy too send you some donation (beer money) for your efforts.

**Comment by jasarien** [comment]
MFi controller support is already implemented. I've tested it with two types of Moga controllers.

**Comment by snhughes** [comment]
I have a Logitech PowerShell. I've been trying loads of ways to connect the controller to see if it works but nothing. :( I tested the controller with another software and it was good.
I just saw that I'm running version 1.0.1 which is the one they have on iEmulators. Maybe that's the problem or maybe the fact that it's non-jailbreaked. I sent an e-mail to them asking for the new version. Let's see how it goes. :)

**Comment by jasarien** [comment]
Hm, I'm not sure what the problem could be... I have a Moga Ace Power (fits around the phone like a Powershell), and a Moga Rebel (wireless over bluetooth), and they both work for me. Since the Moga controllers are MFi controllers, they use the same code and framework, so it should work with the Logitech and other MFi controllers too...

**Comment by Keloran** [comment]
👍

**Comment by cplr** [comment]
it's because there's only support for extended controllers. the logitech powershell is not an extended controller.

**Comment by jasarien** [comment]
Yep, that makes sense. Thanks for pointing that out @cplr. I probably ignored the normal layout when I refactored the controls to add snes support as it didn't have enough buttons to fit the snes controller. 

I'll see what can be done.

**Comment by snhughes** [comment]
Cheers James.
I mistakenly updated to iOS 8.1.2 :( I registered with builds.io to see if it worked but it didn't. I also don't know which version they are using.

**Comment by snhughes** [comment]
I'm not sure what the non-extended controller is but the PowerShell layout is like a SNES controller but with a "Pause" button and no "Start" or "Reset" button.

**Comment by asos-jamesaddyman** [comment]
I'm going to close this issue. MFi game controllers are now fully supported, both extended and normal layouts and wired/wireless. I'll create a separate issue for button mapping customisation.

**Comment by jasarien** [comment]
I'm going to close this issue. MFi game controllers are now fully supported, both extended and normal layouts and wired/wireless. I'll create a separate issue for button mapping customisation.
