### ISSUE TITLE
App crashes when pressing a button on iCade SteelSeries Free game controller

### ISSUE THREAD

**Issue by maverick530** [jasarien/Provenance#260]
I'm trying to use my SteelSeries Free iCade game controller and the app crashes as soon as I hit any button on my controller--any game, any system. The error is:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: ''

I tried compiling the non-release version but I still don't get any more information.

What can I try to resolve this?

My controller does work with the MeSNEmu emulator app so I know it's not the controller. 
I've selected the correct iCade controller in the controllers menu, but does my controller have to be selected as "player 1"? Because the controller selection menu doesn't show my controller.

**Comment by pmp174** [comment]
#228

**Comment by maverick530** [comment]
Sure enough, I reverted my repo to commit: d500148 (Oct 9, 2015) and patched it with a patch for commit:

 cc1b30e (Nov 20) Add controller mapping for SteelSeries Free

so I could use my SteelSeries Free controller, and now I'm up and running! Not sure what if anything I'm missing, but Zelda (NES) work's great with my controller and just beat Contra again in 15 minutes!
