### ISSUE TITLE
Build fail - tvOS - library not found for -lPVSupportTV

### ISSUE THREAD

**Issue by Marvin91** [jasarien/Provenance#261]
following https://github.com/jasarien/Provenance/wiki/Building-Provenance step by step

build fail with this error:

```
ld: library not found for -lPVSupportTV
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Can I do something?

**Comment by jasarien** [comment]
Open the workspace file instead of the project file.

**Comment by Marvin91** [comment]
I did it

**Comment by Marvin91** [comment]
Using another user account on the same computer with the same developer account everything works.
