### ISSUE TITLE
unnecessary touch controls when using mfi controller

### ISSUE THREAD

**Issue by giankdm** [jasarien/Provenance#262]
When using an mfi controller like the Logitech Powershell for the iPhone 5 on Provenance v1.2.6, the soft buttons "select" and "start" hover the gameplay screen, even if they are unnecessary because they are mapped to the X and Y hardware buttons.

![img_0285](https://cloud.githubusercontent.com/assets/3578378/12096126/89d00160-b313-11e5-9c69-b6c5bf903f97.PNG)

**Comment by giankdm** [comment]
I forgot to mention that this happens on the Gameboy Advance emulator. I understand that other controllers like the SNES one do use X and Y, thus require the soft buttons to operate.

I clarify specifying that these softbuttons should disappear just when unnecessary for the operation of the specific emulator.

**Comment by apexad** [comment]
This does not occur when using an iPhone 6s Plus with a SteelSeries Nimbus.

Provenance/Controller/PVControllerViewController.m contains the following:
`- (void)hideTouchControlsForController:(GCController *)controller
{
    [self.dPad setHidden:YES];
    [self.buttonGroup setHidden:YES];
    [self.leftShoulderButton setHidden:YES];
    [self.rightShoulderButton setHidden:YES];
    
    if ([controller extendedGamepad])
    {
        [self.startButton setHidden:YES];
        [self.selectButton setHidden:YES];
    }
}`

It looks like the Logitech PowerShell is not recognized as an Extended Gamepad.  Perhaps there could also be a check for System Identifier here in addition to just the Extended Gamepad check?

**Comment by giankdm** [comment]
This is not an extended layout controller.

![logitech_powershell_1280](https://cloud.githubusercontent.com/assets/3578378/14361453/31e83274-fcfb-11e5-9460-ab1c3515d8ed.png)

It is indeed a Formfitting Standard.

Compare, this is a standard controller:
![featureshidgamecontrollerstandardformfittingsample_2x](https://cloud.githubusercontent.com/assets/3578378/14361421/12bf6d7c-fcfb-11e5-89de-cdb4f5bf6934.png)

This is an extended controller:
![featureshidgamecontrollerextendedformfittingsample_2x](https://cloud.githubusercontent.com/assets/3578378/14361430/1da99c1c-fcfb-11e5-8a85-f59cbd8ebfba.png)

I understand that the buttons appear always even for games that have X and Y mapped to start and select.

The code should become

if([controller extendedGamepad] || [runningEmulator requiresExtended])

...

where runningGame requiresExtended should be wired up a routine that returns if the emulator needs more a certain number of buttons. For example, the GBA core requirements are fullfilled by the standard layout, whereas the SNES ones are not.

**Comment by apexad** [comment]
Try my branch `unnecessary-touch-controls` to see if this does what you want.  If it does, I can make a PR for it so this issue can be Closed.

**Comment by apexad** [comment]
I realized I missed Game Boy Color in the first commit, but I've added that and gone ahead and submitted the PR as I was able to test this by temporarily just removing the check for extended game pad and confirmed these buttons are gone on GB/GBC/GBA.
