### ISSUE TITLE
Apple TV UI Improvements

### ISSUE THREAD

**Issue by swemoney** [jasarien/Provenance#266]
A better UI that would line up with most other Apple TV apps right now would be to use the top tab bar that hides and make a tab for each type of ROM. So on the top, you would have NES, SNES, Sega Genesis, GameBoy Advance, etc. and then Search and Settings at the end. The import option could get placed into the settings menu because it isn't necessary to always have it available once you're done importing your ROMs. Having all of the ROMs on one giant page makes it hard to scroll through a really large library when you want to get to a certain game system so having a separate tab for each system would help by limiting the number of ROMs on a single page, making it easier to get to the top to switch tabs, search, go to settings, etc.

Edit: Another quality of life improvement would be to add a section to the top of each tab with either "favorites" (the user could mark a ROM as a favorite maybe in the same menu where delete is located) or just a "Recently Played" list with a dozen or so games that have been played most recently.

**Comment by jasarien** [comment]
Most of your concerns have been outlined in separate issues.
#205 - library interface tvos
#23 - game library organisation
#3 - ROM collections

Have a look through those and add any comments/suggestions you have to those.
