### ISSUE TITLE
SNES audio buffer issues

### ISSUE THREAD

**Issue by hikaru224** [jasarien/Provenance#272]
Looks like there may be some sound buffering issues with SNES emulation. Every now and then there will be stutters in games, etc...Doesn't happen with any other emulators.

**Comment by dvincent747** [comment]
Yeah, it is quite noticeable in Mega Man X and Final Fantasy 3 in release mode. Basically manifests as warbly sound particularly in horn-like samples.

**Comment by jasarien** [comment]
Could you please include more information when creating bug reports: which version of the code are you using (commit hash would be most useful), iOS, tvOS, which versions, which devices, etc etc.

**Comment by dvincent747** [comment]
For me:

1995a442fcfee3f52c7ee017a3837c41cbbb8cfd
ProvenanceTV 1.2.6 Release
AppleTV 4thGen, tvOS 9.1

Tested plugged directly into a TV with the same results. NES games seem to sound OK (I'm particularly sensitive to Bionic Commando and it sounds OK), but SNES, in particular anything that uses highly custom samples, tends to have warbles or skips. Sigma Stage 1, the opening of FF3 or FF2 are all good examples.

**Comment by orenwolf** [comment]
Just adding a "Me too" here, the sound will stutter for SNES games like Final Fantasy II/III/Chrono Trigger, which makes it sound "warbly", with random clicks and pops.

ProvenanceTV 1.3.2 - 27560f9
ATV4, tvOS 10.1

**Comment by convolutionbbs** [comment]
I also notice this.  v 1.3.2 iPad Pro 12.9" 128 GB.  

I tried changing the sample rates in the PVSNESEmulatorCore.mm as described in link below, but it did not fix the garbled audio.

https://github.com/dborth/snes9xgx/issues/466

I'm not sure if anyone out there will read this, but I thought I'd throw in that I see the garbled audio too.

**Comment by sevdestruct** [comment]
…So, there was some major improvements done to the renderer not long ago by @braindx, I haven't noticed stuttering since then, as there are massive frame rate and performance boosts from that work.  I've played Chrono Trigger and it's all been smooth. Is anyone still experiencing this?? If not, going to close this as it's now nearly a year old..

**Comment by dvincent747** [comment]
I've given up on Provenance in favor of a SNES Mini, so by all means.

**Comment by sevdestruct** [comment]
Then why follow the thread.. Anyone wIth an answer of a more useful nature like actually tested a current release or one the dev branches builds?

**Comment by dvincent747** [comment]
Well, it was one of the bugs I had commented on and had given feedback about previously. If it is fixed, then great. It really was one of the things that turned me off from Provenance. My intent was not to belittle your request, so I apologize.

**Comment by JoeMatt** [comment]
We could try updating snes9x too, it's 2 point releases behind. Also Mednafen can play SNES games though we don't have support for multiple cores mapped to the same hardware. I kind of remember mapping out how to do this. Changing the plist structure to be in the Frameworks for one and adding distinction between system and core, which is outlined in #691

**Comment by sevdestruct** [comment]
Closing this in light of my testing and Joe's suggestion, now #737. Will reopen if it resurfaces.
