### ISSUE TITLE
Bundle identifiers must be unique.

### ISSUE THREAD

**Issue by 00JohnD** [jasarien/Provenance#273]
Hi all, I did exactly as mentioned in the Wiki. I'm trying to install the app on my Apple TV 9.1. It says the build is successful but in the end of the run I get this error message: 

"This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique." 

Any help would be appreciated.

Thx 
00John

**Comment by dvincent747** [comment]
Make sure to set the BundleIDs on all targets. There's Provenance, ProvenanceTV, and TopShelf. All require you to set the BundleID to your own ID. A lot of people miss TopShelf's setting.

**Comment by 00JohnD** [comment]
Great! Thank you it works !
