### ISSUE TITLE
iOS 9.2.1 No sound

### ISSUE THREAD

**Issue by davidwkeith** [jasarien/Provenance#274]
WIth the volume at 100%, I don't get any sound output with the following NES ROMs:L

* Super Mario 3
* Dragon Warrior
* Dragon Warrior II
* Dragon Warrior III
* Dragon Warrior IV

I can't find anything on the wiki for debugging, so I am am starting to dig into the code. I haven't found a ROM file that works yet.

**Comment by pmp174** [comment]
Is the ringer off?

**Comment by jasarien** [comment]
Check your silent switch.

**Comment by davidwkeith** [comment]
Hmm, issue was with dirt in the headphone jack, phone thought headphones were plugged in.
