### ISSUE TITLE
NES30 Pro Crissaegrim not working in any version

### ISSUE THREAD

**Issue by ryohumar** [jasarien/Provenance#275]
I can't get my NES30 Pro Crissaegrim to work in seemingly any version of provenance. I can connect it in iCade mode, but Provenance doesn't recognize it, despite what settings I select. On the off chance it does pick it up, any button press crashes the app.

**Comment by asos-jamesaddyman** [comment]
Duplicate of #228 - iCade controllers are a bit buggy in the latest version due to a controller layer refactor. No-one's had the chance to fix it yet.

**Comment by jasarien** [comment]
Duplicate of #228 - iCade controllers are a bit buggy in the latest version due to a controller layer refactor. No-one's had the chance to fix it yet.
