### ISSUE TITLE
Add Category Filters

### ISSUE THREAD

**Issue by Naatan** [jasarien/Provenance#278]
It would be great if there was a way to quickly navigate to just SNES games for example. Atm I would need to scroll down every system before that before I get to SNES.

**Comment by jasarien** [comment]
This is planned for the future. Not exactly sure when. I'll eventually get round to it, or someone else can implementment. Yay, open source! 

#3 - ROM Collections

**Comment by Naatan** [comment]
Note collections wouldn't exactly be the same thing, unless you'd offer a way to generate them in an automated way.

**Comment by jasarien** [comment]
That issue covers everything to do with ROM organisation; custom fave lists, automatic lists by system, etc. It just hasn't been updated since it was created.
