### ISSUE TITLE
added game won't play

### ISSUE THREAD

**Issue by markboston** [jasarien/Provenance#279]
I've just added space invaders to the roms folder however the game won't load. i can click on the box art image and that launches the emulator but does not launch the game.

**Comment by jasarien** [comment]
That's probably because Space Invaders is an Atari game, and Atari is not one of the emulated systems in Provenance.

**Comment by markboston** [comment]
ah that would make sense lol. is there a list of what systems are supported? or is it only sega and NES?

**Comment by jasarien** [comment]
Right here on the front page of the repository: https://github.com/jasarien/Provenance#currently-supported-emulators
