### ISSUE TITLE
Bundle Identifiers must be unique  (TVOS)

### ISSUE THREAD

**Issue by calebcoverdale** [jasarien/Provenance#283]
I follow the Wiki to the final word.  However when I try to build my app, it says "This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique."

I have made a bundle identifier, it is set for the ProvenanceTV and TopShelf  - both match, but it still will not run.

Any thoughts?

**Comment by calebcoverdale** [comment]
https://github.com/jasarien/Provenance/issues/273  - Read through this and changed it appropriately but it still happens

**Comment by jasarien** [comment]
Have you made sure to use your own bundle ID and not one owned by someone else?

**Comment by elbarbari** [comment]
Hi Jasarien,

What do you mean someone else? who would that be and how do I know if my ID is unique?. I tried different names, and added numbers, but still get this error. I get Build successful, but at the end I get App Installation failed.

"This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique."

Please help

**Comment by dvincent747** [comment]
Make sure to update the BundleID on all necessary bundles in the project: Provenance, ProvenanceTV and TopShelf. If you don't update TopShelf (which ProvenanceTV uses), it'll complain.

**Comment by elbarbari** [comment]
Thanks. I got provenance to work. However, I am having similar issue with Mame as I build it. It is about provisioning. 

I get this error:
No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.ksmith.iMame4tvOS” were found.

I tried changing the bundle ID with no success. Please help.

**Comment by jasarien** [comment]
We can't help you with anything that isn't provenance. You'll need to go to the appropriate place for anything else.
