### ISSUE TITLE
Provenance 1.2.6 crash when I try to using iCade

### ISSUE THREAD

**Issue by djhan** [jasarien/Provenance#291]
My one is iCade core ( http://www.ionaudio.com/products/details/icadecore ). But Provenance 1.2.6 crash when try to using iCade core. Of course, I set iCade controller to standard controller in setting menu. 

I attached Log file from device(iPad mini retina). Please check it, Thanks.

[log_160227.zip](https://github.com/jasarien/Provenance/files/149186/log_160227.zip)

**Comment by elbarbari** [comment]
Nothing was changed. provenance just stopped with an error provenance not available.

Also, Mame for tvOS stopped at the same time!!

Thank you.

**Comment by jasarien** [comment]
The discussion for iCade support (which is currently broken in Provenance) is here: #228.

**Comment by GrimReaper38** [comment]
When will this be fixed..I hope to play with my new nes30 controller soon
