### ISSUE TITLE
slow gba games & audio

### ISSUE THREAD

**Issue by m1lesmorales** [jasarien/Provenance#295]
when i play a game, it is slow, and the audio is also slow & choppy.

**Comment by Gyurn** [comment]
could you be more specific? what are you emulating on?

**Comment by jasarien** [comment]
Firstly, please ensure you've followed the build instructions *to the letter*. That means building with release mode enabled, and not debug.

Secondly before reporting any issues, make sure you're running the latest version of Provenance, and not an older one downloaded from iEmulators or BuildStore, etc. (The only place you can get the very latest version is from here and building it yourself).

Lastly, when reporting performance issues, please state the device you're running Provenance and which ROMs you're seeing the issues in.

**Comment by jasarien** [comment]
Closing after not hearing anymore details.
