### ISSUE TITLE
tvOS Infrared Remote support

### ISSUE THREAD

**Issue by mofux** [jasarien/Provenance#297]
Hi, 

tvOS has support for legacy Infrared remotes. You can train tvOS with a regular IR remote, and map the left, up, down, right, ok, play, pause, forward, rewind and skip actions to the buttons of the remote. Once configured, you can use tvOS with this remote. As you can see, that's a lot of buttons and certainly enough to emulate all the buttons of a regular game console pad like for the snes, gameboy and so on. 

Here is my point:
Most people have an old IR remote at home that can easily be coupled with tvOS. Wouldn't it make sense to provide a binding for those keys (the ones that are supported by tvOS for mapping) to emulate the full capability of a game controller, without actually having to buy a tvOS compatible game controller?

Do you think it would be possible to implement this?

**Comment by JoeMatt** [comment]
I don't think it works this way. My understanding is that the OS allows you to map a remote in place of what the standard remote buttons are, as a function of tvOS. This isn't an app API. To the app the buttons would look the same as they are from the standard ATV remote. If Provenence doesn't currently see clicks from an IR remote, then that's a limitation of tvOS not expanding it as a GameController, since Provenance is already using the game controller APIs.

**Comment by jasarien** [comment]
I believe it's as @JoeMatt explains.

**Comment by mofux** [comment]
@JoeMatt is right, but missed my point :) 

It is possible to listen to [Remote Control Events](https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/Remote-ControlEvents/Remote-ControlEvents.html) and then map the [commands listed here](https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPRemoteCommandCenter_Ref/index.html#//apple_ref/occ/cl/MPRemoteCommandCenter) to gamepad actions, which would effectively turn the remote into a game controller.

I know, by design this API is for controlling media players, but why shouldn't we be able to leverage it :)

Doesn't that make sense?

**Comment by jasarien** [comment]
Yeah I'm not going to do that. That's a lot of effort for a very niche feature. Those gamepads aren't that expensive, ;)

**Comment by mofux** [comment]
No worries, fine with me, thanks for looking into it. I just figured that it would probably be buggy anyway, because the IR remote can only send one signal at a time, so running top left and jumping at the same time wouldn't be possible.
