### ISSUE TITLE
com.jamsoftonline.ProvenanceTV.TopShelf is not available

### ISSUE THREAD

**Issue by iAmRenzo** [jasarien/Provenance#304]
I really don't know what I am doing wrong but I cannot get Provenance to work on my Apple TV.

<img width="756" alt="screen shot 2016-03-15 at 09 45 34" src="https://cloud.githubusercontent.com/assets/1183790/13772173/117699ce-ea93-11e5-982d-a8b3c040ab91.png">

Followed the guide, press run and I get this:

<img width="857" alt="screen shot 2016-03-15 at 09 45 18" src="https://cloud.githubusercontent.com/assets/1183790/13772186/1e746d86-ea93-11e5-897b-8abc664d98e5.png">

No idea what error this exactly is and how to fix it...

**Comment by jasarien** [comment]
Change the bundle identifier for the top shelf target.
