### ISSUE TITLE
App Installation Fails

### ISSUE THREAD

**Issue by sm33** [jasarien/Provenance#307]
Read thru comments/instructions

Provenance, Provenance TV, and Top Shelf all have updated Bundle IDs and Teams. Build succeeds.But App Installation Fails:

"This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique."

Any help would be much appreciated.

**Comment by jasarien** [comment]
Either you've entered an ID that someone else has already used or you've missed one of the bundle IDs in the project.
