### ISSUE TITLE
Save States Glitch Out on NES

### ISSUE THREAD

**Issue by GettinGittyWitIt** [jasarien/Provenance#308]
If I don't use a save state for a while and I load it back up on the NES, it glitches out, but in different ways. I've only tried this with two games: Super Mario Bros. and Super Mario Bros. 3. In SMB1 it redirects you to a title screen with messed up sprites and you can't even begin the game by pressing start without a reset. In SMB3 it just takes you back to the regular title screen.

**Comment by GettinGittyWitIt** [comment]
Closing to add a tag

**Comment by jasarien** [comment]
?

**Comment by GettinGittyWitIt** [comment]
Just look at the original thing. I kept opening and closing cuz I didn't see the option to add a tag. Probs cuz I'm on mobile.

**Comment by jasarien** [comment]
It's because you don't have admin privileges for this repo.

**Comment by GettinGittyWitIt** [comment]
Oh, okay. But yeah, the real problems above. It really stinks whenever my phone dies out and I'm not able to continue from the last save state I made and I have to restart the whole game. Also, plz add support for Tilt 'n' Tumble.

**Comment by binarydev** [comment]
@GettinGittyWitIt Please don't make feature requests in a bug report issue. Thanks for sharing the issue though, so it can be addressed.

**Comment by GettinGittyWitIt** [comment]
@binarydev okay then.

**Comment by jasarien** [comment]
> If I don't use a save state for a while

How long is a "while"? What sort of time frames are we looking at here? Is it possible that Provenance had been updated in between creating the save state and reloading it?

**Comment by jasarien** [comment]
I think this may have been related to #529 

Games with `.`'s in the name before the file extension caused a bug where save states would be available to the incorrect ROM, leading to corruption when loaded with the wrong ROM.
