### ISSUE TITLE
Portrait mode support? 

### ISSUE THREAD

**Issue by mithical** [jasarien/Provenance#31]
Don't mind using Landscape at all (actually, much preferred in gaming), but portrait would just add another level to the whole experience. Is this a work in progress or something in mind for the future? 

I have a lot more suggestions/bug reports coming. Would you like me to open a new issue for each one?

**Comment by pheraph** [comment]
Portrait mode is a must have for the Game Boy mode imho.

**Comment by gun378** [comment]
It's a good idea

**Comment by bsr95** [comment]
It would be great to have it back in the app. It's more comfortable for some people, plus some games get too covered up by the controls in landscape. 
Also, resizable buttons would be great!! They're currently way too small for me.

**Comment by gun378** [comment]
Minedtiger7's skin for gba4ios worked really well. You can use that as a starting point

**Comment by bsr95** [comment]
Set the app up with some games for my little brother today and he immediately tried to get into portrait mode...

**Comment by gun378** [comment]
This is the problem with provenance 
Along with dropbox

**Comment by gun378** [comment]
I know right

**Comment by joransrb** [comment]
Any updates on portrait support...? :)

**Comment by dalecoop** [comment]
+1
Please, portrait support would be great.

**Comment by R135** [comment]
Would love to see a portrait mode as well

**Comment by bsr95** [comment]
My little brother is still asking me, "When is that guy gonna fix his app?" Asks me like every week, lol. This is a really big deal for a lot of people.

**Comment by jasarien** [comment]
I dunno, maybe this weekend?

**Comment by bsr95** [comment]
Cool.

**Comment by gun378** [comment]
Yayyyyyyyyyy thank you thank you

**Comment by R135** [comment]
Great! Really appreciate your work!

**Comment by jasarien** [comment]
Provenance can now be used in portrait mode. I don't think it's perfect, but let me know if it works for you guys.

**Comment by gun378** [comment]
Where can I download the updated version

**Comment by jasarien** [comment]
You'll need to build it yourself with Xcode.

**Comment by gun378** [comment]
Will you build it within the next day or so

**Comment by jasarien** [comment]
I don't distribute Provenance. People either build it themselves or download it from somewhere like iEmulators who build it and sign it for distribution.

**Comment by gun378** [comment]
Ok can you tell them about the update

**Comment by jasarien** [comment]
no-one's complained, so I'll close this issue :P

**Comment by inureyes** [comment]
Controller location problem found after screen rotation.
