### ISSUE TITLE
Directional pad losing focus when finger moves out of their touch area

### ISSUE THREAD

**Issue by jmx773** [jasarien/Provenance#310]
In my opinion, the directional pad should not lose focus when the finger is moved out of its touch area. It should should still keep the directional pad pressed until the finger is actually lifted off the screen. For me, this would help alot since I keep having to worry about where my thumb is pressing and that kinda distracts away from the game.

Additionally, maybe remove the unresponsive empty spot on the middle of the directional pad since this makes delays when switching between directions (eg. going from left to right without lifting your finger off the screen makes you touch this empty middle area, hence delaying response).

NES games were made to be hard, and a slight delay can mean the difference between beating the level and throwing your iDevice to the wall, LOL.

Thank you for the awesome work, sorry if I'm asking too much.

EDIT: Upon further speculation, it would seem that all buttons should be made to behave this way. I tested some control schemes on some iOS games with great controls and this seems apparent.

**Comment by bcostoff** [comment]
I feel I have this same issue playing NES games.

**Comment by sevdestruct** [comment]
There is a slight conflict with this idea and upcoming free-placing joystick option... thoughI also have some ideas in mind for how to implement a free-placing Dpad option, as am part of #718 that would of course integrate this. As for handling slipping off touch buttons maybe we create a buffer zone when pressed or track a button with your finger once active within a limit, but I have a feeling this will already get baked in with the visual feedback intent of #718 with animating/enlarging buttons on press.

Thst said absorbing this into #718 Overlay Overhaul. Any additional comments about this can go there.
