### ISSUE TITLE
Can't access Saved States using Menu button in tvOS 9.2

### ISSUE THREAD

**Issue by KrisasMan** [jasarien/Provenance#311]
Since I upgraded to tvOS 9.2 I can no longer access saved states by pressing the Menu button on my controller or Siri remote, it just goes back to the games library instead of opening the saved state menu.

I have re-synced my code using terminal 
`git pull origin master`
and upgraded my Xcode to 7.3 and re-built to tvOS 9.2 but still no change in behavior.

**Comment by jeaz** [comment]
Have the same issue.

**Comment by CodelabOne** [comment]
Same on my side. Menu button works like the back button now.

**Comment by jasarien** [comment]
I had a look at this bug this evening and I can't figure it out...

I can see that the `pauseButtonHandler` is called, but before any of its implementation is executed, the `emulatorViewController` is dismissed...

I can't figure out why it dismisses the view controller when `controllerUserInteraction` is set to false. Anyone have any ideas?

**Comment by arbitrarytech** [comment]
Experiencing the same issue using my Nimbus Controller (running latest firmware v1.6.4.1) since the 9.2 tvOS update.

**Comment by madangus** [comment]
Same with the hori controller.

Great project team.

Hopefully it ends up being easy. Trying to see if there's a way to force downgrade of tvos in meantime.

**Comment by jonwills** [comment]
Are battery saves still working for you?  I am experiencing the above issue and battery saves don't seem to be working.

**Comment by binarydev** [comment]
Having the same issue (Nimbus), although it seems like a general issue that will happen with any controller. Tried tracking logical flow on button press, but in the emulator it works perfectly every time. On device, I'm not hitting any of my breakpoints. So much for family retro game night this weekend :disappointed:

**Comment by djsyche** [comment]
Id like to report the same thing. I actually do not know if it would have worked on my device prior to the upgrade as I was not using Prov previous to the 9.2 upgrade. I finished installing it today and got about an hour of zelda lttp in and saved after returning to my game play I noticed that I actually had no way of using saved states or bat saves. Its sort of weird. But essentially the saves are there in their appropriate folders and I am just not able to access any of them. In regards to the Menu button I am being booted directly to the app landing screen with the rom list laid out and no options present.  Some times upon exiting the back ground music will continue. This has happened with all 30 or so different roms I have tried to use.

**Comment by leolobato** [comment]
I was able to fix this on my fork and can confirm it's working well on a device running tvOS 9.2. I could not reproduce it on the 9.2 or 9.1 Simulator though, so it would be nice to check if everything is still OK on a tvOS 9.1 device.

**Comment by ajmathe86** [comment]
I'm new to this whole Xcode thing. Where do I go to perform the fix?

**Comment by jasarien** [comment]
You need to checkout the latest code. Follow the build instructions on the wiki.

**Comment by MysticalOS** [comment]
Just bumping because I have latest code and menu button does NOT work on iOS 9.3. I checked out code a few hours ago and just verified my code is latest and includes commit https://github.com/jasarien/Provenance/commit/ccc6df1be4633c0e3d3ba702aef95873896e19b7 . My pause/menu button on gamevice controller on iOS 9.3 does not do anything at all using gamevice controller on iphone 6s plus

**Comment by jasarien** [comment]
Looking into it.

**Comment by jasarien** [comment]
@MysticalOS Checkout the latest commit and try again please.

**Comment by MysticalOS** [comment]
Compiled and tested. Menu works once more via pause button on controller. All is well!

**Comment by ajmathe86** [comment]
I feel really bad, but I don't understand in the wiki where it says run command under the source folder. Is it a right click on the source folder? Do i run the command under check out? I am new to this and have google searched with no real help. I am sorry to come off so noob-ish.

**Comment by jasarien** [comment]
It's a terminal command. You need to open Terminal.app (located in /Applications/Utilities/) and change to the directory where you checked out Provenance and then run the command listed in the wiki. Learning to use the command line and/or git is outside the scope of the support I can provide.

**Comment by starlessblack** [comment]
So I just downloaded and built ver 1.3.1 a few days ago, and I'm having this problem as well. SteelSeries Nimbus controller, ATV4 running latest iOS ver.10.1--Menu button on Nimbus controller goes straight back to Provenance games library, not to in-game menu. My workaround has been to quickly double-tap the Siri button on the ATV remote which briefly brings up the Siri listening dialog but also has the side effect of pausing the game and bringing up the in-game menu.

I also noticed that if I turned on the iCade controller support in Provenance settings, it appears to fix the menu button issue, however, it also appears to map the Nimbus' "B" button to Menu. Or, rather, it's double-mapped--if you hit the B button, you can briefly see your in-game sprite or whatever start doing what it's supposed to do (jump, shoot, stab, run, flee, fly, kick, dance, etc.), but only for a brief millisecond before the in-game menu pops up.
