### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by johnRivs** [jasarien/Provenance#312]
Scheme: Release
Device: iPad Mini 2
iOS: 9.3
Xcode: 7.3
Errors during compilation/installation: none
Console: GBA
Game: Fire Emblem

Uploaded the game using the built-in web server, launched it but had no audio.

**Comment by jasarien** [comment]
Have you ensured your silent switch isn't turned on and your volume is up?

**Comment by johnRivs** [comment]
Yes. Still doesn't work.

**Comment by jasarien** [comment]
Tried other ROMs other systems, other apps?

**Comment by johnRivs** [comment]
Double tapped on the home button, swiped every app, reopened Provenance and it now works. Lol.
