### ISSUE TITLE
Installing Provenance onto Apple TV 4th gen

### ISSUE THREAD

**Issue by ajmathe86** [jasarien/Provenance#315]
I'm in Xcode 7.2.1, it says code sign error: no code signing identities found: no valid signing identities (I.e. Certificate and private key pair) matching the team id "63497P68S6" were found. 

What do I do?

**Comment by jasarien** [comment]
Follow the instructions at https://github.com/jasarien/Provenance/wiki/Building-Provenance

**Comment by ajmathe86** [comment]
I guess I'm not seeing where I messed up... I'm new to this

**Comment by jasarien** [comment]
It sounds like you either haven't signed into your AppleID in Xcode preferences, or your haven't selected your development team from the dropdown in the project settings. Go through the instructions again, step by step, making sure to tick them off as you go. If you do that you can't go wrong.

**Comment by ajmathe86** [comment]
Where is the project settings? I must be blind haha.

**Comment by ajmathe86** [comment]
Wait! I think I figured it out. I'm sorry for bugging you. I appreciate everything.

-AJ
