### ISSUE TITLE
Show recently played games as a separate section on games library

### ISSUE THREAD

**Issue by leolobato** [jasarien/Provenance#317]
It would be nice to leverage the recent games list already implemented for the 3D touch shortcuts to add an extra section on the games library with the recently played games.

I actually kind of missed this feature for me, so I implemented it on my fork as a separate branch. It will show the last 10 games I played on a top section, which can be hidden on settings.

This should be a pretty clean merge back to master, if everyone thinks this might be a nice feature. Or we can discuss here any tweaks on concerns.

Let me know what you think.

https://github.com/leolobato/Provenance/tree/recent-games

**Comment by jasarien** [comment]
This is implemented in PR #318
