### ISSUE TITLE
iCade 8bitdo nes30 not working in 1.2.6

### ISSUE THREAD

**Issue by the-roamer** [jasarien/Provenance#320]
First let me say thank you for this amazing project, truly awesome. 

I'm trying to use an 8bitdo nes 30 (pro) on 1.2.6 and I get no response from any button. I downgraded to 1.2.5 and it works like a charm, so it seems like something broke functionality between that and the latest version.

**Comment by Fmms09** [comment]
Hi, i have the same problem, but with the controller fc30 zero by 8bitdo. I configure in other games and work well, only with this app i have the problem.

**Comment by jasarien** [comment]
Have you checked this? https://github.com/jasarien/Provenance/pull/313

It was merged today, have you updated your checkout? Did you follow the instructions in the comments on that pull request?

**Comment by the-roamer** [comment]
Sorry I'm new to this stuff. Here's what i tried:

1. ran: git clone https://github.com/jasarien/Provenance.git
2. reinstalled to iPhone 6 9.3
    Controller still non-functional

3. Edited the 3 files referenced in #313, reinstalled. Still non-functional.

Maybe I'm doing something wrong, like I said I'm new to this stuff. 1.2.5 works without a problem though.

**Comment by jasarien** [comment]
Did you follow this instruction from the comments in the issue I linked?

> kyuzumaki commented 4 days ago
> Tested on iPhone 5 with 8bitdo Zero. Works but you have to go to options and open and close the controller selection menu each time before the controller works.

**Comment by jkjwong** [comment]
Perfect timing, I have just bought a 8bitdo controller! I have tested and along with kyuzumaki's tip it works  fine :)

**Comment by ajmdonker** [comment]
Unfortunately it does not work on an iPhone 6s with iOS 9.3.
I've connected a 8bitdo SFC30, but 1.2.6 does not recognize the controller. In version 1.2.5 it works fine. 
The tip from kyuzumaki did not help.

**Comment by CapnWiggles** [comment]
@jasarien Hi, I'm new to Provenance and just received an SFC30 PRO (pretty much an SNES contoller but different colors) and was experiencing similar problems. My controller connects perfectly via BT but won't cause any movement on Provenance games. I've been wanting to edit my files to the specified ways you have, but it seems I don't have the right file editor for the job (I use iExplorer, not much experience with tweaking iPhones). Also, if by any chance there has been a new fix, I'd be more than happy to try it.
Thanks!

**Comment by polygon82** [comment]
@the-roamer

I've been having the same issues with Provenance 1.2.6. Is there anyway you can point me to where I can download version 1.2.5? I looked into building it myself but have zero programming knowledge :-/

I just wanna play megaman 2 :(

**Comment by the-roamer** [comment]
> I've been having the same issues with Provenance 1.2.6. Is there anyway you can point me to where I can download version 1.2.5? I looked into building it myself but have zero programming knowledge :-/

**Comment by CapnWiggles** [comment]
@the-roamer Thank you for supplying the version files, but I have already located them myself. The problem I'm having is that I have no idea of a way to import one of the previous versions onto my iPhone 6. Like I said in my previous post, I am new to iPhone tweaking. If you could suggest a program that is capable of replacing/editing files, that would be great. Thanks!

**Comment by the-roamer** [comment]
Follow the instructions here: https://github.com/jasarien/Provenance/wiki/Building-Provenance

Start at "Building for iOS" and use the 1.2.5 version

**Comment by CapnWiggles** [comment]
@the-roamer Thanks for the help! The controller works perfectly on version 1.2.5!

**Comment by syltheboy** [comment]
I've bought a iCade 8bitdo nes30 pro controller to control Provenance on my Apple TV 4 (tvos 9.2), but it won't work. There is no 1.2.5 version available for the Apple TV 4.

**Comment by jkjwong** [comment]
I can confirm it works on 1.2.6 but you need to use kyuzumaki's workaround. See above.

**Comment by Frankiefresh** [comment]
Hey guys I'm new to this but I downloaded provenance and bought a ipega controller it has icade mode and I can't get it to work on my new iPhone 6 Plus. Can anyone help me with this please?

**Comment by the-roamer** [comment]
> Hey guys I'm new to this but I downloaded provenance and bought a ipega controller it has icade mode and I can't get it to work on my new iPhone 6 Plus. Can anyone help me with this please?

1.2.6 Breaks iCade support. Install 1.2.5 instead, or use kyuzumaki's workaround which is near the top of this thread.

**Comment by Frankiefresh** [comment]
I go to settings in provenance and click icade controller and nothing happens when I try and play games

**Comment by Frankiefresh** [comment]
Oh ok

**Comment by Frankiefresh** [comment]
I know this is prolly going to sound stupid but how do I download that version?

**Comment by the-roamer** [comment]
Version 1.2.5 can be downloaded here:
https://github.com/jasarien/Provenance/releases

**Comment by syltheboy** [comment]
1.2.5 isn't available for Apple TV 4. How it's possible with Kyuzumaki's workaround? With 1.2.6 it isn't possible.

**Comment by the-roamer** [comment]
I don't know about the Apple TV versions. You may be out of luck unless the
next release fixes iCADE.

**Comment by Frankiefresh** [comment]
I know I'm asking a lot but it's coming up as a zip file how would I download that on my iPhone?

**Comment by jasarien** [comment]
You can't do this from an iPhone. You need a Mac and Xcode. You need to compile the code to your device. If you don't have a Mac or Xcode you don't have much option. Sorry.

**Comment by Frankiefresh** [comment]
Then does anyone know a snes emulator that is compatible with ipega controller

**Comment by jasarien** [comment]
This isn't a discussion forum. If you have comments related to the issue feel free but anything else take it somewhere else.

**Comment by Frankiefresh** [comment]
Thanks a lot buddy

**Comment by 14-4Kbps** [comment]
Mad props to jasarien and those who have contributed to this amazing project! It pains me to see of the ignorant self entitled BS that is posted here. 

I am new to coding but would like to try to remap buttons so I can use my iCade Mobile controller. The current iCade configs don't work well with this particular iCade controller. Can anyone please point me to the lines of code I should look at? Is it possible to run two instances of Provenance on the same device? This way if I have luck remapping the buttons then I can run one version for my iCade Mobile and another version for the NES30. My devices don't support MFI controllers. Any feedback is greatly appreciated, thanks!

**Comment by jasarien** [comment]
Your devices don't support MFi controllers? What do you mean? Any device running iOS 7+ supports MFi controllers, and provenance has iOS 8 as a minimum deployment target, so logically, if you can run provenance, your device supports MFi controllers.

**Comment by oliviercharavel** [comment]
Unfortunately, devices without a Lightning connector don't support MFI controllers.

**Comment by jasarien** [comment]
Even Bluetooth ones?

**Comment by oliviercharavel** [comment]
Even with Bluetooth ones. I was very surprised by it when I wanted to give it a try with a jailbroken iPad 3. It's a very strange requirement by Apple.

**Comment by 14-4Kbps** [comment]
Yep, only models with lightning connectors support MFI controllers and I haven't found any solutions even with jailbreak. Do either of you have any feedback to the 2 questions I posted above? Thanks.

**Comment by nasredin** [comment]
Hello, i got NES30 PRO i'm able to make it work with older version, but when try to play anything it still hold "down arrow" :) anybody with same experience?

**Comment by alexjeune1** [comment]
Hey my snes30 8bitdo gamepad bluetooth controller isnt working with my builds.io only works with the super smash brothers app and iFBS app. But not gba4ios and my snes app wont even open up

**Comment by vdruts** [comment]
No luck here, builds.io 1.2.7 build. Nes 30 controller (you can select it from the icade menu) but when you go to the assign controller to player 1/2, it's blank always. Just says "not playing" as an option... :/

**Comment by jkjwong** [comment]
@vdruts theres a 1.2.7? If you click on Menu at the top within a loaded rom, do you see an option to "Disconnect iCade"? What I tend to do is press a few buttons on the gamepad in-game, come back out to Library and then try to assign a controller again. It should say Generic Controller. Go back into the game and the touchscreen controls should have been disabled and the 8bitdo should work. This is on 1.2.6 though.

**Comment by vdruts** [comment]
Unfortunately there is no disconnect iCade option, or generic gamepad. In fact in the settings where I go to assign a gamepad to player 1/2, it's blank. Only option is they aren't playing.... :/

**Comment by furrshurr** [comment]
In Xcode I was able to follow all of your instructions until it came to selecting Provenance-Release from the 'Scheme Menu.' I can't seem to find wherever the scheme menu is to enable Provenance-Release. I also don't know where I can be able to Run it. Please help! I have zero experience in this and would like a few more specifics in these steps please. Maybe provide an image of where I can find them within Xcode?

**Comment by jasarien** [comment]
1.2.6 is an old and unsupported version. PR #493 has been merged, which contains fixes for iCade. Please try the latest master code and create a new issue if you still have problems.
