### ISSUE TITLE
Not finding developers disk image

### ISSUE THREAD

**Issue by ajmathe86** [jasarien/Provenance#329]
I followed the instructions on how to do this on my other Apple TV hardcore and now I get an error saying "could not find developer disk image" 
I've deleted all the provenance files from the computer and redid the repo and still nothing. Thoughts?

**Comment by b-** [comment]
I'm not the most Xcode-savvy person by any means, but it sounds like your Xcode installation is fucked.

**Comment by b-** [comment]
Which is completely unrelated to provenance itself.

**Comment by jkjwong** [comment]
This is not related to Provenance. You are getting the error because you have updated iOS on your device but Xcode is not up to date.

**Comment by ajmathe86** [comment]
Forget it. Solved my own problem. Sorry for wasting time everyone
