### ISSUE TITLE
Setting emulator speed to Fast freezes/reboots phone

### ISSUE THREAD

**Issue by MysticalOS** [jasarien/Provenance#330]
Using an iphone 6S + running iOS 9.3.1 and latest code checkout version. I am able to reproduce a phone crash by opening sonic the hedgehog 3 & knuckles rom then once in emulator as soon as I set game speed to fast, the phone instantly freezes followed by a reboot.

I'm unable to find any meaningful logs other than this

Incident Identifier: AE1C46DC-F550-4D50-939C-414046CFC8B9
CrashReporter Key:   abfe49c379ca3e85cf9fe7c8f7ba7fcb791f05a4
Date: 2016-04-01 01:44:34.34 -0400
Reset count: 1
Boot failure count: 0
Boot faults: 
Boot stage: 0
Boot app: 421785170

Unable to find any actual crash logs other than gamecontrollerd constantly crashing/rebooting. but none that match time stamp for the hard freeze/reboot

**Comment by jasarien** [comment]
Wow, that sucks. Stuff like this shouldn't even be possible due to sand boxing.

**Comment by MysticalOS** [comment]
I'll try to recompile a debug build later and get more info for you. I'm leaning toward maybe some kind of infinite loop bug. It triggers a dead lock freeze. In my own coding I've done this before, even in sandbox when I managed to schedule something to schedule a loop to run infinite times. Max out the cpu and hang system when it gets hung up on that loop execution. I could be wrong too but that may be type of thing to look into :)

To note, I've used fast forward successfully when playing other games like super metroid (SNES) or zelda DX (gameboy color). Sonic 3 & knuckles is only one that triggers the dead lock so could be related specifically to doing it with that rom or that console (genesis)

**Comment by sevdestruct** [comment]
Not sure this is an active bug on recent builds. I went ahead and tested all the Sonic games running turbo on Fast, that little bastard flies. No crashes on swift builds in dev branches, Tested on an iPhone X and an iPhine that has an old battery (so.. throttled slow). Gonna close this unless it resurfaced on subsequent releases.
