### ISSUE TITLE
Mocute-032 iCade controller

### ISSUE THREAD

**Issue by shokk** [jasarien/Provenance#339]
Just received this as an item with other things I ordered. Does the Mocute-032 work as any of the other supported iCade controllers, or is it its own thing? The only response I ever get it to have is to crash Provenance when I click any of the 4 ABXY controller buttons or Start button.

If I go into the iCade controller menu and go back out to the game, there is no crash, but there is also no response.

**Comment by jasarien** [comment]
Doesn't seem to mention iCade at all in what little documentation I could find for it. But I'd never heard of it until you mentioned it, so I don't know.

**Comment by edgarjcfn** [comment]
Reviving this 1-year old thread. I've just purchased a Mocute as well (super cheap, ideal for testing the waters before commiting to a more expensive controller like SteelSeries).

Anyway, I'm working on Mocute support now, based on iCade support from @josejulio in #39. Will submit a PR soon. This thread is very old but @shokk if you still have your controller, stay tuned.

**Comment by edgarjcfn** [comment]
https://github.com/jasarien/Provenance/pull/589
