### ISSUE TITLE
Menu Selection Rotation

### ISSUE THREAD

**Issue by mithical** [jasarien/Provenance#34]
> Reported by Ryan Paulley in the beta page.

It isn't so much a bug but a consistency issue. When the menu selection is open, it is able to rotate to all angles of the device - including portrait - even though the game screen can only rotate in landscape.
![original](https://cloud.githubusercontent.com/assets/3520542/4726786/cecad23a-5965-11e4-84df-309b5edbe24f.jpg)

**Comment by jasarien** [comment]
Fixed with addition of portrait mode
