### ISSUE TITLE
Menu button no longer brings up menu after FDS disk swap (tvOS)

### ISSUE THREAD

**Issue by tpm1999** [jasarien/Provenance#342]
Tried 2 FDS games recently (Doki Doki Panic and legend of zelda: Hyrule Fantasy).  After switching sides on the disks, the Menu button would not bring up a menu.  This is for both the remote and the controller.  I have only tested this on tvOS, unsure if iOS has the same issue.

**Comment by blanham** [comment]
@tpm1999 I just issued PR #402, which fixes this.
