### ISSUE TITLE
Make it harder to accidentally press Start and Select

### ISSUE THREAD

**Issue by sethfowler** [jasarien/Provenance#345]
My friends and I have been playing games with Provenance on the Apple TV a lot. (Thanks for making it; it's great!) The biggest problem we've been having is that it's extremely easy to accidentally press Start or Select, which are mapped to the left and right triggers, and pause the game. I've solved this in my local build by changing the controller handling code so that to press Start you must hold down left trigger and press left bumper, and similar on the right side for Select.

I've got the patch all ready to go and can submit a PR, but I figured I'd create an issue first to see if the patch would be accepted or if anyone's got a different proposal that might work better.

**Comment by svanimpe** [comment]
I'd love to see this problem solved too. Even when actively trying to avoid pressing L2 and R2, I still seem to trigger them all the time.

**Comment by jasarien** [comment]
What controller are you using that the triggers are so easily pressed accidentally? I have to say I don't experience this issue myself.

As for your solution, it feels to me like it hides the functionality of the start/select buttons being on the triggers, and if you didn't already know that you had to hold the trigger and press the left shoulder to press start, you'd never discover it, and it would feel like the triggers do nothing. I also don't really know how you'd inform a player of that button combo without some cumbersome tutorial UI, which I'd like to avoid like the plague.

**Comment by sethfowler** [comment]
I'm using the SteelSeries Nimbus. Every friend who has tried it has had this problem; it's not just me.

@jasarien You know, I think the problem may actually be that these are analog triggers and the code doesn't take that into account. Maybe all that's necessary is to require that the triggers are *fully* depressed before triggering Start or Select. I could try implementing that this weekend; would you feel better about that solution?

**Comment by jasarien** [comment]
It's possible that is the case. The code uses the `isPressed` property for the triggers. It's difficult to know fully because the framework obscures what values Apple define as "pressed". Maybe try looking for analogue values greater than 0.5 or whatever threshold might be better.

**Comment by appletv4** [comment]
I thought I was the only one with this problem , it only happens when playing intense games like mega man or Mario were you have to jump real fast or you die 
Sometimes I hit L1 L2

**Comment by GoldenChaos** [comment]
Wanted my girlfriend to try playing Metroid: Zero Mission, she ended up literally throwing the controller across the room because of this issue. I tried it myself, and I don't blame her.

_Please_ fix this! It makes GBA games unplayable.

**Comment by sevdestruct** [comment]
Might I direct this ticket to be merged with the proposal in #679. It's about as robust of an idea for getting those buttons on MFi with it's limitations as we can get. @sethfowler If you're still working in this I'd like to recommend those suggestions over what you've outlined, let's continue the conversation there, as I'm closing old and cold tickets. 

Also, Joe is currently working on a rather novel solution to use full feature controllers with Provenance and potentially other iOS and tvOS apps. But I won't spoil it here..
