### ISSUE TITLE
Suggestion: reorder emulator cores

### ISSUE THREAD

**Issue by jonathanhirz** [jasarien/Provenance#346]
They seem to be in alphabetical order, which makes sense in a way. But right now on my phone they go Gameboy, Gameboy Advance, Gameboy Color, etc. I would like to see them go in order of console release maybe, or just reorderable by user.

**Comment by drakkhen** [comment]
Good idea!

Or maybe order by number of ROMs associated with each emulator, or most recently used emulator.

Or maybe an option to NOT group by emulator -- instead alphabetically order all ROMs, or order all ROMs by most recently used.

Hrm.  I'm not sure there's a "right" answer..so maybe a user preference is the right approach.

**Comment by pmp174** [comment]
it would be good to have the options in the settings to change the order since many would also like it to stay the same way.

**Comment by sevdestruct** [comment]
This being assessed as part of my work on the UI Redesign with #722 planned for a 2.x release that addresses this specifically.
