### ISSUE TITLE
Provenance reset on Apple TV 4

### ISSUE THREAD

**Issue by mazerati** [jasarien/Provenance#347]
I have Provenance sideloaded on my Apple TV 4. I loaded the app today to discover that it had reset and all of my ROMs were gone. This might be related, I also had Kodi sideloaded and that reset to factory settings as well. Could this be that my Apple TV was running low on disk space and deleted the data in these two sideloaded apps?

**Comment by jasarien** [comment]
It's entirely possible. Provenance stores it's stuff in cache since that's the only possible place to put it and Apple TV may wipe that area in low space conditions. since this has happened for other apps for you and not just provenance I'd say this isn't a provenance issue.
