### ISSUE TITLE
Full external sound support

### ISSUE THREAD

**Issue by mithical** [jasarien/Provenance#35]
I'm aware we can already listen to our music playing by simply swiping up Control Center and tapping 'play.' We can even send Provenance to the background as we change songs in the *Music* app and come back. However, every time a new game is started, the music fades as the in-game sound plays. 

A full external sound option would be where you can start any game you like while your music is playing and it continues on. If the music is off, it would default to using the in-game music. I guess I'm just asking for a more enhanced experience between the game and our music. Perhaps, *if even possible*, an option where we could adjust in-game sound and music to play together; not completely necessary of course.

**Comment by jasarien** [comment]
Should be fixed in #214
