### ISSUE TITLE
Sound lag

### ISSUE THREAD

**Issue by meetjimmyjammer** [jasarien/Provenance#350]
I'm not sure if it's just because my I phone 4s is to slow but I'm getting major sound lag from my games and I'm not sure how to fix it

**Comment by MysticalOS** [comment]
I actually notice the sound lack too. sound desyncs from video after a while. Hitting pause actually fixes it for a short time. hit the menu button, then unpause again and sound is synced with video again, for a while anyways. This is on an iphone 6s+ so it's not just an older device.

**Comment by Legan79** [comment]
Exactly the same problem with me. Sound desync at all Emulations after a while (iPhone 6+).
James, did you see a Way to fix this Issue?
Otherwise great Job James!

**Comment by sevdestruct** [comment]
Closing this unless anyone has a current confirmation of this in a recent build, preferably the swift based  branches currently in development, in which it or one of it's many duplicates can reopen…
