### ISSUE TITLE
Register device in Members centre

### ISSUE THREAD

**Issue by subree** [jasarien/Provenance#351]
So firstly I had the whole "com.jamsoftonline.ProvenanceTV.TopShelf is not available" issue, which even when I changed the bundle identifier it would still pop up with the issue, however when I click the Fix Issue button it now pops up with
http://i.imgur.com/q0QgvTD.png
and I guess I can't register in the Members Centre without a paid account?

**Comment by jasarien** [comment]
Follow the instructions here. Pay particular attention to the requirements section and the link to create a free developer account. Then ensure you sign into Xcode with that account in Xcode's preferences.  https://github.com/jasarien/Provenance/wiki/Building-Provenance
