### ISSUE TITLE
MFI Apple TV4  latency  

### ISSUE THREAD

**Issue by dallasgroot** [jasarien/Provenance#353]
I couldn't find anyone else that has posted this, but is there anyway to fix the latency of games emulating? The controller works fine and other apps and in the menu itself, but when emulating, there is a noticable lag. The controller works fine in other apps and in the menu itself, but when emulating, there is a  noticeable leg to the point where it's almost unplayable but not fully.  This doesn't happen on the iOS version of it only the AppleTV that I've noticed, I played Sega sonic 2 on the Apple TV with no leg, running the same game through the emulator , and there is about 100mm delay.

**Comment by jasarien** [comment]
Seriously? #157

**Comment by dallasgroot** [comment]
Yes Jasarien, seriously, and you don't need to be a dick about either. Thank you for your work.

**Comment by jasarien** [comment]
Just look a little harder next time. This is an issue that ha been debated to death and it's a little wearing when people keep posting new issues about it.

**Comment by dallasgroot** [comment]
Unfortunately githubs mobile version lacks search, otherwise I would have known.
