### ISSUE TITLE
AppleTV SNES MFI controller lag & solution

### ISSUE THREAD

**Issue by ubnt-tonytoole** [jasarien/Provenance#354]
Please find attached a small patch to remove the MFI controller lag from SNES games on the Apple TV

```
diff --git a/PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm b/PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm
index 1f8989d..0530d68 100644
--- a/PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm
+++ b/PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm
@@ -131,11 +131,11 @@ - (void)stopEmulation
 - (void)executeFrame
 {
     IPPU.RenderThisFrame = YES;
-    S9xMainLoop();
     if (self.controller1 || self.controller2)
     {
         [self pollControllers];
     }
+    S9xMainLoop();
 }
 
 - (BOOL)loadFileAtPath:(NSString *)path
```

**Comment by apexad** [comment]
You should fork the repository and make this change on a new branch and submit a pull request.

**Comment by ubnt-tonytoole** [comment]
Done, and thanks.

**Comment by appletv4** [comment]
Tony if you have time can you look at the other emulators & fix the lag 
Especially NES

**Comment by ubnt-tonytoole** [comment]
I will look into this next week

**Comment by JoeMatt** [comment]
Here, I made a branch for it.
https://github.com/JoeMatt/Provenance/tree/nes_mfi_lag
Might be easier to merge together and make a single pull. If anyone who was seeing lag on NES (I haven't noticed) can verify I'll make a pull request.

**Comment by jasarien** [comment]
Closing this - please see #355 for continued discussion.
