### ISSUE TITLE
Sometimes library will have repeated games right after an import

### ISSUE THREAD

**Issue by leolobato** [jasarien/Provenance#359]
Tried to import 9 NES roms sorted by larger to lower size (Zelda was the first one on the list) and ended up with the attached library. Was able to reproduce it twice. Refreshing the UI (restarting the app) fixes it.

![simulator screen shot](https://cloud.githubusercontent.com/assets/134285/15944658/e1276bdc-2e8e-11e6-9969-389273f530a5.png)

**Comment by jasarien** [comment]
Ouchy..

**Comment by leolobato** [comment]
At least I'm able to reproduce it. Will look into it when I have some time. :)

**Comment by sevdestruct** [comment]
As @JoeMatt works on improving the importer, this is likely being resolved if isn't already. Gonna fold this into that project.
