### ISSUE TITLE
Switch to last configured controller if it's connected while the app is launched

### ISSUE THREAD

**Issue by leolobato** [jasarien/Provenance#361]
On tvOS, if I launch the app with the controller turned on and connected, everything works as expected.

But if I turn on and connect the controller after the app is launched, it will not switch to it automatically. I need to go into setting and reconfigure it.

This might be related to #325 and #334.

**Comment by ryanjmclaughlin** [comment]
I find that my controller occasionally loaded as player 2 and needs to be re-configured to get it working.  The behavior is inconsistent.

**Comment by leolobato** [comment]
OK, now when a new controller is connected, it will be automatically assigned to the first player without a controller or who has the siri remote is assigned (moving the siri remote to the next player).
