### ISSUE TITLE
Unused variable 'components'

### ISSUE THREAD

**Issue by atombone80** [jasarien/Provenance#363]
MAC OS 10.11.5 / Xcode 7.3.1 / iPad Pro iOS 9.3.1; having some issues popup when the project is ready to build;

PVAppDelegate.m  
UICollectionViewFlowLayout *flowLayout = [[UICollectionViewFlowLayout alloc] init]; and NSURLComponents *components = [NSURLComponents componentsWithURL:url resolvingAgainstBaseURL:NO];

getting a failed build seemingly because of this. I've noticed that the build number is now 1.2.7 and didnt have these issues in 1.2.6.  any advice guys?

results of failed build:

Undefined symbols for architecture arm64:
  "_PVMaxRecentsShortcutCount", referenced from:
      -[PVGameLibraryViewController registerRecentGames:] in PVGameLibraryViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jasarien** [comment]
Ignore the warning about unused components. The components variable is used in tvOS but not in iOS, but the codepath is such that I can't exclude it from iOS.

**Comment by jasarien** [comment]
I made it ignore the warning - rejoice.

**Comment by atombone80** [comment]
rejoicing :) and thank you!
