### ISSUE TITLE
Resolution flickering in Seiken Densetsu 3 (SNES)

### ISSUE THREAD

**Issue by alexcreid** [jasarien/Provenance#366]
When text boxes are shown in Seiken Densetsu 3, the screen resolution flickers randomly. This is on master as of 5eaf45c978558e835d6ec4863620c7fe7bd2c430, and seems to be a regression since 1.2.6 – specifically, it seems likely to be the same as issue #42.

**Comment by jasarien** [comment]
This appears to be working now in Provenance 1.4 (latest version)
