### ISSUE TITLE
Snatcher Sega CD

### ISSUE THREAD

**Issue by txemanovelo** [jasarien/Provenance#367]
Dear Jasarien, first of all thank a lot for such an amazing emulator for iOS, Its efficient, clean and steady!

I am writing you because the thing that got me the most excited in the first place was the ability to play Sega CD Games. I been dying for playing Kojima early masterpiece "Snatcher" and following all your sega cd steps (Adding the bio files and rename them) I can't still make it work.

Has somebody asked you before on this game in particular?

Bests

TX

**Comment by appletv4** [comment]
Do other sega cd games work for you? 
It works for me , I got a zip folder with like 10 sega cd bios 
I took one from u,e,j and renamed them like the instruction says 
Then I got snatcher.zip , you have to be a hustler to make it work

**Comment by jasarien** [comment]
@txemanovelo Please see #370 and see if it applies to your issue.
