### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by muttlly** [jasarien/Provenance#368]
Hi
Excellent emulator, thank you for your hard work!
Are there any plans to add some sort of filter or scan lines. I realise that some people like the blocky look, and understand it is considered accurate, but the choice would be nice. I don't mean lots of fancy or complicated filters, a simple scan line on/off option would be welcome(if that is simple to do?).

**Comment by MysticalOS** [comment]
https://github.com/jasarien/Provenance/issues/54

**Comment by muttlly** [comment]
Ok, thanks, sorry for duplicating questions.
