### ISSUE TITLE
ROMs not showing up on the Provenance app on TVOS

### ISSUE THREAD

**Issue by jdm2119** [jasarien/Provenance#369]
I have previously used Provenance by using an xcode developers account to install. I used the video here to install on my ATV4 and upload ROMS with no problems:

http://forums.macrumors.com/threads/atv4-how-to-play-classic-nintendo-and-sega-games.1933938/

I recently did a factory reset on my ATV4 and with the developer accounts expiring every 7 days I decided to use this service to install Provenance:

https://tv.ipwnstore.me/

Everything worked great, the Provenance app showed up on my ATV4, I opened it up and uploaded a few roms via the built in web server procedure.

However when I close that down and return back to the Provenance app the roms still don't show up, my library is still empty.

I am pretty new to all of this and not very technical so please let me know if there is additional information I can provide to assist.

**Comment by RedLucas** [comment]
That service may not be installing an up to date version of Provenance. I'd like to point out that in a sense, that "service" is making money from open source products made by others and I'm sure the hardworking people that contribute to provenance would not appreciate it.

**Comment by jdm2119** [comment]
Where can I find out what the latest version is of Provenance to check this?

Also I apologize for using the service like that, I really had no idea that type of thing was frowned upon in the community. Again I am pretty new to all of this and was referred that site from another thread.
