### ISSUE TITLE
Cannot get Sega CD working on (jailbroken) Apple TV 4

### ISSUE THREAD

**Issue by ko9x** [jasarien/Provenance#370]
I have followed the instructions on the wiki for adding the bios files and the zipped .cue and .bin files but I cannot get the sega cd games displayed in provenance.

Is sega cd supported for the apple tv 4?

If so, do I need to use a program like cyberduck to access the necessary files or is the web server all I need to get it set up?

**Comment by jasarien** [comment]
Just tested this and it's working fine for me. Are you sure the Sega CD ROM you're importing is a zip containing the `bin` and `cue` file? Also make sure you're uploading it into the `roms` folder in the web UI, and into the root directory.

**Comment by ko9x** [comment]
Yes, that is what I have done.

When I upload the zip file to the roms folder and go back to the root, there is no com.provenance.segacd folder created. But, when I go back into the roms folder again there will be two folders containing the .cue and .bin files, one zipped and one regular folder. When I go back to the root after looking inside the rom folder there is now a com.provenance.segacd folder. 

I still get no sega cd header listed in the provenance library on my apple tv 

If I add the zip of the .bin and .cue files to the root I still get no sega cd header

If I add the zip of the .bin and .cue files to the com.provenance.segacd folder (the way all the other folders have the roms inside the com.provenance.x folder) I still get no sega cd header in my provenance library on my apple tv.

**Comment by ko9x** [comment]
Also, do I need to have the sega cd bios files in a certain place for sega cd games to show up?

If i had the wrong bios would it cause the games to not even appear in the library?

**Comment by jasarien** [comment]
Yeah, don't manually put ROMs into the `com.provenance.<system>` folders.

The way it works:

- You upload a zipped ROM into the `roms` folder
- Provenance detects the zip when the upload completes
- Provenance unzips the zip and copies the ROMs to the correct system folder, updates the DB and refreshes the UI.

From what you said about there being a folder inside the `roms` folder after uploading, it sounds like your zip file is a zipped folder, containing the ROMs -- the ROMs need to be at the root level of the zip.

Try this:

- Unzip the zip on your computer
- Move the `bin` and `cue` files out of the folder and zip them together without any folders involved
- Reimport the new zip

As for the BIOS, they need to be manually placed into a folder: `BIOS/com.provenance.segacd`. You'll need to create the `BIOS` folder and then create the `com.provenance.segacd` folder inside the `BIOS` folder.

Then ensure the BIOS ROMs are named exactly as described in the SegaCD instructions and upload them into the `com.provenance.segacd` folder. 

The SegaCD section should still appear after importing a SegaCD ROM even if the BIOS files aren't uploaded, or are the wrong BIOS's or something. In that case, when you try to run the ROM, you'll get an error message telling you it can't find the BIOS files.

**Comment by ko9x** [comment]
Yup, I'm a dummy.

I was zipping the folder the files were in, not the files themselves, so when it unzipped the file it just saw another folder not the bin and cue files it was expecting.

Thanks a bunch for your help!
