### ISSUE TITLE
1.2.7 (419) builds.io / iCade not working /w Snes30 Gamepad.

### ISSUE THREAD

**Issue by vdruts** [jasarien/Provenance#372]
Got the 1.2.7 build (419) from builds.io, connect the Snes30 gamepad using iCade mode. Go to settings in provenance, choose icade; attempt to select controller for first player, only option available "not playing". Go into game, no buttons work, controller not working. Option "Disconnect icade" also not working. 👎

**Comment by appletv4** [comment]
I think icade only works on 1.2.6

**Comment by vdruts** [comment]
Hmm, too bad :/

On Mon, Jul 4, 2016 at 2:31 PM, appletv4 <notifications@github.com> wrote:

> I think icade only works on 1.2.6
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jasarien/Provenance/issues/372#issuecomment-230339114>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATU0UDQCPgB_Zw5BIwyTfk2R72goQdJfks5qSVGJgaJpZM4JECO0>
> .
>



-- 


*Vladimir Druts*

*Founder / Director *
*INTANGIBLE.CO <http://INTANGIBLE.CO>*vimeo.com/vdruts | 416-471-8523

**Comment by appletv4** [comment]
Really just use a mfi controller , I gave up on the 8bido ATV/provenance dream long ago

**Comment by jasarien** [comment]
iOS or Apple TV? Also check out #313. This issue may be a duplicate.

**Comment by markohive** [comment]
iCade works fine with v1.2.5, but not in v1.2.6. Please, could you try to fix it for future versions? Thank you so much! I love this emulator!

**Comment by jasarien** [comment]
@markohive did you read #313 ?

**Comment by markohive** [comment]
@jasarien Thank you for the reply! I did read it. Are you referring to the kyuzumaki`s trick? It didn`t work for me. When I press any button on the controller, the app crashes. I will try again today and report if I had luck. The version 1.2.5 works great with iCade. I am using SFC30 controller by 8bitdo, which is a replica of the original SNES controller - it looks and feels great, that is why I bought it, for the nostalgic feelings. I could try MFI controllers which should definitely work, but they are not visually appealing as the ones by 8bitdo. Right now I am using the v.1.2.5 which I compiled in Xcode, but I will have to repeat the process each week (the certificates for free dev accounts are valid for only 7 days now). I wish I could have Provenance permanently on non-jailbroken iDevices. I really enjoy it very much, it is so clean, nice and working well.

**Comment by markohive** [comment]
@jasarien I have tried it again with 8bitdo`s SFC30 and it didn`t work or it crashed the app. I tried what kyuzumaki wrote, entering the controller option and exiting before pressing any buttons. I tried with the option "standard controller" and "8bitdo NES30".

**Comment by icysea** [comment]
@jasarien Can support the icade controller custom buttons?The ver1.2.5 works great with icade,but Button position is wrong with the 8bit zero controller.Thank you！

**Comment by tiagoln** [comment]
@jasarien Hey, I was looking through GitHub for some implementations of iCade support and I came across this framework here [VirtualGameController](https://github.com/robreuss/VirtualGameController). It maps the iCade controllers through a Mfi profile so the app thinks the iCade controller is a Mfi controller, do you think it can help with better iCade support for Provenance?

**Comment by JoeMatt** [comment]
This looks very interesting. I'm curious how the remotes work. I have a bunch retro USB controllers that work on Mac but not ATV. Had the idea myself of trying to make a bridge app from Mac to ATV as a virtual MFi but didn't know how. Even better would be an Raspberry PI or Arduino USB to MFi. Maybe there are hints on how to do that in this project. I will definitely be looking at this project when I get back from vacation.

**Comment by jasarien** [comment]
I think @leolobato was already looking at integrating this library for something he was working on with provenance, if my memory serves me right.

**Comment by leolobato** [comment]
I had it working on my branch for the SNES emulator, but I need time to review the changes to the emulators core protocol with the other devs and apply the changes to the other cores. :)

Feel free to give it a try [here](https://github.com/jasarien/Provenance/compare/master...leolobato:feature/remote-controller) @JoeMatt

**Comment by cyclone5uk** [comment]
1.2.7 works with my 8bitdo NES30 PRO - the trick is to press a couple of buttons on the controller before you load a game, this seems to work every time for me. The only problem now is the mapping for the NES emulator, it maps:

A - A
B - A
X - B
Y - B

**Comment by rafcabezas** [comment]
See https://github.com/jasarien/Provenance/pull/416 for SFC30 (possibly SNES30 support -- they are probably identical controllers except for the color, but I haven't tested SNES30). Someone please do and I'll update the description.

**Comment by jasarien** [comment]
This issue is about 1.2.7 which is now an old and unsupported version. If you still have iCade issues in the latest master code, then please create a new issue.
