### ISSUE TITLE
no menu button on screen. v1.2.5

### ISSUE THREAD

**Issue by lilcdj** [jasarien/Provenance#374]
d-pad and a,b buttons and start, select, all button is on screen except menu button. i can't back to menu after i launch any rom. please help!

**Comment by lilcdj** [comment]
is the menu button of iOS Provenance removed??

**Comment by jasarien** [comment]
1.2.5 is an older version. Can you update to a later version and see if you still have the issue. Also provide more details about your situation. Which device do you use, any external controllers connected? If so, which controllers, etc.
