### ISSUE TITLE
8bitdo Zero doesn't work and crashes app

### ISSUE THREAD

**Issue by giliammc** [jasarien/Provenance#375]
I have 1.2.6 in release mode. My 8bitdo zero wont work and if I put it in snes30 mode it crashes the app

**Comment by giliammc** [comment]
my phone just died so i wont have a way to test anything.

**Comment by appletv4** [comment]
More info here 
https://github.com/jasarien/Provenance/pull/313

**Comment by jasarien** [comment]
Dupe of #313
