### ISSUE TITLE
Link or instructions to join the Slack?

### ISSUE THREAD

**Issue by CameronBanga** [jasarien/Provenance#379]
Updated the project and saw latest commit (5eaf45c978558e835d6ec4863620c7fe7bd2c430) mentioning that we could request invite to join the Slack.

I'd like to join and contribute if I can, but not sure where to request, as Slack doesn't seem to have an option when visiting that URL to request to join. Just get a login screen, and haven't created credentials yet, so I'm out of luck.

**Comment by JoeMatt** [comment]
Ditto

**Comment by jasarien** [comment]
Just tweet me (or DM if possible) the email address you wanna use for the slack and I'll send an invite. @jasarien on twitter.

**Comment by JoeMatt** [comment]
Can only DM followers and would rather not tweet my email address publicly. Maybe the project needs an email address.

**Comment by jasarien** [comment]
I have the setting enabled to allow anyone to DM me regardless of whether they follow or not.
