### ISSUE TITLE
Custom Controller Skins

### ISSUE THREAD

**Issue by mithical** [jasarien/Provenance#38]
As previously mentioned, custom controller skins à la GBA4iOS would be quite nice for Provenance in the future. If a 'portrait' mode is to ever come, I can only think of the possibilities for these since they wouldn't just be reliant on the opacity setting.

**Comment by gklka** [comment]
I see that this ticket was closed in 2015. Is still the case? I would love to see better button layouts and a more attractive design.

**Comment by jasarien** [comment]
It’s not a priority right now. There are more important bugs/improvements that need to be worked on. Also, with the amount of systems that Provenance now supports, any custom controller skin would need to support each and every controller layout type, which would be a huge undertaking. Finally, there is a ticket related to resizable/positionable controls, which don’t work with skins.
