### ISSUE TITLE
Can't Use Cheats

### ISSUE THREAD

**Issue by nv58298** [jasarien/Provenance#381]
I'm using OpenEmu with Gameboy Advance core mGBA and I'm playing pokemon fire red and the codes i try to put in don't work. I could totally be putting them in wrong but here's an example of what i've put in
000014D1000A+1003DAE60007+83007CEE0001
Its a gameshark code to find bulbasaur in the grass and it won't work. I've tried a bunch of different ones and they don't work either. Please help haha

**Comment by jasarien** [comment]
If you have issues with OpenEmu, please post on their issue tracker.
