### ISSUE TITLE
Sound only from headphones on iPhone and iPad

### ISSUE THREAD

**Issue by xkalibur** [jasarien/Provenance#386]
I cannot get sound to work from the speakers on iPhone or iPad.  Sounds work correctly from the Music (or other) apps, but not from Provenance, so it is not a volume or mute issue.  But if I plug in my headphones, I can hear sound from the games.  Soon as I disconnect, still no sound from the device speakers.

Provenance 1.2.7 built as RELEASE mode.  Same build/version works with sound on AppleTV 4.

**Comment by xkalibur** [comment]
OK -- not sure what the issue is, but I added another rom (before sound problem was present on several others), and now device speakers work on all of the 6-7 roms I have added.  I swear this morning and yesterday I spent 10-15 minutes w/ and w/o headphones and there was no sound from device speakers

Earlier failed on:  NES (Mario 1, Metroid), and SNES (Super Mario All Stars, Super Metroid)
Worked this evening on Super Mario Kart, and suddenly working on the previous as well after discovering SMK had sound.

**Comment by jasarien** [comment]
Could have been a multitude of things. Most likely you had an app running in the background that was hogging the audio session. Apps like Music and anything that might use the microphone or play any audio can do that.
