### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Approximately** [jasarien/Provenance#388]
I've tried this, and it still doesn't work.

**Comment by james-rantmedia** [comment]
Follow the instructions. It works - I and many others have successfully built Provenance. https://github.com/jasarien/Provenance/wiki/Building-Provenance

**Comment by jasarien** [comment]
Follow the instructions. It works - I and many others have successfully built Provenance. https://github.com/jasarien/Provenance/wiki/Building-Provenance
