### ISSUE TITLE
8bitdo controller to provenance

### ISSUE THREAD

**Issue by Pasjr23** [jasarien/Provenance#389]
Kyuzumaki's workaround doesn't make sense to me ? I have 1.2.6 and I heard 1.2.5 is confirmed to work with my controller but I don't know how to get that version! Please help thanks!

**Comment by markohive** [comment]
You have to build it with Xcode, here is the source code https://github.com/jasarien/Provenance/releases/tag/1.2.5. For me, the mentioned workaround does not work. I hope that the 8bitdo controller support will be fixed for the next version of Provenance! I love this emulator.

**Comment by Pasjr23** [comment]
I have NO idea how to do that lol but I guess I'll try

**Comment by cyclone5uk** [comment]
1.2.7 works with the 8bitdo controllers - the trick is to press a couple of buttons on the controller before you load a game, this seems to work every time with my NES30 PRO. The only problem now is the mapping for the NES emulator: it maps

A - A
B - A
X - B
Y - B

**Comment by maddox** [comment]
> the trick is to press a couple of buttons on the controller before you load a game, this seems to work every time with my NES30 PR

Huh? Is there an explanation to this?

**Comment by cyclone5uk** [comment]
To clarify:

1. Connect controller in iOS settings
2. Open Provenance and make sure your controller model is selected under 'ICade controller' in settings
3. Return to game list
4. Press a random button or two on the controller
5. Open a game and the controller will be working 

(you'll instantly know if its working when you load the game, as the on screen controller icons will not be visible)

This works for me every time.

**Comment by markohive** [comment]
I have 8bitdo SFC30 and I never got it to work with 1.2.6. Pressing buttons before launching the game crashes Provenance. I haven`t tried version 1.2.7. I am using version 1.2.5 but I have to rebuild the app every week (I have only a free developer account). Is there anyone who can, please, send me version 1.2.5 built with paid developer account? That should last a year. I would be so thankful, I love Provenance!

**Comment by maddox** [comment]
> This works for me every time.

I understand what you're doing to make it work. But what is the explanation on why this is required. Surely determining that may help to make this hack not required.

**Comment by cyclone5uk** [comment]
Not sure, I suspect it may be something to do with iCade controllers being seen as keyboards - hence some button presses (key strokes) are needed?

**Comment by jasarien** [comment]
I don't know iCade very well - but it might have something to do  with the fact that the iCade listener is refreshed just before loading a game.

After selecting the type of iCade controller in the settings, it might be that the iCade controller must have its buttons pressed before the listener is able to pick it up?

Again, I don't know iCade very well, but as far as I can see in the code the iCade listener should pick up the controller immediately before loading a game, provided the iCade type has been set in the settings. If the controller doesn't work without having its buttons pressed before the listener is refreshed, then that might just be a quirk of the _hacks_ that iCade uses to function the way it does.

**Comment by rafcabezas** [comment]
For the SFC30 I opened a pull request last night/today. See https://github.com/jasarien/Provenance/pull/416

**Comment by zachthom1213** [comment]
Would anyone mind compiling this for me to an IPA file and sending it to me? I don't have a mac to run Xcode on

**Comment by jonw-bb** [comment]
Can confirm 8bitdo NES Pro works on 1.2.7 using above trick.

**Comment by Dochartaigh** [comment]
I'm also running 1.2.7 and this trick only works half the time (my biggest problem is having it sync 100% of the time - syncs to the phone, but just not to Provenance) 

Also, for any systems other than NES, the key mapping is totally jacked up no matter that controller mode I use. I'm using an 8BitDo Zero by the way (identical button layout to the 8BitDo SNES30/SFC30/NES30/FC30 models).

**Comment by rafcabezas** [comment]
Make sure your controller firmware is up to date. Also, if you're not sure you started it correctly in iCade mode (Start+A), turn off (Start until the LEDs go out) and try again. I usually Press Start+A for 5 seconds and let go, and never had problems in Provenance (SNES, GBA)

**Comment by Orphanmac** [comment]
I've been trying to read through most of the feeds to make sure I'm not asking the same question that someone else has but if you know where to direct me I would appreciate it.

I have the 8bitdo nes30 controller and I want to use it with the provenance iOS version (using iCade) I had previously installed the 1.2.7 v of provenance and it didn't work so I scrapped it and installed the latest being the 1.3.1 v but that doesn't seem to work either. From what I understand the last time it worked consistently was the 1.2.5 and with some bugs on the 1.2.6. Can anyone confirm that for me and if so please direct me how to download the correct version please. Thank you.

ref issue #320

P.S. I don't know a lot about coding or Xcode but am willing to learn so please be patient with me.

**Comment by jasarien** [comment]
PR #493 has been merged which includes fixes for iCade and iCade support for tvOS. Please try the latest code in master and create a new issue if it still has problems.
