### ISSUE TITLE
Controller support for iCade/8Bitdo NES30/Bluetooth keyboard

### ISSUE THREAD

**Issue by sojuicy** [jasarien/Provenance#39]
Please consider adding controller support for the 8Bitdo NES30 controller, which can operate in icade or bluetooth keyboard modes.

**Comment by Keloran** [comment]
👍

**Comment by josejulio** [comment]
+1

**Comment by josejulio** [comment]
is anyone working on this?

**Comment by jasarien** [comment]
I don't have any plans to implement this myself. I don't have any of the listed controllers so wouldn't be able to test them. MFi game controllers are supported. If someone else wants to implement this and make a pull request I'll be happy to merge it in.

**Comment by josejulio** [comment]
I just ordered a nes30 pro(which has an iCade mode), once it arrives i'll seriously consider to implement this myself. Thanks.

**Comment by josejulio** [comment]
iCade mode works as a bluetooth keyboard, with events to handle the buttons pressed (https://github.com/stuartcarnie/iCade-iOS/blob/master/iCadeTest/iCade/iCadeReaderView.h)

Did some google searchs and dug a bit on the iOS sdk, and seems that detecting if a external keyboard is not possible (workarounds use UIKeyboardWillShowNotification, since the keyboard never shows i guess that it won't be the case), another way is to listed to some private API to know if an external keyboard is connected, but after a bit of though, an external keyboard doesn't mean that the user has an iCade controller. 

So i'm guessing that the user could actually choose if he wants to use an iCade controller (in settings) or have the iCade controller always listening.

Also, for the actual inner working, I'm thinking on create a classes that implements the GCControllerDirectionPad and GCControllerButtonInput to make it compatible with the actual implementation of PVControllerViewController.

May i know your thoughts on this?

**Comment by josejulio** [comment]
I have raw implementation, needs to tune some details, and add a configuration for the controller, like Listen for iCade Controller, but it works, for anyone wanting to test it out, you can get it from https://github.com/josejulio/Provenance, i'll send a PR once I finish. Would be nice to hear comments about it.

**Comment by axroberts** [comment]
Great work jose! Works like a charm with my SNES 8bitdo controller!

**Comment by josejulio** [comment]
Thanks, though it still needs a bit more of work.

**Comment by cortneytaylor** [comment]
I agree. It works great, with a few small issues you may already be aware of: 

1) The major one that i can see is that the controller doesn't disconnect from the game when you exit, which then makes it unavailable for the next game.

2) Another issue/request is that it doesn't detect which type of controller is being connected, which then messes with button mapping. I have both the NES30 and the NES30 Pro; the NES30 works great, but the NES30 Pro buttons are all over the place.

3) The previous issue could perhaps be solved by either having controller detection, which seems a little cumbersome, or you could implement a customize button mapping feature. This could be done on a system by system basis, or a global one.

All in all, great work!

**Comment by josejulio** [comment]
I'm aware of those issues, thanks for your comments. I'm going to try to guess the controller with some private API(if possible) or let the user choose which iCade layout he wants to use (Standard iCade controller, Nes30, Nes30 Pro, ...).

**Comment by cortneytaylor** [comment]
I'm not sure if this helps or not, but 8bitdo just released a firmware update for the NES30 Pro (v. 1.62) yesterday that remaps the iCade's buttons. They're now the same as the NES30, so the Pro is working great now. It would, however, be nice if, like with the MFi controllers, there was a way to access the menu from the controller, and for both types of controllers, be able to navigate that menu from it. I think there may be an issue already addressing that, though.

**Comment by cortneytaylor** [comment]
I did just notice one more small issue with the iCade controller. Since it technically is a keyboard, Provenance/iOS thinks that it is, indeed, a wireless keyboard. This then disables the software keyboard, which then makes the search basically useless.

**Comment by josejulio** [comment]
Didn't know! Awesome, in that case i will only create a 8bitdo controller and icade standard.

As for the be able to navigate, I might look what can be done with that. Thanks for the info.

**Comment by josejulio** [comment]
Yeah, that's an iCade controller issue, though maybe there is a private api to by-pass that.

**Comment by josejulio** [comment]
@cortneytaylor I tested the 1.62 with my nes30 pro, and with the current setup A&B and X&Y are the other way around (A is B and X is Y), tested in mario rpg, so is pretty obvious there. Could you confirm that it also happens on your nes30 and nes30 pro?

**Comment by cortneytaylor** [comment]
Yep, it's the same on both controllers. I just got used to it and forgot to add that to the issue.

**Comment by josejulio** [comment]
Great! I'm finish on these features and will soon push to https://github.com/josejulio/Provenance

1) A, B, X & Y are correctly mapped.
2) The controller "disconnects" on game finish (no longer crash when pressing a button after the game finishes and still works on next game)
3) You can select what kind of iCade controller layout should use on Settings, "Disabled, Standard controller (i just made up a controller layout with this on mind https://github.com/josejulio/Provenance/issues/3) and 8bitdo nes30 (compatible with nes30 and nes30 pro with v1.62 firmware). Disabled is the default option, any thoughts on this?

Next i would like to try the following:
1) Detect the controller (if possible) and add the "Autodetect" option (and maybe remove the disabled one)
2) If the former is possible, also try to detect when you disconnect the controller
3) Add an option to "disconnect" and repaint the gui.

**Comment by rimiex** [comment]
Josejukio hello. Sorry for being such a noob, but how can i upload that on my provenance emulator? Would love to play it with icade and ipega

**Comment by josejulio** [comment]
Hey @rimiex, this is already merged on the last version of Provenance. You can enable it on settings "iCade Controller" and choose Standard Controller. Now you can connect your iCade controller to your iOS device, start a game, and press any key on your iCade Controller, the HUD control will disappear and you will be able to control the game with your iCade. There seems to be a problem when loading a game(at least it happens with the nes30 pro), that makes the iCade Controller *laggy* on the first seconds, but after (about 20 seconds or so) you will be able to play without lag from the controller.

**Comment by Alazoral** [comment]
I would love to see an option to remap buttons so you can play NES games with the ergonomically superior B+Y (or A+X) instead of A+B.

**Comment by jasarien** [comment]
Closing this issue as the feature has been implemented by josejulio via pull request.

**Comment by tristan-k** [comment]
is it possible to connect to icade controllers at the same time to enable multiplayer? I'm using two ipega 9017's.

**Comment by josejulio** [comment]
I don't think that there is a way to do so, unless ipega 9017 supports iCade player 1 and iCade player2 configurations, like http://gamedock.tv/ (but I'm unsure if it does. I'll try to take a look at the info on the controller.

**Comment by KULIK121** [comment]
@josejulio can you help me with how to connect my 8Bitdo nes30 pro with provenance for tvOS?

**Comment by Jay4160** [comment]
Why is it when I connect my nes30 pro with provenance start is the jump button and A is start

**Comment by franky-supero** [comment]
Hi I use an iPega 9023 Controller, I can just used PSX game and GBA and working perfectly in Icade mode on my iPad IOS 13.1.3 , only issue is that the D-pad doesn't for ex: up, down, left, right or the Analog stick for navigation.
