### ISSUE TITLE
Provenance not able to open on iPhone

### ISSUE THREAD

**Issue by rbmahlum** [jasarien/Provenance#390]
Has anyone else run into an issue where after a week of working just fine, the app will open in the background, but is not be able to be accessed?  Has happened twice to me now.  Would like to not lose all my game saves having to delete the app and then re-deploying it.
Please advise.

**Comment by jasarien** [comment]
Free developer accounts are limited to 7-day provisioning profiles. Unless you decide to create a paid developer account you will have to redeploy the app via Xcode each week. You don't need to delete the app, and as long as you continue using the same bundle identifier you should retain your ROMs and saves.
