### ISSUE TITLE
Question: Library size

### ISSUE THREAD

**Issue by ajmathe86** [jasarien/Provenance#397]
Is it possible to have too many games? I uploaded all my games via the web client and the app now freezes when I first open it. Is that because I have too many games? What should I do?

**Comment by marcelvoss** [comment]
Could be a general performance issue. Do you know the number of games you added to your library?

**Comment by imseandavis** [comment]
Attempted to replicate @ajmathe86 issue, added 500 NES/SNES games and same thing happened on first load. Assuming it's due to the fact it's trying to get all the artwork and build the index for the games. Have a 64GB model / Latest ATV OS with 40% free space.

**Comment by appletv4** [comment]
I have 10gb of roms in provenance and when you first boot up the app it takes 30 seconds to a minute to load everything 
It's been like that for a year so is normal 
Just don't remove the app from the background and you won't see any freezing on bootup

**Comment by sevdestruct** [comment]
Closing this to be revisited after #714 is implemented.
