### ISSUE TITLE
Random Lag?

### ISSUE THREAD

**Issue by Spooj** [jasarien/Provenance#398]
For some reason, when not connected to wifi, Provenance strangely slows down to a crawl sometimes. Any known reason why?

**Comment by Armored-Dragon** [comment]
What games are affected? Any recordings or ways to reproduce?

**Comment by Spooj** [comment]
Sorry for being so horribly late. I have no way to record or reproduce. No specific game gets hit, but it's most common in GBA games.

**Comment by rafcabezas** [comment]
Make sure you use the Provenance-Release scheme in Xcode.

**Comment by lorenzoferrarajr** [comment]
I'm using version 1.2.7 (492) mode RELEASE. I'm having a similar problem.

While playing the screen doesn't update but the game actually continues. It happens only when the 8bitdo NES30 controller is connected (both with the iPhone 5 with iOS 10 and with the iPad Air 2 with iOS 10.1). Also, the screen freeze lasts for much shorter time if WiFi is turned off. I don't know if my problem is related to the one pointed out by @Spooj.

**Comment by lorenzoferrarajr** [comment]
@Spooj are you still having the same issue? I just downloaded the 1.3 release and I'm still having the same problem: while playing the screen freezes for ~ one second, the audio continues, no frame-drops in the fps counter. I am now updating iOS to 10.2. I'll keep you updated.

**Comment by lorenzoferrarajr** [comment]
Same problem with iOS 10.2. I'll try to post a video.

**Comment by sevdestruct** [comment]
Not reproduce able, and in light of render and performance improvements recently, closing this unless someone reports this against a current  release or dev branch build.
