### ISSUE TITLE
iPad Pro Smart Keyboard not responding/no control

### ISSUE THREAD

**Issue by fraannk** [jasarien/Provenance#399]
When I try to play a game, I'm not able to use the iPad Pro Smart Keyboard, even though Provenance supports Bluetooth keyboards. Anybody knows why? Does the app need to support the keyboard because it goes through the Smart Connector?

**Comment by jasarien** [comment]
Provenance does t support Bluetooth keyboards for input. Provenance has limited support for iCade controllers which work in similar ways to Bluetooth keyboards, but iCade support does not mean support for all Bluetooth keyboards.

**Comment by fraannk** [comment]
Would it be possible to add support for the iPad Pro Smart Keyboard? That would be awesome :)

**Comment by jasarien** [comment]
Possibly in the future, however the keyboard input API is not ideal as they do not behave like the controller APIs, and have no guarantee on timing of events which may lead to input lag.

**Comment by fraannk** [comment]
Okay. I'll look forward to it. :)

**Comment by JohnSlaughter** [comment]
Don't look forward to it for too long.  Sadly, Apple doesn't treat their iOS keyboard like a traditional keyboard.

**Comment by jasarien** [comment]
I don't think this is something we can implement, the keyboard APIs just aren't ideal for using as a controller.
