### ISSUE TITLE
Crash on launch - Issue with Realm

### ISSUE THREAD

**Issue by cchelberg** [jasarien/Provenance#400]
I'm trying to set up Provenance from scratch, and I keep encountering this issue once I get it loaded on my iPhone 6S+. I've included below what output Xcode gives me. When I try and run Provenance after exiting out of Xcode, it crashes instantly.

```
dyld`dyld_fatal_error:
->  0x12002d088 <+0>: brk    #0x3
```

```
dyld: Library not loaded: @rpath/Realm.framework/Realm
  Referenced from: /var/containers/Bundle/Application/F3E6DEC8-24D6-4292-9F9E-2E44F6EA8A0B/Provenance.app/Provenance
  Reason: no suitable image found.  Did find:
    /private/var/containers/Bundle/Application/F3E6DEC8-24D6-4292-9F9E-2E44F6EA8A0B/Provenance.app/Frameworks/Realm.framework/Realm: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/F3E6DEC8-24D6-4292-9F9E-2E44F6EA8A0B/Provenance.app/Frameworks/Realm.framework/Realm'
```

I've wiped my Provenance directory twice now and reinstalled from a clean git clone. I'm trying to use Provenance build 427, Version 1.2.7. All I've done is change the bundle ID and the team.

If I'm doing something wrong with my setup, please let me know.

**Comment by maddox** [comment]
I had trouble making an archive in Xcode 8 due to bitcode and Realm.
