### ISSUE TITLE
Sega CD battery saves do not show up in web server

### ISSUE THREAD

**Issue by nicoNaN** [jasarien/Provenance#401]
When using a battery save with Sega CD games, Provenance is able to load them instead of save states, but the battery save files do not appear in the web server.

**Comment by jasarien** [comment]
Hm strange one... I haven't had time to properly investigate, but it appears that the battery save file isn't written until you quit the game and return to the game library in provenance. Thing is, the data to be written is NULL, yet when I restart the game (tested with Sonic CD), there is a continue option and it reloads the last saved game. It must be storing it somewhere else internally? :/

**Comment by jasarien** [comment]
Ok, so I think I figured it out. The SegaCD saves it's 'backup ram' alongside the BIOS files (seems its just the way it does it internally. You should be able to access them in the web server at `/BIOS/com.provenance.segacd/cart.brm` and `/BIOS/com.provenance.segacd/scd_X.brm` (where X will be replaced with U, E or J depending on the BIOS used).

http://d.pr/i/D2hv

**Comment by nicoNaN** [comment]
Yep, I see it there as well. Thanks for looking into this! Quirky behavior for a great system.
