### ISSUE TITLE
New version of xcode seems to be creating some issues

### ISSUE THREAD

**Issue by kegewe** [jasarien/Provenance#403]
Since I upgraded to the newest version of xcode, I seem to be having issues installing provenance.  I get the following error:

App Installation failed
This app contains an app extension with an illegal bundle identifier. App extension bundle identifiers must have a prefix consisting of their containing application's bundle identifier followed by a '.'.

Under the Target "Provenance"  The display name now reads "${PRODUCT_NAME}" and any attempt to change it is rejected.  I also try changing the Bundle Identifier to a unique one, but then it automatically gets changed back.  I think maybe the new version of xccode has created some new issues.

**Comment by kegewe** [comment]
UPDATE: I seem to have gotten it working, I had to manually change more fields than the instructions initially indicate, but after fulling changing the suffix in the Target "ProvenanceTV" as well as adding TV to the Display name, it seems to have built successfully.

**Comment by jasarien** [comment]
Project is now fully updated for Xcode 8. Any issues that arise surrounding provisioning or bundle identifiers aren't the fault of the project itself.
