### ISSUE TITLE
TVos Failing During Build

### ISSUE THREAD

**Issue by jefe78** [jasarien/Provenance#406]
I'm trying to build Provenance for TVos with the latest version.

I've built this successfully for the iPad. However, I'm receiving this error under the general tab:

Provenance has conflicting provisioning settings.
Provenance is automatically signed, but provisioning profile tvOS Team Provisioning Profile: com.jtaylor.ProvenanceTV-Release has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.

In addition, I'm also receiving the following error:

None of your accounts are a member of '63497P68S6':  An unexpected error occurred. Xcode cannot find a team matching '63497P68S6'.
No profiles for 'com.jamsoftonline.ProvenanceTV.TopShelf' were found:  Xcode couldn't find a provisioning profile matching 'com.jamsoftonline.ProvenanceTV.TopShelf'.
Code signing is required for product type 'TV App Extension' in SDK 'tvOS 10.0'

After quite a bit of searching, I've found no solution for the above. Thanks!
Worth noting is the fact that I followed all steps specifically, and modified both the TV-Release and Top Shelf as the Building for TVos section suggestions

**Comment by Armored-Dragon** [comment]
Do what Xcode says and change settings to automatic (it should be on the same page where you got the errors).

Then, click the Unknown team dropdown and select your name under it.

Change the Bundle ID for com.jamsoftonline.ProvenanceTV.TopShelf in the text box to com.jefe78.ProvenanceTV.TopShelf

**Comment by jefe78** [comment]
For anyone with this issue, hitting enter in the bundle id box was the solution. Thanks!

**Comment by jefe78** [comment]
Between hitting 'Enter' (incredibly important, as you mentioned) and properly switching schemas, I was able to build for tvOS. Thanks!

Bottom right menu, not the top menu in the screenshot.

<img width="237" alt="screen shot 2016-09-29 at 9 59 34 am" src="https://cloud.githubusercontent.com/assets/654451/18963844/64fffb88-862b-11e6-8fa5-febbd3d6cde1.png">

**Comment by Armored-Dragon** [comment]
You have to change it to ProvenanceTV-Release or emulators will perform very poorly.

**Comment by jefe78** [comment]
It is for the actual build. This was just to demonstrate the schema mechanism and where I went wrong.

**Comment by ajzimme** [comment]
"None of your accounts are a member of '634 etc.."
"No profiles for com.jamsoft etc..."
Already changed that shit.
Why isn't it working?
Press enter? What?

**Comment by jasarien** [comment]
Sounds like you changed the code signing settings and bundle ID for the iOS target but not the tvOS target. Go back and change those.

**Comment by ajzimme** [comment]
Thanks

**Comment by sunmetis** [comment]
Hi guys. 
I can't install Provenance ... got the same problem about identification .... 
`alidateEmbeddedBinary /Users/anthony/Library/Developer/Xcode/DerivedData/Provenance-dekoqymhnanuwhgqgzzxxoqnvxfv/Build/Products/Debug-appletvsimulator/Provenance.app/PlugIns/TopShelf.appex
    cd /Users/anthony/Downloads/Provenance-master
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-embeddedBinaryValidationUtility /Users/anthony/Library/Developer/Xcode/DerivedData/Provenance-dekoqymhnanuwhgqgzzxxoqnvxfv/Build/Products/Debug-appletvsimulator/Provenance.app/PlugIns/TopShelf.appex -signing-cert - -info-plist-path /Users/anthony/Library/Developer/Xcode/DerivedData/Provenance-dekoqymhnanuwhgqgzzxxoqnvxfv/Build/Products/Debug-appletvsimulator/Provenance.app/Info.plist

error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

		Embedded Binary Bundle Identifier:	com.provenance-emu.provenancetv.topshelf
		Parent App Bundle Identifier:		com.jefe78.ProvenanceTV.TopShelf

`

**Comment by jasarien** [comment]
@sunmetis you need to change the bundle ID for the top shelf target the same as you changed the provenanceTV target's bundle ID. They need to match.

**Comment by sunmetis** [comment]
Hi 

Thx for your answer. 

Profile is fine with my but all others stuff are worst : 
Just mirroring your video :(

Got an Raspberry and compile all source its working .. Just have to click 3 things on iMac and thats soooooo complicated .
