### ISSUE TITLE
Nimbus Steelseries with Double Dragon

### ISSUE THREAD

**Issue by oskargunn** [jasarien/Provenance#410]
Hello,

Not sure if I am on the right forum for this, but I decided to give it a shot :)
I am trying out double dragon 2 for nes on Provenance and I am using Nimbus wireless controller as my input device on ATV4. However none of the a,b,x,y buttons seem to perform a jump action. 
I have read somewhere that there button remapping is underway. 
Is there anyone else experiencing something similar?

Btw, really good work on Provenance, awesome app :)

**Comment by appletv4** [comment]
Don't you have to press 2 buttons to jump in double dragon

**Comment by imseandavis** [comment]
Yes A + B

see here: http://doubledragon.kontek.net/games/dd2/mdd2nes.html
