### ISSUE TITLE
Add Nintendo64 emulation

### ISSUE THREAD

**Issue by evitiello** [jasarien/Provenance#412]
Mupen64 and sixtyforce seem to be the leading ones:

Mupen64: http://mupen64.emulation64.com
sixty force: http://sixtyforce.com

Looks like OpenEmu chose mupen64 for reasons unknown.

**Comment by JoeMatt** [comment]
Duplicate #17 Please search first.

**Comment by Armored-Dragon** [comment]
Plus, Mupen64Plus is open-source, so Provenance/OpenEmu/RetroArch could include it. SixtyForce is closed source, Mac-only, and has less rendering capabilities than Mupen64Plus. Overall, Mupen is better. It's far more widespread than SixtyForce.
