### ISSUE TITLE
iPhone 7 and 7+ issues - freezes causing OS reset

### ISSUE THREAD

**Issue by meldridge** [jasarien/Provenance#417]
iPhone 7, iOS 10 (not jailbroken), compiled on Xcode 8. I couldn't grab any logs unfortunately. I'm novice at iOS development, so let me know if there's any better debugging I can grab.

I was previously running Provenance on an iPhone 6 compiled with Xcode 7, and had no issues at all .

Since updating to the latest master, compiling with Xcode 8, and running on an iPhone 7, the SNES core seems to have issues (tested with Super Metroid and Final Fantasy 3). Gameplay and sound stutters occasionally, controller input gets stuck, and sometimes opening the Provenance menu causes a complete hang (had issues force quitting the app when this happens).

Other cores (GBC) seem fine, although I haven't done thorough testing,

**Comment by jasarien** [comment]
Make sure you're building for RELEASE and not DEBUG.

**Comment by meldridge** [comment]
Yep, build is for RELEASE. Sorry, should have mentioned in the OP.

**Comment by meldridge** [comment]
I just had Pokemon Yellow freeze the phone and force a hard-reset, so it seems this isn't isolated to the SNES core? I was running it on fast speed, if that makes a difference.

**Comment by jasarien** [comment]
Yeah just had it do the same to me too. The GB core hadn't changed, so it must be something else, not SNES specific like you said.

**Comment by jasarien** [comment]
There fact that it reboots the whole phone is disturbing, it could be a big in iOS 10 and not necessarily provenances fault? I'm not certain though.

**Comment by meldridge** [comment]
It might be a watchdog built into iOS forcing a reboot when it detects a hung app stuck at 100% CPU or something? 

Although I would expect it to kill the app, not force a reset.

**Comment by jasarien** [comment]
Possibly, but the design of iOS should be that if an app hangs it shouldnt affect the OS. They should just close back to the home screen.

**Comment by willco007** [comment]
I have an iPhone 7, I will take a look when I get a chance. Doesn't seem snes core related.

**Comment by rafcabezas** [comment]
Having the same issues here. It's not iOS10, it's iPhone 7 related. Installed on both iPhone 6 and 7Plus. 7Plus consistently freezes/reboots phone.
Has anybody tried xcode7?

**Comment by Armored-Dragon** [comment]
I've played many hours in Provenance, on an iPhone 6s (iOS 10 PB 7 as well as GM and 10.0.2), and had no problems, so I can confirm this only affects iPhone 7 (A10) devices.

Maybe this has something to do with the new memory protection qwertyuiop was talking about?

**Comment by jasarien** [comment]
@armored-dragon Do you have any info on this new memory protection that you can link to? Also who or what is qwertyuiop?

**Comment by lopeza511** [comment]
@Armored-Dragon is referring to this tweet https://twitter.com/qwertyoruiopz/status/779395547648126976

**Comment by jasarien** [comment]
Ah ha... Unfortunately I still don't quite know what that means or if it does indeed affect how particular types of apps work.

**Comment by Armored-Dragon** [comment]
KPP is memory protection that has existed in older devices but is now much stricter. It mostly has to do with the kernel, but might affect some other things?
https://twitter.com/qwertyoruiopz/status/779395547648126976: Memory Protection Init

**Comment by lopeza511** [comment]
This is a very interesting issue. I ran the release version from Xcode on my iPhone 7. I played Pokemon Leaf Green for about 20 minutes, while my iPhone still plugged in and running from Xcode. I experienced no issues, aside from minor lag. I saved and stopped the application from Xcode. I rebooted the app and launched Pokemon Leaf Green. Provenance crashed and rebooted my phone within five seconds. I found this odd, so I tried again with my phone plugged in to my mac without running from Xcode. I managed to play Pokemon Leaf Green for ten minutes with no issues while plugged in to my mac. I then closed the app and plugged my phone to the outlet. Then launched Pokemon Leaf Green. The app crashed after loading the save.

This is a very difficult issue to debug, since the crash does not happened while plugged in to my computer. I ran Instruments and I did not find anything weird while running Provenance. I did manage to export some crash logs from the timeframe of the crash. However, the crash logs have very little information about what happened.



[Provenance_crash_logs_iPhone7.zip](https://github.com/jasarien/Provenance/files/504588/Provenance_crash_logs_iPhone7.zip)

**Comment by jasarien** [comment]
Anyone know what coreduet and duetexpert processes are?

**Comment by rafcabezas** [comment]
@lopeza511 +1 This is similar to my experience. No crashes while connected to Xcode.

**Comment by lolkthxbai** [comment]
@jasarien no but I suspect it's the process that handles continuity

**Comment by samadulator** [comment]
As far as I am aware, coreduetd handles Apple's Continuity / Handoff feature for transitioning certain working content between apps on iOS and macOS devices—like messages, email, notes, reminders, etc. Turning off Handoff might be a good way to see if there's some sort of incompatibility between coreduet and Provenance...

**Comment by lopeza511** [comment]
I have done a bit more research, and it looks like it might be a WDT timeout. I have poked around the code, and I think that the issue might be in the [frameRefreshThread:](https://github.com/jasarien/Provenance/blob/master/PVSupport/PVSupport/PVEmulatorCore.m#L104) method. There might be an issue with the timing.

**Comment by jasarien** [comment]
> If everyone tries to crowd to the front of the line, all the real time threads will fail.

Sounds particularly relevant. Perhaps provenance is competing with other system real time threads, such as continuity? 

No idea how to solve that though, without the precision timers, the emulators won't run accurately. 

The emulation threading stuff is pretty much lifted from open emu as-is, and hasn't been modified much.

**Comment by rafcabezas** [comment]
Came across this http://stackoverflow.com/questions/23378063/how-can-i-use-mach-absolute-time-without-overflowing
Gonna play with that; also will try using GCD

**Comment by rafcabezas** [comment]
If someone wants to test this branch: 
It replaces thread/monotonic timing with GCD; it's not perfect, but if no crashes, it might help pinpoint the problem.
https://github.com/rafcabezas/Provenance/tree/iphone7_gcd_test

**Comment by jasarien** [comment]
Is this still frame accurate in terms of timing?

**Comment by rafcabezas** [comment]
"should" be; but definitely not performing very well. It's definitely not a solution, just a test; hence not a pull-request. 
Based on this test, I don't think GCD is the solution to this problem, just trying to help pinpoint if the monotonic timing is the problem. 
But feel free to review, maybe I made some mistake and GCD is not the problem for my performance issue. I tried this code, and so far I haven't gotten it to crash. But only tried with GBA (minish cap).

**Comment by rafcabezas** [comment]
OK, this new branch seems to work much better, and so far no crashes for me.
https://github.com/rafcabezas/Provenance/tree/iphone7_simpletiming_test
(branch iphone7_simpletiming_test)
In this one I'm using NSThread sleep / NSDate timing instead of monotonic timing, low level wait calls.

**Comment by bmt626** [comment]
rafcabezas that branch didn't seem to work for me. It still caused the same problem. although it took a bit longer for it to occur.

**Comment by rafcabezas** [comment]
@bmt626 which branch? Also what emulator core were you using. I've been playing gba for a few hours without issue. 
If it still crashes then it's definitely not the monotonic timer/ low level wait call. Might be the real-time thread then.

**Comment by bmt626** [comment]
@rafcabezas I delete the install and rebuilt it and it is no longer freezing. I just spent about 30 minutes playing, which normally was only a minute or two before it would lock up.

the only thing I did notice is that the game speeds are not working.

**Comment by rafcabezas** [comment]
Well, that's real good news. Yeah, the game speeds are not enabled in this test branch. But should be super easy to add. As a matter of fact, let me do that now real quick ;P

**Comment by rafcabezas** [comment]
OK, done. Try a git pull on that branch. Game speed switching is working now.

**Comment by rafcabezas** [comment]
@jasarien if this solution works, maybe we can start this thread function (frameRefreshSimple) instead of the original one (frameRefreshThread:) at run-time depending on if the device is an iPhone 7. Seems like a safe-enough option, given that iPhone 7 is not really usable as-is anyway, and it wouldn't affect users with previous devices.

**Comment by lopeza511** [comment]
@rafcabezas I played tested the latest test branch for about 30 minutes on my iPhone 7, and I did not experience any crashes. The timing is working fine as well. Your solution seems to work. I have only tested with GBA. I will check out some of the other systems as well.

**Comment by rafcabezas** [comment]
Awesome @lopeza511. Well, if this pull request:
https://github.com/jasarien/Provenance/pull/443
is approved, I can integrate into this solution and issue a pull request for this.
(@jasarien)

**Comment by lopeza511** [comment]
I spoke too soon. I tested the app while connected to Xcode. I just attempted to play a game and froze. I will look into it a little further later in the day.

**Comment by rafcabezas** [comment]
@lopeza511 that's a bummer. BTW, make sure you're using the actual branch in my repo, not the master.

**Comment by lopeza511** [comment]
Ah, I did not pull like you mentioned in a previous comment. Seems to work well now.

**Comment by rafcabezas** [comment]
Can ppl test this PR?: https://github.com/jasarien/Provenance/pull/445

Really hoping this was the issue all along.

**Comment by deyil** [comment]
@rafcabezas I have tried it. You PR seems to fix the issue

**Comment by rafcabezas** [comment]
Thanks for testing, and letting us know, @deyil!
For anyone else that has tested, please let us know of your results

**Comment by rafcabezas** [comment]
In anyone is interested in checking it out, I updated the https://github.com/rafcabezas/Provenance/tree/iphone7_simpletiming_test
(branch iphone7_simpletiming_test) branch. 

I believe it performs better than the current implementation, and it's simpler.

**Comment by rafcabezas** [comment]
Updated my last comment; feedback is very welcome for PR https://github.com/jasarien/Provenance/pull/453

**Comment by jonw-bb** [comment]
Seems to work pretty well on my 7+. Played for around 20mins unplugged. My MFi controller did hang though but thats another issue, I had on older devices too.

**Comment by jasarien** [comment]
This appears to be solved now. There is another PR related to this (#453), so feel free to continue any discussion there.
