### ISSUE TITLE
Building for tvOS 10 - No Such Product-type 'tv-app-extension'

### ISSUE THREAD

**Issue by bobjunior** [jasarien/Provenance#418]
TopShelf Dependency Error:
`target specifies product type 'com.apple.product-type.tv-app-extension', but there's no such product type for the 'iphoneos' platform`

Latest Xcode update with tvOS 10 no longer recognizes product-types as tv-app-extension.

Anyone know a fix for this?

**Comment by bobjunior** [comment]
For those who come across this, looks like Provenance hasn't been updated for latest builds.

In Build Settings, I had to :
Base SDK to tvOS 10.0
tvOS Deployment Target to tvOS 9.0
TARGETED_DEVICE_FAMILY to 1,2,3

tvOS 10 didn't like a few functions which needed to be removed as well...before it would build.

**Comment by marcelvoss** [comment]
Which version of Xcode? Xcode 8.0 (release) or Xcode 8.1 (beta)?

**Comment by jasarien** [comment]
It's my fault. I accidentally reset the base SDK on the tvOS target. I'll commit a fix for it ASAP.

**Comment by bobjunior** [comment]
I'm using Xcode 8.0.

**Comment by jasarien** [comment]
Should be fixed now.

**Comment by drakkhen** [comment]
I believe a few more changes were needed to build on tvOS:  https://github.com/jasarien/Provenance/pull/420
