### ISSUE TITLE
Resolution flickering (SNES)

### ISSUE THREAD

**Issue by Atnik** [jasarien/Provenance#42]
When playing Secret of Mana 2 (Seiken Densetsu 3) on Provenance, the screen changes the resolution of the game randomly each time a text box opens or closes, making the game almost unplayable. 
I'm playing on an iPad Mini with iOS 8.1. Other games work fine.

**Comment by peanut256** [comment]
I found a solution to this problem while working on a (seemingly) unrelated issue. See [issue #86](https://github.com/jasarien/Provenance/issues/86).

**Comment by jasarien** [comment]
Fixed in pull request #87

**Comment by alexcreid** [comment]
This seems to have regressed in master, as of (at least) 48b2d02.
