### ISSUE TITLE
Provenance refuses to build, "Command /usr/bin/codesign failed with exit code 5"

### ISSUE THREAD

**Issue by allgamesallfree** [jasarien/Provenance#422]
I have been trying to get Provenance to build for the past three hours, I followed the instructions precisely and got the error below:

```
CodeSign /Users/maxwellstein/Library/Developer/Xcode/DerivedData/Provenance-fmhaoyibccnihxgkputjdsvlulfw/Build/Products/Release-iphoneos/Provenance.app/Frameworks/Realm.framework
    cd /Users/maxwellstein/Documents/Provenance
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

Signing Identity:     "iPhone Developer: Maxwell Stein (982PD2BZN4)"

    /usr/bin/codesign --force --sign 7D243F3FB8EFCEBFA108C07664338CB8167D422B --preserve-metadata=identifier,entitlements --timestamp=none /Users/maxwellstein/Library/Developer/Xcode/DerivedData/Provenance-fmhaoyibccnihxgkputjdsvlulfw/Build/Products/Release-iphoneos/Provenance.app/Frameworks/Realm.framework

Command /usr/bin/codesign failed with exit code 5
```

I've tried several different developer accounts, several different Provenance builds (483, 467, 427), deleted my derived data, turned bitcode off, tried opening it in Xcode 7, and many other troubleshooting steps but have had no luck so far.

**Comment by Armored-Dragon** [comment]
No idea here. You should keep bitcode on.
You should try resetting your profiles and certs, and also deleting them from the keyring (there's a tool in Utilities for that)

**Comment by jasarien** [comment]
Are you attempting to archive a build rather than building directly to a connected iOS/tvOS device?

Someone here: (https://forums.developer.apple.com/thread/64784) mentions that it is an issue with the keychain.

I don't think this is an issue with Provenance.
