### ISSUE TITLE
How to get my game library back after provenance re-install?

### ISSUE THREAD

**Issue by elbarbari** [jasarien/Provenance#425]
Hi,
I have the 3 month apple developer account. So every three months I have to re-install provenance on my Apple TV 4. My question is how to get all my roms back after every re-install?

Or do I have to download manually each time provenance stops and do everything from the beginning? I have a big library that already disappeared.

Thank you

**Comment by jasarien** [comment]
If you use the same bundle ID when you rebuild it should simply update the app and not wipe it, keeping your library intact.
