### ISSUE TITLE
'SDL.h' file not found

### ISSUE THREAD

**Issue by awalkerca** [jasarien/Provenance#427]
I'm running OSX 10.12 (Sierra), and Xcode 8.0.

Compiling for aTV.

I followed instructions, changing Team and Build Identifier in the following projects: Provenance, ProvenanceTV, TopShelf. I click 'play' and receive the following error:

/Users/{username}/{source}/Provenance/PVNES/NES/FCEU/fceu.cpp:78:10: 'SDL.h file not found'.

I've tried installing sol with homebrew, and it informed me I already had sdl installed.

Any suggestions would be welcome. I'm sure I've missed something, but am certain I've followed the instructions point-by-point.

**Comment by lolkthxbai** [comment]
I compiled the project myself on macOS Sierra and the latest version of Xcode. Try this: uninstall Xcode and delete the Provenance folder, restart your mac, install Xcode and clone Provenance again. Make sure the release version is selected and update the build id and  team id. Then try building again.

**Comment by awalkerca** [comment]
Seems to still be an issue. I've got a co-worker who does iOS development (alas, I am but a humble web developer), and see if we can sort out what's going on with my setup.

**Comment by jasarien** [comment]
Sounds like one of the compiler flags is possibly missing from the target?

SDL shouldn't be being used, at all. 

Compare the tvOS targets compiler flags with the iOS targets flags and see if any are missing.

**Comment by awalkerca** [comment]
Looking at the PVNES project, the file "sdl.h" was being referenced, but it wasn't included in the project files (it was in the folder, but not in the project). We added it to the project, and it compiled.

**Comment by lorenzoferrarajr** [comment]
Also, the file `SDL.h` is being referenced but the actual file name is all lowercase.

**Comment by jasarien** [comment]
The file with `#include <SDL.h>` (SoundSDL.h in PVGBA) is included from `SoundSDL.cpp` in the same target, however that cpp file is not added to the target to be compiled.

The only other instance of `sdl.h` is from FCEU in PVNES, and that is included from a relative path (`#include "drivers/sdl/sdl.h"`) and doesn't need to be added to the project.

I don't know why it fails to include the file from the relative path on your setups -- perhaps you cloned Provenance to a path it was unable to parse? Maybe with spaces or special characters -- I'm just guessing.

All I know is that it builds out of the box with no modification for me and almost every other person that has compiled it for themselves.

The issue must be with your setups and not with Provenance's project itself.

**Comment by diogoviannaaraujo** [comment]
The Problem is with case sensitive Systems, OS X can run on case sensitive and case insensitive fs... mine is sensitive, thats why i was getting the error

**Comment by orenwolf** [comment]
One of the many reasons Apple doesn't go case-sensitive by default is the many, many cases of third-party software being designed on case-insensitive osx filesystems, then failing on case-sensitive ones.

**Comment by jasarien** [comment]
Good to know. Case sensitive filesystems are bad, m'kay?

**Comment by diogoviannaaraujo** [comment]
Not bad, im a developer and I really need Case Sensitive, bad is not taking care of your filenames ;)

**Comment by jasarien** [comment]
It's not mine. It's in FCEUX. In case you haven't noticed I too am a developer and am getting along just fine with a case insensitive filesystem.

**Comment by diogoviannaaraujo** [comment]
Not blaming, Just explaining that case sensitive filesystem is not bad, depends on what you need.. Lost of Linux based packages needs case sensitive filesystems, expecially when dealing with really old codebases

**Comment by hahla** [comment]
suggestion: add to FAQ, or better add to pre-build stage test. I'm also a developer who uses case-sensitive because yeah it's simply better, but I run into this thing semi-frequently by crappy developers, or at least those who didnt grow up on a healthy diet of linux (to put it more kindly :) )

**Comment by jasarien** [comment]
Crappy developers? Again, this issue is in the FCEUX codebase, not Provenance itself. You’re free to go to them and ask them to fix their naming/importing conventions, but I’d probably avoid calling them crappy developers.... 🙄

**Comment by JoeMatt** [comment]
@hahla LOL WHAT?

For fucks sake it's a free app with a tiny collection of developers who have better things to do than QA edge case scenarios. If you want that, go find a commercial iOS emulator... oh wait, don't exist.

fceu.cpp isn't even our file, it's an upstream project, go bitch at them you whiney cunt.

Please don't consider taking upon yourself to take Provenance to task. Could do without, thanks.

**Comment by hahla** [comment]
Sorry all, my bad experience with cocoapods and my sarcasm shouldn't taint
what is v good work. Sry!
