### ISSUE TITLE
Failed to extract archive (request)

### ISSUE THREAD

**Issue by jamesroseuk** [jasarien/Provenance#429]
Not sure where to put a request, but it would be great to know which archive failed so I can delete it.

Apologise in advance if this is the wrong area for this.

**Comment by sevdestruct** [comment]
As in an archiver fail log? I haven't had an archive fail ever between any .zip or .7z I've thrown at the app. Did you archive them yourself and no which archiver was used or just using whatever original archive from whatever source as is? 

Gonna close this unless this gets a reproduce confirmation against a current release or dev branch build.
