### ISSUE TITLE
Failed to verify bitcode in Realm

### ISSUE THREAD

**Issue by maddox** [jasarien/Provenance#430]
I'm getting this error when trying to archive and export for Adhoc. Am I missing something here?

>Failed to verify bitcode in Realm.framework/Realm:
>error: Cannot extract bundle from >/var/folders/4z/3hcxwy6j2vx4mc1ktx3n0xs40000gn/T/XcodeDistPipeline.zaj/Root/Payload/Provenance.app/Frameworks/Realm.fra…

**Comment by maddox** [comment]
Is anyone else seeing this issue? I see that there was a recent fix for building `tvOS`. I assume people have been building, archiving, and exporting since Xcode 8. Has no one else run into this same issue?

Am I missing some kind of step in the process?

**Comment by littlejackal** [comment]
Having same issue, but I can choose to simply not recompile from bitcode on export and that seems to work as expected.

Not sure if that's preferable in any way to actually solving the problem above, but it's all I had the patience for.

**Comment by maddox** [comment]
This worked for me too. I guess bitcode is really only required for App Store submissions?

**Comment by jasarien** [comment]
Bitcode is only required for submission to the app store - it is used to recompile versions of the app for specific hardware requirements, thus reducing the app bundle size. When archiving it should be fine to archive without bitcode.
