### ISSUE TITLE
Dark mode for tvOS

### ISSUE THREAD

**Issue by davidmuzi** [jasarien/Provenance#431]
tvOS 10 has support for a light and dark theme.  

To support this screen elements must have colours for both light and dark themes which are specified using a trait collection.

https://developer.apple.com/reference/uikit/uitraitenvironment

**Comment by appletv4** [comment]
This is much needed

**Comment by sevdestruct** [comment]
@davidmuzi Does iOS support anything like this? I was jus starting out on a Dark Mode feature for it, planning my approach. I'm aware of Smart Invert, which also needs proper support in Provenance and I'm already working on that. But is there a trait collection for iOS similar to tvOS that can be flagged easier or will this require setting a check for all views and restyling everything?

**Comment by davidmuzi** [comment]
iOS does not have system wide support for dark mode. You would need to roll your own

**Comment by sevdestruct** [comment]
Thought so. Thanks.
