### ISSUE TITLE
Bundle identifier error While building provenance - similar to #293

### ISSUE THREAD

**Issue by twerkken** [jasarien/Provenance#432]
Hello.  I keep getting this error: 

"App instillation failed - This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains.  Bundle identifiers must be unique." 

I've read through all of the other posts regarding this issue and I've tried all that was suggested.  I changed all of the identifiers to be the same throughout and my apple TV is connect, but I've also noticed this error (only on the Provenance tab, not the ProvenanceTV, or TopShelf):

<img width="407" alt="screen shot 2016-10-08 at 10 10 19 pm" src="https://cloud.githubusercontent.com/assets/22719902/19217332/44a43caa-8da6-11e6-9d96-b203614837bb.png">

Do you have any ideas?

Thanks in advance.

**Comment by jasarien** [comment]
The error states that you haven't registered any devices with your developer account - therefore it is unable to create a profile for that bundle ID. Register a device and try again.

**Comment by twerkken** [comment]
I'm not sure I am "Registering" the device correctly.  When I plug it in Xcode sees it and all seems to be fine.  Do I need to register it in another way?  Could you point me to a walkthrough for registering a device?  I've found this one ( https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingProfiles/MaintainingProfiles.html ), but when I login to my apple developer account it only looks like this: 
<img width="1372" alt="screen shot 2016-10-16 at 10 04 14 pm" src="https://cloud.githubusercontent.com/assets/22719902/19423273/af7b7376-93ec-11e6-9ed9-2d0a3d09c879.png">

Could you help me further?  I know these are very rudimentary questions.  I apologize for that.  I'm just learning.  

Thanks for your help!
