### ISSUE TITLE
IOS 10 doesn't let me verify

### ISSUE THREAD

**Issue by Spooj** [jasarien/Provenance#434]
I had this app for a month or two. When I upgraded to IOS 10, I had to trust again. However, I can't trust. Verify app does nothing.

**Comment by jasarien** [comment]
Tried rebuilding?

**Comment by Spooj** [comment]
Sorry to say, but I don't know what that is and how to do it.

**Comment by jasarien** [comment]
https://github.com/jasarien/Provenance/wiki/Building-Provenance Try this. If you still have issues, check other issues related to building provenance - if none of them help, raise a new issue.
