### ISSUE TITLE
Provenance won't open (iOS 10)

### ISSUE THREAD

**Issue by apachexliv** [jasarien/Provenance#439]
Hi, I was using Provenance normally on my iPhone 6, iOS 10.0.2, already far ahead on Phantasy Star 2. Yesterday I turned the phone off, and today when trying to reopen it... it won't!!! The app window shows for half a second, then closes. How to fix this? How to ever trust this app again?? 😆

**Comment by jasarien** [comment]
Where did you get the app from? If you downloaded it from some website, then its probably had its illicit certificate revoked.

The only reliable way to keep Provenance installed and working is by sideloading it yourself. https://github.com/jasarien/Provenance/wiki/Building-Provenance

**Comment by apachexliv** [comment]
Hi, I got it from builds.io, and it was working perfectly until yesterday (I didn't install any new versions of iOS). Do you have a working download link I could use?
Tks!

Enviado do meu iPhone 6+
