### ISSUE TITLE
tvOS import webserver infinite loading in browser

### ISSUE THREAD

**Issue by dkcas11** [jasarien/Provenance#446]
Hi,

When running the webserver on the Apple TV i am unable to access it from my computer. Tried Windows with Chrome and Chrome/Safari on my Mac. All just loading forever.

Anything i missed, any port forwarding (shouldn't be needed), or can the roms be included from within XCode?

Thanks.

**Comment by jasarien** [comment]
Are you on the same network? Are you running any services on any other machines on the same network as the AppleTV that might use the same port? (Port 80 for HTTP)

**Comment by dkcas11** [comment]
On the same network. Confirmed no programs on port 80 using TCPView. Also closed Skype which usually causes problems with port 80 and 443. Also closed all other unnecessary programs.

**Comment by dkcas11** [comment]
Btw, this was with the master branch.

**Comment by dkcas11** [comment]
Tried to compile to my ATV a couple of days ago with master branch and for some reason I had no trouble.

**Comment by imseandavis** [comment]
Attempted this with version 1.2, 1.2.7 and now 1.3 and no issues. This should be able to be closed.
