### ISSUE TITLE
Controller Opacity to 0%

### ISSUE THREAD

**Issue by txcx** [jasarien/Provenance#449]
Could the Option to hide the controller opacity completely or at least to set them to 0%?
It would be nice if you play with an external controller :)

**Comment by rafcabezas** [comment]
When you use an external controller, the on-screen controller is supposed to disappear. What controller are you using?

**Comment by txcx** [comment]
Sorry, wasn't aware of that. If so this issue is useless, thanks for enlighting me :)

Improvement: Add a small sentence underneath the slider "External controller removes onscreen controls" 👍
