### ISSUE TITLE
Add option to hide notifications while playing

### ISSUE THREAD

**Issue by msikma** [jasarien/Provenance#455]
While playing, notifications can be [a bit obtrusive](https://cloud.githubusercontent.com/assets/1507745/19816978/dd22110c-9d49-11e6-93c8-6790a77a0385.PNG). They pop up on top of the output area, which could potentially be quite a problem for the player. They go away after a couple of seconds, or if manually swiped away.

Note in this screenshot, the notification was already on its way out so that's why it's only partly visible.

**Comment by davidmuzi** [comment]
This is an iOS mechanism, and its not possible to hide them

**Comment by msikma** [comment]
Ah, that's a shame. But I kinda figured, since I did some searching and couldn't find anything on how to do this...

I'm an iOS noob, so I didn't yet know you can just turn on "do not disturb" temporarily, or even airplane mode. That's just as good.

**Comment by jasarien** [comment]
As @davidmuzi says, this isn't something that can be done in the SDK, so I'll be closing this issue. DND and airplane mode are you friends for this issue.
