### ISSUE TITLE
tvos10 provenance stop worlking after 1 week of use

### ISSUE THREAD

**Issue by sansvisage** [jasarien/Provenance#458]
hello everyone !
bit of a newbie, i don't understand why provenance stop working ( says "not available" when selected on the main menu ) on my apple tv.
is there a trick or is it normal ?

i'm on tvos10.

ty & enjoy
gregg

**Comment by apexad** [comment]
If you are not using a paid developer license, this is normal. It is an Apple restriction and has nothing to do with Provenance.
You will build/run it again in Xcode and send it to your Apple TV.
