### ISSUE TITLE
Provenance occasionally gets into an unstartable state

### ISSUE THREAD

**Issue by msikma** [jasarien/Provenance#460]
I've noticed that, occasionally, Provenance refuses to start up when tapping the icon. The program shows for a brief moment, but disappears right away after the open animation finishes.

Since a video is the best way to show what's going on, I've recorded this:

https://www.youtube.com/watch?v=7o7Qn0rqacA

This is my own build running on an iPhone 7, iOS 10.0.1 (14A403). Restarting the device doesn't change anything.

Rebuilding the project fixes the problem. Unfortunately I can't provide more details because I don't know exactly how or when this happens. It seems to take a while, though, possibly it requires that the emulator isn't being opened for a while.

**Comment by lolkthxbai** [comment]
If you are on a free developer account then this issue occurs after seven days when your provisioning profile expires. This is a known behavior and is not an issue with Provenance

**Comment by msikma** [comment]
Thanks for clearing that up. I didn't know about this limit. It's a shame.

To help other noobs like me, would it be wise to add a note about this in the [instructions](https://github.com/jasarien/Provenance/wiki/Building-Provenance)?

**Comment by lolkthxbai** [comment]
It wasn't always a 7-day period, it used to be longer but Apple changed it. I guess it could be added to the readme but Apple could change it again and jasarien would have to keep track of it. Although, it would help avoid duplicate issues being brought up and it's a very commonly asked question.

**Comment by chrononess7777** [comment]
I have the same issue. Is there a way to renew the provisioning profile without losing data (save states)?

**Comment by lolkthxbai** [comment]
Rebuilding the app on top of the old build will not cause you to lose game saves or roms.

**Comment by msikma** [comment]
I added a quick note on this in the wiki: https://github.com/jasarien/Provenance/wiki/Building-Provenance#updating

I'll just close it then since I don't see what else could be done. Thanks again for clearing it up. 👍

**Comment by micahshelton** [comment]
Would it be possible for someone to post detailed instructions on how to rebuild Provenance on top of an existing build on an Apple TV? Every 7 days I end up having to delete Provenance and rebuild it from scratch. I'm not sure what step I am missing. The build says it succeeds, but Provenance still won't start until I delete it and start over. Thank you for any help you can give me.

**Comment by drakkhen** [comment]
Are you using a free developer account?  If so you'll have to rebuild every 7 days.  If you would like a valid certificate for a year you will need to purchase a developer account from Apple.

**Comment by micahshelton** [comment]
Right, I understand that I have to rebuild every seven days. My problem is rebuilding doesn't resign. I have to delete my install and start fresh every seven days.
