### ISSUE TITLE
Apple TV 4, provenance

### ISSUE THREAD

**Issue by stevedafen** [jasarien/Provenance#464]
Apple controller not working. Roms show up, but controller does not work

**Comment by fluidImages** [comment]
I have two MFI and both work for all Roms.

**Comment by mint5auce** [comment]
@stevedafen It would be useful to know exactly which Apple controller you are having problems with...

**Comment by stevedafen** [comment]
Sorry, I'm using the original Apple remote. Just got some basic Roms like mario, all Roms work, but got no functions on remote. Thanks

**Comment by lolkthxbai** [comment]
@stevedafen Provenance for AppleTV was designed to be used with a controller, not the Apple Siri Remote. I can personally recommend the Nimbus SteelSeries made for AppleTV.

**Comment by mint5auce** [comment]
I too use and can recommend the Nimbus SteelSeries for use with Provenance.
