### ISSUE TITLE
Bundle identifiers must be unique

### ISSUE THREAD

**Issue by joshdot35** [jasarien/Provenance#465]
I am attempting to install Provenance on my Apple TV and I am getting a message that "This application or bundle it contains has the same bundle identifier as this application or another bundle that it contains.  Bundle Identifiers must be unique."

Now, I can assure you that I set each of the 3 Bundle identifiers with a unique ID, not used by anyone else.  All three are the same as one another, do they to be unique from one another as well?  Any advice is helpful.

thanks.

**Comment by jasarien** [comment]
Yep they all need to be unique from each other too. Generally I do something like `myid`, `myid-TV`, and `myid-TopShelf`
