### ISSUE TITLE
The provenance app in the appleTV doesn't open

### ISSUE THREAD

**Issue by saotome077** [jasarien/Provenance#467]
After load the ap in the 4th gen appleTV and play with some roma, from a week ago the app doesn't open it. I don't know if the iOS load a new version, but now the tvOS version is 10.0.1

Can you help me? I need to reload the app?

**Comment by QuarterSwede** [comment]
Free accounts have a 7 day certificate expiration. You need to upgrade to a paid $99/year dev account for 1 year certificate expirations.

**Comment by jasarien** [comment]
As @quarterswede mentioned free accounts are limited to 7 provisioning profiles. You will have to build the app to your Apple TV again. As long as you use the same bundle ID you shouldn't lose any of your roms or saves.
