### ISSUE TITLE
Atari 5200 Support

### ISSUE THREAD

**Issue by JoeMatt** [jasarien/Provenance#468]
Adding this ticket to track progress of another core I've added work on.

https://github.com/joematt/Provenance/tree/atari800

Summary
---

Atari 800 / 8Bit family & Atari 5200.

The 8bit family I were PCs and probably not much interest to the goals of Provenance. The 5200 on the other hand was a console similar to the 2600 & 7800. A commercial bust but there were some pretty neat [games](https://en.wikipedia.org/wiki/List_of_Atari_5200_games).

Progress
---
Working:
- Core boots
- Core loads ROMs
- Core shows Graphics

Issues:

- The system has a [number pad input controller](https://en.wikipedia.org/wiki/Atari_5200#/media/File:Atari-5200-Controller.jpg) which would require a custom controller layout for this core. It also probably wouldn't work very well with Apple TV unless we had a remote controller app for secondary iOS device. iOS devices could probably use a USB keyboard also but ATV doesn't allow keyboard input without an active text input label (hence no iCade mode).
- The controller also allowed plastic overlay sheets for the number pad and that would have to be dealt with on a per-rom basis. We currently have no infrastructure for matching resources to roms.

Notes
---
Right now I'm treating this core as a novelty that may one day see further development when the technical hurdles of input are resolved.

**Comment by jimmythegreek** [comment]
cool.  The Pitfall II game for 5200 had an extra level if you beat the main board.

As a suggestion, you could consider only initially supporting the joystick and primary "fire" buttons for simple games that don't require the number pad.

**Comment by JoeMatt** [comment]
I'll go ahead and finish this then if there's value even without the number pads.
I'd rather get this merged so I don't have to maintain a separate branch, and the we can always add a feature ticket to add number pad support in the future.

I want Atari Jaguar, Intellivision and ColecoVision also use number pads so there's added value there.

**Comment by JoeMatt** [comment]
This ticket has been implemented in #564

**Comment by hstriepe** [comment]
Ok. Got 5200 working from the branch. What is the current button mapping? Does Atari 800 function? Could it be maple to the iOS (or a bluetooth) keyboard?

**Comment by JoeMatt** [comment]
It's in the #566 branch. 800 is not functioning since there isn't an easy way to get a keyboard to input. Bluetooth keys aren't captured. Maybe there's a hack with a text view, not sure how that works on Apple TV. Other options is on-screen custom keyboard but that would be iOS only. Either way, not something I'm working on.

**Comment by JoeMatt** [comment]
Also it looks like Atari 800 uses the .bin extension which is shared by a lot of EMUs. Importing will be tedious until the MD5 rom matching is implemented from #566. I can't remember if Atari 800 ROMs are even in the OpenEMU ROM Database.

**Comment by josephillips85** [comment]
Is possible just use atari 5200 emulation without keyboard.
800 is broken right now no joystick or remote controller response
any idea of how to make it work ?
