### ISSUE TITLE
Help error

### ISSUE THREAD

**Issue by brunochung** [jasarien/Provenance#470]
<img width="1405" alt="captura de tela 2016-11-30 as 00 08 21" src="https://cloud.githubusercontent.com/assets/24262263/20738403/97ce6248-b691-11e6-91e9-eb435b5f7d6d.png">

**Comment by brunochung** [comment]
my apple tv tvOS 10.01 and my Xcode 8.1

**Comment by jasarien** [comment]
Follow the instructions. https://github.com/jasarien/Provenance/wiki/Building-Provenance

**Comment by brunochung** [comment]
I can not install, I'll post my step by step

**Comment by brunochung** [comment]
<img width="159" alt="captura de tela 2016-11-30 as 05 42 30" src="https://cloud.githubusercontent.com/assets/24262263/20745456/3a581a44-b6c0-11e6-9fce-0f94283dfbc4.png">
<img width="183" alt="captura de tela 2016-11-30 as 05 42 36" src="https://cloud.githubusercontent.com/assets/24262263/20745457/3c162c54-b6c0-11e6-8b45-ec091a2d59e9.png">
<img width="1451" alt="captura de tela 2016-11-30 as 05 43 13" src="https://cloud.githubusercontent.com/assets/24262263/20745461/40e1863e-b6c0-11e6-9162-3d341505e293.png">
<img width="321" alt="captura de tela 2016-11-30 as 05 43 19" src="https://cloud.githubusercontent.com/assets/24262263/20745462/40fb3a48-b6c0-11e6-9b4f-47611a9710a7.png">
<img width="1145" alt="captura de tela 2016-11-30 as 05 43 26" src="https://cloud.githubusercontent.com/assets/24262263/20745463/41081b82-b6c0-11e6-8039-7bd6ca4e5341.png">
<img width="1454" alt="captura de tela 2016-11-30 as 05 43 43" src="https://cloud.githubusercontent.com/assets/24262263/20745464/4108f872-b6c0-11e6-842c-dad5607a02e1.png">
<img width="1229" alt="captura de tela 2016-11-30 as 05 44 18" src="https://cloud.githubusercontent.com/assets/24262263/20745470/46fce590-b6c0-11e6-8f1e-59c70746afaa.png">
<img width="827" alt="captura de tela 2016-11-30 as 05 44 30" src="https://cloud.githubusercontent.com/assets/24262263/20745468/46fa36ec-b6c0-11e6-8588-122028f554af.png">
<img width="722" alt="captura de tela 2016-11-30 as 05 44 43" src="https://cloud.githubusercontent.com/assets/24262263/20745472/4724e874-b6c0-11e6-806d-682efc852e88.png">
<img width="1108" alt="captura de tela 2016-11-30 as 05 44 52" src="https://cloud.githubusercontent.com/assets/24262263/20745469/46fba28e-b6c0-11e6-832d-3a8b114035f5.png">
<img width="1162" alt="captura de tela 2016-11-30 as 05 45 10" src="https://cloud.githubusercontent.com/assets/24262263/20745471/47122f2c-b6c0-11e6-8ae0-d62782a19baa.png">

**Comment by jasarien** [comment]
You haven't followed the instructions I linked to. You didn't change the bundle ID for the top shelf target.

**Comment by brunochung** [comment]
Please, I'm not understanding, take a photo of what I should do.

**Comment by jasarien** [comment]
You need to change the bundle ID of the TopShelf target, just like you already did with the ProvenanceTV target. I can't make it any more clear.

**Comment by brunochung** [comment]
<img width="1413" alt="captura de tela 2016-11-30 as 06 13 09" src="https://cloud.githubusercontent.com/assets/24262263/20746330/19586552-b6c4-11e6-8c3f-3d134d191f9b.png">

**Comment by brunochung** [comment]
Now the error has changed

**Comment by brunochung** [comment]
Help me, I already changed id apple and still the same error continues

**Comment by jasarien** [comment]
Did you even read the error message? The bundle IDs need to be different. You can't enter the same I'd for both targets.

**Comment by lolkthxbai** [comment]
@brunochung each target requires their own unique identifier
Go back to the page that has the column that lists the targets in the Provenance project, just like the last screenshot you posted.
Click on each target (Provenance, ProvenanceTV, and TopShelf) and make sure the bundle identifier is different for each one.
For example:
Provenance - com.gamecorp.Provenance
ProvenanceTV - com.gamecorp.ProvenanceTV
TopShelf - com.gamecorp.TopShelf.ProvenanceTV

PS: Consider removing your screenshots and editing them the next time you post them as your email and name is easily exposed. Cheers

**Comment by JoeMatt** [comment]
Or you know, search first.

https://github.com/jasarien/Provenance/issues/273
