### ISSUE TITLE
Atari 2600 - Controller "reset" also toggles black & white mode

### ISSUE THREAD

**Issue by jimmythegreek** [jasarien/Provenance#471]
Using an 8bitdo icade controller, there is an odd quirk with the button mapping. Joystick controls, "Fire" button, and "game select" all function as expected. However, the "game reset" (i.e. the "start" button) seems to be mapped to 2 functions. It DOES function as the "reset" switch on the Atari, but it also switches the display to black & white mode. Multiple presses of reset doesn't toggle back to color display, however pressing the "select" button does toggle back to color display. 

I looked in the core files (PVStellaGameCore.mm) to see if I could fix this behavior, but the color/b&w behavior wasn't defined there. My guess is it's somewhere in the libretro files, but I didn't know where to look.

**Comment by JoeMatt** [comment]
If this is happening it probably is in libretro. I've only tested with MFi and on screen controls. I have an 8bitdo SNES controller I haven't used yet I can check out.

Is this happening on any specific ROM? More than 1 ROM?

**Comment by jimmythegreek** [comment]
It seems to be consistent across multiple ROMs that I've tested (tried with a few Activision and a few Atari games).  The Pitfall games don't seem to switch to B&W but those are the only exceptions.  Perhaps those games don't have a B&W mode, but that is a complete guess on my part.  I would test the B&W toggle for those 2 games with the original 2600 console, but my mom sold it at a yard sale 20+ years ago (yes, I'm still upset).

**Comment by jimmythegreek** [comment]
I think I found the line of code in libretro.cpp (line 101) that triggers the display to B&W

`    stella->GameConsole->event().set(Event::ConsoleBlackWhite, input_state_cb(Controller::Left, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_R3));
`

The odd thing is that ..._JOYPAD_R3 is not defined/mapped in PVStellaGameCore.mm so I'm not sure how that event is being triggered.

Stumped for the moment but will keep digging.  Let me know if your 8bitdo controller has the same behavior as mine.  I have the 8bitdo zero.

**Comment by JoeMatt** [comment]
There are two sets of ENUMs at work, what provenance uses to send controller data, and what libretro uses to set the button state array, so even if RETRO_DEVICE_ID_JOYPAD_R3 isn't used it might have the same integer value as some other button coming in from Prov. 

Or it might not be that at all. I won't be able to look until this weekend.

**Comment by JoeMatt** [comment]
Finally had a chance to look at this. The issue is the scanning code from Stella looks for 15 values and the buffers were only 12 ints long, and the memory zero'ing was also too short so it was most likely reading junk data. I think it's useful to actually map these controllers to buttons on the gamepads. I'll have something shortly.
