### ISSUE TITLE
iCade controller not working

### ISSUE THREAD

**Issue by jelle619** [jasarien/Provenance#474]
Hello. I really love Provenance, but my Gamesir G3s, an iCade controller, doesn't seem to be working with it. I can confirm the controller is working and I've tried all the layouts available. Whenether I press a button, the emulator does nothing, like it even wasn't connected.

**Comment by jelle619** [comment]
I'm using 1.2.7 (419)

**Comment by jasarien** [comment]
Hi, 1.2.7 is an old version. Please try the latest version from the master branch and create a new issue if it still doesn't work.
