### ISSUE TITLE
Problems on Iphone 7 +

### ISSUE THREAD

**Issue by Raynords** [jasarien/Provenance#480]
After several tests, I notice freezes with repetition and big problem with the sound (sound that cuts and that sizzles) on the emulator SNES.
I repeat the test on my Mini 4 Ipad and no problem of kind.

**Comment by jasarien** [comment]
Dupe of #417

Have you tried the latest version?

**Comment by Raynords** [comment]
Yes it is the last version that I use
I tried to uninstall and re-install and try several Roma and I have always the same problem of freeze and sounds

**Comment by Raynords** [comment]
de plus les controles se retrouve au millieu de l'ecran au lieu de se trouver en bas.
