### ISSUE TITLE
Steelseries Nimbus controller latency

### ISSUE THREAD

**Issue by mykeln** [jasarien/Provenance#481]
I saw some code was merged that was supposed to address this, but I just bought a brand new Steelseries Nimbus controller and am experiencing some lag on the SNES emulator that makes games unplayable.

Here's a video: https://www.youtube.com/watch?v=0h7mwOxdTHo&feature=youtu.be

Running on version 1.2.7 (514) RELEASE.

**Comment by appletv4** [comment]
Did you update the firmware of the controller ?

**Comment by mykeln** [comment]
When running the Steeleries app, it says the firmware is up-to-date, so I assume so! I will double check the versions.

**Comment by jasarien** [comment]
You're running 1.2.7 which is old now. Try updating to 1.3 and see if it helps.

**Comment by mykeln** [comment]
Well that's embarrassing! I did a git clone and figured it'd give me the latest version; just did a sync and have 1.3 built. It's now throwing an error 'ProSystemGameCore.h file not found' but I will assume that's on my end. Will keep investigating. Thanks for your help! Will close this.

**Comment by mykeln** [comment]
Okay. 1.3 installed and running. Nimbus firmware is 1.6.4.1. Delay seems to be about the same as the video above, unfortunately.

**Comment by jasarien** [comment]
Could you try again with the latest master code? I merged in a PR that changed how frame execution  works and should be more accurate. I don't know if it will actually solve anything, it's good to know.

**Comment by mykeln** [comment]
BEFORE:
https://youtu.be/buqhuJMmoVo

AFTER:
https://youtu.be/j_Fplhhk6Uk

AFTER is confirmed running revision 4baa3e3.

**Comment by vitalizm** [comment]
I am also having the lag issue with the SteelSeries Nimbus controller on my Apple TV 4. Firmware up to date.

**Comment by orenwolf** [comment]
I just got a fresh SteelSeries Nimbus this week and am not experiencing latency - I wonder if the problem you're seeing is latency from your TV, rather than latency from the emulator? I use an old LCoS 60" rear projection set which is as instant as it gets.

**Comment by mykeln** [comment]
You know, that's a really good point. I will double check the ATV is on "Game Mode"

**Comment by mykeln** [comment]
Confirmed. I switched the TV to game mode and it performs flawlessly. Amateur hour on my end! Thanks for the help and patience everyone.
