### ISSUE TITLE
Local multiplayer on Jailbroken iphone 6 with 2 PS3 controllers. 

### ISSUE THREAD

**Issue by khangkaka** [jasarien/Provenance#488]
hello. I'm really enjoy your works and I'm experiencing this problem. 
Whenever I connect my ps3 controllers for using Provenance (for SNES games), it turns off the touch screen controller on my iphone 6 (ios 9.3.1 Jailbroken) 
Even though I select my controller specifically for player 2, but the touch screen buttons still gone. 
I want to play 2 players locally on my iphone. Is there a way to fix this? Player 1 on touch , player 2 using PS3 controller is fine, or player 1&2 using their own PS3 controllers even better.
Sorry for English is not my native language.

**Comment by apexad** [comment]
I do not think jailbreak issues are supported.

**Comment by khangkaka** [comment]
hmm. but without jailbreak i cannot get my phone to work with my PS3 controller.

**Comment by jasarien** [comment]
That's the bit that's unsupported

**Comment by khangkaka** [comment]
alright. what if i want to play local coop with 2 players ? 1 with MFi controller and 1 with touch screen, or both with MFi controllers ?

**Comment by jasarien** [comment]
Two MFi controllers works fine for local multiplayer. 

I'd argue that it doesn't make sense to have 1 mfi and still want to use the touch screen as one person's fingers would be in the way and the other person with the mfi controller wouldn't be able to see the screen. 

Either way whenever a controller is connected the on-screen controls are hidden. This can be changed in the future - I'd prefer it to be a setting.

**Comment by khangkaka** [comment]
Thanks for your reply. 
MFi controllers are quite expensive though.

**Comment by jasarien** [comment]
I don't set the prices, sorry.
