### ISSUE TITLE
Add games using UIDocumentPickerViewController

### ISSUE THREAD

**Issue by marcelvoss** [jasarien/Provenance#495]
It should be possible to add games to Provenance using [UIDocumentPickerViewController](https://developer.apple.com/reference/uikit/uidocumentpickerviewcontroller). This would allow users to import games from Dropbox or any other app that provides a UIDocumentPickerViewController extension without leaving the app.

This would require the iCloud entitlement but that should be okay if we describe that in detail in the wiki, right? I mean, users have to compile it on their own anyways.

Quick example of the document picker in action:
![d4z66](https://cloud.githubusercontent.com/assets/5435925/21542319/36c3d2a6-cdbd-11e6-9890-96131c104180.png)

**Comment by lolkthxbai** [comment]
Does this work for tvOS?

**Comment by marcelvoss** [comment]
Nope, but we could do a fallback for tvOS that'll do the same thing as before. So, nothing changes for tvOS users.

**Comment by lolkthxbai** [comment]
Last I remember, @jasarien did not want to maintain two separate implementations #1 
Ideally, that would be great to not have to split them between tvOS and iOS but it might be worth looking into because importing roms is essential to the function of Provenance and iOS users would greatly benefit from this

**Comment by marcelvoss** [comment]
Right, I understand that but why would we split it into two separate implementations? We could simply use the good old preprocessor macros to check for the current target and add a fallback for tvOS. It's not that complicated – I just built a prototype for this.

Apart from having access to UIDocumentPickerViewController we could also finally add synching via iCloud. Users will have to do a couple of more steps, in order to compile Provenance but will have huge benefits of this. I would love to see Provenance become even more powerful by adding these features.

**Comment by codemonkey85** [comment]
@marcelvoss
> I just built a prototype for this.

What did you do to accomplish that? I'm interested in doing the same for my build.

**Comment by JoeMatt** [comment]
This is now in the N64+Swift feature branch. Seems to be working without iCloud entitlements for me but I have a real dev account linked to app. Could use some testing from non-dev account users.
