### ISSUE TITLE
Take screenshot for save states

### ISSUE THREAD

**Issue by marcelvoss** [jasarien/Provenance#496]
It would be handy to have a screenshot for every save state that'll be taken right before saving the state. This way, it'll become a lot easier to find the save state you are looking for since every screenshot is associated with its save state. OpenEmu provides a very similar feature which definitely improves the UX.

![screen shot 2016-12-29 at 12 04 58](https://cloud.githubusercontent.com/assets/5435925/21542595/2d65e9b8-cdbf-11e6-9688-a66ded6e6094.png)

This would obviously require a new UI for the save state menu (it is a UIAlertController with action sheet style at the moment).

**Comment by sevdestruct** [comment]
closing this to merging this into newer #719 , part of 2.0 milestone…
