### ISSUE TITLE
if Build Location is set to "legacy" Provence doesn't build

### ISSUE THREAD

**Issue by RobertoD91** [jasarien/Provenance#498]
Hi, if "Build Location" (Preferences -> Locations -> Derived Data -> Advanced ) is set to "legacy" Procevence doesn't build.

i have a lot of error:
a lot of header files like "PVSupport/DebugUtils.h" and other are not found
all framework like "PVSupport.framework" are built but are not found in later steps.

I don't think it is necessary to fix this "bug", but I want to report.
maybe write it in the wiki build instructions

**Comment by jasarien** [comment]
Done, thanks.
