### ISSUE TITLE
tvOS App Installation Fails

### ISSUE THREAD

**Issue by amlcreative** [jasarien/Provenance#499]
Hi there,

After closely following the instructions I still can't successfully install the app for tvOS. I changed the Bundle Indentifier for TopShelf, ProvenanceTV and Provenance to exactly the same thing (see screenshots) and yet it still won't install.

There are other closely-related issues and I checked them to see if the resolution could help me but none of them did. Any help is greatly appreciated!

![screen shot 2016-12-29 at 6 14 50 pm](https://cloud.githubusercontent.com/assets/17347996/21558204/4db7a95c-cdf3-11e6-96aa-038698e664a7.png)
![screen shot 2016-12-29 at 6 15 03 pm](https://cloud.githubusercontent.com/assets/17347996/21558205/4dc89122-cdf3-11e6-838f-5bc95a42e50d.png)
![screen shot 2016-12-29 at 6 15 15 pm](https://cloud.githubusercontent.com/assets/17347996/21558206/4dcbe0c0-cdf3-11e6-8875-1116eda79cdc.png)
![screen shot 2016-12-29 at 6 15 39 pm](https://cloud.githubusercontent.com/assets/17347996/21558207/4dcc06a4-cdf3-11e6-9baa-9342aa2c0ca5.png)

**Comment by appletv4** [comment]
I'm no app developer or know anything about Xcode but I think that message means somebody else is using that name 

Try another or add numbers to the end of it

**Comment by jasarien** [comment]
Each target needs a unique bundle ID, but they need the same prefix. 

EG:

com.banderan.provenance
com.banderan.provenanceTV
com.banderan.provenanceTV.TopShelf
