### ISSUE TITLE
Provenance TV doesn't build, gives 'PVSupport/DebugUtils.h' file not found error

### ISSUE THREAD

**Issue by geekchicshipper** [jasarien/Provenance#501]
Whenever I try to build Provenance onto my Apple TV, the build fails with the error "'PVSupport/DebugUtils.h' file not found." Followed all instructions on the wiki to the letter, even tried to get the repo again, plz help.

**Comment by timmfin** [comment]
I had the same problem when I first started. We both missed one important detail in the instructions.

> Open the Provenance Xcode workspace (the white icon, not the blue icon). 
>
> ![](https://camo.githubusercontent.com/99f1fb12ef7c66e6bda7a89a7f84a3ac50838522/687474703a2f2f642e70722f692f3161316b482b)

The white icon has all the projects setup correctly for you, the blue one doesn't... hence the build error.
