### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by nharkins** [jasarien/Provenance#502]
Hi. I am "following the instructions on your wiki *to the letter*", yet
am continually frustrated by trying to build Provenance, just as you seem 
to be frustrated supporting it (judging from the other issues' responses). 
I know git and gcc compilation on unix quite well, but am admittedly 
unfamiliar with Xcode, as it seems are most of your "customers"
(so-to-speak). By filing this issue, I'm trying to A) help others
build provenance more easily, and B) thereby reduce the
amount of support questions and frustration you experience.

Last January, I was able to build Provenance 1.2.6 
with a free developer account, and load it onto my ATV3.
It was by no means easy then, but it worked... for about one week.
After reading in the new docs that it probably expired and would 
need to continually be re-signed and rebuilt every week, 
I finally paid apple $99 for a one year supported developer 
membership today, but still ran into problems building on 
OSX El Capitan 10.11.6  with X-Code 8.2 and an ATV3 
running tvOS 10.1.

Although better than the previous docs, even the new docs at 
https://github.com/jasarien/Provenance/wiki/Building-Provenance#building-for-ios
did not work as described. I have suggested some improvements below
and am willing to make the changes to the wiki myself if you'd like,
although it'd be good to first understand how and why my experience 
diverged from the docs.

First off, please use numbered bullets in docs, so steps can be referred to easily.
Because they are not numbered today, I will use the first few words/sentence:

* "Open the Provenance Xcode workspace (the white icon, not the blue icon)."

After doing this, Xcode's status bar (very top of the window, middle) says 
""Indexing | Processing Files" for *8* minutes. That's a VERY long time, 
and the reader's expectation should be set (or is there a way to defer 
indexing until actually building?). Also note that if you change the
"scheme" at any point, it will start indexing all over again. Argh.

To the right of that text is a warning icon ("!" in a yellow triangle)
with the number "3" next to it. The three issues are PVSNES,
PVGenesis, and PVGBA, "Update to recommended settings".
This should also be called out by the docs if they can be ignored,
e.g. fixed by a later step in the process.

* "Open Xcode preferences, and from the Accounts tab, sign in with your developer account"

This is fairly simple to do, HOWEVER the docs should provide the reader some idea 
of what they should expect to see if they have completed this step properly. e.g.
Under my apple id, I see two "Teams": one with just my name, which is an "Agent" Role,
another which has my name followed by "(Personal Team)", which is a "User" Role.
The latter does not seem to be delete-able, nor is the old/expired provisioning profile.
The former does have a non-expired provisioning profile, which i created at
developer.apple.com, downloaded and "installed" (merely by double-clicking it).

* "From the project settings, select your Development Team and update the bundle ID to something unique."

It is completely unclear how to access "project settings". Xcode has *tons* of UI widgets, 
and none of them seem to have "tooltips" when you hover over them. 
A screenshot of how to access this should be included in your docs.
I believe I have found this, because I see fields matching the small
screenshot you include here, HOWEVER there are multiple "targets":
"Provenance", "ProvenanceTV", "Provenance Tests", and "TopShelf".
Your docs fail to distinguish between any of them them. Aside from 
"Provenance Tests", the other three have "Bundle Identifier" and "Team" 
fields, but changing it for one of them does not change the others. 
At this point, after changing both fields as directed, a "Status" area 
appears below, containing two error icons (red octagon with a "!"). 
They are:
** "Failed to create provisioning profile. There are no devices registered in your
account on the developer website. Plug in and select a device to have Xcode register it."
** "No profiles for 'com.neilharkins.Provenance' were found. Xcode couldn't find a
provisioning profile matching 'com.neilharkins.Provenance' "

It's worth noting that those two errors do NOT happen if those changes
are made in "ProvenanceTV" and "TopShelf" instead of "Provenance". 

* "Select 'Provenance-Release' from the Scheme menu"

It's not clear to an Xcode beginner what a scheme is
or where it is to be selected. Screenshot please.

* "Select your connected iOS device from the device menu"

Note that 'device' is a submenu of the scheme menu,
so this step could be combined with the previous step.
However, my 'device' submenu says "No devices connected to 'My Mac'..."
I don't know why that is, because following the dialog shows the device 
and says it is connected. It also shows up in "Menubar->Window->Devices" 
AND it shows up as a submenu option for the "ProvenanceTV-Release" scheme, 
but NOT for the "Provenance" or "Provenance-Release" schemes.

* "Hit the Run button."
* "You might see a message saying there are no signing identities found. Just press 'Fix it' and rebuild."

I can't even get to this point with "Provenance-Release", 
but a screenshot of this "Fix it" button should be provided. 

With "ProvenanceTV-Release", I was able to successfully build,
but when it tried to load the program onto the appletv, it errored
with: "This application's application-identifier entitlement does
not match that of the installed application These values must
match for an upgrade to be allowed". Note that the "display name"
and "bundle id" *DO* match the "Installed Apps" entry in the
Menubar->Window->Devices pane, but I assume that the
free developer account no longer matches my paid 
developer account id.

Next, I deleted the installed app from the atv, then 
was able to install, although interestingly, the Version 
in the Menubar->Window->Devices is "645", 
i.e. the build number, not the version (1.3.1).

I now have the application loaded successfully, was able
to load a ROM and play it. I'll update here next week if it
still works, which would indicate the correct/paid Team 
is being used, not the free developer account which I
can't seem to delete.

Finally, is there a "tipjar" where users can donate to Provenance maintainers?

**Comment by QuarterSwede** [comment]
I'll clear up some of this. Provenance and Provenance-Release are for iOS devices only (iPhone & iPad). ProvenanceTV-Release is for tvOS (Apple TV 4) only. 

Also you don't have to wait for it to finish indexing when no device is selected. Attach your device, and then select the appropriate Provenance release and drill down to the attached device. It'll start indexing from there. Once it's done hit run and it'll compile and install to the device.

**Comment by sevdestruct** [comment]
@nharkins: so, you, might be happy to know someone here agrees with your suggestions above and I've actually been rewriting all the docs from the ground up for clarity, information srchitexture and to be more concise and specific or broad where neeses., And otherwise organizing the without or it all. It's on going process, but a lot is already done, you can follow the progress in the new doc updates project here in out GitHub. I will be rewriting the installation docs soon as well, trying to eat there done before 1.5 release.

**Comment by sevdestruct** [comment]
Will link this to the board for reference but otherwise I am closing this issue now that this is underway and being tracked so it's specific suggestion can be folded into the tasks at hand:

**Comment by sevdestruct** [comment]
(Just tidying up loose ends) The wiki has officially been relocated: https://wiki.provenance-emu.com/
