### ISSUE TITLE
Menu button on Steelseries Nimbus controller bypasses in-game menu, goes straight to games library view

### ISSUE THREAD

**Issue by starlessblack** [jasarien/Provenance#506]
So I just downloaded and built ver 1.3.1 a few days ago, and I'm having this problem: SteelSeries Nimbus controller, ATV4 running latest iOS ver.10.1--Menu button on Nimbus controller goes straight back to Provenance games library, not to in-game menu. My workaround has been to quickly double-tap the Siri button on the ATV remote which briefly brings up the Siri listening dialog but also has the side effect of pausing the game and bringing up the in-game menu.

I also noticed that if I turned on the iCade controller support in Provenance settings, it appears to fix the menu button issue, however, it also appears to map the Nimbus' "B" button to Menu. Or, rather, it's double-mapped--if you hit the B button, you can briefly see your in-game sprite or whatever start doing what it's supposed to do (jump, shoot, stab, run, flee, fly, kick, dance, etc.), but only for a brief millisecond before the in-game menu pops up.

**Comment by rogersbowne** [comment]
I am having the same exact issues in the same situations.

**Comment by OKNoah** [comment]
Affects Mad Catz CTRLi too.

**Comment by jasarien** [comment]
I just merged #503 - you can try the latest code in master and see if it fixes the issue?

**Comment by starlessblack** [comment]
Yep! That #503 fix did the trick! Thank you, and keep up the great work :-)

**Comment by zfisher323** [comment]
First. Great app, thanks! Just recently updated from 1.2.7 to 1.3.2. I'm having the B button issue. Using nimbus steel series controller. When I press the B button in-game, it does the B butting Action but also immediately pulls up the provenance in-game menu. Am I doing something wrong? Thanks. Zack

**Comment by zelik** [comment]
Same issue as zfisher,  don't know if this is something wrongly configured on my side?  Love this app. Helps with being in hospital!

**Comment by lolkthxbai** [comment]
@zelik the issue was resolved but resurfaced again PR #561 resolves the issue but was merged into PR #566 As soon as the pull request is merged into master you can update the app to fix it. In the meantime, using the Siri button tvOS can be used as a workaround
