### ISSUE TITLE
Will only load NES titles on tvOS 

### ISSUE THREAD

**Issue by Chouse28** [jasarien/Provenance#507]
I just loaded provenance onto my Apple TV 4. I can get whichever NES game that I want, but whenever I try SNES or anything else, it won't load them. What I am doing wrong?

**Comment by jasarien** [comment]
Can you give some more detail on your issue?  Which version of Provenance are you using? Which ROMs are you trying to import? What are the file extensions of the ROMs that "won't load"? What do you mean by "won't load", do they import into the library? If so, what happens when you try to run them? The more detail you provide the better I can help find out what's wrong.

**Comment by Chouse28** [comment]
Hello,
I am running Provenance tvOS 1.2 and tvOS 10.1

All the NES roms will import and play fine into the library. When I tried to import Mario Kart for SNES and N64 they wouldn't even import into the library.

http://www.freeroms.com/dl_roms/rom_download.php?title=super_mario_kart&system=SNES&game_id=28448

http://www.freeroms.com/dl_roms/rom_download.php?title=mario_kart_64&system=N64&game_id=3845

These are the 2 files I tried. And neither were able to import. I believe they are both .7z files

Thanks!

Sent from my iPhone

On Jan 5, 2017, at 2:01 PM, James Addyman <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you give some more detail on your issue? Which version of Provenance are you using? Which ROMs are you trying to import? What are the file extensions of the ROMs that "won't load"? What do you mean by "won't load", do they import into the library? If so, what happens when you try to run them? The more detail you provide the better I can help find out what's wrong.

-

**Comment by Chouse28** [comment]
Ok. I will try converting 7zip to zip. Thanks for your help!

Sent from my iPhone

On Jan 5, 2017, at 3:36 PM, James Addyman <notifications@github.com<mailto:notifications@github.com>> wrote:


7z archives are unsupported. You need Zip archives.

-

**Comment by imseandavis** [comment]
Verified the same thing happens reported by @Chouse28 with 7z, but works fine with a regular zip file. This should be able to be closed :)

**Comment by gingerbeardman** [comment]
Looks like the NES core supports 7zip?
