### ISSUE TITLE
ERROR! What is it?

### ISSUE THREAD

**Issue by iTKirill** [jasarien/Provenance#509]
install in Apple tv

None of your accounts are a member of '63497P68S6':  An unexpected error occurred. Xcode cannot find a team matching '63497P68S6'.
No profiles for 'com.provenance-emu.provenancetv.topshelf' were found:  Xcode couldn't find a provisioning profile matching 'com.provenance-emu.provenancetv.topshelf'.
Code signing is required for product type 'TV App Extension' in SDK 'tvOS 10.1'

**Comment by lolkthxbai** [comment]
If you're using a free Apple developer account you can not use the topshelf feature. Topshelf requires AppGroup functionality which is only available to paid developers.
If you've used multiple Apple IDs in Xcode make sure you are using the same one to sign each target and that the `companyname` in your bundle identifier is the same.

**Comment by orenwolf** [comment]
@lolkthxbai actually I was able to get topshelf working just fine with a free account, following the instructions in #242 - I'm not sure if it changed recently but it's possible free devs can use App Groups now?
