### ISSUE TITLE
Provenance stopped working

### ISSUE THREAD

**Issue by genesisfreak** [jasarien/Provenance#51]
I don't understand what and how it happened but just yesterday I went to fire up the emulator on my iPhone and it immediately quit out everytime. Only Rom I had on it was sonic 3 & knuckles which worked no problems before that. I uninstalled and tried to reinstall it thinking it might just be a weird bug, now it will not install at all. Can't figure out what the issue is.

**Comment by jasarien** [comment]
According to iEmulators' tweets, it seems the cert they used to sign the app for distribution was revoked again, which will cause the issues you're seeing. Wait until they get a new version up, or contact them for more information.

<blockquote class="twitter-tweet" lang="en-gb"><p>We&#39;re aware of some issues with some apps crashing. It&#39;s that time again, cert was revoked. Don&#39;t worry, we&#39;re working on it! :)</p>&mdash; iEmulators (@iEmulators) <a href="https://twitter.com/iEmulators/status/553329016963624961">January 8, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by genesisfreak** [comment]
Ok great, thanks for the quick update, I did not know of iemulators since I got my version from a different source that needed a password. Thanks again
