### ISSUE TITLE
Won't import N64 games

### ISSUE THREAD

**Issue by Chouse28** [jasarien/Provenance#510]
Hello,
I have another issue. I got SNES, NES and Sega games to import, once they were all .zip files. I however cannot import any N64 game. They are .zip files for sure. I have tried the same N64 game from 3 different sites and none of them will import. Please Help!!

I am using Provenance 1.2.7 and tvOS 10.1.

Thanks

**Comment by JoeMatt** [comment]
Provenance doesn't support N64 at this time.

**Comment by Chouse28** [comment]
Ok. Thank You

Sent from my iPhone

On Jan 9, 2017, at 7:14 PM, Joe Mattiello <notifications@github.com<mailto:notifications@github.com>> wrote:


Provenance doesn't support N64 at this time.

-
