### ISSUE TITLE
Donation Link

### ISSUE THREAD

**Issue by blark** [jasarien/Provenance#513]
You're doing a great job here. You should put a donation link somewhere so those of us reaping the benefits of your work can give a little back...

**Comment by orenwolf** [comment]
Seconded. Please do so!

**Comment by jasarien** [comment]
Thanks for the kind words. However there won't be any donation links for a couple of reasons. 

The main reason is that Provenance wouldn't be possible without the extremely hard work done by the emulator authors. If anyone should be donated to, it's them. 

Another reason is that as soon as people start contributing money to open source projects they tend to get a feeling of entitlement that they're now paying for something and expect certain work to be done when they expect it. Obviously this is something I want to avoid. 

The best way for people who don't program to contribute is to find and document bugs and request features at the issues section. The more tasks there are, the more developers might find something they may want to work on.

**Comment by asaladino** [comment]
Well said.
