### ISSUE TITLE
Provenance stopped starting

### ISSUE THREAD

**Issue by Costeau** [jasarien/Provenance#515]
Hi all

First Thanks for the great emulator - i love it. 

I have however experienced an issue and need som help.  Provenance wont start anymore. I played on it a few hours earlier, and everything worked smooth. When I tried again it just highlighted and did not load/start up. The wholebuild is only a week old. Anyone tried this and have a solution. Its on Apple tv 4 

Thanks

**Comment by jasarien** [comment]
Free developer accounts only allow 7-day provisioning profiles. Rebuild the app to your apple TV and it will work again for another week. 

Make sure to use the same bundle ID as you did previously or else you'll lose your data

**Comment by Costeau** [comment]
Thanks for the answer. So you have to rebuild each week? I Hope Apple would alle emulator on the shop

**Comment by jasarien** [comment]
You can pay $99/year for a full developer account where the profiles last for a year. Other than that, yes you need to rebuild each week. Apple will never allow an emulator on the app store. Too many legal and security issues.

**Comment by Costeau** [comment]
Yeah I know. But thanks for you great work:-)
