### ISSUE TITLE
Bundle Identifier Not Prefixed 

### ISSUE THREAD

**Issue by maxbiscuit** [jasarien/Provenance#516]
New to this, I'm getting this error. I'm sure it is quite simple, however I have tried prefixing the Topshelf bundle identifier with the Parent App bundle Identifier, and I still get the same error.

error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

		Embedded Binary Bundle Identifier:	com.provmax12.topshelf
		Parent App Bundle Identifier:		com.provmax12.provenancetv

**Comment by maxbiscuit** [comment]
OK - Worked out - needed to have the full ID com.provmax12.provenancetv not just the middle section - so it was com.provmax12.provenancetv.topshelf. Instructions kind of imply it is just the middle section that needs changing. Now to plug it back into the TV and see if it runs.

**Comment by dkatsafouros** [comment]
Thanks for the explanation. Was stuck on this without knowing what to do!
