### ISSUE TITLE
Atari 2600 games not loading on AppleTV

### ISSUE THREAD

**Issue by jamesmweir3** [jasarien/Provenance#519]
NES roms all load great, but none of the Atari roms will.  The artwork for them shows up but when I try to launch one I just get a black screen.  They are all in .bin format, but they show up as GENESIS titles in Provenance.

**Comment by JoeMatt** [comment]
Rename the roms with the proper extensions for their system and reimport. 
Should be, .a26, .a52, .a78; for 2600, 5200, 7800.

**Comment by gareauk** [comment]
Found these instructions in another forum.  It worked for me on my iPad.

Known Issues. - Atari2600 rom extension conflicts with Sega Genesis as they are both .bin extensions, see below how to add 2600 Roms.

Add Atari2600 Roms.

[iTunes Method] 1. Plug phone in of course 2. Navigate to your Phone/Apps in iTunes 3. Click Provenance 4. Make a folder called "com.provenance.2600" 5. Put the 2600 roms into the folder you made. 6. Drag folder into Directory shown in iTunes (right side) 7. Enjoy.

[Webserver Method] {?} 1. Access the webserver with the IP Provenance gives. 2. Make a folder called "com.provenance.2600" 3. Put the 2600 roms into the folder you made. 4. Enjoy

**Comment by drjackyl** [comment]
A hint somewhere about this would be nice.

The `systems.plist` contains the mapping of file-extensions to systems:

**Atari**

Atari 2600: a26
Atari 7800: a78

**Nintendo**

Famicom Disk System: fds
Gameboy: gb
Gameboy Advance: gba
Gameboy Color: gbc, sgb
NES: nes
SNES: smc, snes, fig, sfc

**Sega**

Sega 32X: 32X, 32x
Sega Game Gear: gg
Sega Genesis: smd, bin, md, gen
Sega Master System: sms
Sega SG-1000: sg
SegaCD: cue

Didn't check these results, though. "cue" sounds like cue/bin.
