### ISSUE TITLE
Sega Mega CD - Bios Not Working

### ISSUE THREAD

**Issue by mypurdue99** [jasarien/Provenance#521]
Bc if the recent revocation of Provence I got the $10 dev kit and all games work save sega cd.  In the past, I could get scge cd to work by placing the bios in a variety of locations until I got the games working.  With this paid version I have not only done that but also followed every online instruction to the "t" even capitalization and renaming bios and still either get "no bios" in the segacd area or "game corrupt"in the genesis area.  I followed that latest on this site too.  Any additional guidance?

**Comment by mypurdue99** [comment]
I meant build store - not dev kit

**Comment by jasarien** [comment]
You've followed these instructions regarding the BIOS? https://github.com/jasarien/Provenance/wiki/Sega-MegaCD-Instructions

You need each BIOS for each region, US, EU and JP.

Ensure the BIOS files your are using are valid and unmodified. Try downloading them from a different source if the ones you have don't work. 

Just as a side note: the "paid version" is not official in any way and may even be an older version than the source code found here. You can always get the latest source code from here for free and build it yourself. You paid for the distribution method, not the application.

**Comment by mypurdue99** [comment]
AHA! Your last paragraph is probably the answer. I am a mechanical engineer so I may be slow in learning how to get the source code and figuring out what to do.  Shall I presume it wont be as simple as the download was from iemulator to my ipad for this older version I probably have?

In the mantime, I am reading through your pages around here to try and find out for myself.

Thank you too!

JIM

**Comment by jasarien** [comment]
Sega CD has been supported for a while, and nothing significant has changed, since it was added, so the version you have from buildstore is likely to be fully functional in terms of Sega CD. 

Just make sure you're following the instructions for placing the BIOS files and using the correct names and ensuring their valid.
