### ISSUE TITLE
App Installation Failed

### ISSUE THREAD

**Issue by AMilitantPeanut** [jasarien/Provenance#524]
Thanks to everyone on these forums who has been contributing and to all of the hard work that has gone into developing the Provenance app. I have really been helped by reading everything here.  However, I am still having some slight issues:

I am following all of the instructions on the Provenance wiki.  I have the Apple developer account and I am running Xcode 8.2.1 on OS 10.12.2. I go through the build process with no hiccups, get everything working just fine--the build goes through successfully.  However, after everything is done, I get a popup in Xcode that says, _"App Installation Failed" and says the bundle identifiers  is the same as another bundle identifier._  

I have cleaned and re-built several times after double-checking everything.  I have even started from scratch and done several new builds, including removing the AppleTV and testing it a few times to see if maybe something was just wonky.  I even use a new, unique bundle identifier with each attempted new build.

Has anyone else had a similar issue or have suggestions on how to get this fixed?  Thanks, in advance, for any help you can offer!

**Comment by lolkthxbai** [comment]
@AMilitantPeanut Hello! According to the error message it seems that the bundle identifiers have not been set properly. Please make sure you're using unique bundle identifiers for each target in the Provenance project. For more information, check out #499

**Comment by jasarien** [comment]
@AMilitantPeanut as @lolkthxbai said, in following the instructions you missed out a very important step. You need to use your own unique bundle identifiers for the targets.
