### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by xXToYeDXx** [jasarien/Provenance#526]
First, let me say thank you for your work on Provenance. It works very well and was actually easy to compile and install. Took me 5 minutes from cloning the git to transferring roms. In every game I've played so far the emulation has been smooth, at full speed and very accurate.

However I have a few features I'd like to request.

1) The ability to filter my roms by system. Currently the rom list lists all of my roms on one scrollable page. It would be nice when I want to play a particular system to be able to only see roms for that system.

2) Other have requested this but I will add it here too. The ability to resize and reposition the Dpad, face buttons, L and R, Menu, Start and Select buttons. In all games the Dpad overlaps the game's viewport making my thumb cover important parts of the screen.

3) I haven't tested this as I don't have a compatible controller just yet so it may already be there, however I will be getting one (probably the Gamevice) and think this would be a great feature to have. If we could reduce the on screen controls opacity to 0% while using a physical MFi or iCade controller so they aren't distracting.

4) Support for a few more systems such as PC-Engine/TurboGfx 16, N64, PSP, Playstation 1.

5) Multi touch support for all on screen buttons. Others have pointed out that certain games, such as Zelda Link's Awakening, requires Start+Select+B+A for battery saves and currently this is not possible as Start and Select are not registering as two separate buttons when both pressed at the same time. It may help to separate them and make them slightly larger. Perhaps placing Start in the bottom right corner, under the face buttons, and Select in the bottom left, under the Dpad?

6) It would be great to be able to play original GB games in monochrome/greyscale rather than with a preselected colour palette. Super Mario Land 2: 6 Golden Coins for example loads up with an awful blue and brown colour palette. Please note I am not talking about playing GBC games in greyscale, I mean original GB games before GBC was a thing.

7) Is it possible to customize the intensity of the Taptic feedback for button presses? Maybe make them vibrate a bit harder?

If I think of any more I'll add them. Again, thank you for all your work on this project. I'm fairly tech savvy but I'm not programmer yet I found the install instructions easy to follow and the process super easy.

**Comment by jasarien** [comment]
Hi thanks for the feedback. Many of the requests you make are already being tracked in their own issue:

1. #3 
2. #114
3. Already implemented
4. #17 
5. #517 
6. #60 
7. This can be looked into. There are three types of Taptic feedback, Impact, Selection and Notification (notification has three subtypes: Success, Warning, Error). The notification types aren't useful and they're feel like double taps. Currently Provenance uses the Selection type, which is fairly subtle. Impact is slightly more intense than Selection, so perhaps that could be a setting to use if you really want it. I am concerned as to how using the Taptic Engine affects battery life (and or the life of the Engine itself) -- I haven't seen any stats on this topic. I would imagine that the frequency of button presses that trigger Taptic Feedback probably can't be good for it.

I will close this issue. Feel free to create a new one for the Taptic Feedback Intensity and copy across my comments from point 7 above.

**Comment by xXToYeDXx** [comment]
On the 7 Plus I don't see it being too big of a hit on battery life, but I take your point for non plus devices. It's a thought, however it's number 7 on my list for a reason. It's something that would be nice, but I don't consider it terribly important.
