### ISSUE TITLE
No pop-up menu, can`t start play any game AppleTv 4

### ISSUE THREAD

**Issue by ra1224** [jasarien/Provenance#528]
Hello, import ROMs and can`t push start button using apple tv remote. It must be some pop up menu, only can switch (select button). Can somebody help? tvOS v. 10.1.1, provenance 1.2.6. Thanks

**Comment by jasarien** [comment]
It's difficult to understand what your problem is. 

When using the Siri remote the start button is an option in the pause menu which is accessed by pressing the menu button on the Siri remote.

**Comment by ra1224** [comment]
When I pressing pause menu on siri remote nothing happens. So I can`t start play.

**Comment by jasarien** [comment]
Have you tried using the latest version 1.3.2? https://github.com/jasarien/Provenance/releases/tag/1.3.2

1.2.6 had a bug where the menu button would dismiss the game.

**Comment by ra1224** [comment]
Ok, thanks, will try

**Comment by jasarien** [comment]
Not heard anything back in 2 weeks - assuming fixed?
