### ISSUE TITLE
Save states shared across three NES games

### ISSUE THREAD

**Issue by cristofercruz** [jasarien/Provenance#529]
Just started using Provenance on Apple TV today so hopefully this isn't just some misunderstood behavior.

I have loaded SMB and SMB2 for NES and the save states seem to be shared for both games. Attempting to load one of the save states created from the other game obviously causes a hang as the data is not for that game.

Choosing the reset item in the menu causes the save states to be reset across both games.

Doesn't seem to be related to naming. I attempted to rename the game via the Apple TV UI and still had the same issue.

Hoping this can be fixed in a way to allow each game to have it's own 5 slots for save states.

**Comment by jasarien** [comment]
This could still be a naming issue. Renaming the game in the tvOS UI doesn't change the filename of the ROM on disk (only its displayed name in the database). 

Could you post the exact file names of both ROMs please? Provenance uses the ROM filename as the basis for save states.

**Comment by cristofercruz** [comment]
Thanks for the feedback. It does seem to be a naming issue. I checked further and save states are shared across the three following roms:

```
Super Mario Bros. (Japan, USA).nes
Super Mario Bros. 2 (USA).nes
Super Mario Bros. 3 (USA).nes
```

Something having to do with the periods in the filename, maybe? Other sequence games like Mega Man are not seeing the same behavior.

**Comment by jasarien** [comment]
Yeah it's that dot after the 'bros'. Should be an easy fix I think.
