### ISSUE TITLE
Web server UI file download fails when filename includes comma

### ISSUE THREAD

**Issue by cristofercruz** [jasarien/Provenance#530]
Attempting to download certain roms from the web server interface fails. Checking common factors, the downloads that fail all have a comma included in the filename.

Here's one such example filename:
`Super Mario Bros. (Japan, USA).nes`

Trying in Chrome and get the following error:
`ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION`

**Comment by jasarien** [comment]
Interesting. I don't download from the webserver so much so I haven't encountered this one myself. 

I'll check it out.
