### ISSUE TITLE
Emulation Skipping on iPhone 7 Plus

### ISSUE THREAD

**Issue by KJ64** [jasarien/Provenance#532]
I recently upgraded from my iPhone 5S to an iPhone 7 Plus, running iOS 10.2.1. Following this upgrade, I have noticed an issue in Provenance. I am using the supplied prebuilt binary for version 1.3.2, specifically revision 27560f9. The SNES core and the GBA core specifically seem to be suffering from stuttering and skipping that was not present when they were run on my 5S, also running iOS 10.2.1. These "skips" consist of the video suddenly freezing and attempting to resume, resulting in lost frames. The same effect happens to the audio, skipping forward creating some garbled sounds. The games tested were Sonic Advance for the GBA and Super Mario World for the SNES. This is also occurring on some of the other cores, though to a much lesser extent and is nearly unnoticeable. I also tested two, slightly more recent builds: revision 5b7e242, and bc6a42a(the latest as of the time of original posting). Both were confirmed to have the same issues. All three of these tested revisions were built using the RELEASE mode. I recall seeing an issue similar to this, but it also involved the phone restarting. I have not encountered such an issue in the builds I am running, only the skipping issue. If more information is needed, do not hesitate to ask. I also urge anyone to test under these circumstances if you have the same hardware.

**Comment by kurtbitner** [comment]
I'm noticing a similar issue on my IP7+ with the GBC core. I'm playing Pokémon Crystal Version and the video stuttering is not as noticeable but there is very noticeable, and a little annoying :), pitch fluctuation with the audio.

**Comment by SeanLintern** [comment]
Also 7+ 10.2.1, running snes with FFII, is it worth trying a previous release ?

**Comment by SeanLintern** [comment]
I seem to have resolved this by running 1.3.2 release at it seems to be fine.

**Comment by kenthinson** [comment]
I'm having  the same issue. iPad Air 2. IOS 10.3

**Comment by Purduecoz** [comment]
Same issue. iPhone 7+ and iPad Pro both running iOS 10.3.2 and Provenance 1.3.2 (678) Github Revision 59b50b9.  Release mode, of course!

**Comment by sevdestruct** [comment]
Closing this unless anyone reports this against the new performance boosts in recent dev branch builds.
