### ISSUE TITLE
Renaming ROMs when searching first, grabs wrong ROM

### ISSUE THREAD

**Issue by gareauk** [jasarien/Provenance#533]
To replicate the issue that I'm seeing, do this....

Search for a rom using the search box at the top of the screen.
Once you've found your rom, hold down to rename it.
The wrong rom is selected and you can tell by the name that is displayed in the rename field.

I'm using an iPad Mini 4 with iOS 10.2.1.

**Comment by jasarien** [comment]
I'm unable to reproduce this issue with version 1.3.2 (659) bc6a42a

Are there any other details about your setup that might help in reproducing this? As far as I can see in the code, it chooses the correct ROM in both unfiltered and filtered mode.

Here's a video of my test: http://d.pr/v/xUqr let me know if there is a step I missed?

**Comment by gareauk** [comment]
Seems to be resolved in 1.3.2 (655).  I was using an older build at the time of this posting.
