### ISSUE TITLE
Choose Custom Artwork, Crashes Provenance

### ISSUE THREAD

**Issue by gareauk** [jasarien/Provenance#534]
To replicate the issue that I'm seeing, do this...

Hold a rom to rename it> Choose custom artwork> Take photo

Crashes provenance every single time.

I'm using an iPad Mini 4 with iOS 10.2.1.

**Comment by jabwd** [comment]
This is related due to the app not having "NSCameraUsageDescription" defined in its Info.plist

**Comment by jasarien** [comment]
Fixed in 0267ffb
