### ISSUE TITLE
USB controller support?

### ISSUE THREAD

**Issue by luserppc** [jasarien/Provenance#541]
#feature Request

For those os us w/o an iCade or Mfi controller, I'd love to see support for using Apple's Lightning Camera Kit (USB) as an option for USB controller support.  On a non-jailbroken iOS device, and side loading Provenance, I don't know of any reason this shouldn't be possible.  For example, one could use a USB Retro link controller, or what I'd really like to see, support for the Wii U pro controller.  (Which does(!) operate as a USB device if the battery is removed).  
If iOS does lock out developers from using the Lightning to USB dongle for button input, I haven't read any confirmation of that, but I suppose it's very possible.

**Comment by jasarien** [comment]
As far as I know, the USB adapter doesn't allow any arbitrary device to work with iOS. There's no driver support in iOS for generic USB controllers beyond the support for MFi controllers.
