### ISSUE TITLE
Question: How do I get Sega 32X roms to play?

### ISSUE THREAD

**Issue by gareauk** [jasarien/Provenance#544]
When I load up any 32X roms, the screen is black.  I can't find any wiki for Sega 32X roms.  
The roms currently reside in my com.provenance.genesis folder.  Is this correct?

iOS 10.2.1 on a iPad Mini 4.
Provenance v1.3.2 (655) Release 5b7e242

**Comment by jasarien** [comment]
It's likely that the ROMs you imported have a `.bin` file extension, which will cause the importer to think they're Genesis ROMs. Try changing the ROMs file extensions to `.32x` and reimport them.

**Comment by gareauk** [comment]
Actually it's the roms with the .32x extension that seem to be giving me the problem.

**Comment by JoeMatt** [comment]
You can try looking at the console logs to the specific issue but it would probably be quicker to find some other set of roms. Most likely the engine doesn't like them.

**Comment by gareauk** [comment]
So I tried to open a 32x file directly from Safari and what it did was create a new folder called com.provenance.32x.  These new roms seem to work ok now.  

A suggestion for your wiki, add in default folders that correspond with the roms (list names of folders and which roms and extensions go in each folder).  Or maybe these folders could be set automatically and just left empty if not needed.  

Anyways, this issue appears to be resolved when the new folder was created.
