### ISSUE TITLE
GBA Distorted Sound

### ISSUE THREAD

**Issue by marpet0805** [jasarien/Provenance#545]
Gameboy Advanced emulation runs perfect, 50-60fps. But the sound is messed up, it is distorted. I am on Iphone 4s, IOS 9.3.5

**Comment by jasarien** [comment]
How did you install Provenance? Downloaded from somewhere, sideloaded through Xcode or sideloaded the IPA from the releases page on this repo with Cydia Impactor?

If you compiled with Xcode, did you ensure to build with Release mode?

**Comment by marpet0805** [comment]
I installed it through the Cydia Impactor. I downloaded the 1.3.2 Provenance from the release page.

**Comment by SeanLintern** [comment]
I am experiencing this through iPhone 7+ built through Xcode release 1.3.2

**Comment by Drewsmits** [comment]
@jasarien FWIW, I experienced a distorted sound issue when building 1.3.2 from source using Debug, but it was solved when building with Release mode.

iPad Mini 2, iOS 10.3.2

**Comment by sevdestruct** [comment]
Using release when building did it for me, and there have been significant performance improvements recently on too thst, closing this unless it resurfaced against current dev branch builds, using the release Target to build instead of debug.
