### ISSUE TITLE
Can't connect to IP address link to download Roms

### ISSUE THREAD

**Issue by lumierephoto** [jasarien/Provenance#546]
I know it should "just work" as far as downloading roms from the IP Address that Provenance gives you, but it's not for me. 

I did pry a bit further and noticed that the IP address on my Apple TV is different that the IP address on my MacBook Pro.

Apple TV:    ***.***.0.7

MacBook Pro:  ***.***.0.3

Could this be the reason it's not connecting?

Otherwise, the connection times out. 

Not sure why this is happening. I don't have any other services or servers running.

**Comment by lolkthxbai** [comment]
Unless you've confused uploading with downloading it sounds a lot like you were under the expectation that the webserver is where you get roms. Am I wrong?

**Comment by jasarien** [comment]
The IP addresses are supposed to be different, they identify individual devices on a network (devices on the same network should have addresses that are mostly the same except for the last digits.)

Can you try rebooting your apple TV and seeing if the webserver still times out after that?

Also, is your apple TV connected via WiFi or Ethernet cable? Is it connected via both? If so, try only using one connection, either WiFi or cable.

**Comment by lumierephoto** [comment]
@lolkthxbai I meant uploading. I can't connect to the Provenance page on my Mac.

**Comment by lumierephoto** [comment]
@jasarien Yeah, that's what I read about IP addresses. 

I already tried rebooting the Apple TV. Didn't work. 

I found a workaround by installing on my iPad and then Airplaying to the Apple TV. Although I'd still like to get the app working on the TV.
