### ISSUE TITLE
MFi controller on 7800 games = no joypad/joystick/ABCD button control

### ISSUE THREAD

**Issue by ducky007** [jasarien/Provenance#547]
My MFi controller works fine on the 2600 games, but when using with 7800 games the joypad/joystick/ABCD buttons do not respond. The strange part is that the shoulder buttons still respond to reset/start the games.

**Comment by JoeMatt** [comment]
@ducky007 Has this been resolved for you after update?

**Comment by ducky007** [comment]
I did get it working. Thanks for all of your hard work with the project.
