### ISSUE TITLE
Cannot upload folders

### ISSUE THREAD

**Issue by QuarterSwede** [jasarien/Provenance#548]
In the Import function you cannot upload folders. Generally this is only needed for Battery saves and Save States but it makes it a royal pain when one has more than 10 roms (probably most users). I'd love to see this functionality added.

**Comment by jasarien** [comment]
You can select multiple files and drag them into the  import webpage and all files will be uploaded into the folder you drag them into.

**Comment by QuarterSwede** [comment]
The issue is that if you have 50 roms then you have to drag and drop for every folder. That's just plain sucks.

**Comment by jasarien** [comment]
You need a tool more sophisticated than a web browser that can do folder uploads (the web UI in Porvenance does not, and will not support this feature). 

You can do what you want to do with a tool like iMazing: http://d.pr/v/DfEp

**Comment by QuarterSwede** [comment]
Really!? That's fantastic. Thanks for the explanation and heads up.
