### ISSUE TITLE
Web UI: Filename containing spaces won't download with certain browser(s).

### ISSUE THREAD

**Issue by jacul** [jasarien/Provenance#549]
Background: I'm trying to download the existing roms in the device to my computer via the browser.
Bug can be replicated with Firefox. Not happening on Chrome.

For example, downloading a file named "Super Mario.nes" will only get you a file named "Super". 
This issue is very likely because of the GCDWebServer framework not encoding the spaces correctly.
However, by replacing both GCDWebServerFunctions.h and GCDWebServerFunctions.m files with the latest copy from the original framework's repository, this issue is gone. Seems like Provenance is not using the latest version of GCDWebServer.

**Comment by leolobato** [comment]
Even though we are not using the latest version, we had it updated to 3.3.3 back in June/2017 and this issue was fixed.

Just confirmed by trying to download `Mike Tyson's Punch-Out!! (Japan, USA).nes` using Firefox 54.0.1.

**Comment by sevdestruct** [comment]
somehow, i missed @leolobato's fix confirmation → closed.
