### ISSUE TITLE
Soft button when a gamepad is connected

### ISSUE THREAD

**Issue by tiberian83** [jasarien/Provenance#550]
Hi,

I use a SteelSeries Nimbus gamepad with the Nyko Smart clip. Unfortunately the physical menu button is hidden behind the Nyko smart clip. It would be great if you added the possibility to show the soft menu button on the iPhone display even if a gamepad is connected. The other soft buttons don't need to be on the display though.

**Comment by tiberian83** [comment]
Is it possible to add this feature to Provenance?

**Comment by jasarien** [comment]
It's possible, yes. Can't say when though.

**Comment by sevdestruct** [comment]
Gonna roll this into #718 and close.
