### ISSUE TITLE
Provenance cannot be opened again if a large Sega Genesis rom is imported. (Ex. Ultimate Mortal Kombat Trilogy)

### ISSUE THREAD

**Issue by Cinibonswirl26** [jasarien/Provenance#558]
UMKT causes the app to be unusable. Can't open unless deleted. Perhaps add support for larger genesis games?

**Comment by JoeMatt** [comment]
Haven't seen this issue, have played UMKT myself without issues. If it's not resolved please provide more details on version and device running on.
