### ISSUE TITLE
App becomes unable to open (crash on open)

### ISSUE THREAD

**Issue by SeanLintern** [jasarien/Provenance#560]
I am using iPhone 7+ release 1.3.2 build

After some use (days- weeks) the app becomes unable to open and crashes on launch, I think the first time it happened I could just re run from Xcode and it would just work again so I can't actually see the crash and probably wouldn't be able to symbolicate the log if I took it from the device?

**Comment by jasarien** [comment]
If you are using a free developer account, then provisioning profiles expire after 7 days. This is the most likely cause of the app failing to launch.
