### ISSUE TITLE
Save States not working with SuperMario RPG SNES

### ISSUE THREAD

**Issue by jonmcclay** [jasarien/Provenance#562]
Verified with 2 different working files for SuperMario RPG. I can save a state, but loading does nothing.

Verified this is not a problem with other iOS emulators.

**Comment by davidbdeath** [comment]
I had the same issue with mega man x2 just a minute ago.

**Comment by Canadadry** [comment]
And I hace the same issue with zelda and metroid

**Comment by jasarien** [comment]
Duplicate of #552
