### ISSUE TITLE
Error in PVsupport /Audio due to OSAtomicAdd32barrier

### ISSUE THREAD

**Issue by krikorola** [jasarien/Provenance#570]
Hello
I'm on Sierra and Apple TV is on 10.2
I'm getting a message that OSAtomicAdd32barrier is deprecated:

"/Users/krikor/Desktop/Provenance/PVSupport/PVSupport/Audio/TPCircularBuffer.h:95:5: 'OSAtomicAdd32Barrier' is deprecated: first deprecated in tvOS 10.0 - Use atomic_fetch_add() from <stdatomic.h> instead"

I also get an error message when the build is finishing and it fails installing the app saying: 

"This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique."

**Comment by Darkangel1154** [comment]
Hello krikorola,

I just encountered the OSAtomicAdd32Barrier is deprecated error as well.....
Provenance was running fine before I updated my ATV4 to 10.2
I'm not sure why this error just came up?

Previous Provenance working set-up;
ATV4 with 9.2

I am using a Paid Apple developer account. I have previously loaded & gotten Provenance to work.
I am using the current up to date version of Sierra. My Xcode is up to date.

Anyone have any ideas?

**Comment by jasarien** [comment]
This message is a warning, not an error and shouldn't prevent the build from succeeding.

The problem @krikorola is having is because of the Bundle ID, not because of the warning. You need to change the Bundle IDs for each target (in this case, the tvOS and TopShelf targets) to be something unique to you.
