### ISSUE TITLE
Nothing uploads to library

### ISSUE THREAD

**Issue by BrymanC** [jasarien/Provenance#571]
I've downloaded several .zip NES and SNES ROMs and fallowed the steps to import them via the built in Provenance server and although on the web browser side they show being successfully imported, when I stop the server and navigate to the Provenance library on my ATV4 the library persistently remains empty. Tried restarting the Provenance app and rebooting the Apple TV.

Provenance 1.3.2
ATV4/TvOS 10.2

<img width="1280" alt="screen shit 2017-04-22 at 5 52 40 pm" src="https://cloud.githubusercontent.com/assets/27905580/25309629/0be398d6-2787-11e7-8403-051c69b98cd7.png">

Also tried using a different browser and wanted to post another screenshot of something else I forgot to mention previously in case it's helpful. I noticed on both browsers that if after the initial upload I refresh the server connection via the button on the lower right above the ROMs directory/cue, the icons change from download icons(which should indicate they're uploaded) to folder icons  and the file size info disappears(which should indicate they're not uploaded). Also, a _MACOSX folder appears in the directory/cue.

<img width="1280" alt="screen shot 2017-04-22 at 8 05 06 pm" src="https://cloud.githubusercontent.com/assets/27905580/25310401/445b828a-2798-11e7-943a-524fef59b2de.png">

**Comment by jasarien** [comment]
It looks like those zip archives contain a folder which the ROM is in. Provenance requires that the ROM is at the top level of the zip. 

You can either re-zip the ROMs so they are at the top level or you can unzip them on your computer and upload the ROMs unzipped.
