### ISSUE TITLE
When I hit play while loading Provenance onto my Apple TV 4 I get this:

### ISSUE THREAD

**Issue by catch12234** [jasarien/Provenance#572]
Check dependencies

None of your accounts are a member of '63497P68S6':  An unexpected error occurred. Xcode cannot find a team matching '63497P68S6'.
No profiles for 'com.provenance-emu.provenancetv.topshelf' were found:  Xcode couldn't find a provisioning profile matching 'com.provenance-emu.provenancetv.topshelf'.
Code signing is required for product type 'TV App Extension' in SDK 'tvOS 10.2'

can anyone help with this? I followed the tutorial exactly and have no idea where this is coming from. I am signed into my apple ID as a developer account as well. Thanks!

**Comment by lolkthxbai** [comment]
you didn't change the bundle identifier for topshelf
