### ISSUE TITLE
Upon the second time opening Provenence, it crashes+ ROMs not showing

### ISSUE THREAD

**Issue by InsertNameHerr** [jasarien/Provenance#573]
The first time i opened the app, it worked fine, but on the second time, it didn't work. The first time i opened it, I already had ROM's downloaded, but they didn't show up.

**Comment by lolkthxbai** [comment]
has it been seven days or more from the first time you opened it?

**Comment by InsertNameHerr** [comment]
No it hasn't. In fact, it happened on the very day after I got it. 

    On Monday, May 22, 2017 7:55 PM, lolkthxbai <notifications@github.com> wrote:
 

 has it been seven days or more from the first time you opened it?—

**Comment by lolkthxbai** [comment]
was sure it was an expired profile
make sure you choose provenance-release and try building again

**Comment by jasarien** [comment]
Did you build and install yourself or download from a website somewhere?

**Comment by jasarien** [comment]
Haven’t heard anything on this issue since May 2017. Closing it for now. If the problem persists, reopen this issue.
