### ISSUE TITLE
App crashes immediately 

### ISSUE THREAD

**Issue by Zackmedic** [jasarien/Provenance#574]
I don't have a free account. I paid $10 on the BuildStore. I would redownload it, but my year is over. So, I can't access the BuildStore without paying again.

**Comment by jasarien** [comment]
The Buildstore is an independent service that Provenance is not affilated with. While the Buildstore hosts a version of Provenance, I don't have anything you do with it. 

The officially supported methods of installing Provenance are listed here: https://github.com/jasarien/Provenance/wiki
