### ISSUE TITLE
MSU-1 Audio Support?

### ISSUE THREAD

**Issue by Todtheguy** [jasarien/Provenance#577]
I was wondering if Provenance will eventually support MSU-1 Audio?

**Comment by jasarien** [comment]
Short answer: no. 

Long answer:

SNES9x (the SNES emulator used by Provenance) apparently does support the MSU-1 in its latest revisions, however it's not as simple as just upgrading SNES9x. 

I did a bit of reading and it seems like in order for enhanced audio to work requires a hacked ROM and separately downloaded high quality music tracks. There would need to be a lot of work done to support importing these tracks and managing them properly within provenance etc. 

It's not an impossible task, but it's not one I will be focused on. I would be happy to review a pull request if someone wants to implement support for it.
