### ISSUE TITLE
Semantic Issue in  cheat.cpp when trying to run in Xcode 9 beta 2

### ISSUE THREAD

**Issue by l80n63** [jasarien/Provenance#580]
<img width="1400" alt="screen shot 2017-06-25 at 11 50 53 am" src="https://user-images.githubusercontent.com/26565971/27513074-ad5ef7cc-599c-11e7-8dde-d85b5e157ff5.png">
No developer so do not know how to fix or where to begin to even fix the problem. Just know that this is an issue that will need to be fixed before Xcode 9 is more widely supported. Happy to try and fix things on behalf of others. I just want to run Provenance on my iOS 11 devices.

**Comment by Tomn94** [comment]
Instead of ` > 0`
write ` > (void *)0`
That's it 😉

**Comment by brianmcdoogle** [comment]
Wait, are cheats finally implemented in the current version or is this just behind the scenes stuff for if/when cheats ever get implemented?

**Comment by l80n63** [comment]
The changing of the code fixed it. Thanks for that Tomn94. I am unsure what the code does Brianmcdoogle, better answered by the developers of the app. I assume the same as you unless it is about loading in external codes.

**Comment by jasarien** [comment]
@Brianmcdoogle most of the emulators used in Provenance support cheats, but Provenance does not yet surface cheat support in its UI anywhere.
