### ISSUE TITLE
Unique Bundle Identifier

### ISSUE THREAD

**Issue by foster0121** [jasarien/Provenance#583]
Hello, I am new to all of this and in way over my head. I have gotten to the point where the build is successful but then i get this error, "This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique." I have tried only changing the bundle identifier for all three targets in many different ways and having all three the same. Still no luck with getting the app onto the appletv. Below are pictures of the target screens Thanks in advance
<img width="885" alt="screen shot 2017-07-08 at 4 36 10 pm" src="https://user-images.githubusercontent.com/30010784/27989943-a0a419c2-63fb-11e7-8ce5-b3be59748342.png">
<img width="882" alt="screen shot 2017-07-08 at 4 32 29 pm" src="https://user-images.githubusercontent.com/30010784/27989941-a09e36b0-63fb-11e7-9926-ffff7884a581.png">
<img width="879" alt="screen shot 2017-07-08 at 4 32 17 pm" src="https://user-images.githubusercontent.com/30010784/27989942-a09ed16a-63fb-11e7-86c5-d14a38686dc6.png">

**Comment by jasarien** [comment]
Each target needs it's own bundle ID, but the prefixes should match, eg:

com.kf.provenance
com.kf.provenancetv
com.kf. provenancetv.topshelf

I would suggest something more verbose than just 'kf' though, it's very likely someone already owns a bundle ID with the prefix 'com.kf'

**Comment by foster0121** [comment]
works for the tv target but I get this error now on the topshelf target. "Your maximum App ID limit has been reached. You may create up to 10 App IDs every 7 days." and No profiles for 'com.xxxxxxx.provenancetv.topshelf' were found
Xcode couldn't find a provisioning profile matching 'com.xxx.provenancetv.topshelf'.

**Comment by foster0121** [comment]
Thanks for responding so quickly. I very much want to sit on my couch for the remainder of the day and play old Nintendo games.

**Comment by foster0121** [comment]
After it is built and I hit play I received this. "Your maximum App ID limit has been reached. You may create up to 10 App IDs every 7 days.
No profiles for 'com.lagernd.provenancetv.topshelf' were found:  Xcode couldn't find a provisioning profile matching 'com.lagernd.provenancetv.topshelf'.
Code signing is required for product type 'TV App Extension' in SDK 'tvOS 10.2'" Thanks again.

**Comment by jasarien** [comment]
The error is self explanatory. Free dev accounts are limited in the amount of bundle IDs they can create per week, and in trying so many combos, you've hit the limit. Your options are: wait a week and try again, upgrade your free developer account to a paid account, or create a new free dev account with s different email and try again.
