### ISSUE TITLE
Improving Sonic and Tails in S3&K 

### ISSUE THREAD

**Issue by Neatstar** [jasarien/Provenance#588]
Sonic 3 and Knuckles was definitely one of my childhood favorites to play. And thanks to you @jasarien I was able to relive the games I love thanks to your provenence app. 

However one issue that seems to have stood out to me was not being able to use Tails to fly when I choose sonic and Tails. For some reason none of the buttons allows Tails to jump or fly in order to help sonic traverse the level. I was wondering if you are able to find the solution on the matter. If so you have my gratitude and I really appreciate it if you look into the problem

**Comment by Neatstar** [comment]
I'm also curious if it's possible to also resize the digital controller and buttons again

**Comment by jasarien** [comment]
As far as I remember, tails was only directly controllable when a second controller was connected to the console. You can connect two MFI controllers and assign each to a player in provenance controller settings to see if this helps

**Comment by Neatstar** [comment]
Oh. So it doesn't work for single player?

**Comment by jasarien** [comment]
Not as far as I remember. It was always the second player that controlled Tails.
