### ISSUE TITLE
xCode crashing on indexing of Provenance

### ISSUE THREAD

**Issue by jasnoyaeger** [jasarien/Provenance#592]
Need some help, I've tried a multitude of ways to get Xcode to not crash during the indexing of Provenance to no avail.

I've tried: Deleted derived data, deleting the xcuserdata folder for both the xcodeproj and xcworkspace packages as well as downgrading Xcode back to 8.3 from 8.3.3.

Can anyone help?

Here's the crash output:

```
Process:               Xcode [1692]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               8.3.3 (12175.1)
Build Info:            IDEFrameworks-12175001000000000~12
App Item ID:           497799835
App External ID:       822319371
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [1692]
User ID:               752501185

Date/Time:             2017-08-23 19:01:35.117 -0400
OS Version:            Mac OS X 10.13 (17A352a)
Report Version:        12
Anonymous UUID:        403A34B9-A40B-01ED-DA38-EC6C455B0537


Time Awake Since Boot: 3400 seconds

System Integrity Protection: enabled

Crashed Thread:        15  Dispatch queue: <IDEBuildOperation:0x7fbb899c25a0:REfc>-builder-queue (QOS: UNSPECIFIED)

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
ProductBuildVersion: 8E3004b
mcount overflow
```

**Comment by jasarien** [comment]
I shortened your crash report, as most of it doesn't mean much unless you have access to the source code of Xcode, which only someone within Apple will have.

I noticed that you're running on the new macOS 10.13 beta -- this could be an issue.

Have you tried Xcode 8.x on 10.12? 
Or alternatively, try Xcode 9 beta on macOS 10.13 beta?

I'm not seeing any crashes when using Xcode with the Provenance project, so I imagine it will be something to do with Xcode 8 + 10.13 beta. Report the issue to Apple at https://bugreport.apple.com

**Comment by jasnoyaeger** [comment]
Using a machine with 10.12 worked. I do know it worked up through 10.13 v6, possible something in 10.13 v7 that broke it. Beta version of Xcode didn’t work either. 

Hopefully Apple fixes it before GA. 

Thanks for your help.

**Comment by jasarien** [comment]
Make sure to report the bug or apple might not catch it

**Comment by jasnoyaeger** [comment]
Will do. 

Jason Yaeger

**Comment by devincentis** [comment]
I am having a similar issue.  Running xCode 9.0 beta 6 and the latest macOS High Sierra 10.13 Beta (17A352a).  Xcode crashes each time trying to open Provenance and any assistance would be appreciated.  I'll also report it.

**Comment by saagarjha** [comment]
Try updating to macOS High Sierra beta 8; this fixed the issue for me.

**Comment by devincentis** [comment]
Thanks!  It worked for me too!
