### ISSUE TITLE
Add frameskip for GBA?

### ISSUE THREAD

**Issue by nsuchy** [jasarien/Provenance#593]
Could you guys add in a toggle to enable frameskip for GBA games? Despite being an emulator that Xcode will compile without errors (great job on this, GBA4iOS was a nightmare to try and compile which is why I'm switching) the audio can sometimes get skippy. Thoughts?

**Comment by sevdestruct** [comment]
This is a duplicate of #545 and similar reports that I think have been taken care of with recent improvements so I'm closing this unless it gets reported against the current dev builds or the upcoming 1.5 release
