### ISSUE TITLE
"There are no devices registered in your account"

### ISSUE THREAD

**Issue by Batman3365** [jasarien/Provenance#596]
So i'm obviously getting "Build Failed". I have several issues.

1. Under Project -> Targets -> Provenance: Under "Signing" getting status errors 
 - "Failed to create provisioning profile.There are no devices registered in your account on the developer website. Plug in and select a device to have Xcode register it."
 - No profiles for 'com.rockets.provenance' were found Xcode couldn't find any iOS App Development provisioning profiles matching 'com.rockets.provenance'.

2. If you look at top bar in the middle where it says "Provenance: Ready" it shows 10 Yellow exclamation marks and 3 Red exclamation marks.

PLEASE HELP. I've spent about 5hours on this and i'm getting no where!!!

<img width="1018" alt="screen shot 2017-09-25 at 10 01 53 pm" src="https://user-images.githubusercontent.com/32286154/30840758-a45ebd2a-a23e-11e7-905f-1d226fd6c28e.png">
<img width="1020" alt="screen shot 2017-09-25 at 10 04 24 pm" src="https://user-images.githubusercontent.com/32286154/30840760-a47d7cce-a23e-11e7-9a25-9ea57b64218d.png">
<img width="1022" alt="screen shot 2017-09-25 at 10 05 25 pm" src="https://user-images.githubusercontent.com/32286154/30840759-a45f409c-a23e-11e7-971c-b7e11195e513.png">
<img width="1021" alt="screen shot 2017-09-25 at 10 06 54 pm" src="https://user-images.githubusercontent.com/32286154/30840757-a45d9cb0-a23e-11e7-86b5-dfbf613946d2.png">

**Comment by jasarien** [comment]
You can ignore the status errors in the Provenance target since that’s for iPhones, and apparently you’re trying to build for AppleTV. From your screenshots I can see that provisioning appears to be correctly setup for the ProvenanceTV target, which is what you want.

You have ProvenanceTV selected in the scheme selector and you have your AppleTV selected too. The BundleIDs for the ProvenanceTV target and the TopShelf target look fine.

Xcode is saying it is *Ready* in its status window, so have you actually tried to built to the AppleTV yet by pressing the Play button in Xcode? As far as I can tell it should successfully build to your AppleTV even if it continues to complain about the iOS target’s provisioning status.

If you’ve already tried to build & run by pressing the Play button, then look at the build log and see why the build failed and post here.

**Comment by Batman3365** [comment]
Thx for the prompt response!

So i have tried building it and i get a "Build Failed". I will post the fail logs here later today.

**Comment by thamilton91** [comment]
I'm having the same issue @Batman3365, did you ever resolve?

**Comment by suzumakes** [comment]
> "Failed to create provisioning profile.There are no devices registered in your account on the developer website. Plug in and select a device to have Xcode register it."

Make sure that your developer account is active, that you are building with a version of xCode that matches your current target device, and that your device is able to verify that your developer profile has been granted access to the device.

For an iPhone you'll need to go into Settings and Developer Apps to authorize Provenance, as well as registering and trusting your developer license, and finally it needs to be able to send the request to your developer account to verify that your account is valid and logged in.

There doesn't seem to be anything wrong with your xCode readout, I generally poke about with the red exclamations to see if I can amend any deprecated selectors to bring everything down to yellow warning signs before building.

**Comment by ArborGold** [comment]
I'm having the same issues listed above. Did anyone get a fix?

**Comment by Batman3365** [comment]
@thamilton91, @ArborGold

Note: anything you flash it with, Kodi or Provenance, it will stop working after 7days. You either will have to flash it every 7days or cough up $99 to Apple for a full developer account.

Now on to your question. Start with clean slate. Make sure you have edited the Builder Identifier name under under Target => under "Provenance, Provenancetv, and Tooshelf".

Signing Certificate should be your created acct user id excel for under Provenance it doesn't allow it so it will say "IOS Developer

When you are ready to hit play, make sure in top bar it say "ProvenanceTV-Release -> Apple TV.
Also male sure you are on "ProvenanceTV" under "Target then hit "Play" in top bar.

Let it run. You will probably get bunch of yellow errors but shouldn't see red errors if you followed my pics above. Don't try to fix the yellow errors. And you will get message I  top bar "Apple TV is ready or something like that. I don't have my laptop in front of me right now.

Good luck.

**Comment by jasarien** [comment]
Sounds like you need to do it manually then.

Follow these instructions from Apple: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingProfiles/MaintainingProfiles.html#//apple_ref/doc/uid/TP40012582-CH30-SW10

**Comment by thamilton91** [comment]
I have added the devices manually to my account and manually created a provision profile..

Same problem.

<img width="1028" alt="screen shot 2017-10-31 at 4 17 06 pm" src="https://user-images.githubusercontent.com/5624324/32246954-19366f9c-be57-11e7-8aa1-83fbf7bf21a8.png">
<img width="1025" alt="screen shot 2017-10-31 at 4 17 26 pm" src="https://user-images.githubusercontent.com/5624324/32246955-19433f24-be57-11e7-9b99-85d81b1f5d78.png">

**Comment by thamilton91** [comment]
If i create a new blank project I have no problem.

![image](https://user-images.githubusercontent.com/5624324/32247132-ba44dcf2-be57-11e7-87b9-a815c181417e.png)

**Comment by thamilton91** [comment]
I was able to get it working, Didn't realize I needed to manually create an iOS profile as well as a tvOS one.

Build is still failing though with one error.

![image](https://user-images.githubusercontent.com/5624324/32248021-b2e6429a-be5a-11e7-9fea-567b0c92bd03.png)

**Comment by Kumuda123** [comment]
<img width="1047" alt="screen shot 2018-07-17 at 9 51 48 pm" src="https://user-images.githubusercontent.com/35873647/42856646-b76d9106-8a0b-11e8-984f-4e682ecbb92c.png">
Hey I am getting this problem. Wats d fix for this ?

**Comment by Kumuda123** [comment]
<img width="538" alt="screen shot 2018-07-17 at 9 54 36 pm" src="https://user-images.githubusercontent.com/35873647/42856707-0a0a4968-8a0c-11e8-8cbf-26c19f94138a.png">
It is showing the device here. 

<img width="1094" alt="screen shot 2018-07-17 at 9 55 38 pm" src="https://user-images.githubusercontent.com/35873647/42856735-2ef26b16-8a0c-11e8-8199-40effb02d528.png">
However, if i try to run it. It fails and gives me this. 

Please help me on this !! Really stuck :(
