### ISSUE TITLE
ios11 - No roms showing. 

### ISSUE THREAD

**Issue by vinnytroia** [jasarien/Provenance#597]
I have completed importing a number of ROMS, but the page is blank. Like nothing is loaded. Using the search bar also yields no results. Is this an ios11 bug?

**Comment by jasarien** [comment]
Can you explain how you imported the ROMs, which ROMs (what were their file extensions, etc), which systems (Genesis, SNES, etc). Did you see the HUD display informing that the ROMs were being extracted and imported?

Have you tried the Refresh Game Library option in the settings?

**Comment by vinnytroia** [comment]
I've tried SNES and NES roms. 
For uploading, i used the web interface. 
I also tried uploading zip files and straight rom files. 
The web interface shows a list of all the imported files (zip, rom, smc, all of them). It's almost like the files have been uploaded by the process to actually import them has not started. Is there a way to manually kick that off? 

Also, yes, i tried to refresh.

**Comment by vinnytroia** [comment]
i figured it out. My fault. Had the roms folder wrong. Sorry.
