### ISSUE TITLE
Unable to load roms on iOS 11.1

### ISSUE THREAD

**Issue by sebastienb** [jasarien/Provenance#598]
When I try the IP address it can’t find server. I also tried dropping files from the app in iTunes but nothing shows up in the library

**Comment by beyondthetech** [comment]
It's working on my iPhone X with iOS 11.11.1. Are you seeing the webserver in your browser when it's active?

**Comment by jasarien** [comment]
I haven’t seen any issues with the web server myself. Ensure your phone and computer are on the same network (same IP subnets: eg, if your phone is displaying 192.168.0.xxx, then your computer’s IP should follow the same 192.168.0.xxx pattern. If your phone is on 192.168.1.xxx and your computer is on 192.168.0.xxx then they will not see each other).
