### ISSUE TITLE
tvOS 11 - Provenance Nimbus controls have analog sticks stuck holding a direction.

### ISSUE THREAD

**Issue by Numbski** [jasarien/Provenance#599]
In-game control is impossible - looks like the sticks are stuck bottomed out for some reason.

**Comment by werminghoff** [comment]
Any specific console? I'm playing Genesis and SNES ROMs on a daily basis with the SteelSeries Nimbus and they work just fine.

**Comment by QuarterSwede** [comment]
Make sure you aren’t pushing the sticks at all when you turn it on. It calibrates them where they are at that moment.

Aaron Soderholm

**Comment by ciscosurplus** [comment]
Is this the same for all sticks? I have the Mad Catz micro and I get the same issue in TvOS 11 (its stuck going down as soon as I open provenance). Even if I then return to the main home screen it moves down. Ive tried rebooting and not touching the stick at all as soon as I open and hit down on the analogue stick its pretty much always going down.

**Comment by leoderbois** [comment]
I get an issues like this and this was due to a low battery level + a long distance from the Apple TV. try to make a full charge of the Nimbus and play closer if the issues continue.

**Comment by jasarien** [comment]
I haven’t seen this issue at all while using multiple different MFi controllers with analogue sticks. I would assume the issue is not Provenance’s fault, and more likely to be something wrong with the controller, or a congfiguration/environmental issue specific to your circumstances.
