### ISSUE TITLE
Possible features added onto the game 

### ISSUE THREAD

**Issue by chileCC** [jasarien/Provenance#602]
Let me start off by saying how exciting it is to be able to play this on my IPhone. It really being my childhood in the palm of my hands when others have failed. Hands down. Thank you for the opportunity to be able to enjoy my youth again. 

With the goods of course comes possible options to optimize the program itself with basic input option for video, and audio. Are there any possibilities in the future for this?

Wether it's a global setting or individual for the emulators. Thanks in advance for your response.

**Comment by jasarien** [comment]
I’m not exactly sure what you’re asking. Could you elaborate?

**Comment by sevdestruct** [comment]
Without any reasonable details for what this is.. I'm going to have to close this for now.
