### ISSUE TITLE
FPS suddenly drop when use physical controller

### ISSUE THREAD

**Issue by CigarZh** [jasarien/Provenance#603]
Provenance 1.3.2
iPad 2017 iOS 10.3.3

When use the build-in virtual controller the game run well.
But when use my 8bitdo zero to play the game often has instantaneously FPS drop.
It happened every few seconds.

Should I change a better controller?

**Comment by pdefreitas** [comment]
Same issue in here.

**Comment by sevdestruct** [comment]
Please run this against the performance boosts current dev branch builds and report, will reopen if still experiencing.

**Comment by CigarZh** [comment]
Still have this question on release 1.4, and I can't do what you say because can't afford a Macbook.

**Comment by sevdestruct** [comment]
You could virtualize macOS to run Xcode. Don't need a Mac.
…or you can build a hackintosh. 

Otherwise you'll just have to wait for 1.5 release and test it again.
