### ISSUE TITLE
TopShelf Items retain original artwork, even despite custom artwork.

### ISSUE THREAD

**Issue by shinkei13** [jasarien/Provenance#605]
I've noticed that when enabling TopShelf functionality, recent games still show their original artwork. 

It seems to stem from line 21 of PVRecentGame+TopShelf.m: "item.imageURL = [NSURL URLWithString:self.game.originalArtworkURL];"

I tested swapping in "item.imageURL = [NSURL URLWithString:self.game.customArtworkURL];" and while it was able to compile and build, the TopShelf items instead load with a blank loading image; never resolving into either the custom artwork or it's original.

Does anyone more familiar with how Provenance assigns custom artwork have any insight to share?
![screen shot 2017-11-05 at 9 55 55 pm](https://user-images.githubusercontent.com/33383758/32423438-5fe515c6-c274-11e7-8d40-418f7d648e56.png)
![screen shot 2017-11-05 at 9 57 35 pm](https://user-images.githubusercontent.com/33383758/32423441-6204c3ce-c274-11e7-9a31-feab2ae60d42.png)
![screen shot 2017-11-05 at 9 56 09 pm](https://user-images.githubusercontent.com/33383758/32423448-64945fbe-c274-11e7-8159-df0362b40281.png)

**Comment by JoeMatt** [comment]
Pretty sureI I fixed this in the N64+Swift branch. Also added densions for a lot of systems that were missing. You can build and test on that branch or wait for next official release.
