### ISSUE TITLE
Steelseries Nimbus controller latency

### ISSUE THREAD

**Issue by jonathantneal** [jasarien/Provenance#607]
Hey there,

Similar to #481: [Steelseries Nimbus controller latency](https://github.com/jasarien/Provenance/issues/481), I am experiencing lag in the controller with the latest f47caf3 release.

**Provenance** version: 1.3.2
**Provenance** build: 685
**Steelseries Nimbus** firmware: 1.6.4.1

It seems more noticeable for NES than SNES.

**Comment by vitalizm** [comment]
I thought that I had the same issue. Enable “game mode” on your TV which disables post processing on the TV which causes lag on controllers.

**Comment by jonathantneal** [comment]
@vitalizm, you are amazing and I am sorry. I saw similar advice in previous threads, and I thought “but I’ve had my TV for years and it doesn’t even have a game mode”. Then I looked into it a bit more and I renamed the HDMI port to "PC", seriously, and the lag disappeared, because the post processing concept is totally true. I am so sorry for wasting anyone‘s time with this issue, and thank you for sharing your advice.

**Comment by vitalizm** [comment]
No worries! Glad you got it working :)

**Comment by uniquewizardz** [comment]
Hi,
we can not pair nimbus mifi on windows 10 x64 
is it posible to connect and play games on windows os ?

**Comment by jasarien** [comment]
@uniquewizardz this is an iOS app. The fact you can’t pair a nimbus on windows has nothing to do with this project.

**Comment by uniquewizardz** [comment]
Thank you mate,
İ will try to make emulator bridge like Xbox identifier.


Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

________________________________
Gönderen: James Addyman <notifications@github.com>
Gönderildi: Friday, June 7, 2019 11:47:18 PM
Kime: Provenance-Emu/Provenance
Bilgi: şaban cesur; Mention
Konu: Re: [Provenance-Emu/Provenance] Steelseries Nimbus controller latency (#607)


@uniquewizardz<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Funiquewizardz&data=02%7C01%7C%7Ca275ca42d9734849ce2108d6eb89558a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636955372401359318&sdata=e8yx3xlRdNte0sjGjhJDiG2ngYC7JoKsySBWg4N2bkw%3D&reserved=0> this is an iOS app. The fact you can’t pair a nimbus on windows has nothing to do with this project.
