### ISSUE TITLE
How about Game Store?

### ISSUE THREAD

**Issue by svanichkin** [jasarien/Provenance#616]
How about create Game Store for games with screenshots and descriptions? Fast and simple install games on device, and absolutely free... Or maybe simple create json file format file for loading by url, with list games?

**Comment by jasarien** [comment]
I totally, unequivocally want to avoid anything like that. The legal implications of displaying a list of downloadable copyrighted games within the app are huge and would be a sure fire way to get nuked by the copyright holders. 

We remember what happened to GBA4iOS for just linking to a Rom site, right? 

The only way it would be legally doable would be to only host Homebrew games within their respective licenses, and let’s be honest, homebrew games aren’t why people are using Provenance.

**Comment by Vanichkin** [comment]
Yes, everyone remembers this, but GBA4ios was in the Apple store. Provenance spreads exclusively through an illegal field?

**Comment by jasarien** [comment]
No it wasn’t in the App Store, at least not for very long. There was a brief period where it was hidden inside a baby names app, but was removed very soon after. The second version is available via test flight but will never make it into the actual App Store itself. 

Nintendo sent a cease and desist order to GitHub forcing GitHub to shutdown the repository of the project. You can still see it here: https://github.com/rileytestut/GBA4iOS

Provenance does not “spread through an illegal field”. It is an open source app that currently does not break any copyright laws as far as I know. It is not in the App Store for the same reason any other emulator isn’t — Apple doesn’t allow them. That doesn’t mean it’s illegal to install. Apple’s store rules and the law are two very separate things. 

Providing downloadable roms would be the beginning of illegal activity that would lead inevitably to the same fate as gba4ios.

**Comment by svanichkin** [comment]
Ok, but what about home use? Just add the URL field in the settings, to load a json file of a certain format. Json with list (name of game, pictures, text description, url for loading)
