### ISSUE TITLE
provenance-emu.com down???

### ISSUE THREAD

**Issue by Rob-Rychs** [jasarien/Provenance#617]
https://provenance-emu.com site seems to be down...
fails DNS lookup, is it a expired domain name?

![image](https://user-images.githubusercontent.com/16437897/33364214-4729c3fc-d498-11e7-94f3-113dadf000c3.png)

**Comment by jasarien** [comment]
I forgot to renew the domain. Thanks, I’ll get on it today.

**Comment by Rob-Rychs** [comment]
Thank you for making this 🙏

**Comment by jasarien** [comment]
I’ve renewed the domain. It’ll take a short while to propagate to the DNS servers.
