### ISSUE TITLE
Build Failed - Semantic Issue

### ISSUE THREAD

**Issue by djdulin27** [jasarien/Provenance#618]
I'm having an issue with my build failing and I am lost at how to fix it. I followed the directions and it looks like everything is going well but then I get the following error and the build fails:

PVNES tvOS
Semantic Issue

Ordered comparison between pointer and zero ('char *' and 'int')
cheat.cpp

When I click on the red exclamation point and go to cheat.cpp, I find this underlined in red on line 219

while(fgets(linebuf,2048,fp)>0)

Hopefully this is enough info for some resolution to my error.

Thanks!!

**Comment by jasarien** [comment]
This is fixed in 439486d9167c89c03f25c6d0acce3c22e8b944e3 . Please update your checkout and try building again.
