### ISSUE TITLE
NES Artworks

### ISSUE THREAD

**Issue by illando** [jasarien/Provenance#62]
Automatic NES artworks download is not working, or it's just not supported?

**Comment by jasarien** [comment]
It should be supported, but it depends entirely on the exact ROM you import. Provenance will look up the ROM's hash in the database to find release info for that game. If the ROM hash matches an entry in the DB and that entry has an artwork URL, it will attempt to download that artwork.

**Comment by illando** [comment]
Thanks James,
I'm trying with some from roms from original "No-Intro" set, that Open Emu is able to recognise applying the correct cover.
If you look at this image posted on iEmulators twitter you'll see they also have the same problem.
https://twitter.com/iEmulators/status/581525953454567424/photo/1

**Comment by jasarien** [comment]
I'll check open emu, see if the query they use has changed.

**Comment by jasarien** [comment]
Should be fixed in 5bf59491e3b5de0718692b460deb8c09446b9733
