### ISSUE TITLE
xcode 9 and apple tv 4k

### ISSUE THREAD

**Issue by darlanmendonca** [jasarien/Provenance#620]
When I open the `Provenance.xcworkspace` file, dont display in deployment info -> Devices the Apple TV, 

<img width="843" alt="screen shot 2017-12-05 at 6 32 16 pm" src="https://user-images.githubusercontent.com/876227/33629293-a48e6d16-d9ea-11e7-98a9-c1a64a229aa7.png">

and dont appear on Provenance-Release "Device"

<img width="441" alt="screen shot 2017-12-05 at 6 32 45 pm" src="https://user-images.githubusercontent.com/876227/33629313-b4de45d8-d9ea-11e7-8337-0d0624139333.png">

In apple tv 4k dont have usb cable, so is required pair using wireless. In my devices the Apple TV is connected, but dont display on device target, as previous image

Any help?

**Comment by jasarien** [comment]
You must select the ProvenanceTVRelease scheme from the scheme selector. It looks like you have one of the iOS schemes selected currently, although it's difficult to tell as it's truncated in your screenshot.

**Comment by darlanmendonca** [comment]
yes, but I already selected (I guess)

<img width="276" alt="screen shot 2017-12-05 at 6 39 20 pm" src="https://user-images.githubusercontent.com/876227/33629576-b1e00032-d9eb-11e7-8ba2-bc9ef381083c.png">

**Comment by jasarien** [comment]
No, that's Provenance-Release, for iOS (which is why only iOS devices and simulators are displaying in the device selector).

You must select the **ProvenanceTV-Release** scheme.

**Comment by darlanmendonca** [comment]
:( my bad

<img width="277" alt="screen shot 2017-12-05 at 6 43 56 pm" src="https://user-images.githubusercontent.com/876227/33629736-446d7de4-d9ec-11e7-84f3-1100df568788.png">


now is right, thank you!!!
