### ISSUE TITLE
Playstation documentation mismatch Mednafen documentation

### ISSUE THREAD

**Issue by Canadadry** [jasarien/Provenance#626]
[In your wiki](https://github.com/jasarien/Provenance/wiki/Playstation-Instructions), you gave the md5's list of bios file needed. 

But I couldn't find the scph5501.bin one. So I start digging a little bit and a found that your documentation differs from the one of [Mednafen](https://mednafen.github.io/documentation/psx.html). Which is supposed to your backend. 

Is this normal ?

**Comment by jasarien** [comment]
I calculated the MD5 hashes from the files I have locally (which I have tested and work in Provenance as far as I can see).

```
PSXBios $ md5 scph5500.bin 
MD5 (scph5500.bin) = 8dd7d5296a650fac7319bce665a6a53c
PSXBios $ md5 scph5501.bin 
MD5 (scph5501.bin) = 1e68c231d0896b7eadcad1d7d8e76129
PSXBios $ md5 scph5502.bin 
MD5 (scph5502.bin) = e56ec1b027e2fe8a49217d9678f7f6bb
PSXBios $ md5 "PSX - SCPH7003.BIN"
MD5 (PSX - SCPH7003.BIN) = 490f666e1afb15b7362b406ed1cea246
```

I Noticed that the 7003 BIOS's hash matches the one listed for the 5501 on the Mednafen docs, no maybe try that one?

It's possible that the ones I have don't match the ones listed in the Mednafen docs, but they work for me.

**Comment by Cepheidsong** [comment]
It's been a long problem in some bios not available anywhere, so what people have been doing is making a 2nd copy of matching hashes, like 7003, and renaming the file name to the 5501- and it works!  It's what I did as well.

**Comment by sevdestruct** [comment]
Closing, unless this is still an issue. Bios reqs are also a visible feature in new UI for 2.0 in #714 which will allow for less need of documentation.
