### ISSUE TITLE
Playstation Games Not Playing Correctly

### ISSUE THREAD

**Issue by thekennygreene** [jasarien/Provenance#633]
Whenever I open a Playstation game from the app being forced closed, it plays fine. But as soon as I go back to the Main menu and select a different Playstation game, its starts to stutter and lag. I did find a temporary solution: if I force close the app every time before I pick a new Playstation game, it works correctly. The stutter also happens if I play a game on a different emulator, then try to go and play a Playstation game. Also found that if I try and use the CRT Filter with Playstation games, it does the same thing, regardless if forced closed or not. 

Also wish there was a way of enabling or disabling the CRT Filter just on selected Systems. I love it with SNES, but it doesn't work with Playstation. Constantly having to switch in on and off.

**Comment by jasarien** [comment]
The PSX emulation speed is a known issue. The current work around is to set the game speed to normal from the menu after starting the game.

The CRT filter will not work with PSX games on certain hardware. The combination of PSX emulation and the filter is too much. It is not recommended to play PSX with the CRT filter enabled. 

Please raise a separate issue as a feature request for the CRT filter per system, as it is not related to the original problem in this issue.

**Comment by frntz** [comment]
Hello @jasarien, it's impossible to play PSX games and the work around you mentioned doesn't work with Provenance 1.4 on iOS 11.2.5 (both tested on iPad Pro 9,7" and iPhone 6). Is there any other workaround I missed ? Thanks 🙇‍♂️

**Comment by jasarien** [comment]
Update your build to a one built with the latest source from master. There have been several performance improvements to the rendering which should include PSX.

**Comment by frntz** [comment]
Updated from commit bbbafbcd9f2093d649dcd8ff5f96a68ef3cf281a but issue is still the same (Tested on iPhone 6 iOS 11.2.5) with Metal Slug X. Trick mentioned above doesn't work neither.

**Comment by jasarien** [comment]
Are you sure you’ve built with release mode and not debug? Also try testing with a build from the develop branch. Lots of good rendering stuff in there.

**Comment by frntz** [comment]
Thank you so much @jasarien it works !

**Comment by JoeMatt** [comment]
Wow, yeah on an iPhone 6 too, I wasn't even sure Release mode would work. Good to know.

**Comment by blegacy** [comment]
everytime i play crash bandicoot warp on the emulator. the character moves on its own. any fix to this? im on ios 13.2, and provenance 1.5 beta.

**Comment by sevdestruct** [comment]
@blegacy this ticket is closed for over two years and that bug is unrelated to the original ticket and was fixed in 1.5b a while back. locking from here on.
