### ISSUE TITLE
'PVPokeMini/PVPokeMini.h' file not found

### ISSUE THREAD

**Issue by teruchi** [jasarien/Provenance#640]
After checking out the latest version.
https://github.com/jasarien/Provenance/tree/ddfeefd56decd8cd4b82665f9ee471947f7db51f

I get an error in PVPokeMiniControllerViewController.m file.

**'PVPokeMini/PVPokeMini.h' file not found**

A file exists in the workspace.

Xcode 9.2 (9C40b)
macOS High Sierra 10.13.2

**Comment by jasarien** [comment]
- did you open the workspace instead of the project?
- do you have the correct target selected?
- does your Mac use a case sensitive file system?

**Comment by teruchi** [comment]
Thank you for answering

I opened the workspace.

Sorry, I did not select a target.
When I selected "Provenance> iPhone 6s", the build succeeded.

It is not a case-sensitive file system.

**Comment by jasarien** [comment]
Cool, enjoy
