### ISSUE TITLE
conflicts bug

### ISSUE THREAD

**Issue by ChunkyMunky1010** [jasarien/Provenance#643]
Just tried to get sonic cd and it took me to the problems page and then the pick system was just greyed out and not allowing me to manually pick the system

**Comment by sevdestruct** [comment]
@ChunkyMunky1010  good chance this is the same issue as #637 which. I've submitted something that might help but isn't in the main master branch yet - pull request details it-> #641

**Comment by ChunkyMunky1010** [comment]
@sevdestructI have the cue/bin files under zip in the rom folder but whenever i complete the download into the roms folder it just goes to the Genesis folder

**Comment by sevdestruct** [comment]
You could just manually dump them directly into the `com.provenance.psx` folder until this is resolved.

**Comment by ChunkyMunky1010** [comment]
@sevdestruct that's what I thought, thanks for the help

**Comment by JoeMatt** [comment]
I wonder if we should consider this more of a bug that .bin's should end up in the conflict dir. 
They currently don't since it assumes a .bin without a .cue is for Sega since I think that's the only non CD system that uses .bin. (I think some atari rom sites use .bin but they should be using .a78, .a26 etc but that's on the sharer being non-standard.)

**Comment by jasarien** [comment]
Sounds sensible to me. There’s still the issue that the conflict alert isn’t currently displaying when ROMs end up there.

**Comment by sevdestruct** [comment]
This is for those finding this issue searching against .bin or multi-file or multi-disc issues --
[Importing ROMs](mazon.com/hz/wishlist/ls/1DRLFNN0IDCIX?&sort=default) wiki has been overhauled - please refer to this as you troubleshoot

**Comment by sevdestruct** [comment]
this is not fixed, and has resurfaced, but not reopening in favor of more extensive testing done around importing in #761 - just dropping into to cross link this since it was in the Ready for QA list in Bugfix project, and now remove from that board…
