### ISSUE TITLE
PSX buttons

### ISSUE THREAD

**Issue by saljumerah** [jasarien/Provenance#644]
Hi,

first of all: Thanks a lot for this beautiful emulator and for adding PSX support!

I got it working fine on my 6S Plus. However, when playing PSX games, I can only see R1 and L1 buttons (onscreen) but not R2 and L2. Might be I've been overseeing something, but I can't seem to find those two buttons.

Thanks for any help you can provide.

**Comment by jasarien** [comment]
The on screen controls currently don’t have R2 and L2. If you use an MFi game pad, then R2 and L2 are mapped to the triggers.

**Comment by saljumerah** [comment]
Great thanks! Would be nice to get this feature in the future though! Thanks again!

**Comment by JoeMatt** [comment]
It would be nice to have them, the layout code for onscreen controls doesn't support more than 2 shoulder buttons.
That being said, early PSX controllers didn't have L/R2 so not all games use or require it, and in my humble opinion I can't think of a good user experience cluttering the screen with that many buttons. As jasarien said, just use a gamepad. Maybe we'll add more and/or custom on screen controls but it's super low priority for the few of us spending time on the project, unless someone comes along with a patch of course :-)

**Comment by jasarien** [comment]
I’m pretty sure every PSX controller has L2 and R2 — it’s the L3/R3 analog clickers that were added later.

**Comment by JoeMatt** [comment]
Ah yes you're right, the original PSX controller didn't have the joystick and was called Playstation Controller but did have L/R2 shoulder buttons. Then came the Dual Analog prototype then Dual Shock, Dual Shock added the joysticks.

**Comment by XeresRazor** [comment]
Dual Analog and the later Dual Shock both added a pair of analog thumb sticks. Dual Shock (as the name implies) added a pair of force feedback motors to the original analog controller. It also became the default, pack in controller upon its release, and is mandatory for most later PS1 titles.

**Comment by pixiong** [comment]
Could support iCade controller ?

**Comment by saljumerah** [comment]
At least know, that it would be greatly appreciated to have the controls on screen by a few (or at least me). I don’t mind having a crowded screen, especially if it‘s possible to adjust opacity, as it is already. :)

**Comment by whatsvital** [comment]
The easiest alternative I can think of are either mapping a combination Start+L1/R1 for the respective buttons or doing a menu toggle for current L1/R1 to L2/R2 buttons as temporary fix.

**Comment by thearcielloyola** [comment]
Hello i have a problem with provenance for ios 11 it works and its very good (good job for that) but the thing is i bought a bluetooth controller for provenance the directional buttons work but the action buttons (square x triangle circle) as well as the shoulder and trigger buttons dont work i tried every brand of controller the store im buying to but each has the same outcome is there a way to map the controls manually or there a specific controller to use for provenance ? Thanks in advance and God Bless

**Comment by BaffleBlend** [comment]
I have to agree, I'd like L2/R2 buttons to be added in the future. I'd much rather take a cluttered screen over a game that's unplayable because actions mapped to L2/R2 are needed to progress.

**Comment by XeresRazor** [comment]
I’ve been wondering if we could map R2 and L2, and then handle start/select and R3/L3 by pressing the menu and a shoulder button at the same time. Seems like the simplest way to map all of the PlayStation controls.

**Comment by JoeMatt** [comment]
Overriding the menu button functionality would be tricky, especially on AppleTV since it's used for all back navigation. It would be too easy to accidentally back out of the game if it's even possible to override at all on ATV, I'd have to read more on that case, but either way seems like not the right option.

**Comment by XxXStefannXxX** [comment]
Please add R2 L2 buttons, they are of great importance in a lot of games, for aiming, looking around you and such things. It would be great if you would consider making an update with all buttons, and mushroom controler besides the usual one for PS One (put it in Settings so people can chose which one to use). It would be a lot easier to move around and would increase precision in movement. Thank you in advance.

**Comment by XxXStefannXxX** [comment]
Just seperate them a bit just like on a controller.

**Comment by ciscosurplus** [comment]
Quick (stupid) question, on Apple TV using MFI controller (Mad Catz) how do you press the start button, Ive tried P1 Start in the menu but that does nothing?

**Comment by jasarien** [comment]
the P1 start in the menu should do it... Are you sure your MFi controller is set to Player 1 and not 2? (Sometimes the AppleTV makes the Siri Remote Player 1) -- You can change it in the Controller Selection settings.

**Comment by ciscosurplus** [comment]
Yes Def set to player 1, could be a bug in the Feature/n64+swift in that case? 

Tried it on 3 games to be sure.

**Comment by jasarien** [comment]
It's definitely working for me on the n64+swift branch with a Nimbus controller on an iPhone X, iOS 11.2.5.

**Comment by jasarien** [comment]
As for the L2/R2 buttons that this issue is originally about, I've tested them and they work fine as implemented in the Feature/N64+swift branch, so I'm going to close this issue.
