### ISSUE TITLE
Game Boy Color games crashing on startup

### ISSUE THREAD

**Issue by pheraph** [jasarien/Provenance#65]
Checked out and built the latest version _and_ installed iOS 8.3 beta (so can't say exactly who is responsible). Since then all GBC games I tried are crashing on startup. Do they still work for you (with a stable iOS version)?

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil' [...] libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by jasarien** [comment]
Yeah, I'm aware of this. 

I split the GB and GBC systems in the confit file and forgot to add a clause for the GBC controller view. 

There's a fix for it committed in the import-rewrite branch but that branch isn't stable right now. I'll merge the fix in later tonight.

**Comment by jasarien** [comment]
You sure you've checked out the latest head from master? I just went to merge the fix for this and noticed I already did it 7 days ago in this commit: c39ea666b987ba3d0dd4766683ab93e90a3641c2

**Comment by pheraph** [comment]
You're right. The fix works, thanks!
