### ISSUE TITLE
Feature Request: Dark Mode for iOS

### ISSUE THREAD

**Issue by sevdestruct** [jasarien/Provenance#652]
TODO:

- [x] iCade tableview
- [x] Adjust red in UIAlerts to less dramatic
- [x] Conflicts table view
- [x] Appearance settings table view
- [x] licenses page
- [x] Long press action sheet text / pause menu action sheet, aka action sheets with multiple actions
- [x] Delete confirmation - both showing red for some reason.

--------
Checked the past Issues… Saw that tvOS has support for Dark Mode as of PR #447, via support for tvOS traits (need to enable that on my AppleTV now that I know about it…), but iOS could use the same. 

Started a project ([Provenance: Dark Mode](https://github.com/sevdestruct/Provenance/projects/1)) for this on my fork, via a [dark-mode](https://github.com/sevdestruct/Provenance/tree/dark-mode) branch, but it's too early for a commit to the jasarien master branch: 

![screen shot 2018-01-14 at 11 37 29 pm](https://user-images.githubusercontent.com/3118097/34931501-03361202-f984-11e7-9535-d24ff7d606ad.png)

Breaking this into two parts:
1. **Smart Invert Support** (what i call the poor man's dark mode) -- already got a initial start to this with an ignore Smart Invert for covert art, and emulator view so far…
2. …and potentially a **proper Dark Mode** [theme] setting, that will restyle everything

Might need support from other GitHub vampires if anyone else is wanting to help out on this…

**Comment by sevdestruct** [comment]
_Poor-Man's Dark Mode:_ Smart Invert ignore already in affect for cover art:

![screen_shot_2018-01-14_at_11_45_58_pm](https://user-images.githubusercontent.com/3118097/34931773-3a5f0c56-f985-11e7-9d06-0d826f980f35.png)

*took photos becauyse you can't screenshot iOS's Smart Invert mode as it just creates screens of how it looks as if it weren't in affect…

**Comment by sevdestruct** [comment]
**Update:** With basic support for Smart Invert in the branch, I've moved on to work on the next bit, the proper Dark Mode, and I've got a decent prototype working so far.

**I'd say… Dark Mode is roughly _75%_ Complete?:**

![screen shot 2018-01-16 at 8 18 42 pm](https://user-images.githubusercontent.com/3118097/35025732-08ea7d4a-fafc-11e7-86a5-cc0a670c6ac1.png)
![screen shot 2018-01-16 at 8 18 57 pm](https://user-images.githubusercontent.com/3118097/35025736-108f8568-fafc-11e7-8d18-f10305c0b107.png)
![screen shot 2018-01-16 at 8 19 23 pm](https://user-images.githubusercontent.com/3118097/35025738-1271d106-fafc-11e7-898f-c59fbf236f5e.png)
![screen shot 2018-01-16 at 8 19 43 pm](https://user-images.githubusercontent.com/3118097/35025739-14afc702-fafc-11e7-8f3d-849ea360ce32.png)

* Heads up, the screens above show my latest dark mode branch merged with the other aesthetic/cosmetic updates and style revisions I previously proposed and submitted via _game-library_, _iPhone-X_, and _settings-updates_ branches on my fork (PRs currently pending review/approval/merge with @jasarien master here), but the base dark mode prototype branches are based on the current master..

----

STATUS:

**Done**:
- Dark Mode Toggle (in Settings> Appearance) with persistance
- Game Library View
- Settings View
- Navigation Bar + Buttons

**Almost Done**:
- Settings: Appearance

**Not Done**:
- Settings: Controllers View
- Navigation Bar Titles
- Alerts/Action Sheet Views
- Live Update on Settings: Appearance View when Dark Mode toggles (will change currently but only when you return to it).
- and various other details…

This still isn't ready for a Pull Request, yet, but thought I'd share my progress…

**Comment by JoeMatt** [comment]
I would suggest making the text in table view cells a little lighter. There's no diff so not sure how you're changing the theme but I hope it's UIAppearance class.

`
[[UILabel appearanceWhenContainedInInstancesOfClasses:@[[UITableViewCell class]]]  
                                        setBackgroundColor:[UIColor lightGreyColor]];  
`

I think this should work. You can make a class that has methods like, +(void)setDarkMode, +(void)setLightMode, that sets all the colors. You could make all sorts of themes this way really.

**Comment by sevdestruct** [comment]
@JoeMatt, at the moment the one the prototype branch I have that is furthest along is utilizing a framework called DKNightVersion, but I may continue in my original dark-mode branch to see about not adding an external framework for this.DKNightVersion had some very useful methods built in.

I haven't had a chance to continue my work on this since the recent update to the thread with screenshots and status, but I hope to continue on it soon, especially motivated now seeings as my first pull requests were merged into the master now 😄

**Comment by gh0sti** [comment]
how close is this to being a PR, this looks awesome to have especially for the iPhone X a pure dark mode for Provenance.

**Comment by sevdestruct** [comment]
@gh0sti, I posted a pretty thorough status update above already… When i find time again I am going to continue, but as stated I might double back and pursue an option that doesn't rely on adding an external framework, which will set me back a bit. 

I could strip out the Phase 1 bit as a PR if preferred, which was simply to support Smart Invert setting (that Apple implemented in iOS 11) by flagging the cover art and emulator view not to invert. That is already done. You could use that as a kind of _poor-man's dark mode_ in the meanwhile, depending on how soon it is reviewed, accepted and jsarien commits it. It isn't perfect but was fairly simple to do. 

You're also welcome to clone a branch from me in its current working state (it's stable, just unfinished), should be basically current with jsarien master at the moment.

**Comment by gh0sti** [comment]
I would go with the poor mans way for now unless apple actually adds dark mode for iOS 12 might be easier to tie into the smart invert for now. I bet they will tie into that API since most app developers are already adding that into their apps like Facebook and such.

**Comment by jasarien** [comment]
@gh0sti I disagree. I don’t think Apple will introduce to iOS a system wide dark theme like on tvOS or provide a specific API for implementing dark mode specifically. A number of versions ago (iOS 6, maybe?) they introduced the UIAppearence APIs which were intended for theming apps. I believe this is Apple’s solution and it’s down to developers to write a theme using UIAppearence to support a ‘dark mode’.  I guess tvOS got special attention as it was new and easy to add a system wide dark theme as there were basically no apps.

**Comment by JoeMatt** [comment]
iPhone's also have the ability to lighten/darken the screen and have night shift. I suspect 'dark mode' was added to Apple TV since it's not as easy to control their brightness in dark lighting. jasarien is correct, the proper way to do this is UIAppearence as I already mentioned. Really shouldn't be that hard, there aren't a lot of UI elements in the app.

**Comment by JoeMatt** [comment]
@sevdestruct I added the start of a Swift UIAppearance theming engine on a new branch,
https://github.com/jasarien/Provenance/tree/feature/SwiftThemes

It's just a start, but you can see how it works for now.

**Comment by sevdestruct** [comment]
Thanks @JoeMatt. That's going to help when we lock on new UI and move into second part of that effort.

For everyone else, as Update to this Issue: dark mode is being rolled into the new UI redesign project as default theme so far (light may become the optional, so I may not continue this branch as it were, and also Joe has the new Swift framework for what we'll use moving forward started which I intent to build on once designs are further along. More to come on that later.

**Comment by JoeMatt** [comment]
All done

**Comment by sevdestruct** [comment]
This is the one thing that didn't get reimplemented that my branch had:

- [ ] **Update:** Smart Invert Support (Ignore Smart Invert: cover art, emulator view)

**Comment by jasarien** [comment]
Why bother with smart invert if we have an actual dark theme?

**Comment by sevdestruct** [comment]
Because it still inverts are art stupidly if someon eis using that to make other apps dark. And I knew how to do it, so it's done.

**Comment by sevdestruct** [comment]
…or, @jasarien  said another way…

## because this is Bad:
![smartinvertlogic-bad](https://user-images.githubusercontent.com/3118097/37391099-72c5229a-2727-11e8-8c6d-964948e4bc38.png)

## …and this is Better:
(already committed and pushed to UIRedesign branch)
![smartinvertlogic-better](https://user-images.githubusercontent.com/3118097/37391103-7558ec62-2727-11e8-916d-0a206d004f74.png)


## …and this is probably Best:
(deny Smart Invert on the whole app/theme if we want):
![smartinvertlogic-best](https://user-images.githubusercontent.com/3118097/37391117-7c577222-2727-11e8-8f0b-03574d0a3081.png)
