### ISSUE TITLE
Request: Switch from Legacy Volume View to new iOS 11 Volume View (present in iOS 11 video player)

### ISSUE THREAD

**Issue by sevdestruct** [jasarien/Provenance#653]
Do you think we could implement this? I'm looking into how in the meanwhile, but wouldn't it be nice to use the new volume view (upper right) seen in the iOS 11 video player instead of the legacy view (still in affect outside of video player) that obstructs large portion of center of screen, wouldn't you agree?

![image](https://user-images.githubusercontent.com/3118097/34934033-d5a56324-f98d-11e7-9d55-17a30d50ff17.png)

So much less obnoxious. Thanks, iOS 11… now how do I hook that in…

**Comment by JoeMatt** [comment]
Doesn't look too difficult. Some FOSS samples,
https://github.com/gizmosachin/VolumeBar
https://github.com/andreamazz/SubtleVolume

**Comment by gh0sti** [comment]
this needs to be a PR would love to see this as a feature

**Comment by JoeMatt** [comment]
You need code written before you have a PR.
Anyone can gladly take this up, not really on my priority list nor a rather good use of my time , though the links I posted suggested it's a rather simple feature to add to anyone with limited iOS coding experience.

**Comment by sevdestruct** [comment]
I think most of the more active contributors/collaborators like @JoeMatt and @braindx (and of course, @jasarien) are focused on much larger fish like performance optimizations, and new core integrations, etc…

Speaking of that… @jasarien and friends, do you have plans for sorting issues into GitHub milestones? Would love to see where the core collaborators are aiming the major releases, and where the priorities lie. I read here that there is a Slack team for Provenance as well, is it in active use? Do you think I could I get an invite if it isn't much trouble? (been meaning to ask but not sure really where to inquire).

Anyhow, @gh0sti , as the one who requested it, and more focused on UI/UX enhancements myself… I might get around to this, but with limited time my priority is currently on a Dark Mode [theme] (also my own request) at the moment before I chisel off anything else. That said, @JoeMatt's leads are where I would start…by all means, if you want to take a crack at it, I think the fellows would appreciate the additional contributing resources and it's a great way to learn.

**Comment by JoeMatt** [comment]
I added this to the branch [N64+Swift](https://github.com/jasarien/Provenance/tree/feature/N64+Swift)

**Comment by sevdestruct** [comment]
Serious? Damn. Thanks, Joe! I have been looking at the YouTube volume
overlay recently it's quite minimal more than the new apple video player
one if we want it more bespoke as well. But whichever way you've got it has
to better than jammed in front of the emulator. Thanks again.
