### ISSUE TITLE
Gamsir Game Controller Support

### ISSUE THREAD

**Issue by 12e1121** [jasarien/Provenance#654]
Hi Jasarien, 

First of all thank you for developing such a great platform that allow me to play PS games in my iphone 8 plus ios 12.2.2.

I wonder is that any update on #474 ? I have my GameSir G4s controller, and it doesn't seem to be working with it.

Phone: Iphone 8 Plus
IOS Version: IOS 12.2.2
Provenance Version: 1.4 (817)

**Comment by jasarien** [comment]
According to their website, Gamesir controllers don’t officially support iOS:

https://gamesir.hk/apps/help-center#!do-gamesir-gamepads-support-iphone-ios

**Comment by 12e1121** [comment]
I will need to wait then. Thank Jasarien.
