### ISSUE TITLE
PSX games loading to Playstation Audio CD Player.....

### ISSUE THREAD

**Issue by AJDJ39** [jasarien/Provenance#662]
Some of the PSX ROMS I've imported seem to work perfectly but many others just load as if the "playstation" thinks I inserted an Audio CD...   Anyone know if there's a setting or something I can tweak to fix this?

Thanks!

**Comment by jasarien** [comment]
Can you list which ROMs you’re experiencing this with? And are you sure the ROMs imported correctly?

**Comment by AJDJ39** [comment]
Actually never mind!  I got some rims from another website and now they all seem to work properly!!
