### ISSUE TITLE
PsOne ROMs Crashes when i open it in my iphone

### ISSUE THREAD

**Issue by Black959595** [jasarien/Provenance#663]
My phone is iphone7plus ios 11.2.1 and this video shows the proplem i have .. can you help me please? 
This is the VIDEO : https://streamable.com/87hrm

This thing happens to me when i open SILENT HILL,PEPSI MAN , TEKKEN3 and many other games

**Comment by jasarien** [comment]
The ROMs haven’t imported correctly. Please follow the instructions here https://github.com/jasarien/Provenance/wiki/Playstation-Instructions

**Comment by Black959595** [comment]
How can i find the cue file for the game? Some files contains only bin
