### ISSUE TITLE
How to vertify the app?

### ISSUE THREAD

**Issue by Black959595** [jasarien/Provenance#666]
This screen appears when i try to open the app .. I tried to trust it in settings but it doesn’t work 
This is a screen shot https://ibb.co/dwjFyb

**Comment by jasarien** [comment]
Looks like you’ve installed the app from an unofficial source that is using some Chinese signing certificate.

My official recommendation would be not to do this as you have no idea whether or the not the app has been modified to be malicious...

However, if you don’t want to install the prebuilt binaries available in this repo for whatever reason you can Google how to trust profiles in iOS.

**Comment by Black959595** [comment]
How can I download it from the official source?

**Comment by jasarien** [comment]
https://github.com/jasarien/Provenance/wiki/Installing-using-the-prebuilt-IPAs
