### ISSUE TITLE
Cutting in the sound

### ISSUE THREAD

**Issue by Black959595** [jasarien/Provenance#668]
I tried to switch the game speed to “normal” but still there is a cutting in the sound

**Comment by Black959595** [comment]
Can you please help me

**Comment by sevdestruct** [comment]
Check if you are running the release or the debug build. In settings view swipe to the bottom and look for MODE. If it says DEBUG, rebuild it using the Provenance-Release target.

**Comment by Black959595** [comment]
MODE says RELEASE

**Comment by Black959595** [comment]
Iphone 7 plus ios 11

**Comment by Black959595** [comment]
No Help :( ?

**Comment by Black959595** [comment]
I am trying to emulate PSX Roms

**Comment by JoeMatt** [comment]
PSX runs fine on my iPhone 7, but the plus has a bigger screen so it actually puts more stress on the GPU in general and the non plus benchmarks slightly better ~5-10% in the charts. Not sure if that's a factor here.

You can try this PR which has some improvements to the rendering engine,
https://github.com/jasarien/Provenance/pull/667

Beyond that there's not much anyone can do. We don't develop the cores, I wouldn't expect any amazing speed improvements out of this project. Beyond the tweaks made in #667

**Comment by Black959595** [comment]
I don’t understand.. what should i do now?

**Comment by Black959595** [comment]
I am having this problem in my both devices iphone5s and iphone 7plus

**Comment by QuarterSwede** [comment]
The only thing you can do is upgrade your device. The 7 Plus doesn’t have the power to emulate PSX games and audio without some noticeable lag.

**Comment by JoeMatt** [comment]
If you can't build from source yourself, then wait for an updated release with performance improvements compiled in. You can build from branch #667 or be patient.
