### ISSUE TITLE
Add Image Smoothing on Apple TV version

### ISSUE THREAD

**Issue by Davu67** [jasarien/Provenance#669]
Please add this feature for the provenance app for apple tv

**Comment by sevdestruct** [comment]
There is recent work on shaders, an potentially more coming.. I don't personally favor smoothing as I think it destroys the original art and makes it all ..blobby, especially considering how particular and nuanced the craft of pixel art creation actually is.. but that's me, i know many people have a preference opposite of that, but may push it down the priority list if the others have a similar view as me. I'm cool with the CRT filter and similar ones that just remind me of how that low res art actually looked on a retro display.

**Comment by JoeMatt** [comment]
There's no technical reason that I can see why this was missing, I think it just wasn't hooked up to the settings UI on aTV. 

I went ahead and added it to the feature branch N64+Swift

**Comment by jasarien** [comment]
Working for me on AppleTV. Option is there and image smoothing is apparent in-game.
