### ISSUE TITLE
Simultaneous Button Pressing

### ISSUE THREAD

**Issue by Cobsters** [jasarien/Provenance#67]
Playing pretty much any platforming game is near impossible due to the inability to hold two or more buttons at once, excluding the D-Pad.

**Comment by jasarien** [comment]
The button controls do support multiple touches at the same time. However, since a thumb is only one touch, and its touch area is relatively small, it isn't able to simultaneously press two buttons the same way one might with the physical gamepad.

**Comment by seadil** [comment]
@jasarien 
Is there any good solution for this issue? I tried to demonstrate the issue: https://vid.me/Qr8B

**Comment by jasarien** [comment]
I went back and had a look at the code for this issue. I think I've solved it in the latest commit. Can you check it out and see?
