### ISSUE TITLE
Cutting in the sound 

### ISSUE THREAD

**Issue by Black959595** [jasarien/Provenance#671]
Please help me this video shows the cutting i have in the sound its very annoying 
https://streamable.com/hrhb0

**Comment by Black959595** [comment]
At first this app was very cool with me but after a while this proplem occurred.. i am using iphone 7 plus ios 11.2.1 and I downloaded the app from iemulators.com

**Comment by JoeMatt** [comment]
No support for builds from 3rd party sites. No way of knowing which revision they're on and what compiler setup they uses. This issue hasn't been reported for anyone using official builds from this site. See the wiki on how to install our builds or from source,

https://github.com/jasarien/Provenance/wiki/Installing-using-the-prebuilt-IPAs
https://github.com/jasarien/Provenance/wiki/Building-Provenance

**Comment by Black959595** [comment]
I downloaded the app using cydia impactor and the ipa file from your website and it atill having the same problem.. sound lag :(
