### ISSUE TITLE
L2 and R2 are mapped incorrectly

### ISSUE THREAD

**Issue by thearcielloyola** [jasarien/Provenance#675]
On my 8bitdo FC30 pro L2 and R2 is mapped on start and select its not even on the same side L2 is on start R2 is on select any advice on how to fix this thank you

**Comment by jasarien** [comment]
Assuming you’re referring to L2 and R2 on the PSX core?

If so, this has been fixed in the master branch, and is awaiting a recompiled release. Compile from source if you can’t wait.
