### ISSUE TITLE
PCE / Turbo Graphics (Buttons Not Responding)

### ISSUE THREAD

**Issue by sypher714** [jasarien/Provenance#676]
Recently found out about Build 1.4 and I am impressed. Got PSX Working etc.

But for some reason the on screen buttons do NOT respond with PCE/Turbo Graphics ROMS. Currently using iPhone 7 Plus.

**Comment by sypher714** [comment]
Also does the same results on iPhone 8 Plus.

**Comment by jasarien** [comment]
Thanks is fixed in the master branch (an update has not yet been published from this code).
