### ISSUE TITLE
I can’t switch disks

### ISSUE THREAD

**Issue by woodster123** [jasarien/Provenance#681]
Playing ffxiii and when I go to the menu to press swap disks nothing happens. ffxiii has 4 disks. Has this feature been added to the app, and if so what should I be doing to fix this. Using iPhone 7 on the latest update. Thanks

**Comment by braindx** [comment]
This hasn't yet been implemented but I believe @JoeMatt is looking into it. Mednafen (the PSX core being used) already supports multi-disc games through the use of m3u playlist files but this support needs to be added to Provenance itself and its game importer.

**Comment by JoeMatt** [comment]
I'm going to close this as I just made a proper feature ticket #682
