### ISSUE TITLE
Add multi-disc support

### ISSUE THREAD

**Issue by JoeMatt** [jasarien/Provenance#682]
- [x] Add m3u import to library
- [x] Add UI menu to switching discs
- [x] Figure out which cores other than Mednafen support multi-disc

Currently only Mednafen (PSX) is setup to support disc swapping.

**Comment by JoeMatt** [comment]
This is in the N64+Swift branch

**Comment by ciscosurplus** [comment]
Tested on Apple TV, it doesn't recognise the .m3u file included in the zip file so uploaded this separately. 

(tested Resident evil 2 Europe, and Final Fantasy Viii usa).

It shows in the game library as two / three games, Disc 1 loads up, disc swap shows in the menu
the action of swapping a disc causes the screen output to crash/lockup. 

The other thing I noticed in this branch (latest build) the frame rate on Apple Tv 4 drops down to 7-8 FPS consistenty and seems to run very sluggish. 

finally I also noticed on this build b button on MFI controller exists back to main apple TV menu.

**Comment by jasarien** [comment]
The low FPS is probably because you’re running in debug mode. The b button exiting the app will likely because you have icade mode enabled with an mfi controller connected at the same time. M3u files recognised and imported fine for when it was part of the zip and named with the same conventions as the ROM files. Also disc swapping worked fine for me with FF7. Are you sure all your disc ROMs were from the same dump?

**Comment by ciscosurplus** [comment]
@jasarien they were downloaded separately but from the same place. So perhaps not? Res Evil 2 was a single download with 2 CDs each with 2 tracks and associated que files. FF7 I created cue files so perhaps a user error. 

Re icade mode, on this build on TVOS I can't enable it as I raised a separate issue (blank screen) although I know the fix (enable target TVOS) Im going to fix again and check that setting. 

That said I can't issue a start on apple TV currently. 


Re debug mode Im confused on that one, Im Archiving > export for Ad Hoc Deployment then uploading like I would any other Xcode app. 

I will try another game and report back.

**Comment by jasarien** [comment]
You need to select `ProvenanceTV-Release` (as opposed to ProvenanceTV) before you archive ands export. Archiving and exporting a debug build will still run in debug mode.

**Comment by ciscosurplus** [comment]
@jasarien whoops didn't know that, explains a lot thanks!! (still learning)

**Comment by jasarien** [comment]
@ciscosurplus 
> disc swap shows in the menu the action of swapping a disc causes the screen output to crash/lockup.

You need to reset the core after swapping a disc if the game is not already prompting you to change discs. Eg. if you want to play Claire's mission in RE2, then start the game, swap to disc 2, then choose reset from the menu. The game will now load with Claire's disc and you can start her mission as a new game. Later on when you finish her mission and create the save for Leon's B mission, you can swap the disc when the game prompts for Leon's disc and it should auto continue when it detects the swapped disc.

**Comment by ciscosurplus** [comment]
Yes perfect confirm the reset works, I also found FF7 with cue files and appears to allow swap.

**Comment by goodwinbg1906** [comment]
Hello, I am a totally new and just discovered this platform for playing Playstation games, per screenshot have I set up the m3u file correctly to zip it into the ROM directory?
![screen shot 2018-02-22 at 8 38 08 am](https://user-images.githubusercontent.com/36734649/36541405-c7420918-17ab-11e8-84b3-2a2b8a1c0b49.png)

**Comment by goodwinbg1906** [comment]
I know how to compress the folder that contains the .bin and .cue file originally but is that where I am suppose to place the m3u file in that same folder I am going to zip to upload?

**Comment by jasarien** [comment]
Yes, that looks correct to me. However, I have noticed a couple of issues when importing multi disc games were the m3u isn’t imported and is left behind in the roms directory after the game is imported. If this happens, you can just move it from the roms directory into the PSX directory alongside the bin and cue files and it should be picked up after that.

**Comment by jasarien** [comment]
I would put all the discs into one directory along with the m3u, and zip them as one, not multiples.

Eg, in your case, you’d have:

Zip:
    Xenogears (USA) (Disc 1).bin
    Xenogears (USA) (Disc 1).cue
    Xenogears (USA) (Disc 2).bin
    Xenogears (USA) (Disc 2).cue
    Xenogears (USA).m3u

**Comment by goodwinbg1906** [comment]
Thank you,  I saw post above about the screen freezing when you enable swap disc action from menu, maybe I missed it but what would be cause of that in the app ?have the zip folder set up like above and put that folder into the ROM folder.

**Comment by jasarien** [comment]
Did you check to see if the m3u file was copied from the roms folder to the PSX folder?

**Comment by goodwinbg1906** [comment]
It wasn't so I manually put the file into the folder like you suggested.

**Comment by goodwinbg1906** [comment]
I can take a screenshot of how it is set up currently for you if that helps

**Comment by jasarien** [comment]
Sure, might help. Also, at what point is it freezing? When you press “swap disc” do you see  another menu with the disc numbers to pick?

**Comment by goodwinbg1906** [comment]
It freezes when I press swap disc.

**Comment by goodwinbg1906** [comment]
Never see any option to choose other disc numbers.

**Comment by jasarien** [comment]
Hm, sounds like it’s not picking up the m3u... post the screenshot.

**Comment by goodwinbg1906** [comment]
![screen shot 2018-02-22 at 9 56 05 am](https://user-images.githubusercontent.com/36734649/36545370-beb7214c-17b6-11e8-838c-2d2ebec9d001.png)
![screen shot 2018-02-22 at 9 56 32 am](https://user-images.githubusercontent.com/36734649/36545372-c00b3a24-17b6-11e8-93ff-7a9e951ef618.png)
![screen shot 2018-02-22 at 9 56 48 am](https://user-images.githubusercontent.com/36734649/36545380-c3cab2e8-17b6-11e8-9884-74240136265d.png)

**Comment by goodwinbg1906** [comment]
So when it leaves the ROM directory it keeps creating genesis folder so I manually put them into folder I created com.provenance.psx is that where I should be putting all those files?  Or are the original .bin and .cue files for the game corrupted and I need to download a new one?

**Comment by jasarien** [comment]
Either you imported the files without zipping them, or you zipped a folder containing the files. You need to zip the files themselves not their containing folder. Delete all the currently imported files, try what I said and reimport.

**Comment by goodwinbg1906** [comment]
So was putting files in a zipped folder, took them all out and zip files as one zip and uploaded to ROM folder.  It started unarchiving it and always would go into the conflicts folder that was created never going into com.provenance.psx folder.  Would resolve the conflict on my phone naming the files PSX but what was weird is that both images came up as Disc 1 instead of Disc 1 and Disc 2.  Have both the .bin and .cue for both CDs for game along with m3u file in zip file but still when start game and click Swap Disc still freezes.  Anything you can think I am missing or not doing correctly from your previous steps?  Appreciate all your help.

**Comment by oCSnow** [comment]
Same here. Seems to not recognize the m3u file. Every disk shows up independently and when you hit the swap disk button the game just freeze. Thank you in advance for the support.
