### ISSUE TITLE
PSX - constant fps drop while playing

### ISSUE THREAD

**Issue by tikstiks** [jasarien/Provenance#683]
tried doing the game speed workaround (game speed > normal), also no crt filter but it doesn't seem to maintain a steady 60fps. it often drops to 30fps.

im using an iphone SE on this.

also, if it helps, the game im playing is monster rancher 2.

**Comment by jasarien** [comment]
There is a PR in the works (should be mergable soon, but needs a bit of testing), that improves the performance of the PSX core. Whether it’ll ever run at full speed on an IPhone SE, though, I can’t say. The SE is an older device, with the internals of an iPhone 6S — I would imagine it should be able to run at full speed with the optimisations done by @braindx on his PR, but you’ll need to test it to be sure.

**Comment by jasarien** [comment]
My mistake, @braindx’s PR for the mednafen improvements was already merged (it’s the N64 PR that is still in progress/testing). 

If you build provenance from source with the latest master code then you should get the performance improvements.

**Comment by tikstiks** [comment]
@jasarien thanks for the quick response. 

unforetunately, no i haven't used to build method to install. will read the wiki for the procedure.
one question, though. this build method from wiki works on non-jailbroken iphones?

**Comment by tikstiks** [comment]
@jasarien nevermind. just saw the requirements. i don't have a mac :(

**Comment by jasarien** [comment]
In that case, you’ll have to wait until a new release is made.

**Comment by JoeMatt** [comment]
You can reopen if this is still an issues after using an updated build. Closing for now.
