### ISSUE TITLE
No more free Apple Developer Program?

### ISSUE THREAD

**Issue by mihalski** [jasarien/Provenance#696]
I can't find a way to enrol without being forced to pay $149/year.

**Comment by jasarien** [comment]
You might just not be looking in the right place. 

But anyway, even if Apple has discontinued the free dev accounts (which I don’t think they have) it is not our problem, so please don’t raise it as an issue on our repo.

**Comment by jasarien** [comment]
https://9to5mac.com/2016/03/27/how-to-create-free-apple-developer-account-sideload-apps/

**Comment by mihalski** [comment]
I understand that it's not an issue with Provenance itself, but the wiki MIGHT need an update to mention that free accounts are no longer available (or that resigning no longer works if that's the case).

The only option (as an individual) I am being given is to "complete enrolment"l:
![screen shot 2018-02-23 09 41 16 am](https://user-images.githubusercontent.com/3755059/36570456-d89e5356-187d-11e8-9031-83732c4ff7b0.png)
I can either purchase or cancel in which case I'm back to the only option being "complete enrolment".
In short I no longer see any way to enable free developer privileges.

I created an application specific password and tried to use Cydia Impactor to resign the provided IPA, but at the very end of the process I get:
![screen shot 2018-02-23 09 34 27 am](https://user-images.githubusercontent.com/3755059/36570752-47c7d5bc-187f-11e8-8e10-d74c76e2e0c7.png)

If free developer privileges are assumed for all developer accounts then I may be experiencing some other problem, but I can't find any info to either back or refute that theory.

Next I will try to build from scratch. Perhaps only resigning has stopped working?

At any rate, I'll update this post so that the next person having these problems has something to go on.

**Comment by jasarien** [comment]
Have you tried just downloading Xcode and signing in with your Apple ID in the Xcode accounts preferences?

**Comment by mihalski** [comment]
It's a 3 hour download so waiting on that now.

**Comment by jasarien** [comment]
Apple’s dev site still had this text on their page: 

> If you’re looking to develop apps for Apple platforms, download the Xcode developer tools, SDKs, and resources for free on the downloads page. Program membership is not required. If you don’t already have an Apple ID, you can create one here.

https://developer.apple.com/support/compare-memberships/

**Comment by jasarien** [comment]
Just go here http://developer.apple.com/account and sign in with your Apple ID. No need to go through the enrolment process.

**Comment by mihalski** [comment]
The link to https://developer.apple.com/programs/enroll/ in the Wiki may have been what led me astray initially.

**Comment by jasarien** [comment]
The Cydia impactor method probably won’t work until you’ve signed into the developer portal and accepted the agreement. It needs access to the portal with your AppleID to register your device and app ids etc.

**Comment by mihalski** [comment]
I accepted the agreement years ago and it hasn't recently asked for me to re-accept any new agreements. Guess I just have to wait and see what happens when using Xcode directly.

**Comment by tomp8628** [comment]
I’ve used Cydia and Xcode with my free developer account for a while.  It could be something stupid like you don’t have iTunes open when using Impactor or you need to revoke your certificates using Impactor.

**Comment by mihalski** [comment]
Well I found someone having a similar problem with Xcode and their solution was this:
https://github.com/fastlane/fastlane/issues/7966#issuecomment-275057858
However, I cannot find these options anywhere on the appleid or apple development portal.

P.S. iTunes is open and Impactor can see my phone. It goes through many stages until finally that error comes up. When you say you've used Cydia are you referring to Impactor? Is your phone jailbroken? Mine is not.

**Comment by tomp8628** [comment]
Yes Impactor. I do not have anything jailbroken, and have used both Windows and Mac.  I would forget about even trying to access anything on the developer portal if you’re using a free account.  When Apple released Xcode 9 they stripped options for free accounts off the portal since Xcode 9 automatically manages provisioning files and certificates.  Have you tried revoking your certificates in Impactor? That always fixed a bunch of those random errors for me.

**Comment by mihalski** [comment]
Trying too revoke certificates using Impactor instantly comes up with this error:
![screen shot 2018-02-23 10 55 40 am](https://user-images.githubusercontent.com/3755059/36572541-2583e0aa-1888-11e8-8c21-0ae2cadefebc.png)

**Comment by tomp8628** [comment]
May have something to do with the version of Impactor you’re running. https://yalujailbreak.net/fix-progress-hpp87-error/

**Comment by mihalski** [comment]
It did and I can revoke using 0.9.42, hover, no matter what combination of steps I take I cannot successfully resign either with 0.9.42 or 0.9.44. I either get the error I was previously getting, or this new one:
![screen shot 2018-02-23 11 13 42 am](https://user-images.githubusercontent.com/3755059/36573453-c9f8dd12-188c-11e8-9428-2da4f08b5e0e.png)
None of the steps listed here helped:

https://www.downloadcydiaimpactor.com/cydia-impactor-error-installation-cpp-51/

I revoke the certificates before every attempt just to be sure (though I have also tried not revoking with no luck).

Still waiting for Xcode to download.

**Comment by tomp8628** [comment]
I had that error before when I was trying to run an .IPA through Impactor that I had already signed with Impactor.  So I downloaded the .IPA fresh and reran it through.  Best of luck on Xcode!

**Comment by mihalski** [comment]
Xcode looks like it should be working but when it comes to code signing I get infinite requesters asking for the login password which does not work. And neither does any other password I have ever used :/
![screen shot 2018-02-23 06 40 04 pm](https://user-images.githubusercontent.com/3755059/36585326-3807caf2-18c9-11e8-94a8-7dd450679c42.png)

**Comment by jasarien** [comment]
@mihalski I’m sorry Impactor isn’t working for you, but this really isn’t Provenance’s issue, and I don’t think discussing it here is going to result in anything. You’ll be better off contacting the developers of Impactor.

**Comment by mihalski** [comment]
That's not an Impactor euro.. It's an Xcode error.

![screen shot 2018-02-23 06 45 48 pm](https://user-images.githubusercontent.com/3755059/36585520-ef00ba66-18c9-11e8-89ff-a6b8a1002c77.png)

**Comment by brandonb87** [comment]
@Mihalski did you make sure to follow the guide and open the correct file. It’s very important that you open the “provenance.xcworkspace” file otherwise when trying to build you’ll get a bunch of errors. Cleaning won’t do you any good as there are certain parts that aren’t linked properly in the “provenance.xcodeproj” file.

**Comment by mihalski** [comment]
Yes. I definitely opened the correct file as I did see that specified in the documentation.

Will give this another go tomorrow.. perhaps something has changed in the last 11 days :/.

**Comment by JoeMatt** [comment]
You're definitely having issues with code signing in your account. Check that your iTunes connect account is configured in Xcode and that you've set the proper identity to sign the app in the General tab of the app project config panel page. 

Xcode will ask you for your password to access your signing certificate from keychain, it's your standard login password. If that doesn't work then your login keychain is probably out of sync with your login credentials and that's beyond the scope of any help that can be given here. You'll have to google that one.
