### ISSUE TITLE
Crashing when launching game on Apple TV 4 (installed via nitoTV)

### ISSUE THREAD

**Issue by RotsiserMho** [jasarien/Provenance#698]
I installed Provenence via the nitoTV package (version 1.4) and while the app launches and runs the web server, whenever I launch a game it crashes. I've tried NES, Genesis, and SNES. Any ideas?

Edit: I've also tried side loading the ipa with Impactor but it alternated between two errors: "APIInternal" and "signed with invalid entitlements".

**Comment by somepornoperv** [comment]
Yup same thing here. Installed Provenance from nitoTV. I can see the game in Library. But crashes when I launch it. I only tried .nes Roms.

**Comment by JoeMatt** [comment]
Sounds like a problem with their signing or package. We have no relationship with nito. We only support our builds via https://github.com/jasarien/Provenance/wiki/Installing-using-the-prebuilt-IPAs or self  built via https://github.com/jasarien/Provenance/wiki/Building-Provenance

**Comment by RotsiserMho** [comment]
Fair enough. Thanks for the info!
