### ISSUE TITLE
Crashing once started game

### ISSUE THREAD

**Issue by stizy** [jasarien/Provenance#702]
Hi I am currently using an iphone 5c under ios 10.3.3 which is the last version for this unit...i have followed every instructions and read the same issues for trouble shooting. I downloaded my game from emu paradise which is alpha gaiden by aeon.. when i first uploaded my game i tried what ive seen on youtube to upload it individually one is .cue and one is .bin.ecm the problem is it crashes i also tried to upload it with the .7z and .cue still it crashes the last is i tried uploading it as the whole file which i downloaded the problem is it only showed a black screen...i uploaded the all the bios correctly..can you tell me what i did wrong?

**Comment by stizy** [comment]
By the way the game shows in recently played but i havent played it yet

**Comment by sypher714** [comment]
The PSX rom is a bad dump most likely, and i am not sure the emulator supports .ecm

.cue and .bin are supported as far as I know, as for a rom site that does offer correct dumped roms, I'd state the site name but I am not sure we're allowed to.

An example of a the files you should have for a rom are. I might have it backwards format wise.

Castlevania Symphony of the Night.bin
Castlevania Symphony of the Night Tracks.cue

**Comment by jasarien** [comment]
ECM is not supported. You will need to convert any ECM files to straight BIN files. You’ll need to google for a tutorial on how to do that, it’s not within the scope of this issue or project to explain or troubleshoot that process.

As a rule, you should always zip the .CUE and .BIN files together into a single archive at the top level (not within a subfolder) before importing them. Don’t import them individually. Also name the files exactly the same (except for the .BIN/.CUE extension). Finally, open up the .CUE file in a text editor and ensure that the .BIN file is referenced exactly by its correct filename.

There are still bugs in the importer, so this won’t be a completely foolproof process just yet. They are being worked on, but time is slim, so please be patient.

**Comment by stizy** [comment]
Thanks, so that is why the game after posting was gone from provenance library but still there when i view it from the pc
