### ISSUE TITLE
B button on Steelseries Nimbus controller is backing out of the Provenance application

### ISSUE THREAD

**Issue by aenhsaihan** [jasarien/Provenance#704]
I looked through the issues and saw that no one has brought this up, even other users who had different issues with the Steelseries Nimbus controller, to my surprise and amazement.

I realize that you still have to be able to control the AppleTV with the MFi controller, but does the B button have to back out of the application? I get that the start button will be used by the AppleTV to back out of the application, but why does the B button do the same thing? In this state, I am unable to use the B button on my controller for actual games. Is there something I'm missing?

**Comment by jasarien** [comment]
This has been brought up before. A few times actually. 

Do you have iCade mode enabled by any chance?

**Comment by aenhsaihan** [comment]
Oh, my bad, I admit I did a quick run through of the 119 issues, but didn't see anything specific to this issue in the titles.

I set iCade controller to Steelseries Free Controller, is this iCade mode?

**Comment by jasarien** [comment]
Yes. iCade interferes with MFi controllers on tvOS as it intercepts the focus from the focus engine. 

If you’re using MFi controllers then don’t enable iCade mode.

**Comment by jasarien** [comment]
More info: https://github.com/jasarien/Provenance/pull/628

**Comment by aenhsaihan** [comment]
Yeah, disabling iCade mode with my MFi controller, and then terminating the app in multitask mode and restarting it fixed the issue. Thank you so much for the reference, that really helped! I hope this helps out more people in the future who have the same issue with MFi controllers.

**Comment by lolkthxbai** [comment]
Does tvOS allow Provenance to request the BT MAC address? If so, what do you think about using that information to suggest the correct controller to the user. Or perhaps instead include an image of the controller so there’s no confusion.

**Comment by sevdestruct** [comment]
Hmm.. actually this is an iCade issue, not Nimbus issue, folding this into the repurposed general use iCade issue: #699.

**Comment by austinarchibald** [comment]
I am having this issue (b button exits out) as well, and I cannot fix it. Any ideas? iCade is not enabled, it never has been. It only started doing this when I updated to Provenance v1.5b 2774 - tvOS (.ipa) from 1.4. I can't use the b button at all in any game. SteelSeries Nimbus+

**Comment by JaxMyers** [comment]
> I am having this issue (b button exits out) as well, and I cannot fix it. Any ideas? iCade is not enabled, it never has been. It only started doing this when I updated to Provenance v1.5b 2774 - tvOS (.ipa) from 1.4. I can't use the b button at all in any game. SteelSeries Nimbus+

This is happening recently for me too but I am on an older version of Provenance (1.4 817 which I think is the latest release). I was using this controller no problem with 1.4 for a while and then all of the sudden it started exiting when I pressed the "B" button. I wonder if it might be related to an iOS update?

**Comment by cheif** [comment]
Yeah, there's a bug when running the latest prebuilt on tvOS14, building yourself from develop with XCode12 should resolve the issue.

**Comment by JaxMyers** [comment]
> Yeah, there's a bug when running the latest prebuilt on tvOS14, building yourself from develop with XCode12 should resolve the issue.

Thanks, I’ll try that!

**Comment by themanro** [comment]
> Yeah, there's a bug when running the latest prebuilt on tvOS14, building yourself from develop with XCode12 should resolve the issue.

Could you please clarify what *building yourself from develop with xcode12* means?

**Comment by JaxMyers** [comment]
> > Yeah, there's a bug when running the latest prebuilt on tvOS14, building yourself from develop with XCode12 should resolve the issue.
> 
> Could you please clarify what _building yourself from develop with xcode12_ means?

Download the source code, open it in Xcode, build the project, and install it to your Apple TV directly via Xcode.  This is slightly less straightforward than it sounds but the instructions are in the wiki and you need a developer account. Also I had to use a workaround to make the Carthage part of the instructions work properly.
