### ISSUE TITLE
Add Dropbox support to sync savegames

### ISSUE THREAD

**Issue by josejulio** [jasarien/Provenance#71]
It would be great to have dropbox support (or google drive, copy, etc) to sync the saved games (or even the roms!) for playing with multiple devices (ipad / iphone for example)

**Comment by jasarien** [comment]
Duplicate of #1 

Please don't raise duplicate issues. Search the other issues before raising new ones.

**Comment by josejulio** [comment]
Sorry @jasarien, i though it wasn't here, I'll do a search next time.
