### ISSUE TITLE
Trying to match file names (openemu?)

### ISSUE THREAD

**Issue by Cepheidsong** [jasarien/Provenance#710]
HI hi

So even though we can do manual cover art, I was just trying to match up file names of games with what database it uses to pull art- when it finds it, even on the rare occasion the database doesn't have art for the game, it does correct the file name to show what the game name is in the database

example: file name 'Hokuto no Ken (Japan)' gets renamed 'Hokuto no Ken: Shin Seikimatsu Kyūseishu Densetsu'

Some games show no artwork or the proper game name unless you rename the file to what it needs to detect.  Same rom, just needs right name!

example: file name 'Bishoujo Senshi Sailor Moon' shows no artwork, but if you rename it 'Bishoujo Senshi Saimormoon (Japan)', the artwork shows!

So anyway there are some games I cannot figure out what the database wants me to name the games to detect the proper name/show artwork.  I've searched high and low in openemu and google searches and I cannot find what file name list it pulls from so I can match the proper file name.

Would anyone by chance know where I can find what file names it cross-references from, like a list?  I'm just trying to create a master list of all proper file names for use in Provenance for ease.

**Comment by sevdestruct** [comment]
You have to use the file names verbatim if you uploading manually cover art, not the game titles.
