### ISSUE TITLE
Cannot import SegaCD Roms - Unable to load ROM

### ISSUE THREAD

**Issue by gareauk** [jasarien/Provenance#711]
Hi,

I'm running Provenance 1.4 (817) on my iPad Mini 4 (iOS  v11.2.6).  I have followed your instructions in the wiki to a tee, but I cannot seem to get any Sega CD roms to load properly.  They appear in Provenance under the Sega CD section, but when I click on the game to run it, I get the error message 'Unable to load ROM.  Maybe it's corrupt?  Try deleting and reimporting it.' 

I've verified the bios files are renamed and are in the /bios/com.provenance.segacd folder and the roms (both bin and cue files) are in the /com.provenance.segacd folder.  

Can anyone else replicate this issue or am I doing something wrong?

Any help would be much appreciated.

Thank you,
gareauk

**Comment by gareauk** [comment]
Must have been a couple of bad roms.  I was able to get it working with another rom.  Closing issue.

**Comment by JoeMatt** [comment]
The develop branch also has a partial rewrite of the importer code. You can try building from that branch too.
