### ISSUE TITLE
Input lag when using 8Bitdo gamepads

### ISSUE THREAD

**Issue by vincentsaluzzo** [jasarien/Provenance#712]
Maybe it's normal, but I've a little input lag from the tap on my gamepad and the action on the emulator. That's so difficult to play game like Super Mario in this case.

**Comment by jasarien** [comment]
You can read through this thread for some more info on input latency. Though, it might make you lose your mind by the time you read all of it 🤪https://github.com/jasarien/Provenance/issues/157

**Comment by vincentsaluzzo** [comment]
I've read it and very first comments think me to use game mode on my TV. I've put it by default on Switch HDMI port but not on Apple TV one... My bad for this useless issue ! 😅
