### ISSUE TITLE
Copy to Provenance [from other apps] not working (dev Swift builds)

### ISSUE THREAD

**Issue by sevdestruct** [jasarien/Provenance#726]
Though picking a file from an apple files/clouds from Provenance with document picker works now, the ability to send a file to Provenance via common share button in other apps and selecting Copy to Procenance is now broken in the new Swift builds in dev and feature branches. Tested with multiple roms/cores and a couple apps like File Browser and Apple Files.

**Comment by JoeMatt** [comment]
This is because when the import path was changed, it wasn't changed everywhere. It's hardcoded to /roms still in the app delegate. I'll fix this.

**Comment by sevdestruct** [comment]
that would have been my bad, thanks joe.
