### ISSUE TITLE
Feature Enhancement: Roll-up Game Sections

### ISSUE THREAD

**Issue by gareauk** [jasarien/Provenance#727]
I currently have thousands of games loaded into Provenance (iOS 11 on iPad Mini 4) and sometimes it can be a pain to scroll through all of them trying to find a game I want to play.  Yes I could use the search feature but sometimes I just want to browse and maybe skip over the Atari and Nintendo games for example.  It would be nice to roll-up all of the game console sections into one line each so I can quickly skip by them.

Thanks!
gareauk

**Comment by sevdestruct** [comment]
Hey @gareauk, please take care to check the existing issues before posting new ones, this is more or less being addressed in #714 as part of 2.0, and furthermore with #721 i a subsequent 2.x release - if you have suggestions or want to support those efforts, please continue you there.

Side note, is thousands of roms in your library really necessary?? You don;t think you couldn't isolate your like top favorites for now until we get the new UI implemented.

**Comment by gareauk** [comment]
Hi @sevdestruct, I did look for an existing issue but couldn't find what I was looking for.  Having thousands of roms is not necessary but I like showing it off and I like to find new games that I've never played before.  Yes I can isolate my favourites at the top until a new UI is implemented.  This issue was brought forward not really as a complaint but more of a feature request for a future version.  Thx for your help!
