### ISSUE TITLE
Starting PSX game freezes application

### ISSUE THREAD

**Issue by aenhsaihan** [jasarien/Provenance#729]
Hey guys, just wanted to say thanks for all the hard work and contributions made to this great platform, nothing better than retro gaming on an Apple TV :)

I tried following your instructions to have the correct BIOS files for PSX before starting Harvest Moon Back to Nature, which comes with the .bin and .cue files.

I think initially I downloaded some garbage BIOSes that showed up as genesis files. I have since deleted them and installed the three requisite PSX BIOS files that now show up correctly under the BIOS/PSX directory.

I then proceeded to upload the .bin and .cue files for Harvest Moon Back to Nature into the ROMs folder of the web server, and everything looks great on the application, the cover art shows up just fine.

But when I try to start the game, the application just freezes. When I back out of the application and go back into the application, I see what I believe to be the game, but I have the Provenance menu screen on display, also frozen.

Have you guys come across this before?

**Comment by sevdestruct** [comment]
What build are you using? current release v1.4 or one of the current dev branches?

Also, make sure the contents of your .cue file points to the **exact** name of your .bin file, and both files are named **exactly** the same:
```
[game].bin
[game].cue
```

If that doesn't work you might have a bad ROM file. Try uh.. redownloading or acquiring from another source, and then try replacing your BIOS files in case those are junk?

**Comment by aenhsaihan** [comment]
I'm on Version 1.4 (858) release.

The .bin and .cue are named exactly the same.

The only thing I can think of is yes, maybe I should try another game or, the original BIOS that I uploaded are interfering somehow since it was hard to find and delete them all.

BIOS files could also be bad, but I googled under the checksum you guys provided :/

**Comment by sevdestruct** [comment]
You said you uploaded then .bin/cue files, generally speaking this needs to be done as a an archive togetger, at the moment, s did you upload separately or in an archive? walk through your process.. do any other games work for you? Just this one?..

**Comment by BaffleBlend** [comment]
Also, check if any of your PSX games are filed under "Genesis". If they are, the .bin got separated from the .cue and you'll have to move it to the PSX folder manually.

**Comment by sevdestruct** [comment]
Right, which is why I mentioned the archives, forgit to mention the reason why, thanks @BaffleBlend.

Game importer needs improvement and is currently in the works to resolve so these are workarounds for now.

**Comment by aenhsaihan** [comment]
I uploaded the .bin/cue files separately and just now together as a .rar file, still no dice. I tried two games so far.

**Comment by aenhsaihan** [comment]
That was it BaffleBlend, thanks man!

**Comment by sevdestruct** [comment]
@aenhsaihan: In the future use **.zip** or **.7z** archives, not .rar (as is stated in the wiki and in the app itself)
