### ISSUE TITLE
GBA: Super Mario Advance 2 lags

### ISSUE THREAD

**Issue by seadil** [jasarien/Provenance#73]
Hi,

I've tested the game "Super Mario Advance 2 - Super Mario World" for GBA and it lags on my iPhone 6 Plus (no Jailbreak). Compiled the latest version with Xcode 7 beta. I've tested the game with GBA4iOS and it runs with full speed and no lags at all.

**Comment by jasarien** [comment]
Compile with the release scheme. This solves any performance issues. Debug scheme doesn't have optimisations enabled.
