### ISSUE TITLE
[Suggestion] Color/Hardware Modes for Game Boy and Virtual Boy

### ISSUE THREAD

**Issue by BaffleBlend** [jasarien/Provenance#748]
Game Boy games on the Nintendo 3DS Virtual Console have the ability to switch between playing in black-and-white, as it is usually, or black-and-green, as it was on the original hardware. I would like a similar option to be available, perhaps in addition to toggling Super Game Boy mode (which is enabled by default in games that have it, such as Donkey Kong '94) or GBA-Enhanced mode (which is *not* enabled by default, in games such as Shantae); I would appreciate the latter especially, because in several games, content is locked behind the mode.

In a similar vein, I would like the option for a greyscale filter in Virtual Boy games. While this was never an *official* function, the distinctive dim red of the Virtual Boy is just as hard on the eyes now as it was back in 1995; currently, I work around it using the accessibility options on my phone to change the entire screen to black-and-white temporarily, but I would like if something similar was incorporated officially.

**Comment by sevdestruct** [comment]
@BaffleBlend…pretty sure this issue post already exists, or, if not, you can take it onto #743 probably., but i swear i saw it…

<sup>Don't make me link the new [Issues Usage](https://github.com/jasarien/Provenance/wiki/Issues-Usage) wiki…</sup>

**Comment by JoeMatt** [comment]
There's actually code i the medafengamecore.mm file `- (void)changeDisplayMode` will cycle through different VB color modes. It's just not hooked up into anything. 

If you're building from source, you can just add a bunch of calls at loadFile to get the mode you want, or hook up a button callback since not all the buttons are used on MFi.

It'll get added later with per-core settings but that's a bit off from now.

**Comment by sevdestruct** [comment]
@BaffleBlend: just for your reference he's talking about #680, which yeah, is probably a better place to coattail this addition, but it's later…

**Comment by sevdestruct** [comment]
ah, i found it: #60 - close enough anyway, @BaffleBlend please try to search a little more before posting duplicates - if you find something similar, just add your comment to the existing thread - the issue can always be updated to absorb your comment
