### ISSUE TITLE
Can't call the full Game Info View from 3D Touch preview

### ISSUE THREAD

**Issue by sevdestruct** [jasarien/Provenance#756]
To keep the user flow forward in a game browsing mode, I suggest we add a button to the action list to call the full view, which allows you to swipe left and right between games already as well as bring up the link to manual. (this will also be super helpful for when we have a more extensive Single Game View (#720) with screenshots and revised UI in 2.x…

**Comment by sevdestruct** [comment]
Due to limitations of PushPop previews, revised the purpose of this ticket ⬆️ .

**Comment by JoeMatt** [comment]
There's no reason to add a button, force touch preview does exactly that if you continue the touch and it against Apple User Interface Guidelines for 3D touch peak.

https://developer.apple.com/ios/human-interface-guidelines/user-interaction/3d-touch/
**Avoid providing an action button that opens a peeked item.**

**Comment by sevdestruct** [comment]
![image](https://user-images.githubusercontent.com/3118097/37550781-51e68962-2950-11e8-9d5a-00a8d99a6ebc.png)

Touché. Alright Joe, I get your point. Didn't have to go all Apple Human Interface Guidelines on me… 😛 - Although Apple breaks their own guideline/recommendatiuon in Safari.. so there is edge cases.

**Comment by JoeMatt** [comment]
Yeah but Safari's open in tab is not the same as the default force touch action of open not in a new tab. They meant don't do the same thing as tapping or force touch without sliding up the menu would do.

**Comment by sevdestruct** [comment]
@JoeMatt : …So, i know this is closed, but i think after i played with the feature more, on Safari... i retract my original stance on this. I realize i was still getting familiar with 3D touch and something you described I wasn't interpretting correctly: i thought you had to send the pushpop completely away after you lock it up with action buttons, like a point fo no return... but, now i realize you can slightly swipe down to unlock it and while there you can 3D touch all the way through -- man, i had an iphone 6 for way too long.. i'll shutup about this now. keep this closed , not needed, **you are right joe**… but it does make me wonder why another 3D touch on the preview isn't allowed by apple without swiping down to put the action sheet away first... oh well.
