### ISSUE TITLE
PSX ROMs freezing on launch

### ISSUE THREAD

**Issue by sevdestruct** [jasarien/Provenance#762]
PSX on UIRedesign branch isn't working no games launch …seems Atari 2600 Stella core is being called by mistake? 

![unknown](https://user-images.githubusercontent.com/3118097/37539652-80fbd52a-2911-11e8-972b-e2f1d27cf2fb.png)

**Comment by JoeMatt** [comment]
You don't have to make tickets for in development branches otherwise we'll end up with 100 tickets.

**Comment by sevdestruct** [comment]
was just logging it… you know LA time, NY, UK, etc… we're spread, but hey, at least it's all labelled appropriately so you could filter the non-master ones out

@JoeMatt, would prefer those just as non-issue notes in the project board(s) then? can't paste images in those… or that just leaves me with the #bugs channel and chat, and pins i guess.
