### ISSUE TITLE
Phone Call = Web Server No Network

### ISSUE THREAD

**Issue by sevdestruct** [jasarien/Provenance#763]
Happened to be running a test when I got a phone call and app switch back to Provenance to start the web server, and got this:

![image](https://user-images.githubusercontent.com/3118097/37552866-2df2b6d2-297a-11e8-9da4-2f223dc3bad0.png)

Reporting no network connection which was false. Needs additionally testing against a false positive (for instance maybe there really was an unlikely intermittence in my WiFi at that same moment?)

**Comment by jasarien** [comment]
According to your status bar you’re using LTE, not WiFi.

**Comment by sevdestruct** [comment]
So it does, and I just at did a quick test. I was wrong works fine on phone call.
