### ISSUE TITLE
Linker error during compilation from Realm.framework on Xcode 7 beta 4

### ISSUE THREAD

**Issue by Alazoral** [jasarien/Provenance#80]
Attempting to build Provenance-Release on Xcode 7 beta 4 (7A165t) results in the following error:
> ld: '/Users/leon/Downloads/Provenance-master/Realm.framework/Realm(RLMListBase.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by jasarien** [comment]
Fixed in 9c124b4ecc272cc8102165d7b3b4a1365e241211

**Comment by Alazoral** [comment]
❤️
