### ISSUE TITLE
"Refresh Game Library" only removes images, does not re-download titles or images

### ISSUE THREAD

**Issue by cplr** [jasarien/Provenance#84]
If I run a debug build to enable logging, "Refresh Game Library" doesn't seem to do what it says - it only clears the images in latest build.

**Comment by jasarien** [comment]
Logging isn't indicative of every exact action. Either observe the database or read the code to see hat is actually happening. For the most part the logging was put there to help me debug certain things and mostly just forgotten to remove.

**Comment by jasarien** [comment]
There does seems to be a bug in that area though. I'll look into it if I get some time.
