### ISSUE TITLE
Choppy SNES gameplay

### ISSUE THREAD

**Issue by peanut256** [jasarien/Provenance#86]
On my devices, SNES emulation often becomes choppy for no apparent reason.
I believe a syncing issue related to frame flipping is to blame. Changing [line 73 in PVSNESEmulatorCore.mm](https://github.com/jasarien/Provenance/blob/master/PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm#L73) to `waitUntilDone:YES` seems to solve the problem for me. (Note that this hack slows down emulation too much on some complex games, e.g. games using the super fx chip.)

Edit: Using a more aggressive scheduling helps with the slowdown on super fx games; change [line 166 in PVSNESEmulatorCore.mm](https://github.com/jasarien/Provenance/blob/master/PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm#L166) to `OESetThreadRealtime(gameInterval, 0.016, 0.02)`.

**Comment by peanut256** [comment]
I've found a much nicer solution:

* Ignore my suggestions from the last comment
* Put a `@synchronized` block around the drawing (`glkView:drawInRect:` in PVGLViewController.m) and emulation code (`executeFrame` in [line 181 in PVSNESEmulatorCore.mm](https://github.com/jasarien/Provenance/blob/master/PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm#L181))
* Now we can flip buffers on the emulator thread, i.e., replace `performSelectorOnMainThread` in [line 71 in PVSNESEmulatorCore.mm](https://github.com/jasarien/Provenance/blob/master/PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm#L71) by a simple direct call.

This works really well for me.

PS: This change also solves [issue #42](https://github.com/jasarien/Provenance/issues/42).

**Comment by jasarien** [comment]
Which games were being choppy for you at the time you raised this issue? I tried the @synchronised solution you suggested and it doesn't solve the resolution flicker in Secret of Mana for me...

**Comment by peanut256** [comment]
Sadly, any game I've tried was choppy, although not all the time.
I believe this problem occurs when drawing and emulation are updated with unfavourable timing (probably almost simultaneous).

Yes, Secret of Mana indeed has resolution issues. I wasn't aware of that yet.
But the problem with Secret of Mana 2 (Seiken Densetsu 3) from [Issue #42](https://github.com/jasarien/Provenance/issues/42) seems to be solved.

**Comment by peanut256** [comment]
Experimenting with SoM I realized that (auto)loading a gamestate can crash the app.
I think this happens when the state is loaded while the emulator computes the next frame simultaneously. So a possible solution would be to protect the state loading code `loadStateFromFileAtPath:` with `@synchronized`. (Btw, I always synchronized to the PVEmulatorCore instance).

Not sure if this is also responsible for the resolution problem in SoM, but at least I can not reproduce the issue anymore.

**Comment by jasarien** [comment]
Issue #42 is the one I was talking about - It's not solved for me with the @synchronise block. I'm looking at it right now and it's still flickering like crazy.

**Comment by peanut256** [comment]
Did you also replace `performSelectorOnMainThread` for buffer flipping by a direct call?

Otherwise I would like to send you the source files with my changes. (I'm new to GitHub. Maybe the usual way would be to create a branch that I can commit to?)

**Comment by jasarien** [comment]
Yes, I did everything you said. It doesn't solve the issue for me. I'm interested to know some details. What devices are you using, are you building with Release mode or debug mode? Debug mode would explain why it was choppy in the first place, since it has no optimisations applied and a synchronise might solve that on a fast device, but not a slow one.

I'm testing it on an iPhone 6 in release mode. For what it's worth SNES games aren't choppy for me at all, and the only issue I know of is the resolution flicker in Seiken Denetsu 3, which isn't solved with the @synchronise for me.

If you want to show your solution for me to test it the best practise is to create a fork of this repo on your account, make the change and commit to your fork and then I can check it out.

**Comment by peanut256** [comment]
I used release mode on an iPad Air 2 and iPhone 5s (with iOS 8 and 9). My build settings should be the same as yours (Bitcode deactivated).

The choppiness wasn't caused because the computation took to long; I measured the time of `executeFrame` and it was always much less than 1/60 sec. It was probably a syncing issue between the main and the emulation thread (this would also explain why the choppiness appeared and disappeared at random).

I will setup a fork in my account.

**Comment by peanut256** [comment]
My commit is [here](https://github.com/peanut256/Provenance).

There is another screen resolution bug that affects SoM (both 1 and 2).
The bug is triggered by loading a gamestate that displays dialog text.
For now, you can simply wait for the dialog scene to end, save the state again, quit the game and reload.

**Comment by jasarien** [comment]
I tried your fork, and you were right all along, it does solve issue #42. I took the liberty of creating a pull request from your fork and merging it into Provenance, so that keeps your contribution notes intact too. Welcome to being a Provenance contributor, and thanks for solving the bugs! :)

**Comment by peanut256** [comment]
Okay, that's great! I'm happy I could help.
