### ISSUE TITLE
Support for tvOS

### ISSUE THREAD

**Issue by cplr** [jasarien/Provenance#89]
https://developer.apple.com/tvos/ :)

**Comment by jasarien** [comment]
http://youtu.be/qnRVPMdjua4

**Comment by jasarien** [comment]
tvOS is definitely high on my list. It's something I've been anticipating for a long time, but there are some restrictions I need to work around before it can happen. 

The first is that tvOS apps aren't allowed any persistent local storage, they must use iCloud if they want to store things - problem 1. iCloud is only usable from App Store apps and provenance is not allowed in the App Store, and without local persistent storage, where are the roms going to live?

**Comment by cplr** [comment]
I haven't had time to dive into the docs yet - Is that restriction about local storage an API issue?

**Comment by jasarien** [comment]
I'm not 100% sure. I also ha net had much time to dive deep yet. It's just what is written on the first page of the tvOS programming guide. I would imagine it's an environment restriction as in the app doesn't have permission to write to disk in a location that would persist ( perhaps it's possible to write to a temp location that is cleared often/unpredictably).

**Comment by jasarien** [comment]
If it's not a system restriction, but something enforced by app review then we can definitely just ignore it and carry on. But I don't think that will be the case.

**Comment by cplr** [comment]
For initial testing, roms could just be built into the app bundle, but otherwise I guess Dropbox or similar 3rd party cloud service would need to be used.

**Comment by jasarien** [comment]
I'll be taking a look at tvOS over the weekend so I'll post any updates/progress here.

**Comment by jpete24** [comment]
Integration to Dropbox would be excellent! Save states and Roms that would sync with the iOS versions would be icing on the cake for tvOS

**Comment by davidmuzi** [comment]
I was able to get SNES running on tvOS (https://github.com/davidmuzi/Provenance/tree/tvos-support).  Theres no UI, a few shortcuts, and just loads a hardcoded rom, but I just wanted to prove to myself this could be done.

Kudos on Provenance's architecture, which made it quite easy to port.  Luckily all the frameworks required for the SNES emulator and PVSupport are supported on tvOS.  But, it looks like the Provenance app itself would need to be rewritten for tvOS.  The major factors are the lack of persistent storage, removal of the non-mfi gamepad support, and of course a custom UI for the TV.

As for storage, while Dropbox would make the most logical choice, I don't think it would be possible to get an OAuth token without web view support.  Including the roms in the app bundle is not the worst compromise - and its not like new roms are being released :).  Personally, Id like to see support for NAS (like the Synology DiskStation).

Having Provenance working on the Apple TV looks very promising!

**Comment by cplr** [comment]
Excellent work! The good news is in the new SDKs, UIKit gets the GameController events (at the UIResponder level), so it should be easier (than before at least) to write a new UI driven by the controller. Since the code should probably support navigation with the Siri remote, it'd be cool to get Siri Remote support in platforms that would be applicable, like the NES and GBA, etc...

Regarding storage, there are some more open DropBox alternatives like BTSync, or syncthing. I wonder if the new Apple TV will support AirDrop?

Since there's already a web server, maybe we could leverage that to host roms from an iPhone or iPad on the same local network...

**Comment by jasarien** [comment]
I'm already working on this in the tvOS branch. 

Roma will not be included in the bundle regardless - I don't want a dmca from Nintendo like GBA4iOS got just for including a link to a place where Roma can be downloaded.

**Comment by davidmuzi** [comment]
great!

Why wouldn't you be able to add roms directly to the bundle? Its my understanding that the only way to get Provenance on your device is to clone the repo and build and install it yourself.  It would never be distributed with roms already in the repo.  Am I misunderstanding something?

**Comment by jasarien** [comment]
are you not saying to include roms with the app?

**Comment by davidmuzi** [comment]
Well, only at build time.

Developer clones the repo, adds some roms to a resource bundle, builds and installs on their personal device.

**Comment by jasarien** [comment]
Also on iOS (and probably by extension tvOS) the app bundle isn't writable (sandboxing rules etc) so I don't think saving roms inside the app bundle would work either.

**Comment by jasarien** [comment]
I see what you're saying now. I guess that could work, not sure it would be a permanent solution though.

**Comment by jasarien** [comment]
Wouldn't work if there is any kind of OTA install for people on iemulators and such

**Comment by Asmod4n** [comment]
Maybe just add SMB support?

**Comment by jasarien** [comment]
Yeah, maybe. The only real reliable solution is going to be some kind of external storage, however, as davidmuzi stated, Dropbox probably won't work without OAuth support (thanks to no web views in tvOS...).

**Comment by Asmod4n** [comment]
doesn't dropbox have a simple (json) api for that where you don't need a web view?

**Comment by jasarien** [comment]
I can't find anything in the Dropbox API docs about suing the API without OAuth, which requires webviews.

**Comment by maddox** [comment]
> Yeah, maybe. The only real reliable solution is going to be some kind of external storage, however, as davidmuzi stated, Dropbox probably won't work without OAuth support (thanks to no web views in tvOS...).

You can get your keys via a browser and input them at runtime/buildtime. A simple little hosted widget would work to let people auth. 

The bigger problem with dropbox is that their apps only support a small amount of authentications before you have to make them public. So people will have to actually create their own dropbox apps via their own dropbox account. 

That makes the widget scenario tougher. Though you could easily make one that took their app creds, and then authed against it. It would appear shady as hell, lol, but you could maybe do your best to ensure nothing shady was happening and no keys were ever being written.

It's def doable though I think.

**Comment by maciekish** [comment]
Is the controller supported yet? I don't see any mention of `GCMicroGamepad` in the code and I'm able to start ROMs but not control the game.

**Comment by jasarien** [comment]
Microgamepad is supported to an extent, but it just has so few buttons available that it's mostly useless for provenance. It has a dpad and two click buttons, but all the emulators in provenance require at a very minim 3 or 4 buttons.

**Comment by jasarien** [comment]
I'm going to close this issue, since tvOS is now supported. But please feel free to raise other issues if you encounter problems with Provenance on tvOS.

**Comment by adib** [comment]
Now that this is closed, what's the verdict on a permanent location of ROMs in tvOS? [The Wiki Page](https://github.com/jasarien/Provenance/wiki/Importing-ROMs) suggest uploading via the local web server. However tvOS is free to remove those files when the app is not running.

Was the SMB client  implemented?

**Comment by jasarien** [comment]
I've had ROMs in Provenance for tvOS since it was first implemented. Seems tvOS isn't very aggressive with removing data from apps caches folders. I wouldn't worry about it unless your AppleTV is constantly on the edge of being full up. 

SMB isn't implemented.
