### ISSUE TITLE
ios 9 - Not pulling http web server 

### ISSUE THREAD

**Issue by jpete24** [jasarien/Provenance#90]
Seems that the http web server is broken on iOS 9 GM. Not sure if it has something to do with only allowing https on the new iOS?

**Comment by jasarien** [comment]
Possibly. I think I disabled app transport security recently, but I'll have to check.

**Comment by jpete24** [comment]
See this article - http://www.developer-tech.com/news/2015/jun/11/ios-9-developers-should-exclusively-use-https/

I feel like this and the artwork is broken for this exact same issue.

**Comment by jasarien** [comment]
Are you sure you're using the latest code? I added the "allows arbitrary load" which allows any http/s request to work on iOS 9 in a recent commit. See here: https://github.com/jasarien/Provenance/blob/master/Provenance/Provenance-Info.plist#L119

**Comment by jpete24** [comment]
I think I'm using the latest. I downloaded 1.1.6...maybe I missed the latest build?

**Comment by jpete24** [comment]
Yeah, I pulled release 1.1.6, which was 17 days ago. I see that your "Fix duplicate and phantom roms appearing in game library" was about 11 days ago. I'm assuming that you did this without adding notes related to this change to the http/s request?

**Comment by jasarien** [comment]
The commit text was:

Fix duplicate and phantom roms appearing in game library
- If a system expectes cue sheet roms, don't import the accompanying binary roms images, just the cue sheet.
- Allow arbitrary http loads - artwork fails to load without this.
- Game Library View Controller probably needs a rewrite at this point - it's a bit cumbersome and does far too much.

It does indeed contain a line about the App transport security setting.

**Comment by jasarien** [comment]
The releases aren't always the latest code. I make a new release when a significant feature or addition has been added.

**Comment by jpete24** [comment]
I'll try and then close it tonight.

**Comment by jpete24** [comment]
Works perfect. Very nice. Cover art loaded as well. Closing both issues.
