### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by CircaCitadel** [jasarien/Provenance#94]
Trying to build in Xcode, and I get a Build Failed message, followed by another message.

"No non–expired provisioning profiles were found.

Xcode can attempt to fix this issue. This will reset your code signing and provisioning settings to recommended values and resolve issues with signing identities and provisioning profiles."

Then I click "Fix Issue" and it says:

"An App ID with Identifier 'com.jamsoftonline.Provenance' is not available. Please enter a different string."

Couldn't find any other issue like this by searching. Any ideas why I can't build it? Thanks.

**Comment by jasarien** [comment]
You'll need to change the bundle ID to match whatever is in the provisioning profile Xcode created for you. You can try following the steps in this blog: http://bouk.co/blog/sideload-iphone/
