### ISSUE TITLE
PS4 Controller Support

### ISSUE THREAD

**Issue by maciekish** [jasarien/Provenance#95]
Hi,
Is it possible to add PS4 controller support for those who can't jailbreak and install "Controllers For All"?

Thanks
Maciej

**Comment by jasarien** [comment]
I can look into it, but not making any promises.

**Comment by maciekish** [comment]
Thanks, i have no idea at what level that hack is implemented at but i just thought it may be possible.

**Comment by jasarien** [comment]
There doesn't appear to be a way to connect a PS4 controller to an iOS/tvOS device that isn't jailbroken. Sorry.

**Comment by eirikhm** [comment]
@jasarien I am able to pair my PS4 controller on my AppleTV 4 via Bluetooth without Jailbreak. Has this changed recently?

**Comment by jasarien** [comment]
You can pair it maybe, but I don't believe it works as a GCController and therefore won't work in any games that use the MFi controller framework.
