### ISSUE TITLE
Provenance Crashes when menu button pressed in game

### ISSUE THREAD

**Issue by Shawzborne** [jasarien/Provenance#96]
I am running the iOS 9 public GM and version 1.1.6 of Provenance on my iPad Air 2 and when ever I'm playing any game and I hit the little menu button at the top centre of screen near the clock the whole app crashes.

Is there anything to fix this?

**Comment by jasarien** [comment]
I'll look into it.

**Comment by jasarien** [comment]
Did you compile provenance yourself or download it from somewhere? What game/system were you playing?

**Comment by jasarien** [comment]
I see the crash, I'll fix it very soon.

**Comment by Shawzborne** [comment]
I am using Xcode 7 I copied the https .git URL from your github page and I guess compiled it in Xcode. I selected the provenance >release build as I heard it runs better I'm using paid developer account

**Comment by jasarien** [comment]
I've committed the fix for those crashes. You'll have to 'pull' from the master repo to get the changes (or you could just delete the cloned repo and start over again following the same steps you did previously.

**Comment by jasarien** [comment]
Let me know once you've tested them and I'll close the issue.

**Comment by Shawzborne** [comment]
Its fixed for this issue at least

**Comment by omegaRJ** [comment]
I am experiencing this bug now. The app crash when i pressed the menu button.
I just recently installed provenance. I am on ipad pro iOS 9.3.3
How do i fix this?
