### ISSUE TITLE
Cant see files via web server transfer

### ISSUE THREAD

**Issue by Shawzborne** [jasarien/Provenance#97]
worked fine on my iPad Air 2 but for some reason they won't appear even the system files on my iPhone 6

![screen shot 2015-09-19 at 10 35 10 am](https://cloud.githubusercontent.com/assets/5931778/9976718/41c70b96-5eba-11e5-9c2a-aba7779098a9.png)

**Comment by jasarien** [comment]
Weird. I can't reproduce that myself, it's worked on all devices I've tried, including simulators... Perhaps try reinstalling Provenance on the iPhone 6, and try verifying its network settings? I'm kind of at a loss with this one, I don't know what it could be.

**Comment by jasarien** [comment]
Are you using a pop up/ad blocker in Safari that could be interfering with the page content at all?

**Comment by Shawzborne** [comment]
I just made sure no ad blockers are on and I tried using both chrome and safari. both my iPhone 6 and mac are on the same wifi network.

**Comment by jasarien** [comment]
Try deleting Provenance from the iPhone and re-installing it, let me know if that changes anything.

**Comment by jasarien** [comment]
Do you have any update on this issue?

**Comment by jasarien** [comment]
Closing this issue since I can't reproduce it and haven't heard any updates.
